import { useEffect, useRef, useState } from 'react'
import type { ConversationResponse, Message } from '../api/types'
import './ExportMenu.css'

interface Props {
  data: ConversationResponse
  messages: Message[]
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function exportJSON(data: ConversationResponse, messages: Message[]) {
  const payload = { request: { messages }, response: data }
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
  downloadBlob(blob, `leandeep-analysis-${Date.now()}.json`)
}

function exportHTML(data: ConversationResponse, messages: Message[]) {
  const markerSpans = data.markers
    .map((m) => `<span class="marker marker--${escapeHtml(m.layer?.toLowerCase() ?? '')}">${escapeHtml(m.id)} (${Math.round((m.adjusted_confidence ?? m.confidence) * 100)}%)</span>`)
    .join(' ')

  const messageHTML = messages
    .map((m) => `<div class="message"><strong>${escapeHtml(m.role)}:</strong> ${escapeHtml(m.text)}</div>`)
    .join('\n')

  const narrativeHTML = data.narratives
    .map((n) => `<div class="narrative"><h4>${escapeHtml(n.type)}</h4><p>${escapeHtml(n.text)}</p></div>`)
    .join('\n')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>LeanDeep Analysis Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; }
    h1 { font-size: 1.5rem; }
    .message { margin: 0.5rem 0; padding: 0.5rem; background: #f8f9fa; border-radius: 6px; }
    .marker { display: inline-block; font-size: 0.75rem; padding: 2px 6px; border-radius: 3px; margin: 2px; }
    .marker--ato { background: #dbeafe; color: #1d4ed8; }
    .marker--sem { background: #dcfce7; color: #15803d; }
    .marker--clu { background: #fee2e2; color: #dc2626; }
    .marker--mema { background: #f3e8ff; color: #7c3aed; }
    .narrative { margin: 1rem 0; padding: 1rem; border: 1px solid #e2e8f0; border-radius: 8px; }
    .narrative h4 { margin: 0 0 0.5rem; font-size: 0.875rem; text-transform: uppercase; color: #64748b; }
    .meta { font-size: 0.75rem; color: #94a3b8; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>LeanDeep 6.0 Analysis Report</h1>
  <h2>Dialogue</h2>
  ${messageHTML}
  <h2>Detected Markers</h2>
  <div>${markerSpans}</div>
  <h2>Narrative Interpretations</h2>
  ${narrativeHTML}
  <div class="meta">
    Generated by LeanDeep 6.0 | ${new Date().toISOString()} | ${data.meta.markers_detected} markers | ${data.meta.processing_ms.toFixed(0)}ms
  </div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html' })
  downloadBlob(blob, `leandeep-report-${Date.now()}.html`)
}

export function ExportMenu({ data, messages }: Props) {
  const [open, setOpen] = useState(false)
  const menuRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [open])

  return (
    <div className="export-menu" ref={menuRef}>
      <button
        className="btn btn--secondary export-trigger"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        aria-haspopup="true"
      >
        Export
      </button>
      {open && (
        <div className="export-dropdown" role="menu">
          <button
            className="export-option"
            role="menuitem"
            onClick={() => { exportJSON(data, messages); setOpen(false) }}
          >
            JSON (raw data)
          </button>
          <button
            className="export-option"
            role="menuitem"
            onClick={() => { exportHTML(data, messages); setOpen(false) }}
          >
            HTML (report)
          </button>
        </div>
      )}
    </div>
  )
}
