"""Batch 7: ATO_SELF_SUPPORT_PHRASE through ATO_SHUTDOWN_SYMPTOM (10 markers)"""

EXAMPLES = {
    "ATO_SELF_SUPPORT_PHRASE": {
        "positive": [
            "Ich ermutige mich selbst: Du schaffst das.",
            "Ich muntere mich selbst auf.",
            "Ich stehe mir selbst zur Seite.",
            "Ich muss mich zusammenreißen.",
            "Ich schaffe das, ich bin stark genug.",
            "Selbst ermutigen: Kopf hoch!",
            "Ich muntere mich auf, indem ich laufe.",
            "Mir selbst zur Seite stehen, das lerne ich.",
            "Zusammenreißen und weitermachen.",
            "Ich schaffe das, sage ich mir.",
            "Ich ermutige mich selbst jeden Morgen.",
            "Aufmuntern muss ich mich selbst.",
            "Ich stehe mir zur Seite in der Krise.",
            "Ich reiße mich jetzt zusammen.",
            "Das schaffe ich, ich weiß es.",
            "Selbst ermutigen, wenn niemand da ist.",
            "Ich muntere mich auf mit Musik.",
            "Mir selbst zur Seite stehen können.",
            "Zusammenreißen, auch wenn es schwer ist.",
            "Ich schaffe das, ich hab es schon einmal geschafft.",
            "Ich spreche mir selbst Mut zu.",
            "Aufmunterung von mir für mich.",
            "Ich stehe mir selbst bei.",
            "Ich reiße mich zusammen und gehe weiter.",
            "Das schaffe ich alleine, da bin ich sicher.",
            "Sich selbst ermutigen ist eine Kunst.",
            "Ich muntere mich selbst auf nach dem Rückschlag.",
            "Mir selbst zur Seite stehen: wichtiger denn je.",
            "Ich muss mich zusammenreißen und weitermachen.",
            "Ich schaffe das, Schritt für Schritt.",
            "Ich ermutige mich: Morgen wird besser.",
            "Selbstaufmunterung: Du bist gut genug.",
            "Ich stehe mir selbst zur Seite, immer.",
            "Zusammenreißen und nicht aufgeben.",
            "Das kann ich schaffen, ich glaube an mich.",
            "Ich ermutige mich selbst täglich.",
            "Aufmuntern durch positive Gedanken.",
            "Mir zur Seite stehen, wenn sonst keiner da ist.",
            "Zusammenreißen: die einzige Option.",
            "Ja, ich schaffe das, ganz bestimmt.",
            "Sich selbst ermutigen zu können ist Stärke.",
            "Ich muntere mich auf, es geht weiter.",
            "Mir selbst beistehen in dunklen Momenten.",
            "Ich reiße mich zusammen, es geht.",
            "Ich schaffe das, wie immer.",
            "Ermutige dich selbst, sage ich mir.",
            "Aufmunterung kommt von innen.",
            "Ich stehe mir selbst zur Seite, tapfer.",
            "Zusammenreißen und Krone richten.",
            "Das schaffe ich, kein Zweifel.",
        ],
        "negative": [
            "Ich brauche Hilfe von anderen.",
            "Alleine schaffe ich das nicht.",
            "Bitte unterstütze mich.",
            "Ich bin auf dich angewiesen.",
            "Ohne dich geht es nicht.",
            "Hilf mir bitte.",
            "Ich kann das nicht allein.",
            "Ich brauche jemanden.",
            "Bitte sei für mich da.",
            "Ich komme allein nicht weiter.",
            "Unterstützung von außen ist nötig.",
            "Ich rufe Freunde an.",
            "Ich brauche professionelle Hilfe.",
            "Allein bin ich überfordert.",
            "Hilf mir auf die Beine.",
            "Ich suche mir Unterstützung.",
            "Ohne Hilfe geht gar nichts.",
            "Ich wende mich an euch.",
            "Bitte fangt mich auf.",
            "Ich brauche ein offenes Ohr.",
            "Allein schaffe ich es gerade nicht.",
            "Ich bitte um Unterstützung.",
            "Ohne euch bin ich aufgeschmissen.",
            "Ich brauche dich jetzt.",
            "Bitte hilf mir.",
        ],
    },
    "ATO_SET_BOUNDARY": {
        "positive": [
            "Hier ist meine Grenze.",
            "Bis hierhin und nicht weiter.",
            "Nein, das mache ich nicht.",
            "Stopp, das geht zu weit.",
            "Das ist nicht okay für mich.",
            "Meine Grenze ist erreicht.",
            "Bis hierhin, danach ist Schluss.",
            "Nein, das akzeptiere ich nicht.",
            "Stopp, das möchte ich nicht.",
            "Das ist definitiv nicht okay.",
            "Grenze setzen: Hier ist Ende.",
            "Bis hierhin reicht es.",
            "Nein heißt Nein.",
            "Stopp, ich brauche Abstand.",
            "Das ist nicht okay, und das sage ich dir.",
            "Meine Grenze ist klar definiert.",
            "Bis hierhin und keinen Schritt weiter.",
            "Nein, das kommt nicht in Frage.",
            "Stopp, das übersteigt meine Toleranz.",
            "Nicht okay, und das weißt du.",
            "Grenze: Ich sage Nein.",
            "Bis hierhin war es genug.",
            "Nein, damit bin ich nicht einverstanden.",
            "Stopp, respektiere meine Grenzen.",
            "Das ist überhaupt nicht okay.",
            "Hier ziehe ich die Grenze.",
            "Bis hierhin, jetzt ist genug.",
            "Nein, dazu bin ich nicht bereit.",
            "Stopp, so geht das nicht weiter.",
            "Das geht nicht, das ist nicht okay.",
            "Meine persönliche Grenze ist hier.",
            "Bis hierhin und nicht einen Millimeter weiter.",
            "Nein, darüber diskutiere ich nicht.",
            "Stopp, das verletze mich.",
            "Nicht okay: Ich sage klar Nein.",
            "Hier ist meine rote Linie.",
            "Bis hierhin, dann ist Feierabend.",
            "Nein ist ein ganzer Satz.",
            "Stopp, ich setze jetzt Grenzen.",
            "Das ist absolut nicht okay für mich.",
            "Grenze gesetzt, Punkt.",
            "Bis hierhin: keine Diskussion.",
            "Nein, das lehne ich ab.",
            "Stopp, genug ist genug.",
            "Nicht okay, egal wie du es drehst.",
            "Hier endet meine Bereitschaft.",
            "Bis hierhin war es in Ordnung, jetzt nicht mehr.",
            "Nein, und dabei bleibt es.",
            "Stopp, ich ziehe Konsequenzen.",
            "Das ist nicht okay, und ich sage es laut.",
        ],
        "negative": [
            "Klar, mache ich gerne.",
            "Okay, wenn du meinst.",
            "Ist schon in Ordnung.",
            "Ja, natürlich.",
            "Kein Problem.",
            "Für dich tue ich das.",
            "Mach ich halt.",
            "Geht schon.",
            "Passt.",
            "Wenn es sein muss.",
            "Na gut.",
            "Okay, einverstanden.",
            "Ja, sicher.",
            "Klar doch.",
            "Wird gemacht.",
            "In Ordnung.",
            "Von mir aus.",
            "Meinetwegen.",
            "Alles klar.",
            "Wenn du das willst.",
            "Gut, dann halt so.",
            "Okay, ich mach das.",
            "Ja, kein Ding.",
            "Sicher, warum nicht.",
            "Geht klar.",
        ],
    },
    "ATO_SHAME": {
        "positive": [
            "Ich schäme mich so dafür.",
            "Das ist mir unglaublich peinlich.",
            "Es ist wirklich zum Schämen.",
            "Ich könnte im Boden versinken.",
            "Diese Situation ist mir so unangenehm.",
            "Mir ist das peinlich, das zuzugeben.",
            "Ich schäme mich für mein Verhalten.",
            "Das war eine peinliche Aktion von mir.",
            "Fühle mich gerade echt mies und schäme mich.",
            "Hoffentlich hat das niemand gesehen, so peinlich.",
            "Ich schäme mich in Grund und Boden.",
            "Peinlich, wie ich mich aufgeführt habe.",
            "Zum Schämen, was da passiert ist.",
            "Ich könnte im Boden versinken vor Scham.",
            "Unangenehm ist gar kein Ausdruck.",
            "Ich schäme mich zutiefst.",
            "Das war so dermaßen peinlich.",
            "Zum Schämen: Ich habe mich blamiert.",
            "Im Boden versinken wäre jetzt gut.",
            "Unangenehm und peinlich zugleich.",
            "Schäme mich so sehr dafür.",
            "Peinlich berührt stehe ich da.",
            "Zum Schämen, wie naiv ich war.",
            "Versinken möchte ich im Boden.",
            "Mir ist das wahnsinnig unangenehm.",
            "Ich schäme mich, dass ich geweint habe.",
            "Peinlich war das, sehr peinlich.",
            "Ich schäme mich für meine Worte.",
            "Im Boden versinken, am liebsten sofort.",
            "Das ist mir extrem unangenehm.",
            "Schäme mich für meine Schwäche.",
            "So peinlich, ich will das vergessen.",
            "Zum Schämen, wie ich reagiert habe.",
            "Könnte im Boden versinken.",
            "Unangenehm: Alle haben es gesehen.",
            "Ich schäme mich für gestern Abend.",
            "Peinlich, dass mir das passiert ist.",
            "Zum Schämen: Ich habe gelogen.",
            "Im Boden versinken vor Scham.",
            "Das war so unangenehm für mich.",
            "Ich schäme mich manchmal für mich selbst.",
            "Peinlich, peinlich, peinlich.",
            "Schäme mich dafür, das gesagt zu haben.",
            "Am liebsten im Boden versinken.",
            "Es ist mir sehr unangenehm.",
            "Ich schäme mich für mein Versagen.",
            "Das Peinlichste, was mir je passiert ist.",
            "Ich will im Boden versinken.",
            "Unangenehme Situation, ich schäme mich.",
            "Schäme mich so sehr.",
        ],
        "negative": [
            "Ich denke, wir sollten das sachlich betrachten.",
            "Mir geht es gut, danke der Nachfrage.",
            "Das ist ein interessanter Gedanke.",
            "Ich bin gerade entspannt.",
            "Alles in Ordnung bei mir.",
            "Ich fühle mich heute ruhig und gelassen.",
            "Das überrascht mich, aber es ist okay.",
            "Das kann jedem passieren.",
            "Kein Grund, sich schlecht zu fühlen.",
            "Das war nicht schlimm.",
            "Fehler sind menschlich.",
            "Ich nehme das gelassen.",
            "Kein Drama.",
            "Passiert, weiter geht's.",
            "Ich stehe dazu.",
            "Das ist okay so.",
            "Kein Grund zur Aufregung.",
            "Ich fühle mich wohl.",
            "Das war halt so.",
            "Ich bin im Reinen damit.",
            "Kein Grund für Scham.",
            "Das ist ganz normal.",
            "Ich bin zufrieden mit mir.",
            "Das stört mich nicht.",
            "Alles gut bei mir.",
        ],
    },
    "ATO_SHAME_GUILT": {
        "positive": [
            "Ich empfinde tiefe Scham.",
            "Schämen tue ich mich dafür sehr.",
            "Beschämt stehe ich hier.",
            "Ich bin ganz verschämt.",
            "Die Schuld drückt mich nieder.",
            "Ich fühle mich schuldig.",
            "Schuldgefühle quälen mich.",
            "Das ist mir so peinlich.",
            "Ich bin blamiert worden.",
            "Verlegen wende ich den Blick ab.",
            "Reue empfinde ich zutiefst.",
            "Ich bereue meine Tat.",
            "Bereut habe ich das sofort.",
            "Ich fühle mich unwürdig.",
            "Minderwertig fühle ich mich.",
            "Ich habe versagt, komplett.",
            "Versagen quält mich.",
            "Ich bin ein Versager.",
            "Scham und Schuld wechseln sich ab.",
            "Beschämt und schuldig zugleich.",
            "Peinlich und schuldbeladen.",
            "Blamiert vor allen Leuten.",
            "Verlegen und voller Reue.",
            "Ich bereue zutiefst, was ich getan habe.",
            "Unwürdig fühle ich mich deiner Liebe.",
            "Minderwertig komme ich mir vor.",
            "Versagt habe ich auf ganzer Linie.",
            "Scham überkommt mich.",
            "Schuld empfinde ich dafür.",
            "Schuldgefühle plagen mich seit Tagen.",
            "Peinlich berührt schweige ich.",
            "Blamiert habe ich mich vor dem Chef.",
            "Verlegen lächle ich.",
            "Reue quält mein Gewissen.",
            "Bereuen werde ich das immer.",
            "Unwürdig, so fühle ich mich.",
            "Minderwertig, wertlos, am Boden.",
            "Ich habe total versagt.",
            "Tiefe Scham erfüllt mich.",
            "Schuldgefühle fressen mich auf.",
            "Peinlich, was ich gesagt habe.",
            "Blamiert bis auf die Knochen.",
            "Verlegen senke ich den Kopf.",
            "Reue und Schmerz begleiten mich.",
            "Ich bereue jedes Wort.",
            "Unwürdig dieser Chance.",
            "Minderwertig und klein fühle ich mich.",
            "Versagt, wie so oft.",
            "Scham und Schuld, meine Begleiter.",
            "Ich bin beschämt und gebrochen.",
        ],
        "negative": [
            "Ich bin stolz auf mich.",
            "Kein Grund für Schuldgefühle.",
            "Ich stehe zu dem, was ich getan habe.",
            "Ich bin im Reinen mit mir.",
            "Dafür brauche ich mich nicht zu schämen.",
            "Ich habe richtig gehandelt.",
            "Ich bin zufrieden mit meiner Entscheidung.",
            "Ich vergebe mir.",
            "Das war die richtige Wahl.",
            "Ich bin frei von Schuld.",
            "Ich akzeptiere mich so.",
            "Keine Reue, keine Scham.",
            "Ich bin okay, wie ich bin.",
            "Das war nicht meine Schuld.",
            "Ich fühle mich gut dabei.",
            "Kein Grund, den Kopf zu senken.",
            "Ich bin stolz auf meinen Weg.",
            "Ich stehe aufrecht.",
            "Ich bin wertvoll und gut genug.",
            "Kein Versagen, nur Lernen.",
            "Ich bin dankbar für die Erfahrung.",
            "Ich vergebe mir und gehe weiter.",
            "Ich bin nicht schuld.",
            "Ich stehe zu mir.",
            "Alles gut, ich bin im Reinen.",
        ],
    },
    "ATO_SHARED_CONTEXT": {
        "positive": [
            "Wie besprochen, hier die Unterlagen.",
            "Wie verabredet treffen wir uns um 10.",
            "Vom letzten Mal wissen wir ja, dass...",
            "Im Kontext von unserem Gespräch...",
            "Zurück zu dem, was wir besprochen haben.",
            "Wie vereinbart schicke ich dir das.",
            "Wie besprochen habe ich das erledigt.",
            "Wie verabredet senden wir den Report.",
            "Vom letzten Mal her weiß ich...",
            "Im Kontext von der Präsentation...",
            "Zurück zu unserem Thema.",
            "Wie vereinbart ist der Termin am Dienstag.",
            "Wie besprochen, das ist der aktuelle Stand.",
            "Wie verabredet liefern wir bis Freitag.",
            "Vom letzten Treffen haben wir noch offene Punkte.",
            "Im Kontext von der Reorganisation...",
            "Zurück zu dem, was wir vereinbart hatten.",
            "Wie vereinbart habe ich nachgefragt.",
            "Wie besprochen sende ich dir die Daten.",
            "Wie verabredet melden wir uns morgen.",
            "Vom letzten Mal kennst du das schon.",
            "Im Kontext von unserer Strategie...",
            "Zurück zum Punkt von gestern.",
            "Wie vereinbart starten wir am Montag.",
            "Wie besprochen anbei die Rechnung.",
            "Wie verabredet habe ich reserviert.",
            "Vom letzten Gespräch her ist mir klar...",
            "Im Kontext von dem Feedback...",
            "Zurück zu unserer Diskussion.",
            "Wie vereinbart übernehme ich das.",
            "Wie besprochen geht es weiter.",
            "Wie verabredet treffen wir uns im Büro.",
            "Vom letzten Mal weißt du ja...",
            "Im Kontext von der letzten Entscheidung...",
            "Zurück zum Kernthema.",
            "Wie vereinbart bleiben die Konditionen.",
            "Wie besprochen liegt der Ball bei dir.",
            "Wie verabredet mache ich das fertig.",
            "Vom letzten Meeting haben wir das mitgenommen.",
            "Im Kontext von unserem Projekt...",
            "Zurück zu dem, was du gesagt hast.",
            "Wie vereinbart hole ich dich ab.",
            "Wie besprochen bleibe ich dran.",
            "Wie verabredet kommen wir um 8.",
            "Vom letzten Termin wissen wir...",
            "Im Kontext von den Änderungen...",
            "Zurück zum eigentlichen Thema.",
            "Wie vereinbart kümmere ich mich darum.",
            "Wie besprochen ist das der nächste Schritt.",
            "Wie vereinbart rufe ich dich morgen an.",
        ],
        "negative": [
            "Das ist ein neues Thema.",
            "Davon habe ich noch nichts gehört.",
            "Das kommt unerwartet.",
            "Das ist mir völlig neu.",
            "Wir haben noch nie darüber gesprochen.",
            "Das ist eine neue Information.",
            "Zum ersten Mal höre ich davon.",
            "Das hatten wir nie besprochen.",
            "Das überrascht mich.",
            "Davon weiß ich nichts.",
            "Das ist ein komplett neuer Punkt.",
            "Erstmals kommt das zur Sprache.",
            "Das Thema ist neu für mich.",
            "Wir hatten das nicht auf dem Schirm.",
            "Das war so nicht abgemacht.",
            "Das ist eine Neuigkeit.",
            "Davon ist mir nichts bekannt.",
            "Das stand nicht auf der Agenda.",
            "Zum ersten Mal wird das erwähnt.",
            "Das haben wir nie vereinbart.",
            "Das ist mir nicht bewusst gewesen.",
            "Das kommt aus heiterem Himmel.",
            "Wir hatten einen anderen Plan.",
            "Das ist komplett neu.",
            "Daran erinnere ich mich nicht.",
        ],
    },
    "ATO_SHARED_FUTURE_REFERENCE": {
        "positive": [
            "When we grow old together...",
            "Our future looks bright.",
            "Someday we'll look back and smile.",
            "Eventually we'll figure this out together.",
            "We'll travel the world, you and me.",
            "Move in together, what do you say?",
            "When we have kids someday...",
            "Our future home will be beautiful.",
            "Someday this will all make sense.",
            "Eventually we'll be free.",
            "We'll travel to Japan next year.",
            "Let's move in together soon.",
            "When we're old, we'll laugh about this.",
            "Our future is full of possibilities.",
            "Someday we'll own a house by the sea.",
            "Eventually we'll get married.",
            "We'll travel everywhere together.",
            "Let's move in together next month.",
            "When we retire, we'll have so much time.",
            "Our future plans are exciting.",
            "Someday I'll take you to Paris.",
            "Eventually everything works out.",
            "We'll travel and see the northern lights.",
            "Move in together and start a life.",
            "When we look back in 10 years...",
            "Our future is what we make it.",
            "Someday this pain will end.",
            "Eventually we'll be stronger.",
            "We'll travel the whole country together.",
            "Move in together, start fresh.",
            "When we celebrate our anniversary...",
            "Our future children will love this.",
            "Someday we'll build our dream.",
            "Eventually we'll understand.",
            "We'll travel to every continent.",
            "Move in together this summer.",
            "When we have more time...",
            "Our future self will thank us.",
            "Someday we'll be there.",
            "Eventually it all comes together.",
            "We'll travel together forever.",
            "Move in together, no more distance.",
            "When we achieve our goals...",
            "Our future depends on today.",
            "Someday we'll have it all.",
            "Eventually we'll find peace.",
            "We'll travel and never stop.",
            "Let's move in together already.",
            "When we make it through this...",
            "Our future starts now.",
        ],
        "negative": [
            "I'm focused on today.",
            "Let's deal with the present.",
            "I don't make long-term plans.",
            "One day at a time.",
            "The future is uncertain.",
            "I'm not thinking that far ahead.",
            "Let's focus on now.",
            "Today is what matters.",
            "I live in the moment.",
            "No need to plan everything.",
            "Let's see what happens.",
            "I take it day by day.",
            "The present is enough.",
            "I'm not ready to commit to that.",
            "Let's not get ahead of ourselves.",
            "For now, this is fine.",
            "I'm enjoying the moment.",
            "No plans for the future yet.",
            "Let's just be here now.",
            "The future will sort itself out.",
            "I'm not rushing anything.",
            "One step at a time.",
            "Let's not make promises.",
            "Today is all we have.",
            "I'm happy with things as they are.",
        ],
    },
    "ATO_SHOULD_MORE_OFTEN": {
        "positive": [
            "Wir sollten öfter so was machen.",
            "Müssen wir unbedingt wiederholen.",
            "Nächstes Mal machen wir das wieder.",
            "Bald wieder, versprochen.",
            "Sollten wir mal öfter zusammen machen.",
            "Das müssen wir unbedingt wiederholen!",
            "Nächstes Mal bitte mit mehr Leuten.",
            "Demnächst wieder, auf jeden Fall.",
            "Sollten wir viel öfter machen.",
            "Wiederholen wir das bald.",
            "Nächstes Mal mit Übernachtung.",
            "Bald wieder treffen!",
            "Das sollten wir öfter genießen.",
            "Müssen wir dringend wiederholen.",
            "Nächstes Mal am See.",
            "Bald wieder, ich freu mich.",
            "Sollten wir öfter in den Wald gehen.",
            "Das wiederholen wir auf jeden Fall.",
            "Nächstes Mal mit Musik.",
            "Demnächst wieder, am liebsten morgen.",
            "Das sollten wir öfter tun.",
            "Wiederholen: unbedingt!",
            "Nächstes Mal nehme ich Kuchen mit.",
            "Bald wieder, war super.",
            "Sollten öfter zusammen kochen.",
            "Das müssen wir wiederholen, so schön.",
            "Nächstes Mal im Sommer.",
            "Bald wieder campen gehen.",
            "Sollten wir öfter als Team machen.",
            "Wiederholen wir das nächsten Monat.",
            "Nächstes Mal lade ich ein.",
            "Demnächst wieder, versprochen!",
            "Sollten öfter so zusammensitzen.",
            "Das müssen wir bald wiederholen.",
            "Nächstes Mal mit Kindern.",
            "Bald wieder wandern.",
            "Sollten wir öfter gemeinsam Mittag essen.",
            "Wiederholen wir das am Wochenende.",
            "Nächstes Mal bringe ich Wein mit.",
            "Demnächst wieder, war toll.",
            "Öfter sollten wir so reden.",
            "Müssen wir sofort wiederholen.",
            "Nächstes Mal bleiben wir länger.",
            "Bald wieder zusammen spielen.",
            "Sollten wir öfter spazieren gehen.",
            "Das müssen wir jedes Jahr wiederholen.",
            "Nächstes Mal am Meer.",
            "Bald wieder, keine Frage.",
            "Öfter solche Momente genießen.",
            "Wiederholen wir das definitiv.",
        ],
        "negative": [
            "Das war einmal, reicht mir.",
            "Muss nicht sein.",
            "Einmal war genug.",
            "Darauf kann ich verzichten.",
            "Eher nicht nochmal.",
            "Das brauche ich nicht wieder.",
            "Einmalige Sache.",
            "Nicht mein Ding.",
            "Das muss nicht sein.",
            "Lieber was anderes.",
            "Einmal reicht.",
            "Das war okay, aber einmalig.",
            "Kein Bedarf, das zu wiederholen.",
            "Das machen wir lieber nicht nochmal.",
            "War ganz nett, aber einmal reicht.",
            "Darauf verzichte ich gern.",
            "Das war ein Ausrutscher.",
            "Nie wieder.",
            "Einmal und nie wieder.",
            "Das war die Ausnahme.",
            "Kein Wiederholungsbedarf.",
            "War okay, muss aber nicht nochmal sein.",
            "Das streiche ich von der Liste.",
            "Einmal war's schön, reicht aber.",
            "Das brauche ich nicht wieder.",
        ],
    },
    "ATO_SHUTDOWN_PHYSIOLOGY": {
        "positive": [
            "Mir wird schwarz vor Augen.",
            "Ich fühle mich taub, körperlich taub.",
            "Eine Lähmung breitet sich aus.",
            "Ich bin wie weggetreten.",
            "Schwarz vor Augen, ich sehe nichts mehr.",
            "Mein Körper fühlt sich taub an.",
            "Lähmung in den Beinen.",
            "Weggetreten, als wäre ich nicht da.",
            "Alles wird schwarz vor meinen Augen.",
            "Taubheit in den Händen.",
            "Wie gelähmt sitze ich da.",
            "Ich bin völlig weggetreten.",
            "Schwarz vor Augen, Schwindel.",
            "Taub, als hätte jemand den Ton ausgemacht.",
            "Lähmung überkommt mich.",
            "Ich war kurz weggetreten.",
            "Es wird schwarz vor Augen.",
            "Taubheitsgefühl im ganzen Körper.",
            "Gelähmt vor Angst.",
            "Komplett weggetreten.",
            "Schwarz, alles schwarz vor den Augen.",
            "Ich spüre nichts, bin taub.",
            "Wie eine Lähmung, die mich festhält.",
            "Ich war minutenlang weggetreten.",
            "Plötzlich schwarz vor Augen.",
            "Taub in den Armen.",
            "Lähmung im ganzen Körper.",
            "Ich bin immer noch weggetreten.",
            "Schwarz vor Augen beim Aufstehen.",
            "Taubheit nach dem Schock.",
            "Wie gelähmt, kann mich nicht bewegen.",
            "Kurz weggetreten, dann wieder da.",
            "Es wurde mir schwarz vor den Augen.",
            "Taub, als wäre ich betäubt.",
            "Lähmungserscheinungen in Stresssituationen.",
            "Ich bin die ganze Zeit weggetreten.",
            "Schwarz vor Augen in der Prüfung.",
            "Taubheit breitet sich aus.",
            "Gelähmt vor Entsetzen.",
            "Geistig völlig weggetreten.",
            "Mir wird regelmäßig schwarz vor den Augen.",
            "Taub und stumm zugleich.",
            "Die Lähmung lässt nicht nach.",
            "Weggetreten, als wäre ich im Traum.",
            "Schwarz vor Augen, Panik steigt.",
            "Taubheitsgefühl nach dem Streit.",
            "Lähmung durch Überforderung.",
            "Ich war stundenlang weggetreten.",
            "Plötzlich wird alles schwarz.",
            "Taub und gefühllos.",
        ],
        "negative": [
            "Ich fühle mich lebendig und wach.",
            "Mein Körper fühlt sich gut an.",
            "Ich bin hellwach.",
            "Alles funktioniert einwandfrei.",
            "Ich fühle mich energiegeladen.",
            "Mein Kreislauf ist stabil.",
            "Ich bin voll da.",
            "Alles klar, mir geht es gut.",
            "Ich spüre meinen Körper.",
            "Ich bin wach und fokussiert.",
            "Keine Probleme, alles gut.",
            "Ich bin bei vollem Bewusstsein.",
            "Mir geht es körperlich super.",
            "Ich fühle mich fit.",
            "Alles in Ordnung mit mir.",
            "Ich bin entspannt und ruhig.",
            "Mein Körper funktioniert.",
            "Ich bin aufmerksam.",
            "Keine Beschwerden.",
            "Ich fühle mich stark und gesund.",
            "Ich bin ganz bei mir.",
            "Alles im Lot.",
            "Ich bin ausgeruht.",
            "Mir geht es blendend.",
            "Körperlich und geistig fit.",
        ],
    },
    "ATO_SHUTDOWN_SYMPTOM": {
        "positive": [
            "Mir ist schwindelig, ich kann kaum stehen.",
            "Mir wird schwarz vor Augen.",
            "Ich kann nichts mehr hören, alles ist gedämpft.",
            "Mein Körper fühlt sich taub an.",
            "Ich kann mich nicht mehr bewegen.",
            "Ich fühle mich gelähmt.",
            "Ich kann nicht mehr sprechen, die Worte fehlen.",
            "Schwindelig und benommen.",
            "Schwarz vor Augen, ich sehe nichts.",
            "Nichts mehr hören, wie unter Wasser.",
            "Taubheit überall, als wäre ich betäubt.",
            "Nicht mehr bewegen können, wie festgenagelt.",
            "Gelähmt, innerlich und äußerlich.",
            "Ich kann nicht mehr sprechen vor Angst.",
            "Mir wird schwindelig in der Menge.",
            "Alles wird schwarz vor meinen Augen.",
            "Ich höre nichts mehr, nur noch Rauschen.",
            "Taubheitsgefühl in den Extremitäten.",
            "Ich kann mich nicht mehr bewegen vor Schock.",
            "Gelähmt vor Schreck.",
            "Nicht mehr sprechen können, stumm vor Entsetzen.",
            "Extremer Schwindel nach dem Streit.",
            "Schwarz vor Augen nach der Nachricht.",
            "Ich höre nichts mehr, bin wie abgeschaltet.",
            "Taub im ganzen Körper nach dem Schock.",
            "Nicht bewegen, nicht denken können.",
            "Wie gelähmt sitze ich da und starre.",
            "Ich bringe kein Wort heraus, nicht sprechen.",
            "Schwindelig, mir dreht sich alles.",
            "Es wird mir schwarz, ich falle fast.",
            "Kann nichts mehr hören, alles verschwimmt.",
            "Taubheit und Schwindel gleichzeitig.",
            "Ich bin wie gelähmt, keine Reaktion möglich.",
            "Sprechen fällt mir unmöglich gerade.",
            "Heftiger Schwindel überkommt mich.",
            "Schwarz vor Augen, Kreislauf sackt ab.",
            "Alles klingt gedämpft, ich höre nichts richtig.",
            "Taub und wie betäubt.",
            "Nicht bewegen, nicht fliehen können.",
            "Gelähmt vor Angst und Schmerz.",
            "Nicht sprechen können, die Stimme versagt.",
            "Schwindel und Übelkeit nach dem Konflikt.",
            "Schwarz vor Augen, fast ohnmächtig.",
            "Höre nur noch Rauschen, nichts mehr.",
            "Taubheit im Gesicht nach dem Schock.",
            "Wie festgewachsen, kann mich nicht bewegen.",
            "Innerlich gelähmt, äußerlich starr.",
            "Kein Wort kommt raus, nicht sprechen können.",
            "Plötzlich schwindelig und orientierungslos.",
            "Schwarz vor Augen, Panikattacke.",
        ],
        "negative": [
            "Mir geht es körperlich gut.",
            "Ich fühle mich wach und klar.",
            "Alles funktioniert normal.",
            "Ich bin entspannt und bei mir.",
            "Keine körperlichen Beschwerden.",
            "Ich fühle mich lebendig.",
            "Mein Kreislauf ist stabil.",
            "Ich bin aufmerksam und fokussiert.",
            "Alles in Ordnung, gesundheitlich.",
            "Ich fühle mich fit und gesund.",
            "Keine Probleme, mir geht es prima.",
            "Ich bin hellwach.",
            "Mein Körper macht mit.",
            "Ich fühle mich energiegeladen.",
            "Alles gut, keine Sorge.",
            "Ich bin ganz bei Sinnen.",
            "Mir geht es blendend.",
            "Ich fühle mich stark.",
            "Keine Symptome.",
            "Ich bin gesund und munter.",
            "Alles im grünen Bereich.",
            "Ich fühle mich ausgeruht.",
            "Körperlich einwandfrei.",
            "Mir geht es sehr gut.",
            "Ich bin fit wie ein Turnschuh.",
        ],
    },
}
