"""Batch 5: ATO_SACRED_LEXEME through ATO_SD_YELLOW_LEX (13 markers)"""

EXAMPLES = {
    "ATO_SACRED_LEXEME": {
        "positive": [
            "Das ist mir heilig, daran rühre ich nicht.",
            "Ein sakraler Ort der Stille.",
            "Diese Tradition ist mir geheiligt.",
            "Heilige Stätte, heiliger Boden.",
            "Sakrale Musik berührt mich tief.",
            "Das Heilige im Alltag finden.",
            "Ein geheiligtesVersprechen.",
            "Sakrale Handlungen geben mir Kraft.",
            "Heilig ist mir die Sonntagsruhe.",
            "Der sakrale Raum der Kirche.",
            "Geheiligt sei dein Name.",
            "Etwas Heiliges liegt in der Luft.",
            "Sakrale Kunst im Museum.",
            "Mir ist die Familie heilig.",
            "Geheiligtes Ritual am Abend.",
            "Sakrale Symbolik durchzieht den Text.",
            "Das Heilige bewahren.",
            "Sakraler Gesang erfüllt den Raum.",
            "Mir ist Ehrlichkeit heilig.",
            "Ein geheiligtesGefühl der Verbundenheit.",
            "Sakrale Architektur beeindruckt mich.",
            "Das ist heiliger Boden für mich.",
            "Geheiligter Raum der Meditation.",
            "Sakrale Zeremonien faszinieren mich.",
            "Mir ist die Natur heilig.",
            "Ein heiliger Moment der Stille.",
            "Sakrale Texte lesen und reflektieren.",
            "Geheiligte Traditionen pflegen.",
            "Das Heilige respektieren.",
            "Sakraler Tanz als Ausdruck.",
            "Mir ist Freundschaft heilig.",
            "Geheiligter Ort der Ruhe.",
            "Sakrale Bedeutung dieses Ortes.",
            "Das Heilige in der Kunst.",
            "Ein sakrales Erlebnis.",
            "Mir ist dieses Versprechen heilig.",
            "Geheiligter Brauch seit Generationen.",
            "Sakrale Klänge am Morgen.",
            "Das ist heilig, das bleibt so.",
            "Sakraler Charakter des Festes.",
            "Mir ist diese Zeit heilig.",
            "Geheiligte Werte verteidigen.",
            "Sakrale Stimmung im Raum.",
            "Heilige Schriften studieren.",
            "Sakraler Ausdruck der Dankbarkeit.",
            "Mir sind Grenzen heilig.",
            "Ein geheiligtesRitualder Wertschätzung.",
            "Sakrale Momente im Alltag.",
            "Das ist mir absolut heilig.",
            "Geheiligter Boden unter meinen Füßen.",
        ],
        "negative": [
            "Das ist mir wichtig.",
            "Ich schätze diese Tradition.",
            "Der Ort hat eine besondere Atmosphäre.",
            "Musik bewegt mich.",
            "Ich finde das Gebäude beeindruckend.",
            "Die Stille ist angenehm.",
            "Ich mag alte Kirchen.",
            "Das Konzert war bewegend.",
            "Ich respektiere andere Kulturen.",
            "Die Natur ist wunderschön.",
            "Ich lese gerne alte Texte.",
            "Der Raum hat eine gute Energie.",
            "Ich besuche gerne Museen.",
            "Das Fest war schön.",
            "Ich bin dankbar.",
            "Die Atmosphäre war besonders.",
            "Ich genieße die Ruhe.",
            "Das war ein besonderer Moment.",
            "Ich schätze gute Gespräche.",
            "Der Abend war unvergesslich.",
            "Ich finde Traditionen wichtig.",
            "Der Ort ist friedlich.",
            "Ich bin beeindruckt.",
            "Das war ein tolles Erlebnis.",
            "Ich fühle mich wohl hier.",
        ],
    },
    "ATO_SADNESS_GRIEF": {
        "positive": [
            "Ich bin so traurig darüber.",
            "Die Trauer überwältigt mich.",
            "Ich betrauere den Verlust.",
            "Ich fühle mich betrübt und leer.",
            "Diese Niedergeschlagenheit drückt mich.",
            "Ich bin deprimiert seit Tagen.",
            "Eine melancholische Stimmung liegt über mir.",
            "Wehmütig denke ich an früher.",
            "Schwermütig gehe ich durch den Tag.",
            "So sad, ich kann nicht mehr.",
            "Grief überwältigt mich manchmal.",
            "Kummer nagt an mir.",
            "Leid und Schmerz begleiten mich.",
            "Ich muss weinen, die Tränen kommen einfach.",
            "Ich habe so viel geweint heute.",
            "Der Verlust trifft mich hart.",
            "Ich vermisse ihn jeden Tag.",
            "Die Sehnsucht nach ihr zerreißt mich.",
            "Traurig sitze ich hier und denke nach.",
            "Meine Trauer hat kein Ende.",
            "Betrübt schaue ich aus dem Fenster.",
            "Ich bin so niedergeschlagen.",
            "Deprimiert liege ich im Bett.",
            "Melancholisch höre ich alte Lieder.",
            "Wehmut erfüllt mich bei den Erinnerungen.",
            "Schwermütige Gedanken lassen mich nicht los.",
            "Sadness is all I feel right now.",
            "Grief und Trauer wechseln sich ab.",
            "Kummer um den Verlorenen.",
            "Der Schmerz ist unerträglich.",
            "Ich habe Tränen in den Augen.",
            "Geweint habe ich die ganze Nacht.",
            "Den Verlust zu verarbeiten fällt mir schwer.",
            "Ich vermisse unsere gemeinsame Zeit.",
            "Die Sehnsucht macht mich fertig.",
            "Tiefe Trauer um meinen Freund.",
            "Ich bin unendlich traurig.",
            "Betrübt und allein fühle ich mich.",
            "Diese Niedergeschlagenheit hört nicht auf.",
            "Deprimiert über die Nachrichten.",
            "Melancholie liegt in der Luft.",
            "Wehmütige Erinnerungen an die Kindheit.",
            "Schwermut drückt auf meine Brust.",
            "Grief ist ein langer Prozess.",
            "Kummer und Sorge um die Familie.",
            "Der Schmerz des Abschieds.",
            "Die Tränen fließen von allein.",
            "Ich habe geweint vor Erleichterung.",
            "Verlust ist das schwerste Gefühl.",
            "Ich vermisse dich so sehr.",
        ],
        "negative": [
            "Ich bin gut drauf heute.",
            "Das war ein schöner Tag.",
            "Ich freue mich auf morgen.",
            "Mir geht es richtig gut.",
            "Was für ein toller Moment.",
            "Ich bin glücklich und zufrieden.",
            "Das Leben ist schön.",
            "Alles läuft nach Plan.",
            "Ich genieße den Sonnenschein.",
            "Was für ein Glück.",
            "Ich bin dankbar für alles.",
            "Heute war ein guter Tag.",
            "Ich fühle mich lebendig.",
            "Was für eine Freude.",
            "Mir geht es blendend.",
            "Ich lache gerade so viel.",
            "Das Wetter ist wunderbar.",
            "Ich habe gute Neuigkeiten.",
            "Alles ist in Ordnung.",
            "Mir geht es prima.",
            "Der Tag war produktiv.",
            "Ich habe Spaß gehabt.",
            "Was für ein Erlebnis.",
            "Ich bin voller Energie.",
            "Heute ist ein Feiertag.",
        ],
    },
    "ATO_SADNESS_WORD": {
        "positive": [
            "Ich bin so traurig gerade.",
            "Das ist wirklich schade.",
            "Ich fühle mich bedrückt.",
            "Ich vermisse dich sehr.",
            "Ich bin so allein.",
            "Alles fühlt sich leer an.",
            "Traurig, dass es so gekommen ist.",
            "Schade, dass du nicht kommen konntest.",
            "Bedrückt gehe ich durch den Tag.",
            "Ich vermisse unsere Gespräche.",
            "Allein zu Hause, allein mit meinen Gedanken.",
            "Leer, einfach nur leer.",
            "Mir ist traurig zumute.",
            "Schade um die verpasste Chance.",
            "Bedrückt sitze ich hier.",
            "Ich vermisse die alten Zeiten.",
            "Ich bin allein und einsam.",
            "In mir ist eine Leere.",
            "So traurig war ich lange nicht mehr.",
            "Wirklich schade, wie es gelaufen ist.",
            "Ich fühle mich total bedrückt.",
            "Vermisse meine Heimat.",
            "Ganz allein in der Fremde.",
            "Mir ist so leer im Herzen.",
            "Traurig und müde bin ich.",
            "Schade, dass wir uns nicht sehen.",
            "Bedrückt über die Nachricht.",
            "Ich vermisse meine Familie.",
            "Allein sein ist manchmal schwer.",
            "Leere breitet sich in mir aus.",
            "Traurig über den Abschied.",
            "Es ist so schade.",
            "Bedrückt über die Diagnose.",
            "Ich vermisse deinen Humor.",
            "Allein im Hotelzimmer.",
            "Dieses leere Gefühl geht nicht weg.",
            "Traurig, aber wahr.",
            "Schade, dass es nicht geklappt hat.",
            "Bedrückt durch die Dunkelheit.",
            "Vermisse die Unbeschwertheit.",
            "Allein mit meinen Sorgen.",
            "So leer wie selten zuvor.",
            "Traurig, dass er gehen musste.",
            "Echt schade drum.",
            "Total bedrückt seit gestern.",
            "Ich vermisse sein Lachen.",
            "Allein gelassen fühle ich mich.",
            "Eine innere Leere begleitet mich.",
            "Mir ist traurig ums Herz.",
            "Schade, wir hätten das ändern können.",
        ],
        "negative": [
            "Mir geht es gut heute.",
            "Was für ein schöner Tag!",
            "Ich freue mich riesig.",
            "Alles bestens bei mir.",
            "Heute bin ich richtig fröhlich.",
            "Ich genieße den Moment.",
            "Toller Tag, tolle Stimmung.",
            "Mir geht es prächtig.",
            "Ich bin ausgeglichen.",
            "Was für ein Glückstag.",
            "Ich habe super geschlafen.",
            "Die Laune ist top.",
            "Alles wunderbar.",
            "Ich bin motiviert.",
            "Der Tag war fantastisch.",
            "Mir fehlt nichts.",
            "Ich bin zufrieden.",
            "Heute lief alles perfekt.",
            "Ich bin heiter und gelassen.",
            "Super Stimmung heute.",
            "Ich fühle mich großartig.",
            "Alles im Lot.",
            "Mir geht es bestens.",
            "Fröhlich und munter.",
            "Was für ein wunderbarer Morgen.",
        ],
    },
    "ATO_SAFETY_AFFECT": {
        "positive": [
            "Ich fühle mich gerade sicher bei dir.",
            "Es wird ruhiger in mir.",
            "Ich fühle mich gehalten.",
            "Ich fühle mich getragen.",
            "Bei dir fühlt sich alles sicher an.",
            "Es wird so ruhiger, wenn du da bist.",
            "Gehalten sein, das ist das Gefühl.",
            "Ich fühle mich getragen von der Gemeinschaft.",
            "Hier fühlt sich alles sicher und geborgen an.",
            "Es wird ruhiger um mich herum.",
            "Gehalten werden ist, was ich brauche.",
            "Getragen von deiner Liebe.",
            "Sicher fühle ich mich in deinen Armen.",
            "Es wird ruhiger, die Angst lässt nach.",
            "Ich fühle mich von dir gehalten und beschützt.",
            "Getragen durch die schwere Zeit.",
            "Bei euch fühle ich mich sicher.",
            "Es wird ruhiger in meinem Kopf.",
            "Gehalten sein, das brauche ich jetzt.",
            "Ich fühle mich getragen und aufgehoben.",
            "Endlich fühlt sich etwas sicher an.",
            "Es wird ruhiger, ich entspanne mich.",
            "Hier bin ich gehalten.",
            "Getragen von Freundschaft und Vertrauen.",
            "In diesem Raum fühle ich mich sicher.",
            "Es wird so ruhiger, wenn ich meditiere.",
            "Gehalten in schwierigen Momenten.",
            "Getragen von der Hoffnung.",
            "Sicher und geborgen fühle ich mich.",
            "Es wird ruhiger, die Nacht ist friedlich.",
            "Ich fühle mich gehalten vom Team.",
            "Getragen durch die Musik.",
            "Hier ist ein sicherer Ort.",
            "Es wird ruhiger in meiner Seele.",
            "Gehalten in deiner Nähe.",
            "Ich fühle mich getragen und verstanden.",
            "Dieses Gefühl von Sicherheit ist unbezahlbar.",
            "Es wird ruhiger, ich atme tief.",
            "Gehalten von Menschen, die mich lieben.",
            "Getragen durch die Gemeinschaft.",
            "Sicher fühle ich mich nur hier.",
            "Es wird ruhiger, alles ordnet sich.",
            "Ich werde gehalten, auch wenn ich falle.",
            "Getragen von einem starken Netzwerk.",
            "Das Gefühl von Sicherheit breitet sich aus.",
            "Es wird so ruhiger mit der Zeit.",
            "Gehalten und nicht allein gelassen.",
            "Getragen von Vertrauen und Respekt.",
            "Endlich fühlt sich alles sicher an.",
            "Es wird ruhiger, die Wogen glätten sich.",
        ],
        "negative": [
            "Ich fühle mich unsicher und ängstlich.",
            "Es wird immer lauter in meinem Kopf.",
            "Ich fühle mich fallen gelassen.",
            "Niemand fängt mich auf.",
            "Ich bin total angespannt.",
            "Die Unruhe lässt nicht nach.",
            "Ich fühle mich verloren.",
            "Alles fühlt sich bedrohlich an.",
            "Ich bin voller Angst.",
            "Die Nervosität macht mich fertig.",
            "Ich fühle mich ausgeliefert.",
            "Es wird immer schlimmer.",
            "Ich habe keine Kontrolle mehr.",
            "Alles ist chaotisch.",
            "Ich bin auf mich allein gestellt.",
            "Die Anspannung steigt.",
            "Ich fühle mich bedroht.",
            "Nichts ist sicher gerade.",
            "Ich bin rastlos.",
            "Alles wackelt unter mir.",
            "Ich fühle mich hilflos.",
            "Die Panik steigt.",
            "Ich bin so unruhig.",
            "Nirgendwo fühle ich mich zu Hause.",
            "Es ist alles so instabil gerade.",
        ],
    },
    "ATO_SATISFACTION_STATE": {
        "positive": [
            "Ich bin zufrieden mit dem Ergebnis.",
            "Mein Wohlbefinden ist gerade sehr gut.",
            "Ich bin stolz auf das, was wir erreicht haben.",
            "Mir geht es gut, danke.",
            "Ich fühle mich wohl in meiner Haut.",
            "Das tut mir gut, genau das habe ich gebraucht.",
            "Zufrieden schaue ich auf das Jahr zurück.",
            "Mein Wohlbefinden hat sich verbessert.",
            "Stolz präsentiere ich das Ergebnis.",
            "Mir geht es gut, ich bin ausgeglichen.",
            "Ich fühle mich rundum wohl.",
            "Tut gut, mal rauszukommen.",
            "Zufrieden bin ich mit meinem Fortschritt.",
            "Wohlbefinden ist mir wichtig.",
            "Stolz auf meinen Weg.",
            "Mir geht es gut heute.",
            "Ich fühle mich wohl bei euch.",
            "Das tut mir so gut, danke.",
            "Absolut zufrieden damit.",
            "Mein Wohlbefinden steigert sich.",
            "Stolz auf jedes Teammitglied.",
            "Mir geht es endlich wieder gut.",
            "Ich fühle mich wohl und sicher.",
            "Tut gut, das zu hören.",
            "Zufrieden mit der Zusammenarbeit.",
            "Wohlbefinden durch Bewegung.",
            "Ich bin sehr stolz darauf.",
            "Mir geht es richtig gut heute.",
            "Ich fühle mich wohl wie lange nicht.",
            "Das tut mir unglaublich gut.",
            "Zufrieden mit dem Feedback.",
            "Mein Wohlbefinden ist auf einem Hoch.",
            "Stolz auf die gemeinsame Leistung.",
            "Mir geht es gut, alles ist in Ordnung.",
            "Ich fühle mich wohl in dem Team.",
            "Tut gut, mal Pause zu machen.",
            "Zufrieden gehe ich nach Hause.",
            "Wohlbefinden durch gute Ernährung.",
            "Stolz, dass ich das geschafft habe.",
            "Mir geht es richtig gut seit dem Urlaub.",
            "Ich fühle mich wohl und geborgen.",
            "Das tut mir in der Seele gut.",
            "Ich bin zufrieden, wie es läuft.",
            "Wohlbefinden ist das Wichtigste.",
            "Stolz auf meine Entscheidung.",
            "Mir geht es gut, danke der Nachfrage.",
            "Ich fühle mich wohl mit meiner Wahl.",
            "Tut gut, endlich fertig zu sein.",
            "Zufrieden und dankbar.",
            "Stolz und glücklich zugleich.",
        ],
        "negative": [
            "Ich bin unzufrieden mit dem Ergebnis.",
            "Mir geht es nicht so gut.",
            "Ich fühle mich unwohl.",
            "Das stresst mich total.",
            "Ich bin frustriert.",
            "Es könnte besser laufen.",
            "Ich bin enttäuscht.",
            "Das hat mich genervt.",
            "Mir fehlt etwas.",
            "Ich bin gestresst und müde.",
            "Das Ergebnis ist mittelmäßig.",
            "Ich bin nicht happy damit.",
            "Es bedrückt mich.",
            "Ich bin rastlos.",
            "Das entspricht nicht meinen Erwartungen.",
            "Ich fühle mich leer.",
            "Das war unter meinem Niveau.",
            "Ich bin unglücklich.",
            "Es läuft nicht rund.",
            "Ich bin angespannt.",
            "Das Feedback war schlecht.",
            "Ich bin ernüchtert.",
            "Es fehlt an Motivation.",
            "Ich bin nicht zufrieden.",
            "Mir geht es mäßig.",
        ],
    },
    "ATO_SD_BEIGE_LEX": {
        "positive": [
            "Sicherheit geht vor, immer.",
            "Überleben ist das Wichtigste.",
            "Ich brauche Nahrung und ein Dach über dem Kopf.",
            "Die Gefahr ist überall.",
            "Ich brauche Ruhe, einfach nur Ruhe.",
            "Sicherheit für meine Familie.",
            "Ums Überleben kämpfen wir jeden Tag.",
            "Nahrung und Wasser müssen reichen.",
            "Gefahr droht von allen Seiten.",
            "Ruhe ist das, was ich am meisten vermisse.",
            "Mir geht es um pure Sicherheit.",
            "Überleben in schwierigen Zeiten.",
            "Nahrung zu finden ist die Priorität.",
            "Die Gefahr lauert überall.",
            "Endlich etwas Ruhe gefunden.",
            "Sicherheit ist ein Grundbedürfnis.",
            "Überleben steht an erster Stelle.",
            "Genug Nahrung für alle.",
            "Die Gefahr ist real.",
            "In Ruhe gelassen werden, das ist alles.",
            "Sicherheit für die Kinder.",
            "Wir überleben das zusammen.",
            "Nahrung beschaffen für morgen.",
            "Gefahr erkannt, Gefahr gebannt.",
            "Ruhe und Frieden, mehr brauche ich nicht.",
            "Sicherheit am Arbeitsplatz.",
            "Überleben in der Wildnis.",
            "Nahrung ist knapp.",
            "Die Gefahr unterschätzen wir.",
            "Ruhe vor dem Sturm.",
            "Sicherheit im Straßenverkehr.",
            "Überleben ohne Hilfe.",
            "Nahrung sicherstellen.",
            "Keine Gefahr in Sicht.",
            "Innere Ruhe finden.",
            "Sicherheit durch Gemeinschaft.",
            "Wir überleben Krisen.",
            "Nahrung und Schutz.",
            "Die Gefahr ist gebannt.",
            "Ruhe kehrt ein.",
            "Sicherheit geben.",
            "Überleben heißt Anpassen.",
            "Nahrungsvorräte anlegen.",
            "Gefahr für Leib und Leben.",
            "Ruhe bewahren.",
            "Ohne Sicherheit geht nichts.",
            "Überleben als Instinkt.",
            "Nahrung teilen.",
            "Gefahr und Angst.",
            "Ruhe ist Luxus.",
        ],
        "negative": [
            "Ich optimiere meinen Workflow.",
            "Das System braucht mehr Integration.",
            "Wir brauchen eine holistische Perspektive.",
            "Konsens im Team ist wichtig.",
            "Die KPIs sehen gut aus.",
            "Wir leben in einer komplexen Welt.",
            "Ordnung muss sein.",
            "Respekt ist die Grundlage.",
            "Lass uns das analysieren.",
            "Wir brauchen eine Strategie.",
            "Innovation treibt uns an.",
            "Empathie zeigen.",
            "Leistung zählt.",
            "Die Tradition bewahren.",
            "Kontextwechsel beachten.",
            "Gemeinschaft pflegen.",
            "Ergebnisse liefern.",
            "Ahnen ehren.",
            "Ganzheit anstreben.",
            "Macht demonstrieren.",
            "Verbundenheit spüren.",
            "Regeln befolgen.",
            "Pflicht erfüllen.",
            "Ziele erreichen.",
            "Harmonie schaffen.",
        ],
    },
    "ATO_SD_BLUE_LEX": {
        "positive": [
            "Ordnung muss sein.",
            "Es ist meine Pflicht.",
            "Die Regel ist klar.",
            "Autorität muss respektiert werden.",
            "Gehorsam ist eine Tugend.",
            "Ordnung im Büro schaffen.",
            "Pflichtbewusstsein zeigen.",
            "Regeln sind Regeln.",
            "Die Autorität anerkennen.",
            "Gehorsam gegenüber dem Vorgesetzten.",
            "Ordnung und Struktur sind mir wichtig.",
            "Es ist meine Pflicht und Schuldigkeit.",
            "Regeln einhalten ist selbstverständlich.",
            "Autorität hat ihren Platz.",
            "Gehorsam ohne Murren.",
            "Ordnung halten im Haushalt.",
            "Die Pflicht ruft.",
            "Jede Regel hat ihren Grund.",
            "Autorität braucht man im Team.",
            "Gehorsam gegenüber den Gesetzen.",
            "Ordnung in den Finanzen.",
            "Es ist unsere Pflicht, das zu melden.",
            "Regeln brechen geht nicht.",
            "Autorität und Verantwortung gehören zusammen.",
            "Gehorsam ist keine Schwäche.",
            "Ordnung schaffen, Chaos beseitigen.",
            "Pflicht geht vor Vergnügen.",
            "Regeln geben Sicherheit.",
            "Autorität muss man sich verdienen.",
            "Gehorsam als Wert.",
            "Ordnung im Kopf.",
            "Es ist die Pflicht jedes Einzelnen.",
            "Klare Regeln, klare Verhältnisse.",
            "Die Autorität des Richters.",
            "Gehorsam gegenüber dem Trainer.",
            "Ordnung und Disziplin.",
            "Pflichterfüllung ist ehrenvoll.",
            "Regeln respektieren.",
            "Autorität ist notwendig.",
            "Gehorsam üben.",
            "Ordnung ist das halbe Leben.",
            "Pflicht und Ehre.",
            "Die goldene Regel.",
            "Autorität akzeptieren.",
            "Gehorsam lernen.",
            "Ordnung am Schreibtisch.",
            "Es ist meine verdammte Pflicht.",
            "Regeln aufstellen und durchsetzen.",
            "Autorität zeigen.",
            "Gehorsam und Respekt.",
        ],
        "negative": [
            "Lass uns das mal locker angehen.",
            "Regeln sind dazu da, gebrochen zu werden.",
            "Ich mache das auf meine Art.",
            "Freiheit ist mir wichtiger.",
            "Ich lasse mich nicht einengen.",
            "Spontanität ist mein Ding.",
            "Autoritäten hinterfrage ich.",
            "Flexibilität ist wichtiger als Struktur.",
            "Ich brauche keine Vorschriften.",
            "Kreativität braucht Freiheit.",
            "Ich bestimme selbst.",
            "Kein Bock auf Hierarchien.",
            "Ich mache mein eigenes Ding.",
            "Regeln sind nur Empfehlungen.",
            "Ich bin mein eigener Chef.",
            "Spontan entscheiden.",
            "Ich rebelliere gegen Autoritäten.",
            "Flexibel bleiben.",
            "Regeln einhalten nervt mich.",
            "Ich brauche Freiraum.",
            "Anarchie als Lebensform.",
            "Ich folge meinem Herzen.",
            "Vorschriften bremsen mich aus.",
            "Ich lebe nach meinen Regeln.",
            "Strukturen einreißen.",
        ],
    },
    "ATO_SD_GREEN_LEX": {
        "positive": [
            "Empathie ist die wichtigste Eigenschaft.",
            "Wir brauchen Konsens im Team.",
            "Alle sind gleichwertig.",
            "Gemeinschaft stärkt uns.",
            "Teilen macht glücklich.",
            "Empathie zeigen in schwierigen Zeiten.",
            "Konsens finden statt abstimmen.",
            "Gleichwertig behandelt werden.",
            "Die Gemeinschaft zusammenhalten.",
            "Wir teilen die Verantwortung.",
            "Empathie als Grundlage der Kommunikation.",
            "Im Konsens entscheiden.",
            "Alle Stimmen sind gleichwertig.",
            "Gemeinschaft erleben.",
            "Ressourcen teilen.",
            "Mehr Empathie in der Welt.",
            "Konsens ist mir wichtig.",
            "Gleichwertiger Umgang miteinander.",
            "Die Gemeinschaft trägt uns.",
            "Wissen teilen.",
            "Empathie gegenüber Fremden.",
            "Im Konsens arbeiten.",
            "Gleichwertige Partnerschaft.",
            "Gemeinschaft vor Individuum.",
            "Erfahrungen teilen.",
            "Empathie für die Schwächeren.",
            "Den Konsens suchen.",
            "Gleichwertige Bezahlung.",
            "Gemeinschaftsgefühl stärken.",
            "Freude teilen.",
            "Empathie entwickeln.",
            "Konsens als Ziel.",
            "Gleichwertig am Tisch sitzen.",
            "In Gemeinschaft leben.",
            "Sorgen teilen.",
            "Ohne Empathie geht es nicht.",
            "Konsens unter den Parteien.",
            "Gleichwertige Rechte für alle.",
            "Gemeinschaft ist Stärke.",
            "Aufgaben teilen.",
            "Empathie-Training für Führungskräfte.",
            "Konsens-Kultur etablieren.",
            "Gleichwertiger Dialog.",
            "Gemeinschaftsarbeit.",
            "Das Brot teilen.",
            "Empathie als Schlüssel.",
            "Im Konsens zusammenleben.",
            "Gleichwertige Bildungschancen.",
            "Gemeinschaft und Solidarität.",
            "Teilen ist Kümmern.",
        ],
        "negative": [
            "Ich setze mich durch.",
            "Wettbewerb ist der Motor.",
            "Jeder für sich.",
            "Stärke zeigen.",
            "Leistung zählt, nicht Gefühle.",
            "Ich bin besser als die anderen.",
            "Konkurrenz belebt.",
            "Sieg oder Niederlage.",
            "Einzelleistung wird belohnt.",
            "Gefühle haben im Business nichts verloren.",
            "Ich mache mein Ding.",
            "Schwäche zeigen ist keine Option.",
            "Der Stärkere gewinnt.",
            "Profit geht vor.",
            "Mitgefühl bremst nur.",
            "Ich brauche niemanden.",
            "Allein bin ich schneller.",
            "Hierarchie ist wichtig.",
            "Ergebnis zählt, nicht der Weg.",
            "Hart bleiben.",
            "Nur die Besten überleben.",
            "Ich verfolge meine Ziele.",
            "Emotionen rauslassen ist unprofessionell.",
            "Jeder kämpft für sich.",
            "Leistungsgesellschaft funktioniert.",
        ],
    },
    "ATO_SD_ORANGE_LEX": {
        "positive": [
            "Wir müssen klare Ziele setzen.",
            "Leistung bringt uns weiter.",
            "Die KPIs stimmen.",
            "Ergebnisse sprechen für sich.",
            "Wir müssen den Prozess optimieren.",
            "Gewinnen ist das Ziel.",
            "Ziele setzen und erreichen.",
            "Leistung wird belohnt.",
            "KPIs tracken und auswerten.",
            "Ergebnisse liefern, das zählt.",
            "Ständig optimieren.",
            "Wir wollen gewinnen.",
            "Neue Ziele setzen nach dem Erfolg.",
            "Höchstleistung abrufen.",
            "Unsere KPIs sind im grünen Bereich.",
            "Die Ergebnisse übertreffen die Erwartungen.",
            "Weiter optimieren, da geht noch mehr.",
            "Am Ende zählt: gewinnen.",
            "Ambitionierte Ziele setzen.",
            "Leistungsträger im Team.",
            "KPIs als Steuerungsinstrument.",
            "Ergebnisse messbar machen.",
            "Kosten optimieren.",
            "Fair gewinnen, hart kämpfen.",
            "Ziele klar definieren.",
            "Leistungsorientiert arbeiten.",
            "KPIs monatlich reviewen.",
            "Ergebnisse präsentieren.",
            "Prozesse weiter optimieren.",
            "Gewinnen wollen und können.",
            "Realistische Ziele setzen.",
            "Spitzenleistung abliefern.",
            "KPIs an die Strategie anpassen.",
            "Ergebnisse im Quartalsbericht.",
            "Abläufe optimieren.",
            "Marktanteile gewinnen.",
            "Ziele setzen, Ziele erreichen.",
            "Leistung auf dem Prüfstand.",
            "KPIs für das nächste Quartal.",
            "Ergebnisse vergleichen.",
            "Supply Chain optimieren.",
            "Neukunden gewinnen.",
            "Individuelle Ziele setzen.",
            "Leistung steigern.",
            "KPIs übertreffen.",
            "Ergebnisse in Zahlen.",
            "SEO optimieren.",
            "Vertrauen gewinnen.",
            "Strategische Ziele setzen.",
            "Leistungsbereitschaft zeigen.",
        ],
        "negative": [
            "Der Weg ist das Ziel.",
            "Gemeinschaft ist wichtiger als Erfolg.",
            "Ich brauche keine Zahlen.",
            "Einfach sein reicht mir.",
            "Nicht alles muss messbar sein.",
            "Entspannung ist wichtig.",
            "Ich mache mir keinen Druck.",
            "Qualität vor Quantität.",
            "Wir lassen uns Zeit.",
            "Es geht nicht ums Gewinnen.",
            "Genügsamkeit ist auch eine Tugend.",
            "Ich bin zufrieden mit wenig.",
            "Nicht alles muss effizienter werden.",
            "Einfach mal abschalten.",
            "Zahlen sind nicht alles.",
            "Ich lebe im Moment.",
            "Ohne Druck arbeiten.",
            "Es geht um Menschen, nicht um Metriken.",
            "Entschleunigung statt Optimierung.",
            "Weniger ist mehr.",
            "Ruhe statt Hektik.",
            "Genießen statt performen.",
            "Beziehungen sind wichtiger als KPIs.",
            "Ich arbeite ohne Zeitdruck.",
            "Erfolg definiere ich anders.",
        ],
    },
    "ATO_SD_PURPLE_LEX": {
        "positive": [
            "Der Stamm hält zusammen.",
            "Unsere Ahnen haben das so gemacht.",
            "Das Ritual verbindet uns.",
            "Schutz suchen wir in der Gemeinschaft.",
            "Magie liegt in der Luft.",
            "Zum Stamm gehören ist mir wichtig.",
            "Die Ahnen wachen über uns.",
            "Rituale geben mir Halt.",
            "Schutz durch die Familie.",
            "Magie der Natur.",
            "Der Stamm ist alles.",
            "Ahnen-Verehrung praktizieren.",
            "Ein Ritual der Verbundenheit.",
            "Schutz und Geborgenheit.",
            "Die Magie der Tradition.",
            "Stammeszugehörigkeit ist fundamental.",
            "Die Weisheit der Ahnen.",
            "Rituale im Jahreskreis.",
            "Schutz durch Zugehörigkeit.",
            "Magische Momente erleben.",
            "Der Stamm als Rückhalt.",
            "Ahnen ehren und erinnern.",
            "Rituale für den Übergang.",
            "Schutz bieten und empfangen.",
            "Magie in kleinen Dingen.",
            "Zusammenhalt im Stamm.",
            "Ahnenforschung betreiben.",
            "Tägliche Rituale pflegen.",
            "Schutz vor dem Unbekannten.",
            "Magie und Mystik.",
            "Der Stamm als Identität.",
            "Ahnen-Rituale feiern.",
            "Das Ritual des Erzählens.",
            "Schutz-Amulett tragen.",
            "Die Magie des Feuers.",
            "Im Stamm aufwachsen.",
            "Ahnen und Traditionen.",
            "Ritual am Vollmond.",
            "Schutz durch Glauben.",
            "Magische Kraft der Natur.",
            "Der Stamm gibt Sicherheit.",
            "Ahnen-Weisheit weitergeben.",
            "Rituale der Heilung.",
            "Schutz-Zeichen an der Tür.",
            "Magie der Musik.",
            "Stamm und Sippe.",
            "Die Ahnen rufen.",
            "Ritual der Reinigung.",
            "Schutz-Kreis ziehen.",
            "Die Magie der Worte.",
        ],
        "negative": [
            "Ich handle rational.",
            "Fakten zählen.",
            "Wissenschaft ist der Weg.",
            "Ich glaube an Beweise.",
            "Logik bestimmt mein Handeln.",
            "Daten analysieren.",
            "Evidenzbasiert arbeiten.",
            "Mystik ist mir fremd.",
            "Ich brauche keine Rituale.",
            "Vernunft über alles.",
            "Ich bin Individualist.",
            "Tradition ist mir egal.",
            "Ich entscheide selbst.",
            "Aberglaube lehne ich ab.",
            "Ich brauche keine Gruppe.",
            "Objektiv bleiben.",
            "Zahlen statt Gefühle.",
            "Ich glaube an Fortschritt.",
            "Innovation statt Tradition.",
            "Rationalität ist mein Leitbild.",
            "Ich bin skeptisch.",
            "Keine mystischen Erklärungen.",
            "Ich setze auf Technologie.",
            "Empirie statt Glaube.",
            "Moderne statt Vergangenheit.",
        ],
    },
    "ATO_SD_RED_LEX": {
        "positive": [
            "Ich setze mich durch, Stärke zählt.",
            "Wer nicht hört, kriegt Druck.",
            "Kontrolle behalten, sofort.",
            "Respekt erzwingen, wenn nötig.",
            "Dominanz zeigen in jeder Situation.",
            "Macht ist alles.",
            "Kontrolle über die Situation.",
            "Stärke beweisen.",
            "Respekt erzwingen durch Härte.",
            "Durchsetzen, egal wie.",
            "Macht ausüben.",
            "Kontrolle ist mir wichtig.",
            "Stärke zeigen, Schwäche verbergen.",
            "Respekt verschaffen.",
            "Dominanz im Gespräch.",
            "Machtspiele beherrschen.",
            "Kontrolle nie abgeben.",
            "Stärke ist Überlebensvorteil.",
            "Respekt erzwingen durch Präsenz.",
            "Sich durchsetzen können.",
            "Machtposition verteidigen.",
            "Kontrolle über andere.",
            "Innere Stärke mobilisieren.",
            "Respekt einfordern.",
            "Dominanz ausstrahlen.",
            "Macht demonstrieren.",
            "Kontrolle über die Finanzen.",
            "Stärke in der Krise.",
            "Respekt erzwingen durch Leistung.",
            "Sich gegen alle durchsetzen.",
            "Macht und Einfluss.",
            "Kontrolle über den Prozess.",
            "Körperliche Stärke trainieren.",
            "Respekt verdienen und erzwingen.",
            "Dominanz im Raum.",
            "Machtgefüge verstehen.",
            "Kontrolle übernehmen.",
            "Mentale Stärke aufbauen.",
            "Respekt durch Taten erzwingen.",
            "Durchsetzungsvermögen.",
            "Macht ergreifen.",
            "Die Kontrolle behalten.",
            "Stärke unter Beweis stellen.",
            "Respekt erzwingen, wenn es sein muss.",
            "Dominanz signalisieren.",
            "An der Macht bleiben.",
            "Volle Kontrolle.",
            "Stärke zeigen, nicht jammern.",
            "Respekt ist nicht verhandelbar.",
            "Sich durchsetzen und gewinnen.",
        ],
        "negative": [
            "Lass uns zusammenarbeiten.",
            "Wir finden gemeinsam eine Lösung.",
            "Empathie ist mir wichtig.",
            "Ich höre dir zu.",
            "Gleichberechtigung für alle.",
            "Gewaltfrei kommunizieren.",
            "Miteinander statt gegeneinander.",
            "Ich gebe nach.",
            "Kompromisse sind wichtig.",
            "Sanftmut als Stärke.",
            "Ich bin nachgiebig.",
            "Zusammenarbeit funktioniert besser.",
            "Verhandeln statt kämpfen.",
            "Ich respektiere deine Grenzen.",
            "Dialog statt Konfrontation.",
            "Ich lasse los.",
            "Weichheit ist keine Schwäche.",
            "Ich unterstütze dich.",
            "Friedlich miteinander.",
            "Ich mache einen Schritt zurück.",
            "Kooperation statt Konkurrenz.",
            "Ich höre erst mal zu.",
            "Lass uns vermitteln.",
            "Ich gebe dir Raum.",
            "Gemeinsam sind wir stärker.",
        ],
    },
    "ATO_SD_TURQUOISE_LEX": {
        "positive": [
            "Ganzheit ist mein Ziel.",
            "Kohärenz in allen Lebensbereichen.",
            "Verbundenheit mit allem spüren.",
            "Das Feld beeinflusst uns alle.",
            "Kollektives Bewusstsein erwacht.",
            "Ganzheitlich denken und handeln.",
            "Kohärenz herstellen.",
            "Verbundenheit erleben.",
            "Im morphischen Feld.",
            "Kollektiv handeln.",
            "Ganzheit anstreben in allem.",
            "Kohärenz zwischen Herz und Verstand.",
            "Tiefe Verbundenheit mit der Natur.",
            "Das Feld der Möglichkeiten.",
            "Kollektive Intelligenz nutzen.",
            "Die Ganzheit des Systems.",
            "Kohärenz in der Organisation.",
            "Verbundenheit untereinander.",
            "Das energetische Feld.",
            "Kollektives Wohlbefinden.",
            "Ganzheit in Körper und Geist.",
            "Kohärente Kommunikation.",
            "Verbundenheit als Grundgefühl.",
            "Das Feld spüren.",
            "Kollektiver Wandel.",
            "Ganzheitliche Medizin.",
            "Kohärenz im Team.",
            "Verbundenheit mit dem Kosmos.",
            "Das Feld der Resonanz.",
            "Kollektive Weisheit.",
            "Ganzheit erleben.",
            "Kohärenz im Handeln.",
            "Verbundenheit mit der Erde.",
            "Im Feld sein.",
            "Kollektiv denken.",
            "Ganzheit als Prinzip.",
            "Kohärenz im Leben.",
            "Verbundenheit spüren im Alltag.",
            "Das Feld der Heilung.",
            "Kollektive Transformation.",
            "Ganzheitlicher Ansatz.",
            "Kohärenz zwischen Denken und Fühlen.",
            "Verbundenheit als Lebensform.",
            "Das Feld öffnet sich.",
            "Kollektive Verantwortung.",
            "Ganzheit in der Therapie.",
            "Kohärenz als Ziel.",
            "Verbundenheit mit allen Wesen.",
            "Im Feld der Liebe.",
            "Kollektives Erwachen.",
        ],
        "negative": [
            "Ich denke nur an mich.",
            "Das geht mich nichts an.",
            "Jeder für sich.",
            "Ich kümmere mich um meins.",
            "Das ist nicht mein Problem.",
            "Ich bin Realist.",
            "Esoterik ist Quatsch.",
            "Ich glaube an Fakten.",
            "Jeder ist seines Glückes Schmied.",
            "Ich brauche keine spirituelle Erfahrung.",
            "Eigenverantwortung, nicht Kollektiv.",
            "Ich bin unabhängig.",
            "Das ist nicht wissenschaftlich.",
            "Ich setze auf mich allein.",
            "Individualismus ist mein Weg.",
            "Fakten statt Gefühle.",
            "Ich bleibe pragmatisch.",
            "Keine esoterischen Ansätze.",
            "Jeder ist für sich verantwortlich.",
            "Ich glaube, was ich sehe.",
            "Selbstständig denken.",
            "Das ist mir zu abstrakt.",
            "Ich konzentriere mich auf Konkretes.",
            "Spiritualität ist nichts für mich.",
            "Ich bleibe bei den Fakten.",
        ],
    },
    "ATO_SD_YELLOW_LEX": {
        "positive": [
            "Das System ist komplex.",
            "Komplexität erfordert neue Ansätze.",
            "Im Kontext betrachtet ergibt das Sinn.",
            "Integration aller Perspektiven ist nötig.",
            "Auf der Meta-Ebene sehe ich Muster.",
            "Systemisch denken.",
            "Die Komplexität reduzieren.",
            "Den Kontext verstehen.",
            "Integration verschiedener Ansätze.",
            "Meta-Perspektive einnehmen.",
            "Das System verstehen.",
            "Komplexität managen.",
            "Kontext ist alles.",
            "Integration als Schlüssel.",
            "Meta-Analyse durchführen.",
            "Systemisches Coaching.",
            "In Komplexität navigieren.",
            "Den Kontext berücksichtigen.",
            "Integrationsfähigkeit zeigen.",
            "Meta-Kommunikation nutzen.",
            "Das System als Ganzes.",
            "Komplexität akzeptieren.",
            "Im richtigen Kontext.",
            "Integration von Wissen.",
            "Meta-Kognition trainieren.",
            "Systemdenken lernen.",
            "Komplexität als Chance.",
            "Kontext wechseln.",
            "Integration unterschiedlicher Kulturen.",
            "Meta-Ebene betrachten.",
            "System-Architektur designen.",
            "Komplexität durchdringen.",
            "Im kulturellen Kontext.",
            "Integration in den Alltag.",
            "Meta-Reflexion üben.",
            "Systemische Beratung.",
            "Die Komplexität meistern.",
            "Kontext analysieren.",
            "Integration als Prozess.",
            "Meta-Perspektive hilft.",
            "Das System hinterfragen.",
            "Komplexität wertschätzen.",
            "Ohne Kontext kein Verständnis.",
            "Integration fördern.",
            "Meta-Level.",
            "Systemrelevant denken.",
            "Hohe Komplexität.",
            "Den Kontext nicht vergessen.",
            "Integration gelingt.",
            "Meta und darüber hinaus.",
        ],
        "negative": [
            "Das ist ganz einfach.",
            "Schwarz oder weiß.",
            "Entweder oder.",
            "Das ist doch klar.",
            "Da gibt es keine Diskussion.",
            "So ist es und nicht anders.",
            "Einfache Lösung für ein einfaches Problem.",
            "Das ist simpel.",
            "Ohne Wenn und Aber.",
            "Das ist offensichtlich.",
            "Ich mache das schon immer so.",
            "Das war schon immer so.",
            "Kein Grund, das zu hinterfragen.",
            "One size fits all.",
            "So läuft das hier.",
            "Punkt.",
            "Fertig, aus.",
            "Das ist Fakt.",
            "Schwarz auf weiß.",
            "Das braucht keine Analyse.",
            "Einfach machen.",
            "Da gibt es nichts zu diskutieren.",
            "Das ist trivial.",
            "Offensichtlich.",
            "Klar wie Kloßbrühe.",
        ],
    },
}
