"""Batch 3: ATO_REPETITIVE_CHECKING_LANGUAGE through ATO_RIDDLE_PATTERN (10 markers)"""

EXAMPLES = {
    "ATO_REPETITIVE_CHECKING_LANGUAGE": {
        "positive": [
            "Ich muss das nochmal checken, ob alles stimmt.",
            "Lass mich das noch einmal überprüfen.",
            "Ich muss nochmal nachschauen, ob alles perfekt ist.",
            "Check again: Ist die Tür wirklich zu?",
            "Das muss perfekt sein, lass mich nochmal schauen.",
            "Ich wiederhole das lieber noch einmal.",
            "Double-check: Hast du den Herd ausgemacht?",
            "One more time, lass mich nochmal prüfen.",
            "Ich kontrolliere das lieber noch einmal.",
            "Nochmal checken, ob die Mail raus ist.",
            "Das muss ich wiederholen, um sicherzugehen.",
            "Lass mich das nochmal double-checken.",
            "Hast du wirklich abgeschlossen? Check nochmal.",
            "Ich muss das nochmal kontrollieren.",
            "Das muss alles perfekt stimmen.",
            "Lass mich one more time drüberschauen.",
            "Ich check das nochmal, sicher ist sicher.",
            "Repeat: Ist das Fenster zu?",
            "Nochmal prüfen, ob die Zahlen stimmen.",
            "Double-check bitte die Adresse.",
            "Ich schaue nochmal nach, ob alles passt.",
            "One more time: Stimmt die Uhrzeit?",
            "Das muss perfekt sein, nochmal checken.",
            "Lass mich das wiederholen, zur Sicherheit.",
            "Habe ich das Licht ausgemacht? Nochmal checken.",
            "Double-check: Alle Anhänge dabei?",
            "Ich prüfe das lieber noch einmal.",
            "One more time: Sind alle Teilnehmer eingeladen?",
            "Das muss perfekt sein, deshalb nochmal.",
            "Repeat: Passwort richtig eingegeben?",
            "Nochmal schauen, ob der Drucker funktioniert.",
            "Check again: Termin steht wirklich?",
            "Ich muss das nochmal durchgehen.",
            "Double-check: Wurde die Rechnung bezahlt?",
            "Lieber nochmal kontrollieren.",
            "One more time: Ist der Alarm eingeschaltet?",
            "Das muss alles stimmen, nochmal prüfen.",
            "Repeat: Habe ich die richtige Datei gespeichert?",
            "Nochmal checken, ob der Zugang funktioniert.",
            "Check again: Ist das Backup durchgelaufen?",
            "Ich überprüfe das sicherheitshalber nochmal.",
            "Double-check: Stimmen die Kontodaten?",
            "Lieber one more time drüber schauen.",
            "Nochmal, ob die Adresse richtig ist.",
            "Repeat: Ist das Mikro an?",
            "Check nochmal die Rechtschreibung.",
            "Ich muss das perfekt haben.",
            "Double-check: Alle Seiten gedruckt?",
            "One more time: Stimmt der Betrag?",
            "Nochmal kontrollieren, ob nichts fehlt.",
        ],
        "negative": [
            "Das passt so, weitermachen.",
            "Einmal prüfen reicht.",
            "Ich vertraue darauf, dass es stimmt.",
            "Das habe ich schon gecheckt.",
            "Alles in Ordnung, kein Grund zur Sorge.",
            "Passt, nächstes Thema.",
            "Ich bin mir sicher, das stimmt.",
            "Kein Bedarf, nochmal zu schauen.",
            "Das ist erledigt.",
            "Ich vertraue meiner Arbeit.",
            "Ein Blick reicht.",
            "Das ist gut genug.",
            "Fertig, weiter geht's.",
            "Ich mach mir da keine Sorgen.",
            "Das stimmt schon so.",
            "Hab ich einmal geprüft, passt.",
            "Kein Grund zur Panik.",
            "Einmal reicht.",
            "Ich bin zufrieden damit.",
            "Alles gecheckt, alles gut.",
            "Das lasse ich jetzt so.",
            "Perfekt muss es nicht sein.",
            "Good enough.",
            "Ich vertraue dem Prozess.",
            "Das ist okay so.",
        ],
    },
    "ATO_REQUEST_FOR_FEEDBACK": {
        "positive": [
            "Kannst du mir Feedback geben?",
            "Wie wirkt das auf dich?",
            "Kannst du mir spiegeln, was du siehst?",
            "Ich hätte gerne eine Rückmeldung.",
            "Wie findest du meine Arbeit?",
            "Feedback wäre mir jetzt wichtig.",
            "Kannst du mir sagen, wie das ankommt?",
            "Wie wirkt mein Vorschlag auf dich?",
            "Kannst du das kurz spiegeln?",
            "Ich brauche deine Rückmeldung.",
            "Feedback geben, bitte, wie war das?",
            "Wie wirkt das auf euch?",
            "Kannst du mir ehrliches Feedback geben?",
            "Eine Rückmeldung wäre hilfreich.",
            "Wie wirkt meine Präsentation auf dich?",
            "Feedback von dir wäre mir wichtig.",
            "Kannst du spiegeln, was du wahrgenommen hast?",
            "Ich möchte gerne eine Rückmeldung haben.",
            "Wie wirkt das insgesamt?",
            "Kannst du mir konstruktives Feedback geben?",
            "Eine ehrliche Rückmeldung bitte.",
            "Wie wirkt mein Text?",
            "Feedback geben: Was denkst du?",
            "Kannst du mir spiegeln, wie ich gewirkt habe?",
            "Rückmeldung erwünscht.",
            "Wie wirkt das Design auf dich?",
            "Ich hätte gern Feedback dazu.",
            "Kannst du mir eine Rückmeldung geben?",
            "Wie wirkt das auf außenstehende Personen?",
            "Dein Feedback wäre mir sehr wichtig.",
            "Kannst du spiegeln, was angekommen ist?",
            "Eine Rückmeldung zum Entwurf bitte.",
            "Wie wirkt mein Auftreten?",
            "Feedback geben: Ist das verständlich?",
            "Kannst du mir Rückmeldung zum Konzept geben?",
            "Wie wirkt das auf dich als Außenstehenden?",
            "Ich bitte um ehrliches Feedback.",
            "Kannst du mir spiegeln, wie das wirkt?",
            "Eine kurze Rückmeldung wäre toll.",
            "Wie wirkt das Anschreiben?",
            "Feedback bitte: Ist der Ton richtig?",
            "Kannst du mir deine Rückmeldung geben?",
            "Wie wirkt mein Vorschlag auf das Team?",
            "Ich brauche Feedback zu meinem Plan.",
            "Kannst du spiegeln, wie das bei dir ankommt?",
            "Eine Rückmeldung zum Prozess hätte ich gern.",
            "Wie wirkt die neue Struktur auf dich?",
            "Gib mir bitte Feedback dazu.",
            "Kannst du mir eine ehrliche Rückmeldung geben?",
            "Deine Rückmeldung ist mir wichtig.",
        ],
        "negative": [
            "Ich mache das einfach so.",
            "Mir ist egal, was andere denken.",
            "Das entscheide ich allein.",
            "Ich brauche keine Meinung dazu.",
            "Das steht fest.",
            "Ich weiß selbst, was gut ist.",
            "Darüber muss ich nicht diskutieren.",
            "Das ist meine Sache.",
            "Ich bin zufrieden damit.",
            "Das lass ich so.",
            "Meine Entscheidung, mein Ding.",
            "Das bewerte ich selbst.",
            "Ich brauche da keinen Input.",
            "Das habe ich durchdacht.",
            "Fertig, keine Diskussion.",
            "Das steht so fest.",
            "Ich weiß, was ich will.",
            "Darüber rede ich nicht.",
            "Mein Plan, meine Regeln.",
            "Das passt so für mich.",
            "Ich vertraue meinem Urteil.",
            "Da gibt es nichts zu diskutieren.",
            "Das bleibt so.",
            "Ich habe mich entschieden.",
            "Kein Diskussionsbedarf.",
        ],
    },
    "ATO_REQUEST_TRANSPARENCY": {
        "positive": [
            "Ich brauche mehr Transparenz in dem Prozess.",
            "Kannst du ehrlich zu mir sein?",
            "Ich wünsche mir mehr Offenheit.",
            "Wir brauchen Klarheit über die Situation.",
            "Erklär mir bitte, was da passiert ist.",
            "Ich möchte verstehen, was die Gründe sind.",
            "Bitte sei transparent mit mir.",
            "Ich brauche Ehrlichkeit von dir.",
            "Zeig mir offen, worum es geht.",
            "Wir brauchen mehr Klarheit.",
            "Erkläre mir bitte den Hintergrund.",
            "Ich möchte verstehen, warum das so ist.",
            "Transparenz ist mir sehr wichtig.",
            "Sei bitte ehrlich, auch wenn es unangenehm ist.",
            "Ich fordere Offenheit ein.",
            "Klarheit wäre jetzt hilfreich.",
            "Erklär mir das bitte genauer.",
            "Ich möchte die Wahrheit verstehen.",
            "Bitte leg die Karten offen auf den Tisch.",
            "Ehrlichkeit ist das Fundament.",
            "Offenheit erwarte ich in dieser Sache.",
            "Klarheit über die Kosten bitte.",
            "Erklär mir, warum du so entschieden hast.",
            "Ich möchte verstehen, was dahintersteckt.",
            "Transparenz im Budget ist unerlässlich.",
            "Ehrlichkeit zwischen uns ist mir wichtig.",
            "Offenheit wünsche ich mir.",
            "Klarheit brauche ich jetzt dringend.",
            "Erklär mir bitte die Zusammenhänge.",
            "Ich möchte alles offen verstehen.",
            "Bitte transparente Kommunikation.",
            "Ehrlichkeit gegenüber dem Team.",
            "Offenheit im Umgang miteinander.",
            "Mehr Klarheit über die Erwartungen.",
            "Erklär mir, was sich geändert hat.",
            "Ich möchte verstehen, wie das Ganze funktioniert.",
            "Zuhören und Transparenz schaffen.",
            "Ehrlichkeit, auch wenn es wehtut.",
            "Offenlegung der Fakten bitte.",
            "Klarheit über die nächsten Schritte.",
            "Erklär mir bitte den Plan.",
            "Ich wünsche mir, das ehrlich zu besprechen.",
            "Transparenz bei Entscheidungen.",
            "Ehrlich sein ist mir sehr wichtig.",
            "Offenheit bezüglich der Ergebnisse.",
            "Klarheit schaffen, bevor wir weitermachen.",
            "Bitte erklär mir das offen.",
            "Ich möchte verstehen und nicht raten müssen.",
            "Transparenz von Anfang an.",
            "Ehrlichkeit ist die Basis für Vertrauen.",
        ],
        "negative": [
            "Das geht dich nichts an.",
            "Darüber spreche ich nicht.",
            "Das muss ich nicht erklären.",
            "Vertrau mir einfach.",
            "Das ist vertraulich.",
            "Frag nicht so viel.",
            "Das wirst du schon sehen.",
            "Details sind nicht wichtig.",
            "Lass mich einfach machen.",
            "Ich rede nicht darüber.",
            "Das bleibt unter uns.",
            "Nicht alles muss erklärt werden.",
            "Vertrau dem Prozess.",
            "Manche Dinge bleiben geheim.",
            "Ich sage dir, was du wissen musst.",
            "Das ist nicht dein Problem.",
            "Dazu gibt es nichts zu sagen.",
            "Lass es einfach gut sein.",
            "Nicht jetzt.",
            "Keine weiteren Fragen.",
            "Das erfährst du noch früh genug.",
            "Geduld, alles zu seiner Zeit.",
            "Nicht alles muss transparent sein.",
            "Das regeln wir intern.",
            "Manche Dinge sind besser so.",
        ],
    },
    "ATO_RESIGNATION_METAPHOR": {
        "positive": [
            "Ich stecke den Kopf in den Sand.",
            "Ich hisse die weiße Fahne.",
            "Ich gebe auf, es hat keinen Sinn.",
            "Das Schiff ist am Sinken.",
            "Ich werfe das Handtuch.",
            "Der Zug ist abgefahren.",
            "Das Licht am Ende des Tunnels ist erloschen.",
            "Ich treibe im Strom ohne Ruder.",
            "Die Mauern fallen über mir zusammen.",
            "Ich stehe mit dem Rücken zur Wand.",
            "Die Uhr ist abgelaufen.",
            "Ich bin am Ende meiner Kräfte.",
            "Das Fass ist übergelaufen.",
            "Ich sitze in der Sackgasse.",
            "Die Luft ist raus.",
            "Ich bin auf dem sinkenden Schiff.",
            "Das Kartenhaus bricht zusammen.",
            "Ich stehe vor verschlossenen Türen.",
            "Die letzte Hoffnung ist verflogen.",
            "Ich hänge in der Luft.",
            "Mir sind die Hände gebunden.",
            "Ich bin am Boden.",
            "Der Wind hat sich gedreht.",
            "Ich renne gegen Windmühlen.",
            "Mein Akku ist leer.",
            "Ich bin ausgebrannt wie eine Kerze.",
            "Das Boot ist leck.",
            "Ich stehe im Regen.",
            "Die Brücke ist abgebrochen.",
            "Ich versinke im Treibsand.",
            "Die Flamme ist erloschen.",
            "Ich laufe ins Leere.",
            "Mir geht die Puste aus.",
            "Der Brunnen ist versiegt.",
            "Ich drehe mich im Kreis.",
            "Das Ruder ist mir entglitten.",
            "Ich stecke fest im Schlamm.",
            "Der letzte Strohhalm ist gebrochen.",
            "Ich bin am Verdursten in der Wüste.",
            "Die Segel sind gerissen.",
            "Ich stehe am Abgrund.",
            "Mir fehlt der Boden unter den Füßen.",
            "Das Gebäude steht auf wackeligem Fundament.",
            "Ich bin wie ein Schiff ohne Kompass.",
            "Die Kette ist gerissen.",
            "Ich schwimme gegen den Strom und verliere.",
            "Die Batterie ist leer.",
            "Ich bin am Ende des Weges angekommen.",
            "Das letzte Licht geht aus.",
            "Ich habe meine Munition verschossen.",
        ],
        "negative": [
            "Es gibt immer einen Weg.",
            "Ich gebe nicht auf.",
            "Da geht noch was.",
            "Ich sehe Licht am Ende des Tunnels.",
            "Neue Energie tanken und weitermachen.",
            "Ich kämpfe weiter.",
            "Der nächste Versuch wird besser.",
            "Ich glaube an eine Lösung.",
            "Es wird schon wieder.",
            "Kopf hoch und weiter.",
            "Morgen sieht alles anders aus.",
            "Ich finde einen neuen Weg.",
            "Das wird schon klappen.",
            "Ich bin optimistisch.",
            "Hindernisse machen stark.",
            "Ich schaffe das.",
            "Da geht noch mehr.",
            "Ich lasse mich nicht unterkriegen.",
            "Aufstehen und weitermachen.",
            "Jede Krise birgt eine Chance.",
            "Das wird besser.",
            "Ich bin motiviert.",
            "Wir packen das.",
            "Neuer Tag, neue Chance.",
            "Ich halte durch.",
        ],
    },
    "ATO_RESIGNATION_PHRASE": {
        "positive": [
            "Egal was ich tue, es ändert sich nichts.",
            "Es bringt nichts, das zu versuchen.",
            "Ich kann das nicht, es hat keinen Sinn.",
            "Ich schaffe das nie, egal wie sehr ich mich anstrenge.",
            "Keine Chance, das funktioniert bei mir nicht.",
            "Egal was ich probiere, es ist sinnlos.",
            "Es bringt nichts, sich anzustrengen.",
            "Ich kann das einfach nicht ändern.",
            "Ich schaffe das sowieso nie.",
            "Keine Chance für mich.",
            "Egal was ich tue, es wird nicht besser.",
            "Es bringt nichts mehr, darüber zu reden.",
            "Ich kann das nicht schaffen.",
            "Ich schaffe das nie alleine.",
            "Keine Chance, dass sich was ändert.",
            "Egal was ich versuche, es bleibt gleich.",
            "Es bringt nichts, noch mehr Energie reinzustecken.",
            "Ich kann das Ruder nicht mehr herumreißen.",
            "Ich schaffe das nie in der Zeit.",
            "Keine Chance, das zu retten.",
            "Egal was ich tue, ich versage immer.",
            "Es bringt nichts, es zu versuchen.",
            "Ich kann das nicht allein bewältigen.",
            "Ich schaffe das nie, bin einfach zu schwach.",
            "Keine Chance, das klappt nicht.",
            "Egal was kommt, es ändert sich nichts daran.",
            "Es bringt nichts, weiter zu hoffen.",
            "Ich kann das Schicksal nicht ändern.",
            "Ich schaffe es nie, ihre Erwartungen zu erfüllen.",
            "Keine Chance mehr für uns.",
            "Egal was passiert, ich verliere immer.",
            "Es bringt nichts, sich Mühe zu geben.",
            "Ich kann nichts mehr tun.",
            "Ich schaffe das niemals bis morgen.",
            "Keine Chance, dass mir jemand hilft.",
            "Egal was ich sage, es interessiert niemanden.",
            "Es bringt doch nichts.",
            "Ich kann das Problem nicht lösen.",
            "Ich schaffe das nicht mehr.",
            "Keine Chance bei diesem Arbeitsmarkt.",
            "Egal was ich tue, alle sind enttäuscht.",
            "Es bringt nichts, sich zu wehren.",
            "Ich kann mich nicht ändern.",
            "Ich schaffe das nie so gut wie die anderen.",
            "Keine Chance, daraus rauszukommen.",
            "Egal was ich anfasse, es geht schief.",
            "Es bringt nichts, darüber nachzudenken.",
            "Ich kann das einfach nicht.",
            "Ich schaffe das nie im Leben.",
            "Keine Chance, mich zu retten.",
        ],
        "negative": [
            "Ich versuche es nochmal.",
            "Vielleicht klappt es beim nächsten Mal.",
            "Ich gebe nicht so schnell auf.",
            "Es lohnt sich, weiterzumachen.",
            "Ich habe noch Hoffnung.",
            "Das wird schon werden.",
            "Ich kämpfe weiter.",
            "Es gibt immer eine Möglichkeit.",
            "Ich bin zuversichtlich.",
            "Aufgeben ist keine Option.",
            "Ich schaffe das, wenn ich dranbleibe.",
            "Es gibt schlimmeres.",
            "Ich bin optimistisch.",
            "Jeder Versuch zählt.",
            "Schritt für Schritt.",
            "Ich glaube an mich.",
            "Das ist machbar.",
            "Weitermachen lohnt sich.",
            "Morgen wird besser.",
            "Ich vertraue dem Prozess.",
            "Es lohnt sich, nicht aufzugeben.",
            "Ich werde es schaffen.",
            "Rückschläge gehören dazu.",
            "Ich bin stärker als ich denke.",
            "Dranbleiben zahlt sich aus.",
        ],
    },
    "ATO_RESPONSIBILITY_CLAIM": {
        "positive": [
            "Ich übernehme die Verantwortung dafür.",
            "Die Verantwortung liegt bei mir.",
            "Ich nehme das auf meine Kappe.",
            "Das geht auf mein Konto.",
            "Ich stehe dafür gerade.",
            "Ich übernehme die volle Verantwortung.",
            "Das war meine Entscheidung, die Verantwortung liegt bei mir.",
            "Ich nehme das auf mich.",
            "Ich übernehme die Konsequenzen.",
            "Die Verantwortung dafür trage ich allein.",
            "Ich nehme das auf meine Kappe, kein Problem.",
            "Ich übernehme die Verantwortung für das Ergebnis.",
            "Die Verantwortung liegt ganz klar bei mir.",
            "Ich stehe dafür ein.",
            "Ich nehme das auf meine Kappe, egal was passiert.",
            "Ich übernehme die Verantwortung für mein Team.",
            "Die Verantwortung liegt bei mir als Projektleiter.",
            "Ich nehme das auf meine Kappe und lerne daraus.",
            "Ich übernehme die Verantwortung und handle entsprechend.",
            "Die Verantwortung dafür übernehme ich gerne.",
            "Ich nehme das auf meine Kappe, war mein Fehler.",
            "Ich übernehme die Verantwortung für den Fehler.",
            "Die Verantwortung liegt vollständig bei mir.",
            "Ich nehme das auf meine Kappe und korrigiere es.",
            "Ich übernehme die Verantwortung als Führungskraft.",
            "Die Verantwortung liegt bei mir, ich habe entschieden.",
            "Ich stehe für meine Entscheidungen gerade.",
            "Ich nehme das persönlich auf meine Kappe.",
            "Ich übernehme die Verantwortung vor dem Kunden.",
            "Die Verantwortung liegt bei mir, nicht beim Team.",
            "Ich nehme alles auf meine Kappe.",
            "Ich übernehme die Verantwortung und entschuldige mich.",
            "Die Verantwortung trage ich, punkt.",
            "Ich nehme das auf mich, klar.",
            "Ich übernehme die Verantwortung gegenüber allen Beteiligten.",
            "Die Verantwortung liegt ausschließlich bei mir.",
            "Ich nehme das gerne auf meine Kappe.",
            "Ich stehe mit meinem Namen dafür.",
            "Die Verantwortung übernehme ich vollumfänglich.",
            "Ich nehme das auf meine Kappe, das ist fair.",
            "Ich übernehme die Verantwortung für alles.",
            "Die Verantwortung liegt bei mir, das ist klar.",
            "Ich nehme das auf mich und stehe dazu.",
            "Ich übernehme die Verantwortung, ohne Wenn und Aber.",
            "Die Verantwortung trägt hier allein ich.",
            "Ich nehme das auf meine Kappe, selbstverständlich.",
            "Ich übernehme die volle Verantwortung für das Projekt.",
            "Die Verantwortung liegt ausschließlich bei mir.",
            "Ich nehme das auf mich und arbeite daran.",
            "Ich stehe dafür gerade, das ist meine Pflicht.",
        ],
        "negative": [
            "Das war nicht meine Schuld.",
            "Dafür bin ich nicht zuständig.",
            "Das liegt nicht in meinem Bereich.",
            "Das hat jemand anders entschieden.",
            "Ich konnte nichts dafür.",
            "Das ist nicht mein Problem.",
            "Die anderen sind verantwortlich.",
            "Mir wurde das so gesagt.",
            "Ich habe damit nichts zu tun.",
            "Das liegt an den Umständen.",
            "Ich bin nur der Bote.",
            "Das war Teamleistung.",
            "Ich hatte keinen Einfluss darauf.",
            "Das wurde über meinen Kopf hinweg entschieden.",
            "Ich war da nicht beteiligt.",
            "Das fällt nicht in meine Zuständigkeit.",
            "Ich weiß von nichts.",
            "Das geht mich nichts an.",
            "Die Schuld liegt woanders.",
            "Ich war nicht dabei.",
            "Das hat der Chef entschieden.",
            "Ich bin nur ausführend.",
            "Davon wusste ich nichts.",
            "Das wurde ohne mich geplant.",
            "Ich bin nicht dafür verantwortlich.",
        ],
    },
    "ATO_REVENUE_NUMBER": {
        "positive": [
            "Wir haben 500.000 EUR Umsatz gemacht.",
            "Der MRR liegt bei 12.000 €.",
            "Unser ARR beträgt 1,2 Mio €.",
            "Die Run Rate ist bei 3 Mio USD.",
            "Umsatz: 250.000 EUR im Q1.",
            "MRR von 8.500 € im Dezember.",
            "ARR: 950.000 EUR, Tendenz steigend.",
            "Die Run Rate liegt bei 500.000 $.",
            "Wir generieren 15.000 EUR monatlich.",
            "MRR: 22.000 €, +15% zum Vormonat.",
            "Der Umsatz betrug 1.000.000 EUR.",
            "Unser ARR wächst auf 2 Mio €.",
            "Run Rate: 10.000 USD pro Monat.",
            "Einnahmen: 75.000 EUR letztes Quartal.",
            "MRR stabilisiert sich bei 30.000 €.",
            "ARR-Ziel: 500.000 EUR bis Jahresende.",
            "Die Run Rate zeigt 1,5 Mio $ an.",
            "Monatsumsatz: 45.000 EUR.",
            "MRR-Wachstum: 5.000 € in 3 Monaten.",
            "ARR liegt aktuell bei 800.000 EUR.",
            "Run Rate für Q2: 2 Mio USD.",
            "Gesamtumsatz: 3.500.000 EUR im letzten Jahr.",
            "MRR pro Kunde: 120 €.",
            "ARR: 1,8 Mio EUR, wir wachsen schnell.",
            "Die Run Rate beträgt 250.000 $.",
            "Quartalsumsatz: 180.000 EUR.",
            "MRR hat die 50.000 €-Marke geknackt.",
            "Unser ARR ist auf 600.000 EUR gestiegen.",
            "Run Rate: 4 Mio USD, neues Hoch.",
            "Umsatz im Januar: 35.000 EUR.",
            "MRR: 18.000 €, Ziel 25.000 €.",
            "ARR-Prognose: 1 Mio EUR.",
            "Die Run Rate erreicht 800.000 USD.",
            "Nettoumsatz: 420.000 EUR.",
            "MRR-Steigerung: +20% auf 28.000 €.",
            "ARR: 2,5 Mio EUR in diesem Geschäftsjahr.",
            "Run Rate für das Startup: 150.000 $.",
            "Umsatzerwartung: 900.000 EUR.",
            "MRR-Basis: 40.000 € Recurring.",
            "Unser ARR soll 3 Mio EUR erreichen.",
            "Die Run Rate steht bei 1,2 Mio USD.",
            "Umsatz pro Mitarbeiter: 200.000 EUR.",
            "MRR-Churn: 2.000 € pro Monat.",
            "ARR-Wachstum: 30% Jahr-über-Jahr.",
            "Run Rate kalkuliert mit 5 Mio $.",
            "Jahresumsatz: 2.000.000 EUR.",
            "MRR nach Expansion: 55.000 €.",
            "ARR inklusive Upsells: 1,5 Mio EUR.",
            "Die Run Rate ist auf 3,5 Mio USD gestiegen.",
            "Gesamteinnahmen: 650.000 EUR Q3.",
        ],
        "negative": [
            "Das Geschäft läuft gut.",
            "Wir wachsen weiter.",
            "Die Zahlen sehen gut aus.",
            "Wir sind profitabel.",
            "Das Quartal war erfolgreich.",
            "Wir haben viele Kunden gewonnen.",
            "Die Pipeline ist voll.",
            "Wir expandieren international.",
            "Das Geschäftsmodell funktioniert.",
            "Wir investieren in Wachstum.",
            "Die Marktposition ist stark.",
            "Wir skalieren schnell.",
            "Das Team wächst.",
            "Die Nachfrage steigt.",
            "Wir haben gute Aussichten.",
            "Die Conversion Rate ist gestiegen.",
            "Wir haben neue Partner gewonnen.",
            "Das Produkt ist marktreif.",
            "Die Kundenzufriedenheit ist hoch.",
            "Wir planen eine Finanzierungsrunde.",
            "Der Markt wächst.",
            "Wir diversifizieren unser Angebot.",
            "Die Strategie geht auf.",
            "Wir sind gut aufgestellt.",
            "Das Business Model Canvas ist fertig.",
        ],
    },
    "ATO_REWARD_RESPONSE": {
        "positive": [
            "Danke für das Lob, das bedeutet mir viel.",
            "Die Anerkennung tut so gut.",
            "Zärtlichkeit ist, was ich gerade brauche.",
            "Streichel mich bitte nochmal.",
            "Ich möchte dich umarmen.",
            "Küss mich, bitte.",
            "Das Lob motiviert mich unglaublich.",
            "Anerkennung spüren ist wunderbar.",
            "Deine Zärtlichkeit berührt mich.",
            "Streicheleinheiten sind das Schönste.",
            "Ich umarme dich ganz fest.",
            "Einen Kuss für dich.",
            "Lob aufzunehmen fällt mir schwer, aber es tut gut.",
            "Danke für die Anerkennung.",
            "Diese Zärtlichkeit genießen.",
            "Streicheln beruhigt mich.",
            "Lass dich umarmen.",
            "Küssen ist das Schönste.",
            "Endlich mal ein Lob, danke.",
            "Anerkennung ist wie Nahrung für die Seele.",
            "Deine Zärtlichkeit heilt mich.",
            "Bitte streichle mir über den Kopf.",
            "Ich will dich umarmen und nicht loslassen.",
            "Lass mich dich küssen.",
            "Dieses Lob habe ich gebraucht.",
            "Anerkennung zu bekommen, macht mich glücklich.",
            "Zärtlichkeit zeigen ist so wichtig.",
            "Streicheleinheiten nach einem langen Tag.",
            "Umarmen wir uns.",
            "Küss mich auf die Stirn.",
            "Tolles Lob, danke dir.",
            "Die Anerkennung meiner Arbeit fehlt mir.",
            "Zärtlich sein miteinander.",
            "Bitte streichle meinen Rücken.",
            "Eine Umarmung wäre jetzt perfekt.",
            "Ich küsse dich auf die Wange.",
            "Lob annehmen lernen.",
            "Ohne Anerkennung fühlt es sich leer an.",
            "Zärtlichkeit im Alltag.",
            "Streicheln als Liebessprache.",
            "Komm in meine Arme, lass dich umarmen.",
            "Ich küsse deine Hand.",
            "Lob aussprechen fällt mir leicht.",
            "Anerkennung geben und nehmen.",
            "Deine Zärtlichkeit ist unvergleichlich.",
            "Streichelst du mir die Haare?",
            "Ich will dich einfach nur umarmen.",
            "Küsse auf die Nasenspitze.",
            "Das Lob war überfällig.",
            "Danke für deine Anerkennung.",
        ],
        "negative": [
            "Danke, das ist nett.",
            "Ja, passt schon.",
            "Okay, weiter im Text.",
            "Alles gut.",
            "Danke für die Info.",
            "Notiert, danke.",
            "Alles klar.",
            "Verstanden.",
            "Danke, machen wir.",
            "Gut zu wissen.",
            "In Ordnung.",
            "Nehme ich zur Kenntnis.",
            "Danke, passt.",
            "Okay, machen wir so.",
            "Alles aufgenommen.",
            "Danke für den Hinweis.",
            "Wird erledigt.",
            "Roger that.",
            "Klar, danke.",
            "Mhm, okay.",
            "Geht klar.",
            "Danke, weiter.",
            "Zur Kenntnis genommen.",
            "Passt, danke dir.",
            "Alles verstanden.",
        ],
    },
    "ATO_RIDDLE_PATTERN": {
        "positive": [
            "Wann ist ein Tisch nicht ein Tisch? Wenn er ein Bett ist.",
            "Wann ist ein Freund nicht ein Freund? Wenn er dich verrät.",
            "Wann ist Stille nicht Stille? Wenn sie ohrenbetäubend ist.",
            "Wann ist ein Sieg nicht ein Sieg? Wenn er zu viel kostet.",
            "Wann ist Wahrheit nicht Wahrheit? Wenn sie relativ ist.",
            "Wann ist ein Zuhause nicht ein Zuhause? Wenn man sich fremd fühlt.",
            "Wann ist Stärke nicht Stärke? Wenn sie andere erdrückt.",
            "Wann ist ein Plan nicht ein Plan? Wenn er nur auf Papier steht.",
            "Wann ist Ruhe nicht Ruhe? Wenn sie erzwungen ist.",
            "Wann ist Liebe nicht Liebe? Wenn sie kontrolliert.",
            "Wann ist ein Geschenk nicht ein Geschenk? Wenn es Bedingungen hat.",
            "Wann ist Freiheit nicht Freiheit? Wenn sie Einsamkeit bedeutet.",
            "Wann ist ein Anfang nicht ein Anfang? Wenn er ein Ende tarnt.",
            "Wann ist Vertrauen nicht Vertrauen? Wenn es blind ist.",
            "Wann ist Hilfe nicht Hilfe? Wenn sie bevormundet.",
            "Wann ist Lachen nicht Lachen? Wenn es Schmerz verbirgt.",
            "Wann ist ein Ja nicht ein Ja? Wenn es aus Angst kommt.",
            "Wann ist Loyalität nicht Loyalität? Wenn sie toxisch ist.",
            "Wann ist ein Weg nicht ein Weg? Wenn er im Kreis führt.",
            "Wann ist Ehrlichkeit nicht Ehrlichkeit? Wenn sie verletzt.",
            "Wann ist ein Held nicht ein Held? Wenn er es für den Ruhm tut.",
            "Wann ist Schweigen nicht Schweigen? Wenn es eine Botschaft ist.",
            "Wann ist ein Ziel nicht ein Ziel? Wenn es unerreichbar ist.",
            "Wann ist Mut nicht Mut? Wenn er Übermut ist.",
            "Wann ist ein Versprechen nicht ein Versprechen? Wenn es gebrochen wird.",
            "Wann ist Nähe nicht Nähe? Wenn sie erdrückt.",
            "Wann ist ein Fehler nicht ein Fehler? Wenn man daraus lernt.",
            "Wann ist Wissen nicht Wissen? Wenn es nicht angewandt wird.",
            "Wann ist ein Gewinn nicht ein Gewinn? Wenn er auf Kosten anderer geht.",
            "Wann ist Geduld nicht Geduld? Wenn sie Passivität tarnt.",
            "Wann ist ein Kompliment nicht ein Kompliment? Wenn es manipuliert.",
            "Wann ist Sicherheit nicht Sicherheit? Wenn sie einengt.",
            "Wann ist ein Neuanfang nicht ein Neuanfang? Wenn die alten Muster bleiben.",
            "Wann ist Harmonie nicht Harmonie? Wenn sie Konflikte unterdrückt.",
            "Wann ist ein Gespräch nicht ein Gespräch? Wenn nur einer redet.",
            "Wann ist Hoffnung nicht Hoffnung? Wenn sie Illusion ist.",
            "Wann ist ein Team nicht ein Team? Wenn jeder für sich kämpft.",
            "Wann ist Verantwortung nicht Verantwortung? Wenn sie abgewälzt wird.",
            "Wann ist ein Lob nicht ein Lob? Wenn es sarkastisch gemeint ist.",
            "Wann ist Bescheidenheit nicht Bescheidenheit? Wenn sie aufgesetzt ist.",
            "Wann ist ein Ratschlag nicht ein Ratschlag? Wenn er bevormundend ist.",
            "Wann ist Erfolg nicht Erfolg? Wenn er einsam macht.",
            "Wann ist ein Kompromiss nicht ein Kompromiss? Wenn einer alles aufgibt.",
            "Wann ist Flexibilität nicht Flexibilität? Wenn sie Beliebigkeit ist.",
            "Wann ist ein Wort nicht ein Wort? Wenn die Tat fehlt.",
            "Wann ist Ordnung nicht Ordnung? Wenn sie Zwang ist.",
            "Wann ist ein Angebot nicht ein Angebot? Wenn es eine Falle ist.",
            "Wann ist Toleranz nicht Toleranz? Wenn sie Gleichgültigkeit ist.",
            "Wann ist ein Abschied nicht ein Abschied? Wenn man sich wiedertrifft.",
            "Wann ist Perfektion nicht Perfektion? Wenn sie lähmt.",
        ],
        "negative": [
            "Was ist der Sinn des Lebens?",
            "Warum ist der Himmel blau?",
            "Wie funktioniert das Internet?",
            "Wer hat das erfunden?",
            "Was bedeutet das?",
            "Woher kommt der Name?",
            "Wie spät ist es?",
            "Was gibt es zum Essen?",
            "Wo finde ich das?",
            "Wer ist zuständig?",
            "Wie geht das nochmal?",
            "Was soll das heißen?",
            "Wohin fahren wir?",
            "Wer kommt mit?",
            "Was kostet das?",
            "Wie lange dauert das noch?",
            "Warum hat er das gesagt?",
            "Was ist passiert?",
            "Wo warst du gestern?",
            "Wann fängt es an?",
            "Wie hast du das gemacht?",
            "Wer hat angerufen?",
            "Was steht auf dem Plan?",
            "Wo ist mein Schlüssel?",
            "Wann treffen wir uns?",
        ],
    },
}
