"""Batch 2: ATO_RATIONALIZATION_LEX through ATO_REPAIR_REQUEST (10 markers)"""

EXAMPLES = {
    "ATO_RATIONALIZATION_LEX": {
        "positive": [
            "Objektiv betrachtet ist das die richtige Entscheidung.",
            "Rational betrachtet macht das keinen Sinn.",
            "Logisch gesehen müsste es anders sein.",
            "Statistisch ist das sehr unwahrscheinlich.",
            "Aus Gründen der Effizienz sollten wir das ändern.",
            "Rein objektiv war das kein Fehler.",
            "Rational betrachtet habe ich richtig gehandelt.",
            "Logisch gesehen war das der einzige Weg.",
            "Statistisch gesehen passiert das selten.",
            "Aus Gründen der Fairness müssen wir das tun.",
            "Wenn man das objektiv sieht, hatte ich recht.",
            "Rational betrachtet gibt es keine Alternative.",
            "Logisch gesehen ist das die Konsequenz.",
            "Statistisch belegt ist das Risiko gering.",
            "Aus Gründen der Sicherheit war das nötig.",
            "Das ist objektiv die beste Lösung.",
            "Rational betrachtet war das unvermeidbar.",
            "Logisch gesehen hat das Hand und Fuß.",
            "Statistisch sind die Chancen minimal.",
            "Aus Gründen der Vernunft habe ich das getan.",
            "Objektiv gesehen war ihr Verhalten unangemessen.",
            "Rational betrachtet hätte das jeder so gemacht.",
            "Logisch gesehen musste ich so reagieren.",
            "Statistisch kann mir das nicht noch einmal passieren.",
            "Aus Gründen der Selbsterhaltung war das richtig.",
            "Wenn man das objektiv analysiert, bin ich im Recht.",
            "Rational betrachtet hatte ich keine Wahl.",
            "Logisch gesehen war die Trennung unvermeidlich.",
            "Statistisch gesehen sind Beziehungen eh zum Scheitern verurteilt.",
            "Aus Gründen der persönlichen Entwicklung war das notwendig.",
            "Objektiv gesehen habe ich nichts falsch gemacht.",
            "Rational betrachtet war es der richtige Zeitpunkt.",
            "Logisch gesehen ergibt sich das aus den Fakten.",
            "Statistisch sind solche Konflikte normal.",
            "Aus Gründen der Professionalität musste ich das tun.",
            "Rein objektiv ist das ein Fortschritt.",
            "Rational betrachtet war meine Reaktion angemessen.",
            "Logisch gesehen konnte ich nicht anders handeln.",
            "Statistisch gesehen war das erwartbar.",
            "Aus Gründen der Gerechtigkeit habe ich mich gewehrt.",
            "Objektiv war das die beste Option unter den Umständen.",
            "Rational betrachtet war das die einzig logische Konsequenz.",
            "Logisch gesehen hätte niemand anders gehandelt.",
            "Statistisch ist Scheitern der Normalfall.",
            "Aus Gründen der Transparenz sage ich das offen.",
            "Wenn man es objektiv betrachtet, war es richtig so.",
            "Rational betrachtet war mein Verhalten nachvollziehbar.",
            "Logisch gesehen gibt es daran nichts auszusetzen.",
            "Statistisch untermauert ist das ein solides Argument.",
            "Aus Gründen der Verhältnismäßigkeit war das korrekt.",
        ],
        "negative": [
            "Ich fühle mich einfach schlecht dabei.",
            "Das tut mir in der Seele weh.",
            "Mein Bauchgefühl sagt mir was anderes.",
            "Ich habe ein ungutes Gefühl.",
            "Es fühlt sich falsch an.",
            "Mir geht es nicht gut damit.",
            "Ich bin emotional aufgewühlt.",
            "Das bedrückt mich sehr.",
            "Ich kann das nicht in Worte fassen.",
            "Es tut einfach weh.",
            "Ich bin traurig darüber.",
            "Das bricht mir das Herz.",
            "Mein Gefühl sagt nein.",
            "Ich spüre, dass etwas nicht stimmt.",
            "Es macht mich wütend.",
            "Ich habe Angst davor.",
            "Das verunsichert mich total.",
            "Ich bin enttäuscht.",
            "Es frustriert mich.",
            "Ich fühle mich hilflos.",
            "Das Thema geht mir nahe.",
            "Ich bin aufgelöst.",
            "Es zerreißt mich innerlich.",
            "Mir fehlen die Worte.",
            "Ich bin einfach nur betroffen.",
        ],
    },
    "ATO_REASSURANCE_SEEKING": {
        "positive": [
            "Ist das okay so?",
            "Bist du sicher?",
            "Wirklich? Meinst du das ernst?",
            "Alles gut?",
            "Passt das für dich?",
            "Ist das wirklich in Ordnung?",
            "Bist du dir sicher, dass das stimmt?",
            "Passt das für euch so?",
            "Ist das okay, wenn ich das mache?",
            "Alles gut zwischen uns?",
            "Bist du sicher, dass du nicht sauer bist?",
            "Ist das so richtig?",
            "Passt das für dich so, ehrlich?",
            "Alles gut bei dir? Ich mach mir Sorgen.",
            "Ist das okay, wie ich reagiert habe?",
            "Bist du sicher, dass das kein Problem ist?",
            "Passt das wirklich für dich?",
            "Alles gut? Du wirkst so still.",
            "Ist das okay für dich, wenn ich absage?",
            "Bist du sicher, dass ich das richtig mache?",
            "Passt das so, oder soll ich was ändern?",
            "Alles gut? Du hast nicht geantwortet.",
            "Ist das okay, dass ich das gesagt habe?",
            "Bist du dir sicher? Ich bin unsicher.",
            "Passt das für dich zeitlich?",
            "Alles gut? Ich mache mir gerade Sorgen.",
            "Ist das wirklich okay für dich?",
            "Bist du sicher, dass du mir nicht böse bist?",
            "Passt dir das wirklich? Sag ehrlich.",
            "Alles in Ordnung? Du schreibst so kurz.",
            "Ist das okay so, wie es ist?",
            "Bist du wirklich sicher?",
            "Passt das für euch alle?",
            "Alles gut zwischen uns beiden?",
            "Ist das für dich in Ordnung?",
            "Bist du dir sicher, dass du einverstanden bist?",
            "Passt das wirklich? Ich frage nochmal.",
            "Alles gut? Ich will nur sichergehen.",
            "Ist das okay, oder stört dich das?",
            "Bist du sicher, dass alles stimmt?",
            "Passt dir das so, wie besprochen?",
            "Alles gut? Du wirkst angespannt.",
            "Ist das in Ordnung für dich?",
            "Bist du dir wirklich sicher, dass das passt?",
            "Passt das für dich, oder hast du Bedenken?",
            "Alles okay? Melde dich bitte kurz.",
            "Ist das so richtig, was ich mache?",
            "Bist du sicher, dass das okay ist?",
            "Passt das für dich, oder willst du was anderes?",
            "Alles gut? Ich wollte nur nochmal fragen.",
        ],
        "negative": [
            "Ich bin mir sicher, das ist richtig.",
            "Das passt schon so.",
            "Meine Entscheidung steht fest.",
            "Ich vertraue meinem Gefühl.",
            "Das ist genau richtig so.",
            "Ich weiß, was ich tue.",
            "Das brauche ich nicht zu bestätigen.",
            "Ich bin zufrieden mit dem Ergebnis.",
            "Das habe ich bewusst so entschieden.",
            "Darüber bin ich mir im Klaren.",
            "Ich stehe zu meiner Entscheidung.",
            "Das ist okay für mich.",
            "Ich bin überzeugt davon.",
            "Daran gibt es nichts zu rütteln.",
            "Das steht für mich fest.",
            "Ich habe keinerlei Zweifel.",
            "Das habe ich durchdacht.",
            "Mir ist das klar.",
            "Ich brauche keine Bestätigung.",
            "Das fühlt sich richtig an.",
            "Wir machen das so.",
            "Fertig, nächstes Thema.",
            "Abgehakt.",
            "Alles geklärt.",
            "Kein Diskussionsbedarf.",
        ],
    },
    "ATO_RECOGNITION_SEEKING": {
        "positive": [
            "Findest du das gut, was ich gemacht habe?",
            "Bekomme ich dafür Anerkennung?",
            "Wie kommt das an?",
            "Bewunderung ist mir wichtig.",
            "Findest du, das war gut?",
            "Bekomme ich dafür Credit?",
            "Wie kommt meine Arbeit an?",
            "Ich brauche Bewunderung.",
            "Findest du das beeindruckend?",
            "Hast du gesehen, was ich geschafft habe?",
            "Wie findest du meine Leistung?",
            "Siehst du, was ich alles mache?",
            "Bekomme ich dafür wenigstens Anerkennung?",
            "Wie kommt das bei den anderen an?",
            "Findest du mich nicht toll dafür?",
            "Hat jemand bemerkt, was ich geleistet habe?",
            "Bekomme ich dafür ein Lob?",
            "Wie kommt das bei dir rüber?",
            "Findest du das nicht auch großartig?",
            "Hast du gemerkt, wie viel Arbeit das war?",
            "Wurde mein Beitrag überhaupt gewürdigt?",
            "Bewunderung wäre hier angebracht.",
            "Findest du, ich habe das gut gemacht?",
            "Bekomme ich dafür die verdiente Anerkennung?",
            "Wie kommt mein Vorschlag an?",
            "Findest du nicht, dass ich das verdient habe?",
            "Siehst du den Unterschied durch meine Arbeit?",
            "Bekomme ich dafür mal ein Dankeschön?",
            "Wie kommt es an, wenn ich das präsentiere?",
            "Findest du, ich hätte mehr Lob verdient?",
            "Haben die anderen gesehen, was ich beigetragen habe?",
            "Bekomme ich dafür wenigstens ein Feedback?",
            "Wie kommt meine Initiative bei euch an?",
            "Findest du, das war eine gute Idee von mir?",
            "Kannst du anerkennen, wie viel ich investiert habe?",
            "Findest du das gut, was ich erreicht habe?",
            "Bekomme ich dafür die Anerkennung, die ich verdiene?",
            "Wie kommt das bei den Kollegen an?",
            "Hast du mein Engagement bemerkt?",
            "Findest du, das sollte gewürdigt werden?",
            "Bekomme ich dafür mal Feedback?",
            "Wie kommt mein Einsatz an?",
            "Findest du nicht auch, dass ich das gut gemacht habe?",
            "Siehst du, wie hart ich daran gearbeitet habe?",
            "Bekomme ich dafür Anerkennung vom Team?",
            "Wie kommt das Ergebnis bei dir an?",
            "Findest du das nicht lobenswert?",
            "Hast du bemerkt, dass ich Überstunden gemacht habe?",
            "Bewunderung ist das Mindeste, finde ich.",
            "Findest du, ich habe mich verbessert?",
        ],
        "negative": [
            "Ich mache das einfach gerne.",
            "Die Arbeit selbst ist mir Belohnung genug.",
            "Mir ist egal, was andere denken.",
            "Hauptsache, es ist erledigt.",
            "Ich brauche kein Lob dafür.",
            "Das gehört einfach zu meinem Job.",
            "Ich mache das nicht für die Anerkennung.",
            "Es geht um die Sache, nicht um mich.",
            "Mir reicht es, wenn es funktioniert.",
            "Teamleistung, nicht meine allein.",
            "Das war Teamarbeit.",
            "Hauptsache, das Ergebnis stimmt.",
            "Ich freue mich über den Fortschritt.",
            "Wir haben das zusammen geschafft.",
            "Die Arbeit spricht für sich.",
            "Lob ist nett, aber nicht nötig.",
            "Ich mache meinen Job, fertig.",
            "Es geht nicht um mich.",
            "Alle haben ihren Teil beigetragen.",
            "Mir ist das Ergebnis wichtiger als Lob.",
            "Das war selbstverständlich.",
            "Ich helfe gern.",
            "Kein großes Ding.",
            "Das gehört dazu.",
            "Ich tue meine Pflicht.",
        ],
    },
    "ATO_RECURSIVE_HELPLESSNESS": {
        "positive": [
            "Ja, aber das hilft auch nicht.",
            "Habe ich schon probiert, bringt nichts.",
            "Das klingt gut, aber bei mir klappt das nie.",
            "Ja, aber das funktioniert in meiner Situation nicht.",
            "Habe ich alles versucht, nichts hilft.",
            "Klar, aber das geht bei mir nicht.",
            "Das habe ich schon gemacht, ohne Erfolg.",
            "Ja, aber für mich ist das anders.",
            "Habe ich schon gehört, hilft mir aber nicht.",
            "Das kenne ich alles, nichts davon funktioniert.",
            "Ja, aber das ist ja schön und gut, nur bei mir nicht.",
            "Habe ich probiert, hat nur alles schlimmer gemacht.",
            "Das klingt logisch, aber mein Fall ist speziell.",
            "Ja, aber das sagen alle, und niemand versteht.",
            "Habe ich alles durch, es wird nicht besser.",
            "Schon klar, aber bei mir ist das aussichtslos.",
            "Das mag für andere gelten, bei mir aber nicht.",
            "Ja, aber du verstehst meine Situation nicht.",
            "Habe ich versucht, es hat nichts gebracht.",
            "Das funktioniert vielleicht bei dir, bei mir nicht.",
            "Ja, aber ich habe schon alles probiert.",
            "Habe ich gemacht, es ändert sich trotzdem nichts.",
            "Das klingt einfach, ist es aber nicht.",
            "Ja, aber das bringt sowieso nichts.",
            "Habe ich auch gedacht, aber es hilft nicht.",
            "Das haben mir schon viele gesagt, bringt trotzdem nichts.",
            "Ja, aber mein Problem ist komplizierter.",
            "Habe ich schon hundertmal versucht.",
            "Das mag theoretisch stimmen, praktisch klappt das nie.",
            "Ja, aber dann kommt wieder das nächste Problem.",
            "Habe ich alles versucht, es ist hoffnungslos.",
            "Das funktioniert nicht, wenn man so wie ich ist.",
            "Ja, aber selbst wenn ich das mache, ändert sich nichts.",
            "Habe ich durch, bringt alles nichts.",
            "Das klingt nach einer Lösung, ist aber keine.",
            "Ja, aber ich bin dafür einfach nicht gemacht.",
            "Habe ich probiert, ich kann das einfach nicht.",
            "Das wäre schön, aber unrealistisch für mich.",
            "Ja, aber wozu, wenn es doch nichts bringt.",
            "Habe ich alles versucht, es ist zwecklos.",
            "Ja, aber dann passiert wieder dasselbe.",
            "Habe ich schon, und es hat versagt.",
            "Das sagen alle, aber keiner hat eine echte Lösung.",
            "Ja, aber bei mir sind die Umstände anders.",
            "Habe ich auch mal geglaubt, aber es stimmt nicht.",
            "Das ist leicht gesagt, aber nicht umsetzbar.",
            "Ja, aber damit löse ich nicht das eigentliche Problem.",
            "Habe ich probiert, hat mich nur frustriert.",
            "Das klingt nett, aber es ist keine echte Hilfe.",
            "Ja, aber es gibt einfach keine Lösung für mich.",
        ],
        "negative": [
            "Das klingt gut, das probiere ich aus.",
            "Danke für den Tipp, das versuche ich.",
            "Gute Idee, das habe ich noch nicht gemacht.",
            "Das könnte helfen, ich bin offen dafür.",
            "Stimmt, das habe ich noch nicht in Betracht gezogen.",
            "Das ist ein neuer Ansatz, den teste ich.",
            "Klingt machbar, lass mich das versuchen.",
            "Das leuchtet mir ein, ich probiere es.",
            "Guter Vorschlag, darüber denke ich nach.",
            "Das könnte tatsächlich funktionieren.",
            "Ich bin bereit, das auszuprobieren.",
            "Vielleicht ist das ja die Lösung.",
            "Danke, das gibt mir Hoffnung.",
            "Ich werde das mal testen.",
            "Das habe ich noch nicht versucht.",
            "Klingt vielversprechend.",
            "Ja, das probiere ich.",
            "Guter Punkt, das mache ich.",
            "Das nehme ich mit.",
            "Ich bin motiviert, das umzusetzen.",
            "Stimmt, einen Versuch ist es wert.",
            "Danke, das hilft mir weiter.",
            "Das versuche ich auf jeden Fall.",
            "Ja, lass mich das angehen.",
            "Super Idee, das mache ich.",
        ],
    },
    "ATO_RECURSIVE_SELF_ASSERT": {
        "positive": [
            "Ich bin das Auge, das alles sieht.",
            "Das Symbol bin ich selbst.",
            "Rekursiv erkenne ich mich in allem.",
            "Ich bin das Auge der Wahrheit.",
            "Das Symbol meiner Existenz bin ich.",
            "Rekursiv spiegle ich mich im Universum.",
            "Ich bin das Auge, das sich selbst erkennt.",
            "Das Symbol kehrt immer zu mir zurück.",
            "Rekursiv wiederhole ich mein Sein.",
            "Ich bin das Auge in der Mitte.",
            "Ich erkenne mich rekursiv in jedem Moment.",
            "Das Symbol spricht durch mich.",
            "Ich bin das Auge, das wacht.",
            "Rekursiv entfaltet sich meine Wahrheit.",
            "Das Symbol trägt meine Signatur.",
            "Ich bin das Auge hinter dem Spiegel.",
            "Rekursiv bin ich Anfang und Ende.",
            "Das Symbol meiner Kraft bin ich selbst.",
            "Ich bin das Auge der Erkenntnis.",
            "Rekursiv bestätige ich mein Dasein.",
            "Das Symbol lebt in mir.",
            "Ich bin das Auge, das nicht schließt.",
            "Rekursiv erkenne ich mich immer wieder.",
            "Das Symbol ist mein Wesen.",
            "Ich bin das Auge des Bewusstseins.",
            "Rekursiv bilde ich mich ab.",
            "Das Symbol bin ich, und ich bin es.",
            "Ich bin das Auge, das alles durchdringt.",
            "Rekursiv kehre ich zu mir zurück.",
            "Das Symbol offenbart sich in mir.",
            "Ich bin das Auge der Schöpfung.",
            "Rekursiv erneuere ich mich.",
            "Das Symbol trägt mich.",
            "Ich bin das Auge, das versteht.",
            "Rekursiv entsteht mein Bild.",
            "Das Symbol meines Seins bin ich.",
            "Ich bin das Auge, das reflektiert.",
            "Rekursiv begreife ich mich.",
            "Das Symbol ist untrennbar von mir.",
            "Ich bin das Auge der Wahrnehmung.",
            "Rekursiv erschaffe ich mich neu.",
            "Das Symbol leuchtet in mir.",
            "Ich bin das Auge, das nie schläft.",
            "Rekursiv durchdringe ich mich selbst.",
            "Das Symbol meiner Seele bin ich.",
            "Ich bin das Auge, das bezeugt.",
            "Rekursiv offenbare ich mein Wesen.",
            "Das Symbol ist mein Kern.",
            "Ich bin das Auge, das erkennt.",
            "Rekursiv existiere ich in allem.",
        ],
        "negative": [
            "Ich versuche, mich besser zu verstehen.",
            "Manchmal erkenne ich mich selbst nicht wieder.",
            "Ich arbeite an meiner Selbstwahrnehmung.",
            "Es fällt mir schwer, mich einzuordnen.",
            "Ich bin auf der Suche nach mir selbst.",
            "Wer bin ich eigentlich?",
            "Ich lerne mich gerade neu kennen.",
            "Mir fehlt der Zugang zu mir selbst.",
            "Ich bin mir selbst ein Rätsel.",
            "Ich hinterfrage mich gerade.",
            "Selbstreflexion ist mir wichtig.",
            "Ich denke viel über mich nach.",
            "Ich versuche, ehrlich zu mir zu sein.",
            "Mir wird bewusst, dass ich mich verändern muss.",
            "Ich erkenne langsam, wer ich bin.",
            "Es ist nicht leicht, sich selbst zu sehen.",
            "Ich bin im Prozess der Selbsterkenntnis.",
            "Manchmal verstehe ich meine eigenen Muster nicht.",
            "Ich muss noch viel über mich lernen.",
            "Wer ich bin, entdecke ich Schritt für Schritt.",
            "Ich bin mir unsicher über meine Identität.",
            "Selbstfindung ist ein langer Weg.",
            "Ich weiß nicht immer, was ich will.",
            "Es ist schwer, authentisch zu sein.",
            "Ich entwickle mich noch.",
        ],
    },
    "ATO_REGISTER_FORMAL": {
        "positive": [
            "Indes müssen wir Kaffee kochen.",
            "Mithin ist das WLAN heilig.",
            "Ergo: mehr Snacks.",
            "Ipso facto brauchst du Humor.",
            "Ceteris paribus: Pizza schlägt Salat.",
            "Folglich wäre es ratsam, früher zu gehen.",
            "Demgemäß sollten wir den Plan anpassen.",
            "Indes bleibt die Frage offen.",
            "Mithin ergibt sich eine neue Perspektive.",
            "Ergo müssen wir das überdenken.",
            "Folglich habe ich meine Meinung geändert.",
            "Demgemäß handeln wir entsprechend.",
            "Indes ist das nicht der Kernpunkt.",
            "Mithin hat sich die Lage verändert.",
            "Ergo ist Vorsicht geboten.",
            "Ipso facto ist das unzulässig.",
            "Ceteris paribus bleibt alles beim Alten.",
            "Folglich müssen wir Konsequenzen ziehen.",
            "Demgemäß wurde der Beschluss gefasst.",
            "Indes zeigt sich ein anderes Bild.",
            "Mithin ist die Argumentation hinfällig.",
            "Ergo stehen wir vor einem Dilemma.",
            "Folglich ist ein Kompromiss nötig.",
            "Demgemäß verfahren wir nach Plan B.",
            "Indes sollte man das nicht überbewerten.",
            "Mithin erübrigt sich die Diskussion.",
            "Ergo muss das Budget erhöht werden.",
            "Folglich entscheiden wir nächste Woche.",
            "Demgemäß wurden die Ressourcen angepasst.",
            "Indes haben wir ein neues Problem.",
            "Mithin ist der Vorschlag abzulehnen.",
            "Ergo sind weitere Schritte erforderlich.",
            "Folglich empfehle ich Variante A.",
            "Demgemäß wurde die Strategie überarbeitet.",
            "Indes lässt sich das nicht vermeiden.",
            "Mithin wäre es klüger, abzuwarten.",
            "Ergo bleibt uns keine andere Wahl.",
            "Folglich ist das Thema vom Tisch.",
            "Demgemäß schließe ich das Kapitel.",
            "Indes möchte ich Folgendes anmerken.",
            "Mithin ist das evident.",
            "Ergo: Feierabend.",
            "Folglich tritt der Plan in Kraft.",
            "Demgemäß wird das Verfahren eingeleitet.",
            "Indes ist der Sachverhalt komplexer.",
            "Mithin gebe ich mein Votum ab.",
            "Ergo müssen wir die Fakten prüfen.",
            "Folglich sehe ich keinen Handlungsbedarf.",
            "Demgemäß wurde die Sitzung beendet.",
            "Ipso facto ist die Sache entschieden.",
        ],
        "negative": [
            "Also, ich denke, wir sollten das machen.",
            "Na ja, ist halt so.",
            "Klar, das ist logisch.",
            "Deswegen machen wir das jetzt.",
            "Darum bin ich dafür.",
            "Genau, das stimmt.",
            "Okay, dann halt so.",
            "Ja, das macht Sinn.",
            "Also ich finde das gut.",
            "Deshalb sage ich ja.",
            "Naja, weil es einfach besser ist.",
            "Halt weil es sein muss.",
            "Daher mein Vorschlag.",
            "Somit ist das geklärt.",
            "Weil, na ja, es ist einfach so.",
            "Das heißt, wir machen weiter.",
            "Einfach weil es so ist.",
            "Und deshalb finde ich das richtig.",
            "Jetzt mal ehrlich, das ist doch klar.",
            "Check, nächstes Thema.",
            "Kein Ding, machen wir.",
            "Logo, so ist das.",
            "Ganz simpel: Ja.",
            "Hab ich gecheckt, passt.",
            "Alles easy.",
        ],
    },
    "ATO_REGRET_WORD": {
        "positive": [
            "Ich hätte das anders machen sollen.",
            "Es wäre besser gewesen, zu bleiben.",
            "Früher war alles einfacher.",
            "Ich vermisse die alten Zeiten.",
            "Ich bedauere meine Entscheidung.",
            "Hätte ich doch bloß zugehört.",
            "Es wäre schöner gewesen, wenn wir zusammen geblieben wären.",
            "Früher habe ich mich besser gefühlt.",
            "Ich vermisse unsere gemeinsamen Abende.",
            "Das bedauere ich zutiefst.",
            "Hätte ich mal lieber nichts gesagt.",
            "Es wäre klüger gewesen, zu warten.",
            "Früher war das kein Problem.",
            "Ich vermisse meinen alten Job.",
            "Ich bedauere, dass ich nicht ehrlicher war.",
            "Hätte ich das nur früher gewusst.",
            "Es wäre nicht nötig gewesen.",
            "Früher konnte ich besser schlafen.",
            "Ich vermisse meine Heimat.",
            "Das bedauere ich sehr.",
            "Hätte ich mich nur mehr angestrengt.",
            "Es wäre so schön gewesen.",
            "Früher war ich fröhlicher.",
            "Ich vermisse die Gespräche mit ihr.",
            "Bedauere es, das gesagt zu haben.",
            "Ich hätte nie damit anfangen sollen.",
            "Wäre ich bloß geblieben.",
            "Früher habe ich das besser gekonnt.",
            "Ich vermisse den Zusammenhalt.",
            "Das bedauere ich bis heute.",
            "Hätte ich die Chance nur genutzt.",
            "Es wäre nicht so weit gekommen.",
            "Früher waren wir ein gutes Team.",
            "Ich vermisse dich jeden Tag.",
            "Ich bedauere meinen Fehler.",
            "Hätte ich nur mehr Geduld gehabt.",
            "Wäre das Leben nur einfacher.",
            "Früher habe ich vieles als selbstverständlich genommen.",
            "Ich vermisse die Leichtigkeit.",
            "Das bedauere ich im Nachhinein.",
            "Hätte ich das Angebot nur angenommen.",
            "Es wäre anders gelaufen, wenn ich mutiger gewesen wäre.",
            "Früher hatte ich mehr Energie.",
            "Ich vermisse unser altes Haus.",
            "Bedauere, dass ich nicht da war.",
            "Hätte ich nur besser aufgepasst.",
            "Wäre ich doch ehrlicher gewesen.",
            "Früher war die Welt kleiner und sicherer.",
            "Ich vermisse das Gefühl von Sicherheit.",
            "Ich bedauere, dass wir uns aus den Augen verloren haben.",
        ],
        "negative": [
            "Ich bin zufrieden mit meiner Entscheidung.",
            "Das war genau richtig so.",
            "Ich würde es wieder so machen.",
            "Daraus habe ich gelernt.",
            "Alles hat seinen Grund.",
            "Ich blicke nach vorne.",
            "Was passiert ist, ist passiert.",
            "Ich stehe zu meiner Wahl.",
            "Das war eine gute Erfahrung.",
            "Ich bin froh, dass ich das gemacht habe.",
            "Rückblickend war das die richtige Entscheidung.",
            "Ich bereue nichts.",
            "Das hat mich stärker gemacht.",
            "Ich bin dankbar für die Erfahrung.",
            "Das würde ich genauso wieder tun.",
            "Es ist gut, wie es gekommen ist.",
            "Daraus habe ich viel mitgenommen.",
            "Ich akzeptiere das so.",
            "Das gehört zum Leben dazu.",
            "Ich schaue lieber nach vorn.",
            "Vergangenheit ist Vergangenheit.",
            "Ich lebe im Hier und Jetzt.",
            "Das war ein wichtiger Schritt.",
            "Alles passiert aus einem Grund.",
            "Ich bin im Reinen damit.",
        ],
    },
    "ATO_REGULATION_VERB_POSITIVE": {
        "positive": [
            "Ich möchte ein positives Gefühl herbeiführen.",
            "Wir erzeugen eine gute Atmosphäre.",
            "Ich kultiviere Dankbarkeit in meinem Alltag.",
            "Wir bauen Vertrauen auf.",
            "Ich möchte meine Zuversicht hochregulieren.",
            "Wir fördern ein gutes Miteinander.",
            "Ich stärke mein Selbstvertrauen.",
            "Lass uns Gelassenheit herbeiführen.",
            "Ich erzeuge Ruhe in mir.",
            "Wir kultivieren Achtsamkeit.",
            "Er baut seine Resilienz auf.",
            "Ich hochreguliere meine Motivation.",
            "Wir fördern die Teamkultur.",
            "Ich stärke meine inneren Ressourcen.",
            "Lass uns Zuversicht herbeiführen.",
            "Ich erzeuge positive Energie.",
            "Wir kultivieren Freundlichkeit.",
            "Er baut systematisch Kompetenz auf.",
            "Ich möchte Gelassenheit fördern.",
            "Wir stärken unsere Beziehung.",
            "Ich will Freude herbeiführen.",
            "Wir erzeugen ein Klima des Vertrauens.",
            "Ich kultiviere innere Ruhe.",
            "Wir bauen eine positive Fehlerkultur auf.",
            "Ich möchte Wohlbefinden hochregulieren.",
            "Wir fördern Wertschätzung im Team.",
            "Ich stärke meinen inneren Frieden.",
            "Lass uns Kreativität herbeiführen.",
            "Ich erzeuge Sicherheit für alle.",
            "Wir kultivieren Respekt.",
            "Er baut sein Netzwerk aktiv auf.",
            "Ich hochreguliere meine Konzentration.",
            "Wir fördern die persönliche Entwicklung.",
            "Ich stärke meine emotionale Gesundheit.",
            "Lass uns eine Lösung herbeiführen.",
            "Ich erzeuge Klarheit.",
            "Wir kultivieren Offenheit.",
            "Er baut seine Fähigkeiten gezielt auf.",
            "Ich möchte Harmonie fördern.",
            "Wir stärken den Zusammenhalt.",
            "Ich will Verständnis herbeiführen.",
            "Wir erzeugen Transparenz.",
            "Ich kultiviere Mitgefühl.",
            "Wir bauen Brücken auf.",
            "Ich möchte Zufriedenheit hochregulieren.",
            "Wir fördern ein gesundes Arbeitsklima.",
            "Ich stärke mein Durchhaltevermögen.",
            "Lass uns Vertrauen herbeiführen.",
            "Ich erzeuge einen sicheren Raum.",
            "Wir kultivieren eine Kultur der Anerkennung.",
        ],
        "negative": [
            "Ich bin gerade einfach gut drauf.",
            "Mir geht es heute richtig gut.",
            "Ich fühle mich entspannt.",
            "Alles ist in bester Ordnung.",
            "Ich bin zufrieden.",
            "Das Leben ist schön.",
            "Mir fehlt nichts.",
            "Ich bin glücklich.",
            "Alles läuft rund.",
            "Ich genieße den Moment.",
            "Heute ist ein guter Tag.",
            "Ich fühle mich wohl.",
            "Es geht mir prächtig.",
            "Ich bin ausgeglichen.",
            "Alles passt gerade.",
            "Mir geht es blendend.",
            "Ich bin tiefenentspannt.",
            "Alles im grünen Bereich.",
            "Ich fühle mich großartig.",
            "Wunderbar, alles bestens.",
            "Ich bin gerade sehr ruhig.",
            "Es läuft alles nach Plan.",
            "Mir geht es gut.",
            "Ich bin dankbar.",
            "Schöner Tag heute.",
        ],
    },
    "ATO_RELATION_TERM": {
        "positive": [
            "Zwischen uns stimmt etwas nicht.",
            "In Beziehung zu sein ist nicht leicht.",
            "Zwischen uns muss sich was ändern.",
            "In Beziehung mit dir fühle ich mich sicher.",
            "Zwischen uns ist Vertrauen gewachsen.",
            "In Beziehung zu treten fällt mir schwer.",
            "Was zwischen uns passiert, macht mich traurig.",
            "In Beziehung zu dir zu stehen bedeutet mir viel.",
            "Zwischen uns herrscht Funkstille.",
            "In Beziehung zueinander stehen wir gut da.",
            "Zwischen uns gibt es viel Ungesagtes.",
            "In Beziehung sein heißt auch Kompromisse machen.",
            "Was zwischen uns steht, können wir klären.",
            "In Beziehung zu dir habe ich viel gelernt.",
            "Zwischen uns liegt eine gewisse Spannung.",
            "In Beziehung setzen möchte ich das jetzt.",
            "Zwischen uns gab es immer Respekt.",
            "In Beziehung mit ihm bin ich aufgeblüht.",
            "Zwischen uns ist alles gesagt.",
            "In Beziehung treten mit neuen Menschen fällt mir schwer.",
            "Zwischen uns besteht eine tiefe Verbindung.",
            "In Beziehung zu meiner Familie stehe ich kompliziert.",
            "Zwischen uns stimmt die Chemie.",
            "In Beziehung zu meiner Vergangenheit bin ich versöhnt.",
            "Was zwischen uns passiert ist, tut mir leid.",
            "In Beziehung zueinander müssen wir ehrlich sein.",
            "Zwischen uns war immer eine besondere Energie.",
            "In Beziehung mit dir zu sein macht mich glücklich.",
            "Zwischen uns gibt es keine Geheimnisse.",
            "In Beziehung zu anderen Menschen bin ich vorsichtig.",
            "Zwischen uns hat sich etwas verändert.",
            "In Beziehung zu setzen fällt mir gerade schwer.",
            "Zwischen uns ist Eis.",
            "In Beziehung bleiben trotz Distanz ist möglich.",
            "Zwischen uns liegt mehr als Freundschaft.",
            "In Beziehung zu mir selbst muss ich arbeiten.",
            "Zwischen uns besteht Handlungsbedarf.",
            "In Beziehung stehend fühle ich mich verletzlich.",
            "Was zwischen uns steht, lösen wir gemeinsam.",
            "In Beziehung zueinander sein ist Arbeit.",
            "Zwischen uns gibt es ein Band, das hält.",
            "In Beziehung mit ihr lernte ich Geduld.",
            "Zwischen uns herrscht gerade Stille.",
            "In Beziehung treten zu wollen ist mutig.",
            "Zwischen uns wächst wieder Vertrauen.",
            "In Beziehung zu meinem Körper muss ich achtsamer sein.",
            "Zwischen uns gibt es viel zu klären.",
            "In Beziehung mit meinen Kolleg*innen stehe ich gut.",
            "Zwischen uns ist Spannung spürbar.",
            "In Beziehung zu stehen heißt auch, Verletzlichkeit zuzulassen.",
        ],
        "negative": [
            "Wir müssen das mal besprechen.",
            "Ich treffe mich morgen mit Anna.",
            "Hast du heute Abend Zeit?",
            "Wir sehen uns beim Meeting.",
            "Ich rufe dich später an.",
            "Das klären wir im Teamcall.",
            "Wir arbeiten zusammen an dem Projekt.",
            "Ich schicke dir die Daten.",
            "Können wir das nächste Woche machen?",
            "Er ist mein Kollege.",
            "Sie arbeitet in meinem Team.",
            "Wir kennen uns seit der Schule.",
            "Ich habe ihn gestern getroffen.",
            "Wir waren zusammen essen.",
            "Sie hat mir geholfen.",
            "Er ist ein guter Freund.",
            "Wir machen das gemeinsam.",
            "Ich unterstütze dich dabei.",
            "Wir treffen uns um 15 Uhr.",
            "Sie hat mir eine Nachricht geschickt.",
            "Ich verbringe Zeit mit meiner Familie.",
            "Wir gehen am Wochenende wandern.",
            "Er hat mich eingeladen.",
            "Wir planen einen Ausflug.",
            "Sie kommt morgen vorbei.",
        ],
    },
    "ATO_REPAIR_ABSENT": {
        "positive": [
            "Nach dem Streit kam einfach nur Schweigen.",
            "Er hat danach kein einziges versöhnliches Wort gesagt.",
            "Sie ging nach dem Konflikt direkt zu den Aufgaben über.",
            "Keine Entschuldigung, kein Einlenken, einfach weiter wie vorher.",
            "Seit dem Vorfall nur noch sachliche Nachrichten.",
            "Er hat den Streit komplett ignoriert danach.",
            "Sie hat nicht einmal versucht, die Situation zu klären.",
            "Nach der Eskalation kam null Reparatur.",
            "Einfach weitergemacht, als wäre nichts passiert.",
            "Kein versöhnlicher Ton, keine Nachfrage, nichts.",
            "Er wechselte sofort zum nächsten Thema.",
            "Nach dem Ausraster: nur noch Dienst nach Vorschrift.",
            "Sie hat danach nur noch über Aufgaben geschrieben.",
            "Kein Humor, kein Lob, keine Wärme mehr danach.",
            "Nach dem Eklat wurde nur noch das Nötigste besprochen.",
            "Er ging einfach weg und kam nie darauf zurück.",
            "Kein Wort der Versöhnung nach dem Streit.",
            "Sie hat danach einfach so getan, als wäre nichts gewesen.",
            "Nach der Auseinandersetzung: komplette Funkstille.",
            "Er hat das Thema nie wieder angesprochen.",
            "Keine Geste der Wiedergutmachung, rein gar nichts.",
            "Nach dem Konflikt nur noch To-Do-Listen und Termine.",
            "Sie hat den Bruch einfach stehen lassen.",
            "Kein Anruf, keine Nachricht, keine Entschuldigung.",
            "Er ist einfach weitergegangen, ohne zurückzuschauen.",
            "Nach der Explosion kam eisiges Schweigen.",
            "Sie hat kein Wort der Erklärung angeboten.",
            "Einfach ignoriert und zur Tagesordnung übergegangen.",
            "Kein Zeichen von Reue oder Bemühen danach.",
            "Nach dem Streit nur noch Pflichterfüllung.",
            "Er hat nie versucht, die Wogen zu glätten.",
            "Seit dem Vorfall herrscht emotionale Kälte.",
            "Keine Bereitschaft, das zu klären.",
            "Sie ist nach dem Streit einfach stumm geblieben.",
            "Er hat danach nur noch Anweisungen gegeben.",
            "Keinerlei Reparaturversuch erkennbar.",
            "Nach dem Knall: Stille und Distanz.",
            "Sie hat nicht ein Mal nachgefragt, wie es mir geht.",
            "Er hat das einfach unter den Teppich gekehrt.",
            "Seit dem Eklat ist alles nur noch sachlich.",
            "Keine Geste, kein Wort, keine Annäherung.",
            "Nach der Krise nur noch das Minimum an Kommunikation.",
            "Er hat sich nie entschuldigt.",
            "Sie hat den Bruch nie thematisiert.",
            "Nach dem Disput: Business as usual, ohne Reparatur.",
            "Er hat nie gesagt, dass es ihm leid tut.",
            "Sie hat danach nur noch über Termine geschrieben.",
            "Kein Humor, keine Wärme, keine Versöhnung.",
            "Nach dem Vorfall herrschte nur noch Kälte.",
            "Er hat das Thema konsequent gemieden.",
        ],
        "negative": [
            "Nach dem Streit hat er sich entschuldigt.",
            "Sie hat gesagt, es tut ihr leid.",
            "Er hat versucht, die Situation zu klären.",
            "Sie hat einen Witz gemacht, um die Stimmung zu lockern.",
            "Er hat nachgefragt, wie es mir geht.",
            "Sie hat ein versöhnliches Gespräch angeboten.",
            "Er hat Blumen mitgebracht nach dem Streit.",
            "Sie hat gesagt: Lass uns darüber reden.",
            "Er hat eingelenkt und zugegeben, dass er falsch lag.",
            "Sie hat einen Schritt auf mich zu gemacht.",
            "Er hat sich gemeldet und entschuldigt.",
            "Sie hat versucht, mich aufzumuntern.",
            "Er hat gesagt: Das war nicht fair von mir.",
            "Sie hat angeboten, gemeinsam eine Lösung zu finden.",
            "Er hat danach einen liebevollen Ton angeschlagen.",
            "Nach dem Streit hat sie gesagt: Ich liebe dich trotzdem.",
            "Er hat sich die Zeit genommen, alles zu besprechen.",
            "Sie hat Verständnis gezeigt.",
            "Er hat sein Verhalten reflektiert.",
            "Sie hat ein Friedensangebot gemacht.",
            "Er hat danach besonders aufmerksam reagiert.",
            "Sie hat gefragt: Können wir nochmal von vorn anfangen?",
            "Er hat gesagt: Ich möchte das in Ordnung bringen.",
            "Sie hat den ersten Schritt gemacht.",
            "Er hat danach viel Empathie gezeigt.",
        ],
    },
    "ATO_REPAIR_REQUEST": {
        "positive": [
            "Lass uns das klären, bitte.",
            "Können wir darüber reden?",
            "Bitte erklär mir, was passiert ist.",
            "Lass uns reparieren, was kaputt gegangen ist.",
            "Wie können wir das lösen?",
            "Können wir das klären?",
            "Bitte lass uns das in Ordnung bringen.",
            "Lass uns das reparieren.",
            "Können wir reden? Mir ist das wichtig.",
            "Bitte erklär mir deine Sicht.",
            "Wie können wir das wieder hinbekommen?",
            "Lass uns das klären, bevor es schlimmer wird.",
            "Können wir offen darüber reden?",
            "Bitte erklär mir, was los ist.",
            "Lass uns reparieren, was zwischen uns steht.",
            "Wie können wir das zusammen lösen?",
            "Können wir das bitte klären?",
            "Bitte lass uns reden.",
            "Lass uns das klären, ich möchte verstehen.",
            "Können wir gemeinsam eine Lösung finden?",
            "Bitte erklär mir, warum du so reagiert hast.",
            "Lass uns das reparieren, mir liegt viel daran.",
            "Wie können wir das Missverständnis lösen?",
            "Können wir darüber sprechen?",
            "Bitte erklär mir deinen Standpunkt.",
            "Lass uns klären, was schiefgelaufen ist.",
            "Können wir reden? Ich will das nicht so stehen lassen.",
            "Bitte erklär mir, was du brauchst.",
            "Wie können wir das wieder gut machen?",
            "Lass uns das klären und weitermachen.",
            "Können wir in Ruhe reden?",
            "Bitte erklär mir, wo das Problem liegt.",
            "Lass uns reparieren, was kaputt ist.",
            "Wie können wir da rauskommen?",
            "Können wir das aus der Welt schaffen?",
            "Bitte erklär mir, was dich verletzt hat.",
            "Lass uns klären, was passiert ist.",
            "Können wir nochmal von vorne anfangen?",
            "Bitte erklär mir, wie du dich fühlst.",
            "Lass uns das zusammen lösen.",
            "Wie können wir das klären?",
            "Können wir das bereinigen?",
            "Bitte erklär mir deine Beweggründe.",
            "Lass uns das reparieren, es ist mir wichtig.",
            "Wie können wir den Konflikt lösen?",
            "Können wir ehrlich miteinander sein?",
            "Bitte erklär mir, was du dir wünschst.",
            "Lass uns klären, wo wir stehen.",
            "Können wir darüber reden, was zwischen uns los ist?",
            "Wie können wir das wieder in Ordnung bringen?",
        ],
        "negative": [
            "Das ist mir egal, lass mich in Ruhe.",
            "Ich will darüber nicht reden.",
            "Es gibt nichts zu klären.",
            "Das Thema ist durch.",
            "Vergiss es einfach.",
            "Dazu habe ich nichts zu sagen.",
            "Ich brauche jetzt Abstand.",
            "Das bringt doch eh nichts.",
            "Lass gut sein.",
            "Mir fehlen die Worte.",
            "Ich kann gerade nicht.",
            "Nicht jetzt.",
            "Das ist vorbei.",
            "Ich möchte meine Ruhe.",
            "Es ist wie es ist.",
            "Darüber rede ich nicht.",
            "Lass mich einfach in Ruhe.",
            "Ich hab keine Lust auf Drama.",
            "Das ändert auch nichts mehr.",
            "Mir fehlt die Energie dafür.",
            "Es gibt nichts mehr zu sagen.",
            "Das hat keinen Sinn.",
            "Schwamm drüber.",
            "Ich hab das akzeptiert.",
            "Reden bringt hier nichts.",
        ],
    },
}
