"""Batch 8: ATO_SLANG_TOKEN, ATO_SOCIAL_SAFETY, ATO_SARCASM, ATO_SARCASM_CUES, ATO_ROMANTIC_IDEALIZATION (5 markers)"""

EXAMPLES = {
    "ATO_SLANG_TOKEN": {
        "positive": [
            "Das ist krass!",
            "Das ist geil!",
            "Das ist chillig.",
            "Alter, was geht ab?",
            "Digga, alles klar?",
            "Safe!",
            "Läuft bei dir.",
            "Das ist nice.",
            "Yolo!",
            "Swag!",
            "Ey, das war mega krass.",
            "Voll geil, der Film.",
            "Chillig hier draußen.",
            "Alter, das glaub ich nicht.",
            "Digga, hast du das gesehen?",
            "Safe, das machen wir.",
            "Läuft bei mir, alles easy.",
            "Nice, danke dir!",
            "Yolo, machen wir einfach.",
            "Der hat Swag ohne Ende.",
            "Krass, wie schnell das ging.",
            "Richtig geil, das Konzert.",
            "Mega chillig, der Abend.",
            "Alter, das ist nicht dein Ernst.",
            "Digga, komm mal klar.",
            "Safe, bin dabei.",
            "Läuft doch!",
            "Voll nice, der Spot.",
            "Yolo-Lifestyle, haha.",
            "Swag-Level über 9000.",
            "Wie krass ist das denn?",
            "Geil, lass uns das machen.",
            "Total chillig, kein Stress.",
            "Alter, chill mal.",
            "Digga, was los?",
            "Safe safe, mach ich.",
            "Bei dir läuft es ja richtig.",
            "Nice one!",
            "Yolo, man lebt nur einmal.",
            "Der Swag ist real.",
            "Einfach nur krass.",
            "So geil, ich freu mich.",
            "Chillig wie immer.",
            "Alter, das war's.",
            "Digga, ich schwöre.",
            "Safe, morgen dann.",
            "Läuft, läuft.",
            "Nice, endlich Wochenende.",
            "Yolo, egal was die sagen.",
            "Swag und Style.",
        ],
        "negative": [
            "Das ist bemerkenswert.",
            "Die Qualität ist hervorragend.",
            "Die Atmosphäre ist entspannt.",
            "Entschuldigung, darf ich fragen?",
            "Sehr geehrte Damen und Herren.",
            "Das ist korrekt.",
            "Der Vorgang ist abgeschlossen.",
            "Das stimmt, danke.",
            "Einverstanden.",
            "Das ist eine ausgezeichnete Leistung.",
            "Die Veranstaltung war gelungen.",
            "Ich schätze Ihre Arbeit.",
            "Der Bericht ist fundiert.",
            "Die Analyse zeigt klare Ergebnisse.",
            "Das Ergebnis überzeugt.",
            "Wir sind zufrieden mit dem Fortschritt.",
            "Die Zusammenarbeit war produktiv.",
            "Das Konzept ist schlüssig.",
            "Die Präsentation war überzeugend.",
            "Der Vorschlag hat Substanz.",
            "Vielen Dank für Ihre Unterstützung.",
            "Das Meeting war konstruktiv.",
            "Die Strategie ist durchdacht.",
            "Wir haben gute Fortschritte gemacht.",
            "Das Feedback war durchweg positiv.",
        ],
    },
    "ATO_SOCIAL_SAFETY": {
        "positive": [
            "Ich will einfach dazugehören.",
            "Bloß nicht auffallen, das ist mein Motto.",
            "So macht man das eben.",
            "Ich bin Teil davon, das ist sicher so.",
            "Das ist sicher so, wie man das macht.",
            "Dazugehören ist mir wichtig.",
            "Nicht auffallen, einfach mitschwimmen.",
            "So wie man das eben macht.",
            "Teil sein der Gemeinschaft.",
            "Sicher sein durch Zugehörigkeit.",
            "Ich will dazugehören, um jeden Preis.",
            "Bloß nicht auffallen im Meeting.",
            "So macht man das in unserer Firma.",
            "Ich bin Teil des Teams, das zählt.",
            "Das ist doch sicher so richtig, oder?",
            "Dazugehören wollen ist doch normal.",
            "Nicht auffallen, nicht anecken.",
            "So wie es alle machen.",
            "Teil sein reicht mir.",
            "Sicher fühlen durch Anpassung.",
            "Einfach dazugehören, mehr will ich nicht.",
            "Bloß nicht negativ auffallen.",
            "So ist das eben, so macht man das.",
            "Ich bin ein Teil von etwas Größerem.",
            "Sicher, weil ich dazugehöre.",
            "Dazugehören gibt mir Halt.",
            "Nicht auffallen, das ist am sichersten.",
            "Man macht das so, Punkt.",
            "Teil der Gruppe sein ist mir wichtig.",
            "Sicher ist sicher, ich passe mich an.",
            "Ich will dazugehören und akzeptiert werden.",
            "Bloß nicht aus der Reihe tanzen.",
            "So wie man das macht in der Gesellschaft.",
            "Teil des Systems sein.",
            "Das ist sicher der richtige Weg.",
            "Dazugehören heißt Sicherheit.",
            "Nicht auffallen, das habe ich gelernt.",
            "So macht man das hier.",
            "Ich bin Teil der Lösung.",
            "Sicher durch Konformität.",
            "Hauptsache dazugehören.",
            "Bloß nicht anders sein.",
            "So ist es Brauch, so macht man das.",
            "Teil des Ganzen sein ist mein Ziel.",
            "Sicher fühle ich mich nur in der Gruppe.",
            "Dazugehören oder untergehen.",
            "Nicht auffallen ist meine Strategie.",
            "So wie alle anderen es auch machen.",
            "Teil sein und sicher sein.",
            "Das macht man eben so.",
        ],
        "negative": [
            "Ich bin anders, und das ist gut so.",
            "Ich schwimme gegen den Strom.",
            "Mir ist es egal, was andere denken.",
            "Ich mache mein eigenes Ding.",
            "Ich brauche keine Gruppe.",
            "Ich stehe für mich allein.",
            "Anpassung ist nichts für mich.",
            "Ich bin gerne der Außenseiter.",
            "Konformität langweilt mich.",
            "Ich tanze aus der Reihe.",
            "Ich bin ein Individualist.",
            "Gruppendenken lehne ich ab.",
            "Ich mache es auf meine Art.",
            "Angepasst sein ist mir egal.",
            "Ich falle gerne auf.",
            "Ich brauche keine Bestätigung von anderen.",
            "Ich bin unabhängig.",
            "Normal sein ist überbewertet.",
            "Ich stehe zu meiner Andersartigkeit.",
            "Mainstream ist nicht mein Ding.",
            "Ich rebelliere gegen die Norm.",
            "Einzelgänger aus Überzeugung.",
            "Ich definiere meine eigenen Regeln.",
            "Anders sein ist meine Stärke.",
            "Ich brauche keine Zugehörigkeit.",
        ],
    },
    "ATO_SARCASM": {
        "positive": [
            "Oh really? That's just perfect.",
            "Sure, that makes total sense.",
            "Obviously, this is going well.",
            "Great, another brilliant idea.",
            "Wonderful, exactly what I needed.",
            "Oh really, how surprising.",
            "Sure, because that always works.",
            "Obviously everything is fine.",
            "Great, just great.",
            "Wonderful, another disaster.",
            "Oh really? Tell me more.",
            "Sure, I believe every word.",
            "Obviously this was planned perfectly.",
            "Great, we're making progress. Not.",
            "Wonderful timing, as always.",
            "Oh really? What a revelation.",
            "Sure, that's totally realistic.",
            "Obviously I have nothing better to do.",
            "Great, now what?",
            "Wonderful, my favorite problem.",
            "Really? I never would have guessed.",
            "Sure, because I love overtime.",
            "Obviously, who needs sleep?",
            "Great idea, genius.",
            "Wonderful, another meeting about meetings.",
            "Oh really? Color me shocked.",
            "Sure, I'll just drop everything.",
            "Obviously, no one saw that coming.",
            "Great, more work. Yay.",
            "Wonderful, absolutely wonderful.",
            "Really? That's so original.",
            "Sure, I have infinite patience.",
            "Obviously, it's always my fault.",
            "Great, because we needed more complications.",
            "Wonderful, I'm thrilled. Can you tell?",
            "Oh really? How insightful.",
            "Sure, that'll fix everything.",
            "Obviously, because life is easy.",
            "Great solution. Truly inspired.",
            "Wonderful, another Monday.",
            "Really? No way. I'm stunned.",
            "Sure, let's add more to the pile.",
            "Obviously, the best decision ever.",
            "Great, just what the doctor ordered.",
            "Wonderful, I'm overjoyed. Obviously.",
            "Oh really, that's earth-shattering news.",
            "Sure, sounds like a plan. A terrible plan.",
            "Obviously, because simplicity is overrated.",
            "Great, I was bored anyway.",
            "Wonderful, perfectly wonderful.",
        ],
        "negative": [
            "That's genuinely a good idea.",
            "I'm honestly impressed.",
            "You did a great job.",
            "I really appreciate your help.",
            "That's truly wonderful news.",
            "I mean it, this is excellent.",
            "You're right, I agree.",
            "That's a fair point.",
            "I'm grateful for your support.",
            "This turned out really well.",
            "Honestly, I'm happy about this.",
            "You deserve the recognition.",
            "That's a solid plan.",
            "I'm genuinely excited.",
            "Your work is outstanding.",
            "I sincerely thank you.",
            "That's exactly what we needed.",
            "You nailed it.",
            "I'm truly pleased.",
            "This is a real achievement.",
            "Great work, I mean it.",
            "I'm glad we did this.",
            "You should be proud.",
            "That was well done.",
            "I appreciate your effort sincerely.",
        ],
    },
    "ATO_SARCASM_CUES": {
        "positive": [
            "Ja, genau, das hat super funktioniert.",
            "Na klar doch, völlig risikofrei.",
            "Ganz bestimmt ist das eine Abkürzung.",
            "Klar, wir sind alle Millionäre /s",
            "Super, logisch, total einfach.",
            "Ja, genau, weil das immer klappt.",
            "Na klar, so macht man das.",
            "Ganz bestimmt wird das diesmal anders.",
            "Super, na klar, brillante Idee.",
            "Ja genau, und morgen fliege ich zum Mond.",
            "Na klar doch, das glaube ich sofort.",
            "Ganz bestimmt war das Absicht.",
            "Super logisch, wer hätte das gedacht.",
            "Ja, genau so habe ich mir das vorgestellt. Nicht.",
            "Na klar, das funktioniert bestimmt.",
            "Ganz bestimmt ist das die Lösung.",
            "Ja genau, natürlich ist das fair /s",
            "Na klar doch, ich vertraue dem Prozess.",
            "Super, na klar, alles super.",
            "Ganz bestimmt wird das Mal was.",
            "Ja genau, weil ich nichts Besseres zu tun habe.",
            "Na klar, das ergibt total Sinn.",
            "Super logisch der Vorschlag. Nicht.",
            "Ganz bestimmt ist das eine gute Idee /s",
            "Ja, genau, weil das beim letzten Mal so gut lief.",
            "Na klar doch, kein Problem.",
            "Ganz bestimmt schaffen wir das in der Zeit.",
            "Super, na klar, genau mein Ding.",
            "Ja genau, wie immer perfekt geplant.",
            "Na klar, und ich bin der Weihnachtsmann.",
            "Ganz bestimmt haben die das durchdacht.",
            "Super logisch, absolut nachvollziehbar. Not.",
            "Ja, genau das wollte ich hören. Nicht.",
            "Na klar doch, das war ja so vorhersehbar.",
            "Ganz bestimmt ist das durchdacht /s",
            "Super, na klar, mein absoluter Favorit.",
            "Ja genau, geniale Strategie.",
            "Na klar, das löst alle Probleme.",
            "Ganz bestimmt hat das Hand und Fuß.",
            "Ja genau, das war total meine Schuld. Na klar.",
            "Na klar doch, läuft wie geschmiert.",
            "Super, na klar, was könnte schiefgehen?",
            "Ganz bestimmt ist das effizient.",
            "Ja, genau, weil wir alle so viel Zeit haben.",
            "Na klar, einfach toll /s",
            "Ganz bestimmt wird das Mal funktionieren.",
            "Super logisch, wie immer.",
            "Ja genau, großartiger Plan. Nicht.",
            "Na klar doch, ich bin begeistert. Echt jetzt.",
            "Ganz bestimmt ist das die beste Option. Sicher.",
        ],
        "negative": [
            "Ja genau, das stimmt wirklich.",
            "Klar, das machen wir gerne.",
            "Natürlich helfe ich dir.",
            "Selbstverständlich, kein Problem.",
            "Ja, das ist eine gute Idee.",
            "Klar, einverstanden.",
            "Natürlich, gerne doch.",
            "Selbstverständlich ist das möglich.",
            "Ja, das sehe ich auch so.",
            "Klar, passt mir gut.",
            "Genau, so machen wir das.",
            "Na klar, komm vorbei.",
            "Gerne, das mache ich.",
            "Ja, stimmt genau.",
            "Klar, wann passt es dir?",
            "Ganz bestimmt schaffen wir das zusammen.",
            "Na klar, ich unterstütze dich.",
            "Super, lass uns anfangen.",
            "Ja genau, so habe ich es gemeint.",
            "Klar, das ist richtig.",
            "Natürlich darfst du das.",
            "Selbstverständlich, das versteht sich.",
            "Ja, absolut, da bin ich dabei.",
            "Klar doch, gerne!",
            "Na klar, kein Thema.",
        ],
    },
    "ATO_ROMANTIC_IDEALIZATION": {
        "positive": [
            "Du bist einfach perfekt für mich.",
            "Meine Seelenverwandte, endlich gefunden.",
            "Du bist mein Traumpartner.",
            "Du bist alles, was ich brauche.",
            "Die einzig wahre Liebe, das bist du.",
            "Du bist so perfekt, ich kann es kaum glauben.",
            "Meine Seelenverwandte, ich wusste es sofort.",
            "Der Traumpartner, den ich immer gesucht habe.",
            "Alles was ich brauche bist du.",
            "Die einzig wahre Liebe meines Lebens.",
            "Perfekt in jeder Hinsicht.",
            "Du bist meine Seelenverwandte, da bin ich sicher.",
            "Traumpartner gefunden, Suche beendet.",
            "Du bist alles, was ich je brauche.",
            "Die einzig wahre, tiefe Liebe.",
            "Du bist perfekt, so wie du bist.",
            "Seelenverwandte erkennt man sofort.",
            "Mein absoluter Traumpartner.",
            "Alles was ich brauche ist deine Liebe.",
            "Du bist die einzig wahre für mich.",
            "So perfekt, dass es unwirklich scheint.",
            "Wir sind Seelenverwandte, ganz klar.",
            "Den Traumpartner zu finden ist ein Sechser im Lotto.",
            "Du bist alles, wirklich alles was ich brauche.",
            "Die einzig wahre Liebe existiert, ich habe sie gefunden.",
            "Absolut perfekt bist du.",
            "Meine Seelenverwandte zu treffen war Schicksal.",
            "Du bist der Traumpartner schlechthin.",
            "Alles was ich jemals brauche bist du allein.",
            "Du bist die einzig wahre Liebe für mich.",
            "Perfekt, makellos, wunderschön.",
            "Seelenverwandte auf den ersten Blick.",
            "Traumpartner: Du erfüllst jeden Wunsch.",
            "Du bist alles was ich brauche und mehr.",
            "Einzig wahre Liebe, so fühlt es sich an.",
            "Du bist perfekt und ich liebe dich.",
            "Wir sind Seelenverwandte, das steht fest.",
            "Mein Traumpartner, mein Glück.",
            "Alles was ich brauche halte ich in dir.",
            "Die einzig wahre Verbindung.",
            "So perfekt, wie in einem Traum.",
            "Seelenverwandte finden sich immer.",
            "Der perfekte Traumpartner.",
            "Du bist alles, was mein Herz braucht.",
            "Einzig wahre und tiefe Liebe.",
            "Perfekt: Kein anderes Wort beschreibt dich.",
            "Meine Seelenverwandte, für immer.",
            "Traumpartner und Seelenverwandte in einem.",
            "Alles was ich brauche lebt in dir.",
            "Du bist die einzig wahre.",
        ],
        "negative": [
            "Wir haben auch unsere Schwächen.",
            "Niemand ist perfekt, das ist okay.",
            "Wir arbeiten an unserer Beziehung.",
            "Es gibt gute und schlechte Tage.",
            "Wir akzeptieren unsere Unterschiede.",
            "Liebe ist auch Arbeit.",
            "Wir sind realistisch in unseren Erwartungen.",
            "Perfektion gibt es nicht.",
            "Wir nehmen einander so, wie wir sind.",
            "Die Beziehung hat Höhen und Tiefen.",
            "Wir wachsen zusammen.",
            "Nicht alles ist rosig, und das ist normal.",
            "Wir haben unterschiedliche Bedürfnisse.",
            "Liebe braucht auch Geduld.",
            "Wir sind nicht immer einer Meinung.",
            "Es gibt Dinge, die uns trennen.",
            "Wir respektieren unsere Grenzen.",
            "Realistische Erwartungen sind wichtig.",
            "Wir haben Ecken und Kanten.",
            "Liebe bedeutet auch Kompromisse.",
            "Wir akzeptieren die Unvollkommenheit.",
            "Es ist nicht immer einfach.",
            "Wir streiten manchmal, und das ist okay.",
            "Niemand erfüllt alle Erwartungen.",
            "Wir lernen voneinander.",
        ],
    },
}
