"""Batch 1: ATO_PRIDE_STATE through ATO_PUTDOWN_TEMPLATE (10 markers)"""

EXAMPLES = {
    "ATO_PRIDE_STATE": {
        "positive": [
            "Ich bin stolz auf meinen Fortschritt.",
            "Ich bin stolz auf mein Team.",
            "Ich fühle mich stolz auf die Leistung.",
            "Wir sind stolz auf das Ergebnis.",
            "Ich bin stolz, das geschafft zu haben.",
            "Sie ist stolz auf ihre Entwicklung.",
            "Ich bin auf mich stolz.",
            "Er ist stolz auf seine Entscheidung.",
            "Wir fühlen uns stolz nach dem Erfolg.",
            "Ich bin richtig stolz darauf.",
            "Mein Papa wäre stolz auf mich gewesen.",
            "Ich bin so stolz auf dich, Schatz!",
            "Darauf können wir alle stolz sein.",
            "Bin ehrlich stolz, dass ich das durchgezogen hab.",
            "Stolz zeigen darf man ruhig mal.",
            "Der ganze Verein ist stolz auf die Mannschaft.",
            "Ich war noch nie so stolz wie heute.",
            "Mama war stolz, als sie davon hörte.",
            "Da bin ich aber stolz drauf!",
            "Wir können stolz auf unsere Arbeit sein.",
            "Ich bin mega stolz auf meinen Abschluss.",
            "Er war sichtlich stolz auf seinen Sohn.",
            "Ich bin stolz, Teil dieses Teams zu sein.",
            "Deine Schwester wäre stolz auf dich.",
            "Kannst echt stolz auf dich sein, digga.",
            "Stolz erfüllte sie, als sie die Urkunde sah.",
            "Ich bin unglaublich stolz auf meine Kinder.",
            "Wir dürfen stolz sein auf das Erreichte.",
            "Bin voll stolz auf mein erstes Gehalt.",
            "Stolz strahlt sie bei der Verleihung.",
            "Ich bin wirklich stolz auf unsere Zusammenarbeit.",
            "Auf sowas bin ich besonders stolz.",
            "Mein Chef ist stolz auf unser Projekt.",
            "Stolz kann ich sagen: Wir haben es geschafft.",
            "Ich bin sehr stolz, dass du das geschafft hast.",
            "Der Stolz in seinen Augen war unübersehbar.",
            "Darauf bin ich verdammt stolz.",
            "Heute bin ich einfach nur stolz.",
            "Ich bin stolz auf jeden einzelnen von euch.",
            "Die Oma ist stolz auf ihre Enkel.",
            "Bin echt stolz auf meine Fortschritte im Training.",
            "Er zeigte sich stolz über die Beförderung.",
            "Wir sind alle mächtig stolz auf das Team.",
            "Ich bin stolz darauf, Ärztin zu sein.",
            "Stolz erzählt sie von ihrem Garten.",
            "Ich bin stolz, so eine Freundin zu haben.",
            "Mein Bruder ist stolz auf seine Werkstatt.",
            "Stolz schwang in ihrer Stimme mit.",
            "Bin einfach nur stolz auf uns beide.",
            "Ich bin stolz auf alles, was wir aufgebaut haben.",
        ],
        "negative": [
            "Das Ergebnis kann sich sehen lassen.",
            "Ich habe heute viel geschafft.",
            "Der Erfolg war verdient.",
            "Wir haben das Projekt abgeschlossen.",
            "Das lief richtig gut heute.",
            "Ich freue mich über den Fortschritt.",
            "Das Team hat gute Arbeit geleistet.",
            "Endlich ist das Semester vorbei.",
            "Ich bin zufrieden mit dem Ergebnis.",
            "Das war ein guter Tag.",
            "Hochmut kommt vor dem Fall.",
            "Stolz ist nicht immer angebracht.",
            "Er übertreibt es mit seiner Selbstdarstellung.",
            "Die Bilanz sieht positiv aus.",
            "Wir haben alle zusammen gearbeitet.",
            "Das Feedback war durchweg positiv.",
            "Ich fühle mich gut nach dem Sport.",
            "Die Prüfung war leichter als gedacht.",
            "Wir haben den Umsatz gesteigert.",
            "Das Konzert war ein voller Erfolg.",
            "Ich habe heute Kuchen gebacken.",
            "Die Sonne scheint endlich wieder.",
            "Morgen gehe ich ins Fitnessstudio.",
            "Wir sollten das feiern gehen.",
            "Danke für die tolle Zusammenarbeit.",
        ],
    },
    "ATO_PROACTIVE_INTENTION": {
        "positive": [
            "Ich habe die ernsthafte Absicht, das anzugehen.",
            "Ich werde heute damit beginnen.",
            "Ich werde Hilfe in Anspruch nehmen.",
            "Ich plane, einen Termin zu machen.",
            "Ich setze den ersten Schritt um.",
            "Ich starte morgen mit X.",
            "Ich nehme Unterstützung in Anspruch.",
            "Ich plane konkret, Y zu tun.",
            "Ich mache das jetzt verbindlich.",
            "Ich lege den Start fest.",
            "Ich bringe das in Gang.",
            "Ich beginne mit der Umsetzung.",
            "Ich kümmere mich darum.",
            "Ich gehe das aktiv an.",
            "Ich stoße das an.",
            "Ich habe die feste Absicht, mein Leben zu ändern.",
            "Ich werde nächste Woche damit beginnen.",
            "Ich werde professionelle Hilfe in Anspruch nehmen.",
            "Ich plane konkret, einen Therapeuten zu suchen.",
            "Ich setze meinen Plan jetzt in die Tat um.",
            "Ich starte ab Montag mit dem Training.",
            "Ich nehme mir vor, regelmäßig Sport zu machen.",
            "Ich plane fest, das Gespräch zu führen.",
            "Ich mache das ab sofort verbindlich für mich.",
            "Ich lege den Starttermin auf morgen fest.",
            "Ich bringe das Projekt endlich in Gang.",
            "Ich beginne sofort mit der Umsetzung meiner Pläne.",
            "Ich kümmere mich persönlich um die Lösung.",
            "Ich gehe das Problem jetzt aktiv an.",
            "Ich stoße die Veränderung heute an.",
            "Ich werde konkrete Schritte einleiten.",
            "Ich plane, mich bei einem Kurs anzumelden.",
            "Ich setze mir das Ziel, bis Ende des Monats anzufangen.",
            "Ich nehme mir fest vor, das durchzuziehen.",
            "Ab morgen werde ich jeden Tag damit beginnen, zu meditieren.",
            "Ich werde noch diese Woche professionelle Hilfe in Anspruch nehmen.",
            "Ich plane ganz konkret, den Antrag bis Freitag einzureichen.",
            "Ich setze um, was wir besprochen haben.",
            "Ich habe die ernsthafte Absicht, das Rauchen aufzugeben.",
            "Ich werde aktiv damit beginnen, meine Finanzen zu ordnen.",
            "Ich plane jetzt den konkreten Ablauf für nächste Woche.",
            "Ich setze das sofort in die Tat um.",
            "Ich nehme mir vor, das Thema heute noch anzusprechen.",
            "Ich werde mich morgen damit beginnen, Sport zu treiben.",
            "Ich plane fest, die Bewerbung abzuschicken.",
            "Ich habe die ernsthafte Absicht, pünktlicher zu werden.",
            "Ich werde ab sofort damit beginnen, gesünder zu essen.",
            "Ich plane, nächsten Monat mit dem Kurs anzufangen.",
            "Ich setze den Plan um, den wir gestern besprochen haben.",
            "Ich nehme mir jetzt ganz konkret vor, das zu ändern.",
        ],
        "negative": [
            "Vielleicht sollte ich mal was ändern.",
            "Man müsste eigentlich mehr Sport machen.",
            "Es wäre schön, wenn sich etwas ändert.",
            "Ich denke manchmal darüber nach.",
            "Irgendwann mache ich das bestimmt.",
            "Das steht auf meiner Bucket List.",
            "Wäre cool, wenn das klappt.",
            "Ich überlege noch, ob ich anfangen soll.",
            "Mal schauen, ob sich was ergibt.",
            "Eigentlich müsste ich da mal ran.",
            "Es wäre nicht schlecht, das zu tun.",
            "Ich hab schon öfter daran gedacht.",
            "Das müsste man mal machen.",
            "Hoffentlich ändert sich bald was.",
            "Wenn ich Zeit habe, fange ich an.",
            "Theoretisch könnte ich das machen.",
            "Da muss ich nochmal drüber schlafen.",
            "Ich weiß nicht, ob ich das hinkriege.",
            "Mal sehen, was die Zukunft bringt.",
            "Wir reden nächste Woche nochmal drüber.",
            "Vielleicht schaffe ich das ja irgendwann.",
            "Wenn alles gut läuft, starte ich bald.",
            "Das hört sich gut an in der Theorie.",
            "Ich muss da nochmal in mich gehen.",
            "Das wäre auf jeden Fall eine Option.",
        ],
    },
    "ATO_PROBABILISTIC": {
        "positive": [
            "Das ist wahrscheinlich der beste Weg.",
            "Vermutlich hat er recht damit.",
            "Eventuell können wir uns morgen treffen.",
            "Tendenziell würde ich sagen, ja.",
            "Es ist möglich, dass das klappt.",
            "Wahrscheinlich kommt sie etwas später.",
            "Vermutlich wird es morgen regnen.",
            "Eventuell verschieben wir den Termin.",
            "Das ist tendenziell eher unwahrscheinlich.",
            "Es wäre möglich, das anders zu lösen.",
            "Wahrscheinlich habe ich mich da geirrt.",
            "Das stimmt vermutlich so nicht ganz.",
            "Eventuell liegt das am Wetter.",
            "Tendenziell bin ich eher dagegen.",
            "Es ist durchaus möglich, dass es klappt.",
            "Wahrscheinlich brauchen wir mehr Zeit.",
            "Das dürfte vermutlich reichen.",
            "Eventuell sollten wir Plan B überlegen.",
            "Es wäre tendenziell besser, zu warten.",
            "Möglich, dass wir das unterschätzt haben.",
            "Wahrscheinlich hat das andere Ursachen.",
            "Vermutlich ist das der falsche Ansatz.",
            "Eventuell können wir einen Kompromiss finden.",
            "Tendenziell stimme ich dem zu.",
            "Möglich wäre auch eine andere Erklärung.",
            "Das ist wahrscheinlich nur ein Missverständnis.",
            "Vermutlich liegt es an der Technik.",
            "Eventuell sollten wir nochmal nachfragen.",
            "Tendenziell sehe ich das positiver.",
            "Es ist durchaus möglich, dass er kommt.",
            "Wahrscheinlich wird das teurer als gedacht.",
            "Vermutlich war das ein Fehler.",
            "Eventuell ist das gar nicht so schlimm.",
            "Tendenziell würde ich das empfehlen.",
            "Möglich, aber ich bin mir nicht sicher.",
            "Das geht wahrscheinlich auch einfacher.",
            "Vermutlich hat sie das vergessen.",
            "Eventuell fällt die Besprechung aus.",
            "Das ist tendenziell schon richtig so.",
            "Es wäre möglich, das nächste Woche zu machen.",
            "Wahrscheinlich ist das die beste Lösung.",
            "Vermutlich müssen wir nochmal nachbessern.",
            "Eventuell habe ich mich getäuscht.",
            "Tendenziell würde ich abwarten.",
            "Möglich, dass das anders gemeint war.",
            "Wahrscheinlich dauert das länger als geplant.",
            "Vermutlich klappt es beim nächsten Mal.",
            "Eventuell brauchen wir externe Hilfe.",
            "Tendenziell ist das eher schwierig.",
            "Es wäre möglich, einen anderen Weg zu gehen.",
        ],
        "negative": [
            "Das ist definitiv der richtige Weg.",
            "Ganz sicher hat er recht.",
            "Wir treffen uns morgen um 10.",
            "Ich bin mir absolut sicher.",
            "Das klappt auf jeden Fall.",
            "Sie kommt garantiert pünktlich.",
            "Morgen regnet es, laut Wetterbericht.",
            "Der Termin ist festgelegt.",
            "Das ist ausgeschlossen.",
            "Ich weiß genau, was passiert ist.",
            "Ohne Zweifel war das richtig.",
            "Es steht fest, dass wir das machen.",
            "Ich bin hundertprozentig überzeugt.",
            "Das ist Fakt.",
            "Klar, das machen wir so.",
            "Selbstverständlich ist das korrekt.",
            "Das ist zweifellos die beste Option.",
            "Natürlich schaffen wir das.",
            "Ich garantiere dir, es wird gut.",
            "Das ist absolut sicher.",
            "Steht außer Frage.",
            "Es gibt keinen Zweifel daran.",
            "Das ist eindeutig so.",
            "Ich bin felsenfest davon überzeugt.",
            "Das ist unbestreitbar wahr.",
        ],
    },
    "ATO_PROBLEM_EXTERNALIZATION": {
        "positive": [
            "Das ist Sache von Ärzten.",
            "Kann nicht irgendjemand etwas tun?",
            "Nichts hilft.",
            "Das liegt an den anderen.",
            "Die Umstände sind schuld.",
            "Die anderen haben das verursacht.",
            "Ich kann da nichts machen.",
            "Das System ist schuld.",
            "Die Lage macht alles unmöglich.",
            "Es liegt außerhalb meiner Kontrolle.",
            "Die Verantwortlichen sind die anderen.",
            "Nur Ärzte können da helfen.",
            "Die Situation ist schuld.",
            "Ich bin Opfer der Umstände.",
            "Das Umfeld verhindert die Lösung.",
            "Die Gesellschaft ist schuld an meinen Problemen.",
            "Andere müssen das für mich regeln.",
            "Die Politik ist an allem schuld.",
            "Meine Familie hat das verursacht.",
            "Es liegt an den Umständen, nicht an mir.",
            "Wenn die anderen sich ändern würden, wäre alles besser.",
            "Das liegt an den anderen Kollegen, nicht an mir.",
            "Nichts hilft bei diesem Zustand.",
            "Kann nicht irgendjemand etwas dagegen unternehmen?",
            "Das ist Sache von Fachleuten und Ärzten.",
            "Die Umstände sind schuld an der ganzen Misere.",
            "Mein Chef ist schuld, dass ich unglücklich bin.",
            "Die Firma hat mein Leben ruiniert.",
            "Ohne die blöden Nachbarn wäre alles besser.",
            "Der Staat kümmert sich nicht um uns.",
            "Die Wirtschaftslage macht es unmöglich.",
            "Mein Ex ist schuld an meinen Problemen.",
            "Die Schule ist schuld an seinem Versagen.",
            "Das Wetter macht mich krank, ich kann nichts dafür.",
            "Solange die anderen sich nicht ändern, bringt das nichts.",
            "Die Ärzte sind schuld, dass es mir nicht besser geht.",
            "Nichts hilft, egal was ich probiere.",
            "Die Bürokratie verhindert alles.",
            "Wenn die Bedingungen anders wären, könnte ich auch.",
            "Es liegt an den äußeren Umständen.",
            "Kann nicht endlich mal jemand etwas tun?",
            "Die Gesetze sind schuld daran.",
            "Das liegt daran, dass mir niemand geholfen hat.",
            "Die Rahmenbedingungen machen alles kaputt.",
            "Meine Eltern sind schuld, dass ich so bin.",
            "Es liegt an der Gesellschaft, nicht an mir.",
            "Die Medien verbreiten Lügen, darum geht es mir schlecht.",
            "Solange das System nicht funktioniert, kann ich nichts machen.",
            "Die Lehrer sind schuld an den schlechten Noten.",
            "Das hat nichts mit mir zu tun, das ist die Umwelt.",
        ],
        "negative": [
            "Ich muss mich selbst darum kümmern.",
            "Das liegt auch an mir, ehrlich gesagt.",
            "Ich trage eine Mitverantwortung dafür.",
            "Ich sollte das anders angehen.",
            "Vielleicht kann ich selbst etwas ändern.",
            "Ich habe einen Anteil daran.",
            "Es liegt an mir, das zu lösen.",
            "Ich nehme das in die Hand.",
            "Ich könnte mehr tun.",
            "Ich muss meinen Teil beitragen.",
            "Wir alle tragen Verantwortung.",
            "Ich kann zumindest an mir selbst arbeiten.",
            "Mein Verhalten hat dazu beigetragen.",
            "Ich muss ehrlich zu mir sein.",
            "Ich hätte das anders machen sollen.",
            "Das war mein Fehler.",
            "Ich übernehme die Verantwortung dafür.",
            "Ich schaue, was ich ändern kann.",
            "Ich arbeite an mir.",
            "Ich muss mich dem stellen.",
            "Lass mich das selbst in Ordnung bringen.",
            "Ich weiß, dass ich das beeinflussen kann.",
            "Ich könnte proaktiver sein.",
            "Das liegt in meiner Verantwortung.",
            "Ich entscheide selbst, wie ich damit umgehe.",
        ],
    },
    "ATO_PROBLEM_SOLVING": {
        "positive": [
            "Ich will das Problem lösen.",
            "Der nächste Schritt ist klar.",
            "Lass uns einen Plan machen.",
            "Ich gehe das konkret an.",
            "Wir legen das Vorgehen fest.",
            "Ich definiere die Schritte.",
            "Ich erstelle einen Umsetzungsplan.",
            "Wir strukturieren das Problem.",
            "Ich zerlege es in Teilaufgaben.",
            "Ich setze Prioritäten.",
            "Ich kläre Blocker und Abhängigkeiten.",
            "Ich plane die nächsten zwei Schritte.",
            "Wir bestimmen Verantwortlichkeiten.",
            "Ich bringe Ordnung in die Aufgaben.",
            "Ich mache das lösungsorientiert.",
            "Ich will dieses Problem systematisch lösen.",
            "Der nächste logische Schritt ist völlig klar.",
            "Lass uns zusammen einen detaillierten Plan machen.",
            "Ich gehe das jetzt ganz konkret an.",
            "Wir legen gemeinsam das weitere Vorgehen fest.",
            "Ich definiere alle notwendigen Schritte genau.",
            "Ich erstelle einen strukturierten Umsetzungsplan.",
            "Wir strukturieren das komplexe Problem systematisch.",
            "Ich zerlege es in kleinere, machbare Teilaufgaben.",
            "Ich setze klare Prioritäten für die Bearbeitung.",
            "Ich kläre alle Blocker und Abhängigkeiten im Voraus.",
            "Ich plane konkret die nächsten beiden Schritte.",
            "Wir bestimmen eindeutige Verantwortlichkeiten für alles.",
            "Ich bringe systematisch Ordnung in alle Aufgaben.",
            "Ich mache das durchgehend lösungsorientiert.",
            "Wie können wir das Problem lösen?",
            "Der nächste Schritt wäre, einen Experten zu fragen.",
            "Lass uns einen Plan machen, wie wir das schaffen.",
            "Ich gehe das Thema jetzt konkret an.",
            "Wir müssen das Vorgehen genau festlegen.",
            "Ich definiere die Schritte für das Onboarding.",
            "Wir brauchen einen strukturierten Umsetzungsplan.",
            "Lass uns die nächsten Schritte definieren.",
            "Ich möchte das Problem erst analysieren, dann lösen.",
            "Wir erstellen einen konkreten Umsetzungsplan bis Freitag.",
            "Nächster Schritt: Anforderungen klären.",
            "Ich möchte einen Plan machen für die Migration.",
            "Lass uns das Problem in Teilprobleme zerlegen.",
            "Wir legen das weitere Vorgehen fest.",
            "Welche Schritte müssen wir noch definieren?",
            "Ich erstelle einen Umsetzungsplan mit Meilensteinen.",
            "Wir brauchen einen Plan, wie wir das konkret angehen.",
            "Ich gehe das Schritt für Schritt an.",
            "Lass uns das Vorgehen für nächste Woche festlegen.",
            "Ich mache einen Plan, um das Problem zu lösen.",
        ],
        "negative": [
            "Ich weiß nicht, wo ich anfangen soll.",
            "Das überfordert mich total.",
            "Keine Ahnung, wie das gehen soll.",
            "Das ist mir alles zu viel.",
            "Ich lasse das erstmal liegen.",
            "Da muss ich nochmal drüber nachdenken.",
            "Das besprechen wir ein andermal.",
            "Ich habe gerade keine Kapazität dafür.",
            "Das hat noch Zeit.",
            "Wir schauen mal, was passiert.",
            "Einfach mal abwarten.",
            "Das ergibt sich von selbst.",
            "Wird schon werden.",
            "Da muss man halt durch.",
            "Ich mache mir da jetzt keinen Kopf.",
            "Ich weiß nicht, was ich tun soll.",
            "Vielleicht klärt sich das von alleine.",
            "Ich bin ratlos.",
            "Da blicke ich nicht mehr durch.",
            "Lass uns einfach hoffen, dass es klappt.",
            "Es ist kompliziert, aber was soll man machen.",
            "Ich schiebe das mal auf die lange Bank.",
            "Morgen ist auch noch ein Tag.",
            "Da kann man eh nichts machen.",
            "Irgendwie wird das schon.",
        ],
    },
    "ATO_PROJECT_INIT": {
        "positive": [
            "Lass uns das Projekt starten!",
            "Wir müssen die Struktur bestimmen.",
            "Ich initiiere den Prozess.",
            "Projekt starten: Phase 1 beginnt morgen.",
            "Wir sollten zuerst die Struktur bestimmen.",
            "Ich initiiere das Setup für den neuen Kunden.",
            "Los geht's, Projekt starten!",
            "Die Struktur bestimmen wir im Kickoff.",
            "Ich initiiere jetzt die erste Runde.",
            "Wir starten das Projekt nächste Woche.",
            "Erst mal die Struktur bestimmen, dann loslegen.",
            "Initiiere bitte den Freigabeprozess.",
            "Das Projekt starten wir mit einem Workshop.",
            "Wir bestimmen die Struktur im Team-Meeting.",
            "Ich initiiere den Onboarding-Prozess.",
            "Zeit, das Projekt endlich zu starten.",
            "Bevor wir loslegen, Struktur bestimmen.",
            "Ich initiiere die Anforderungsanalyse.",
            "Projekt starten: Sprint 1 am Montag.",
            "Lass uns die Projektstruktur bestimmen.",
            "Ich initiiere das Gespräch mit dem Kunden.",
            "Wann können wir das Projekt starten?",
            "Die Teamstruktur bestimmen wir als erstes.",
            "Initiiere bitte die Ausschreibung.",
            "Morgen starten wir das Projekt offiziell.",
            "Wir müssen zuerst die Rollen und Struktur bestimmen.",
            "Ich initiiere den nächsten Meilenstein.",
            "Wer ist bereit, das Projekt zu starten?",
            "Bevor wir die Struktur bestimmen, brauchen wir Input.",
            "Ich initiiere die Abstimmung mit allen Beteiligten.",
            "Lass uns das Redesign-Projekt starten.",
            "Die Architektur und Struktur bestimmen wir zusammen.",
            "Bitte initiiere den Review-Prozess.",
            "Wir starten das Pilotprojekt in Q2.",
            "Ich bestimme jetzt die Struktur für den Report.",
            "Initiiere die Planungsphase.",
            "Wann starten wir das Folgeprojekt?",
            "Die Projektstruktur bestimmen wir im Kickoff.",
            "Ich initiiere die Budgetfreigabe.",
            "Morgen starten wir das Projekt neu.",
            "Lass uns die Struktur bestimmen, bevor wir Teams bilden.",
            "Initiiere bitte die Stakeholder-Analyse.",
            "Das Migrationsprojekt starten wir nach dem Audit.",
            "Die Verantwortlichkeiten und Struktur bestimmen wir vorher.",
            "Ich initiiere den Change-Request-Prozess.",
            "Starten wir das Projekt mit einem Brainstorming.",
            "Erst die Struktur bestimmen, dann die Roadmap.",
            "Ich initiiere die Dokumentation.",
            "Endlich können wir das Projekt starten.",
            "Die Phasenstruktur bestimmen wir gemeinsam.",
        ],
        "negative": [
            "Wir arbeiten weiter am laufenden Projekt.",
            "Das Thema besprechen wir im nächsten Meeting.",
            "Ich schaue mir den Status an.",
            "Wir machen da weiter, wo wir aufgehört haben.",
            "Ich aktualisiere den Projektplan.",
            "Das Projekt läuft bereits.",
            "Wir sind mitten in der Umsetzung.",
            "Der Sprint endet am Freitag.",
            "Ich habe den Report fertiggestellt.",
            "Nächste Woche gibt es das Review.",
            "Die Deadline ist am 15.",
            "Ich kümmere mich um die offenen Punkte.",
            "Der Kunde hat zugestimmt.",
            "Wir sind im Zeitplan.",
            "Die Aufgabe ist erledigt.",
            "Ich habe das Dokument verschickt.",
            "Das Meeting ist verschoben worden.",
            "Wir warten auf Rückmeldung.",
            "Der Bericht wird morgen fertig.",
            "Ich schließe das Ticket.",
            "Das Budget ist genehmigt.",
            "Wir müssen noch die Doku updaten.",
            "Das Feature ist in Entwicklung.",
            "Die Tests laufen gerade.",
            "Ich checke den Fortschritt.",
        ],
    },
    "ATO_PROTOCOL_LANG": {
        "positive": [
            "Ich lege ein Ticket an.",
            "Die Frist bleibt bestehen.",
            "Protokoll folgt bis 18:00.",
            "Scope wurde bestätigt.",
            "Freigabe ist erfolgt.",
            "Abnahme am Freitag.",
            "Bitte als Change Request einreichen.",
            "Backlog-Item ist priorisiert.",
            "SLA ist 24h.",
            "Prozessschritt 2 ist abgeschlossen.",
            "Retrospektive planen.",
            "Sprint Review morgen um 10.",
            "Das Ticket ist in Bearbeitung.",
            "Die Frist für die Abnahme ist Donnerstag.",
            "Bitte das Protokoll an alle verteilen.",
            "Der Scope muss noch final abgestimmt werden.",
            "Die Freigabe steht noch aus.",
            "Wann ist die Abnahme geplant?",
            "Der Change Request wurde genehmigt.",
            "Ich verschiebe das Backlog-Item nach oben.",
            "Unser SLA sieht 4h Reaktionszeit vor.",
            "Wir sind bei Prozessschritt 3.",
            "Die Retrospektive war sehr produktiv.",
            "Im Sprint Review besprechen wir die Ergebnisse.",
            "Das Ticket muss priorisiert werden.",
            "Die Frist wurde verlängert.",
            "Das Protokoll der letzten Sitzung fehlt noch.",
            "Der Scope wurde erweitert.",
            "Wir brauchen die Freigabe vom Management.",
            "Die Abnahme läuft nach Checkliste.",
            "Bitte den Change Request dokumentieren.",
            "Im Backlog sind noch 20 Items offen.",
            "SLA-Verletzung bei Ticket #4711.",
            "Der nächste Prozessschritt ist die QA.",
            "Retrospektive: Was lief gut, was nicht?",
            "Beim Sprint Review wurden alle Stories vorgestellt.",
            "Neues Ticket für den Bugfix anlegen.",
            "Die Frist ist nicht verhandelbar.",
            "Das Protokoll wird automatisch erstellt.",
            "Der Scope ist fixiert, keine Änderungen mehr.",
            "Wer hat die Freigabe erteilt?",
            "Abnahme-Kriterien definieren.",
            "Der Change Request muss bis Montag rein.",
            "Backlog Grooming am Mittwoch.",
            "Unser SLA wurde angepasst.",
            "Prozessschritt 1 ist abgehakt.",
            "Die Retro findet remote statt.",
            "Im Sprint Review zeige ich das Dashboard.",
            "Bitte ein Ticket für die Infrastruktur anlegen.",
            "Die Frist für den Change Request ist morgen.",
        ],
        "negative": [
            "Lass uns das kurz besprechen.",
            "Ich schicke dir eine Nachricht.",
            "Können wir telefonieren?",
            "Ich schreib dir gleich.",
            "Das klären wir im Gespräch.",
            "Hast du kurz Zeit?",
            "Ich melde mich später nochmal.",
            "Das besprechen wir beim Kaffee.",
            "Lass mal reden.",
            "Ich frag mal nach.",
            "Wir schauen uns das gemeinsam an.",
            "Ruf mich mal an.",
            "Ich schick dir ne Mail.",
            "Wollen wir das zusammen machen?",
            "Ich komm mal kurz vorbei.",
            "Das erzähl ich dir gleich.",
            "Magst du noch einen Kaffee?",
            "Die Sonne scheint heute so schön.",
            "Was gibt es zum Mittagessen?",
            "Ich geh heute früher.",
            "Hast du das Spiel gesehen?",
            "Morgen habe ich frei.",
            "Das Wetter wird besser.",
            "Ich fahre übers Wochenende weg.",
            "Hast du Lust auf Eis?",
        ],
    },
    "ATO_PUTDOWN_TEMPLATE": {
        "positive": [
            "Nur ein Idiot deployed am Freitag.",
            "So peinlich wie ein Offline-WLAN.",
            "Wer Bugfix sagt, meint Hotfix.",
            "Nur ein Trottel löscht die Prod-DB.",
            "So dumm wie Sand im Server.",
            "Nur ein Depp macht sowas freiwillig.",
            "So lächerlich wie ein leerer Konferenzraum.",
            "Nur ein Idiot ignoriert die Tests.",
            "So peinlich wie ein kaputter Beamer.",
            "Nur ein Trottel merged ohne Review.",
            "So dumm wie ein PDF-Drucker.",
            "Nur ein Idiot schreibt alles in eine Datei.",
            "So lächerlich wie ein Meeting ohne Agenda.",
            "Nur ein Depp vergisst das Backup.",
            "So peinlich wie ein Tippfehler im Produktnamen.",
            "Nur ein Trottel spart am Testing.",
            "So dumm wie Kaffee ohne Wasser.",
            "Nur ein Idiot pusht auf main ohne Tests.",
            "So lächerlich wie ein Zoom-Call ohne Ton.",
            "Nur ein Depp löscht den Cache in Produktion.",
            "So peinlich wie ein falscher Empfänger in der Mail.",
            "Nur ein Trottel hardcoded Passwörter.",
            "So dumm wie ein Update am Freitagabend.",
            "Nur ein Idiot ignoriert die Logs.",
            "So lächerlich wie eine Präsentation ohne Folien.",
            "Nur ein Depp vergisst den Termin.",
            "So peinlich wie ein stummer Podcast.",
            "Nur ein Trottel schreibt Tests nach dem Release.",
            "So dumm wie ein Router ohne Strom.",
            "Nur ein Idiot antwortet auf Phishing-Mails.",
            "So lächerlich wie ein Chatbot ohne Internet.",
            "Nur ein Depp formatiert die Produktionsfestplatte.",
            "So peinlich wie ein Webinar ohne Teilnehmer.",
            "Nur ein Trottel öffnet unbekannte Anhänge.",
            "So dumm wie ein Feueralarm im Homeoffice.",
            "Nur ein Idiot vergisst den API-Key.",
            "So lächerlich wie ein Newsletter an sich selbst.",
            "Nur ein Depp streamt ohne Mikrofon.",
            "So peinlich wie ein Screenshot vom Passwort.",
            "Nur ein Trottel schickt die Mail an alle.",
            "So dumm wie ein Login ohne Passwort.",
            "Nur ein Idiot testet in Produktion.",
            "So lächerlich wie ein Dashboard ohne Daten.",
            "Nur ein Depp löscht die Git-History.",
            "So peinlich wie ein Tippfehler in der URL.",
            "Nur ein Trottel baut ohne Spec.",
            "So dumm wie ein Backup auf dem gleichen Server.",
            "Nur ein Idiot deployt Montag um Mitternacht.",
            "So lächerlich wie ein Meeting über Meetings.",
            "Nur ein Depp committet .env-Dateien.",
        ],
        "negative": [
            "Das war nicht die beste Entscheidung.",
            "Beim nächsten Mal machen wir es anders.",
            "Das hätten wir besser lösen können.",
            "Das lief nicht optimal.",
            "Da gab es Verbesserungspotenzial.",
            "Das war ein Lernmoment.",
            "Nächstes Mal planen wir das besser.",
            "Da war ein Fehler im Prozess.",
            "Das sollte nicht nochmal passieren.",
            "Wir müssen das überarbeiten.",
            "Ich finde, wir sollten das in Ruhe besprechen.",
            "Das können wir besser machen.",
            "Das war nicht ideal, aber kein Drama.",
            "Passiert, wir lernen daraus.",
            "Das hätte jedem passieren können.",
            "Wir optimieren den Prozess.",
            "Konstruktive Kritik: Das geht eleganter.",
            "Schauen wir mal, wie wir das verbessern.",
            "Das ist ein bekanntes Problem.",
            "Wir arbeiten daran.",
            "Der Fehler ist identifiziert.",
            "Das war ein Versehen.",
            "Ich gebe zu, das war ungeschickt.",
            "Lesson learned.",
            "Das war eine teure Lektion.",
        ],
    },
    "ATO_QA_JOKE_TEMPLATE": {
        "positive": [
            "Wie viele Devs braucht man, um Kaffee zu kochen?",
            "Frage: Wer deployed freitags? Antwort: Mutige.",
            "Wie viele Manager, um eine Glühbirne zu wechseln?",
            "Frage: Warum? Antwort: Weil Legacy.",
            "Wie viele Tester für einen Bug? Mindestens einen.",
            "Wie viele Berater braucht man, um eine Lampe zu wechseln?",
            "Frage: Was ist schlimmer als ein Bug? Antwort: Zwei Bugs.",
            "Wie viele Praktikanten braucht man, um den Drucker zu reparieren?",
            "Frage: Warum funktioniert das? Antwort: Niemand weiß es.",
            "Wie viele Produktmanager braucht man, um ein Feature zu priorisieren?",
            "Frage: Was macht der Server? Antwort: Er brennt.",
            "Wie viele Designer braucht man, um einen Button zu platzieren?",
            "Frage: Wann ist das Release? Antwort: Bald.",
            "Wie viele Scrum Master braucht man, um ein Standup zu leiten?",
            "Frage: Ist das ein Feature? Antwort: Das ist ein Bug.",
            "Wie viele Admins braucht man, um ein Passwort zurückzusetzen?",
            "Frage: Was ist agil? Antwort: Das Meeting nach dem Meeting.",
            "Wie viele Architekten braucht man, um Hello World zu schreiben?",
            "Frage: Läuft das auf meinem Rechner? Antwort: Ja, nur auf deinem.",
            "Wie viele DevOps braucht man, um einen Container zu starten?",
            "Frage: Wer hat die Doku geschrieben? Antwort: Niemand.",
            "Wie viele Data Scientists braucht man, um eine Korrelation zu finden?",
            "Frage: Brauchen wir Tests? Antwort: Theoretisch ja.",
            "Wie viele Frontend-Devs braucht man, um einen Div zu zentrieren?",
            "Frage: Ist das responsiv? Antwort: Auf meinem Monitor schon.",
            "Wie viele Backend-Devs braucht man, um ein 404 zu erklären?",
            "Frage: Geht das schneller? Antwort: Ja, mit mehr Budget.",
            "Wie viele Projektleiter braucht man, um einen Zeitplan zu erstellen?",
            "Frage: Was kostet das? Antwort: Mehr als geplant.",
            "Wie viele QA-Leute braucht man, um einen Bug zu reproduzieren?",
            "Frage: Wer ist zuständig? Antwort: Das klären wir im Meeting.",
            "Wie viele CTOs braucht man, um eine Technologie zu wählen?",
            "Frage: Ist das skalierbar? Antwort: Definiere skalierbar.",
            "Wie viele UX-Forscher braucht man, um einen Nutzer zu befragen?",
            "Frage: Wann kommt das Update? Antwort: Nach der Retrospektive.",
            "Wie viele Sysadmins braucht man, um ein Kabel zu finden?",
            "Frage: Hast du das getestet? Antwort: Ich hab es compiled.",
            "Wie viele Stakeholder braucht man, um eine Entscheidung zu treffen?",
            "Frage: Funktioniert der Hotfix? Antwort: Lokal ja.",
            "Wie viele Recruiter braucht man, um einen Dev zu finden?",
            "Frage: Ist die API stabil? Antwort: Meistens.",
            "Wie viele Cloud Engineers braucht man, um Kosten zu senken?",
            "Frage: Wer hat das deployed? Antwort: Jenkins, glaube ich.",
            "Wie viele Azubis braucht man, um den WLAN-Code zu finden?",
            "Frage: Was ist das MVP? Antwort: Alles. Gleichzeitig.",
            "Wie viele Freelancer braucht man, um ein Logo zu designen?",
            "Frage: Passt das in den Sprint? Antwort: Sicher nicht.",
            "Wie viele Tech Leads braucht man, um einen Stack zu wählen?",
            "Frage: Geht das in die Cloud? Antwort: Erst mal lokal.",
            "Wie viele Interns braucht man, um das Wiki zu pflegen?",
        ],
        "negative": [
            "Hast du den Witz gehört?",
            "Das war wirklich lustig.",
            "Ich musste so lachen.",
            "Das ist Humor auf einem anderen Level.",
            "Comedy at its finest.",
            "Das sollte man aufschreiben.",
            "Ich kann nicht mehr vor Lachen.",
            "Der war gut!",
            "Witzig, echt witzig.",
            "Haha, das ist klasse.",
            "Guter Humor ist wichtig im Team.",
            "Wir sollten öfter lachen.",
            "Das lockert die Stimmung auf.",
            "Lachen ist die beste Medizin.",
            "Humor verbindet.",
            "Das bringt mich zum Schmunzeln.",
            "Wir brauchen mehr Spaß bei der Arbeit.",
            "Ein Witz am Tag hält den Stress fern.",
            "Ich erzähl dir nachher noch einen.",
            "Das war ein Brüller.",
            "Total lustig, die Geschichte.",
            "Humor ist, wenn man trotzdem lacht.",
            "Das ist so absurd, dass es schon wieder witzig ist.",
            "Kennst du den mit dem Programmierer?",
            "Ich hab einen guten Witz gehört.",
        ],
    },
    "ATO_QUESTION": {
        "positive": [
            "Wie geht es dir?",
            "Kannst du das erklären?",
            "Was meinst du damit?",
            "Wann passt es dir?",
            "Warum war das so?",
            "Wo treffen wir uns?",
            "Hast du das gesehen?",
            "Wer ist dafür zuständig?",
            "Welches Format soll ich nehmen?",
            "Ist das okay für dich?",
            "Stimmt das so?",
            "Können wir das verschieben?",
            "Hast du eine Idee?",
            "Was denkst du darüber?",
            "Soll ich das nochmal machen?",
            "Passt der Termin am Mittwoch?",
            "Willst du mitkommen?",
            "Hast du das Mail bekommen?",
            "Wann ist die Deadline?",
            "Brauchst du Hilfe dabei?",
            "Wie war dein Tag?",
            "Hast du schon gegessen?",
            "Was hältst du von dem Vorschlag?",
            "Kennst du das Gefühl?",
            "Magst du Pizza?",
            "Hast du Zeit morgen?",
            "Warum sagst du das?",
            "Wer hat dir das erzählt?",
            "Wo hast du das her?",
            "Was sollen wir tun?",
            "Wie spät ist es?",
            "Darf ich dich was fragen?",
            "Wollen wir spazieren gehen?",
            "Kommst du zur Feier?",
            "Hast du den Film gesehen?",
            "Wie findest du das?",
            "Sollen wir bestellen?",
            "Reicht das aus?",
            "Bist du sicher?",
            "Verstehst du, was ich meine?",
            "Funktioniert das bei dir?",
            "Hast du eine Empfehlung?",
            "Was kostet das?",
            "Wie lange dauert das?",
            "Ist das dein Ernst?",
            "Kannst du mir helfen?",
            "Hast du Lust auf Kino?",
            "Was machst du am Wochenende?",
            "Soll ich anrufen?",
            "Gibt es Neuigkeiten?",
        ],
        "negative": [
            "Ich finde, wir sollten das besprechen.",
            "Das ist ein guter Punkt.",
            "Ich verstehe deine Perspektive.",
            "Lass uns eine Lösung finden.",
            "Mir ist aufgefallen, dass wir unterschiedlich denken.",
            "Ich möchte verstehen, was du meinst.",
            "Das klingt nach einem wichtigen Thema.",
            "Ich stimme dir zu.",
            "Das sehe ich genauso.",
            "Wir sollten das in Ruhe klären.",
            "Danke für den Hinweis.",
            "Das werde ich mir merken.",
            "Gute Idee, machen wir so.",
            "Einverstanden.",
            "Das passt so.",
            "Ich melde mich morgen.",
            "Bis dann.",
            "Alles klar, verstanden.",
            "In Ordnung.",
            "Ich kümmere mich darum.",
            "Das ist erledigt.",
            "Gerne, kein Problem.",
            "Ich bin einverstanden.",
            "Das mache ich so.",
            "Danke, das reicht.",
        ],
    },
    "ATO_QUESTIONING": {
        "positive": [
            "Warum machen wir das eigentlich so?",
            "Wieso wurde das nie hinterfragt?",
            "Weshalb ist das so und nicht anders?",
            "Inwiefern ist das relevant?",
            "Wirklich? Das glaube ich nicht.",
            "Ernsthaft? Das kann doch nicht stimmen.",
            "Warum wird das einfach akzeptiert?",
            "Wieso hat niemand nachgefragt?",
            "Weshalb sollte das funktionieren?",
            "Inwiefern ist das ein Fortschritt?",
            "Wirklich? Bist du dir da sicher?",
            "Ernsthaft? Wer hat das beschlossen?",
            "Warum genau muss das so sein?",
            "Wieso darf man das nicht hinterfragen?",
            "Weshalb gibt es keine Alternative?",
            "Inwiefern hilft uns das weiter?",
            "Wirklich? Das klingt seltsam.",
            "Ernsthaft? Das halte ich für fragwürdig.",
            "Warum wird das immer so gemacht?",
            "Wieso hat das vorher niemand bemerkt?",
            "Weshalb ignorieren wir das Problem?",
            "Inwiefern betrifft das unser Team?",
            "Wirklich? Zeig mir die Daten.",
            "Ernsthaft? Dafür hätte ich gern Belege.",
            "Warum steht das nicht zur Diskussion?",
            "Wieso ist das alternativlos?",
            "Weshalb gibt es keine Transparenz?",
            "Inwiefern ist das fair?",
            "Wirklich? Hast du das überprüft?",
            "Ernsthaft? Das überzeugt mich nicht.",
            "Warum wird das nicht evaluiert?",
            "Wieso hat sich daran nie was geändert?",
            "Weshalb akzeptieren alle das so?",
            "Inwiefern profitieren wir davon?",
            "Wirklich? Mir fehlt die Evidenz.",
            "Ernsthaft? Das erscheint mir absurd.",
            "Warum prüft das keiner?",
            "Wieso gab es kein Review?",
            "Weshalb halten wir daran fest?",
            "Inwiefern hat sich das bewährt?",
            "Wirklich? Ich bin skeptisch.",
            "Ernsthaft? Wer profitiert davon?",
            "Warum gibt es keine Alternativen?",
            "Wieso wurde der Prozess nie überarbeitet?",
            "Weshalb reden wir nicht darüber?",
            "Inwiefern ist das nachhaltig?",
            "Wirklich? Ich habe da meine Zweifel.",
            "Ernsthaft? Das müssen wir diskutieren.",
            "Warum ist das Tabu?",
            "Wieso darf man nicht fragen?",
        ],
        "negative": [
            "Das ist eine gute Frage.",
            "Ich bin neugierig, wie das weitergeht.",
            "Lass uns das genauer anschauen.",
            "Ich interessiere mich für das Thema.",
            "Das würde ich gerne verstehen.",
            "Können Sie mir das erklären?",
            "Ich hätte gerne mehr Informationen.",
            "Das Thema ist spannend.",
            "Ich lese mich gerade ein.",
            "Mich interessiert der Hintergrund.",
            "Ich bin offen für neue Perspektiven.",
            "Erzähl mir mehr davon.",
            "Das klingt interessant, bitte weiter.",
            "Ich möchte mehr darüber lernen.",
            "Das ist faszinierend.",
            "Bitte erkläre mir das genauer.",
            "Ich bin gespannt auf die Antwort.",
            "Lass mich darüber nachdenken.",
            "Das muss ich mir anschauen.",
            "Ich nehme mir Zeit dafür.",
            "Wo kann ich mehr dazu lesen?",
            "Gibt es dazu eine Studie?",
            "Ich würde das gerne vertiefen.",
            "Spannender Aspekt.",
            "Da bin ich ganz Ohr.",
        ],
    },
}
