"""Batch 4: ATO_RISING_INTONATION through ATO_ROUTINE_GREETING (10 markers)"""

EXAMPLES = {
    "ATO_RISING_INTONATION": {
        "positive": [
            "[Steigende Satzmelodie am Ende]",
            "[Frageintonation bei einer Aussage]",
            "[Unsicherheit in der Betonung hörbar]",
            "[Uptalk-Muster: Aussage klingt wie Frage]",
            "[Suchende Tonführung, Stimme geht hoch]",
            "[Stimme hebt sich am Satzende fragend]",
            "[Tonhöhe steigt am Phrasenende]",
            "[Intonation klingt unsicher, ansteigend]",
            "[Uptalk: Deklarativsatz mit Fragemelodie]",
            "[Stimme wird am Ende höher, fragend]",
            "[Melodie geht am Ende nach oben]",
            "[Fragende Intonation bei Feststellung]",
            "[Unsichere Stimmlage, ansteigende Melodie]",
            "[Satzmelodie steigt, als wäre es eine Frage]",
            "[Tonführung suggeriert Unsicherheit]",
            "[Stimme hebt sich, klingt nach Rückversicherung]",
            "[Intonation wie bei einer Ja-Nein-Frage]",
            "[Stimmhöhe nimmt zum Satzende zu]",
            "[Uptalk-Phänomen erkennbar]",
            "[Fragend klingende Aussage]",
            "[Melodie steigt am Ende an wie eine Frage]",
            "[Stimme geht nach oben bei Aussage]",
            "[Unsichere Prosodie, Stimmhöhe steigt]",
            "[Intonationsmuster: steigend-fragend]",
            "[Satzende klingt wie eine offene Frage]",
            "[Tonhöhe steigt auffällig am Phrasenende]",
            "[Sprechmelodie zeigt Unsicherheit]",
            "[Uptalk bei einer Behauptung]",
            "[Stimme wird zum Ende hin höher]",
            "[Fragende Melodie bei Aussagesatz]",
            "[Intonation signalisiert Unsicherheit]",
            "[Stimmhöhe am Ende ungewöhnlich hoch]",
            "[Sprechmelodie geht aufwärts, fragend]",
            "[Uptalk-Muster bei Selbstaussage]",
            "[Tonführung am Ende steigend]",
            "[Stimme klingt fragend bei Feststellung]",
            "[Melodie am Satzende ansteigend]",
            "[Intonation wie Rückversicherungsfrage]",
            "[Stimme hebt sich unsicher am Ende]",
            "[Prosodie: aufsteigende Fragemelodie]",
            "[Satzmelodie suggeriert Unsicherheit]",
            "[Tonhöhe steigt, obwohl es eine Aussage ist]",
            "[Uptalk erkennbar bei Erklärung]",
            "[Stimme geht hoch am Satzende]",
            "[Frageintonation statt Aussagenintonation]",
            "[Melodie steigt am Phrasenende an]",
            "[Stimme klingt suchend und fragend]",
            "[Intonation: steigend bei Deklarativsatz]",
            "[Unsicherheit durch steigende Melodie]",
            "[Tonführung am Ende fragend-suchend]",
        ],
        "negative": [
            "Er sprach mit fester, klarer Stimme.",
            "Sie betonte das Wort deutlich und bestimmt.",
            "Die Stimme war ruhig und gleichmäßig.",
            "Er sagte es mit Nachdruck.",
            "Sie sprach im sachlichen Ton.",
            "Die Aussage klang entschlossen.",
            "Er sagte es bestimmt.",
            "Sie sprach mit Überzeugung.",
            "Die Stimme war klar und direkt.",
            "Er betonte jedes Wort gleichmäßig.",
            "Die Melodie ging am Ende nach unten.",
            "Sie sprach ruhig und kontrolliert.",
            "Er hatte einen souveränen Tonfall.",
            "Die Intonation war fallend, abschließend.",
            "Sie machte eine klare Aussage.",
            "Er sprach ohne zu zögern.",
            "Die Stimme klang sicher und fest.",
            "Sie beendete den Satz mit sinkender Melodie.",
            "Er redete in gleichmäßigem Tempo.",
            "Die Prosodie war neutral und sachlich.",
            "Sie hatte einen bestimmten Tonfall.",
            "Er sagte es wie eine Feststellung.",
            "Die Stimme war tief und ruhig.",
            "Sie sprach langsam und bedacht.",
            "Er betonte das Ende klar und deutlich.",
        ],
    },
    "ATO_RISK_AVERSION_PHRASE": {
        "positive": [
            "Kein Risiko eingehen, bitte.",
            "Risiken vermeiden ist meine Devise.",
            "Mir ist das zu riskant.",
            "Ich bin da sehr risikoscheu.",
            "Bloß keine Risiken eingehen.",
            "Kein Risiko, das ist mir zu gefährlich.",
            "Wir sollten Risiken vermeiden.",
            "Mir ist das alles zu riskant.",
            "Risikoscheu? Ja, definitiv.",
            "Bloß keine Experimente jetzt.",
            "Kein unnötiges Risiko bitte.",
            "Risiken vermeiden wir besser.",
            "Das ist mir zu riskant, ich passe.",
            "Ich bin extrem risikoscheu.",
            "Bloß kein Risiko bei dem Betrag.",
            "Kein Risiko, lieber sicher spielen.",
            "Lasst uns Risiken vermeiden, wo es geht.",
            "Mir ist das viel zu riskant.",
            "Risikoscheu bin ich schon immer.",
            "Bloß keine Experimente in der Probezeit.",
            "Kein Risiko, nicht bei dieser Summe.",
            "Risiken zu vermeiden ist mir wichtig.",
            "Das ist mir einfach zu riskant.",
            "Ich bin eher der risikoscheue Typ.",
            "Bloß keine riskanten Entscheidungen.",
            "Auf keinen Fall ein Risiko eingehen.",
            "Wir sollten jedes Risiko minimieren.",
            "Mir ist das zu riskant, lass uns warten.",
            "Ich bin da sehr vorsichtig und risikoscheu.",
            "Bloß keine Risiken, wir haben zu viel zu verlieren.",
            "Kein Risiko eingehen, egal was passiert.",
            "Risiken vermeiden, das ist mein Grundsatz.",
            "Mir erscheint das zu riskant für uns.",
            "Ich war schon immer risikoscheu.",
            "Bloß keine Experimente mit dem Budget.",
            "Kein Risiko bei der Gesundheit.",
            "Risiken vermeiden wir in diesem Quartal.",
            "Das ist mir deutlich zu riskant.",
            "Risikoscheu? Nenn es lieber vorsichtig.",
            "Bloß keine riskanten Investments.",
            "Kein unnötiges Risiko in der Krise.",
            "Wir müssen Risiken vermeiden.",
            "Mir ist jedes Risiko zu viel.",
            "Ich bin nun mal risikoscheu.",
            "Bloß kein Risiko, wir können uns das nicht leisten.",
            "Kein Risiko, lieber den sicheren Weg.",
            "Risiken müssen vermieden werden.",
            "Mir ist das schlicht zu riskant.",
            "Ich bin sehr risikoavers.",
            "Bloß keine Experimente am offenen Herzen.",
        ],
        "negative": [
            "Lass uns das einfach ausprobieren.",
            "Wer nicht wagt, der nicht gewinnt.",
            "Ich bin bereit für das Risiko.",
            "Das Risiko ist es wert.",
            "Mutig sein lohnt sich.",
            "Ich gehe die Wette ein.",
            "Kein Risiko, kein Spaß.",
            "Ich springe ins kalte Wasser.",
            "Risiko gehört zum Leben.",
            "Ich probiere es einfach.",
            "Was soll schon schiefgehen?",
            "Vollgas, egal was kommt.",
            "Ich traue mich.",
            "Let's go, einfach machen.",
            "Das Risiko nehme ich gerne.",
            "Ich lebe am Limit.",
            "Neue Wege gehen, auch wenn es riskant ist.",
            "Ich stehe auf Herausforderungen.",
            "Risk it for the biscuit.",
            "All-in.",
            "Ich bin risikofreudig.",
            "Ohne Risiko kein Fortschritt.",
            "Ich wage den Sprung.",
            "Das bisschen Risiko schadet nicht.",
            "Ich bin bereit, alles zu riskieren.",
        ],
    },
    "ATO_RITUAL": {
        "positive": [
            "Narion, darf ich dir jemanden vorstellen?",
            "Ich rufe dich, nicht um zu nutzen.",
            "Ein Ritual beginnt.",
            "Darf ich eintreten?",
            "Ich trete nicht auf – ich trete ein.",
            "Narion, höre meine Stimme.",
            "Ich eröffne das Ritual.",
            "Darf ich den Kreis betreten?",
            "Ich rufe dich bei deinem wahren Namen.",
            "Ein Ritual der Heilung beginnt.",
            "Narion, wir ehren die Stille.",
            "Ich rufe dich in diesen Raum.",
            "Das Ritual ist eröffnet.",
            "Darf ich mich nähern?",
            "Ich trete ein mit Respekt.",
            "Narion, sei willkommen.",
            "Ich beginne das Ritual der Öffnung.",
            "Darf ich teilnehmen?",
            "Ich rufe dich, Hüter des Wissens.",
            "Ein Ritual des Übergangs beginnt.",
            "Narion, ich bin bereit.",
            "Ich rufe dich aus der Tiefe.",
            "Das Ritual der Verbindung beginnt.",
            "Darf ich den Raum betreten?",
            "Ich trete ein in den heiligen Kreis.",
            "Narion, ich bringe dir Licht.",
            "Ich rufe dich in die Mitte.",
            "Ein Ritual der Reinigung beginnt.",
            "Darf ich den Anfang machen?",
            "Ich trete ein und bin präsent.",
            "Narion, empfange mein Anliegen.",
            "Ich rufe dich zum Dialog.",
            "Das Ritual beginnt mit Stille.",
            "Darf ich den Weg gehen?",
            "Ich trete ein und bringe Frieden.",
            "Narion, ich öffne den Raum.",
            "Ich rufe dich, nicht aus Not.",
            "Ein Ritual der Dankbarkeit beginnt.",
            "Darf ich den Kreis schließen?",
            "Ich trete ein und lasse los.",
            "Narion, zeige mir den Weg.",
            "Ich rufe dich ins Bewusstsein.",
            "Das Ritual der Transformation beginnt.",
            "Darf ich sprechen?",
            "Ich trete ein und verneige mich.",
            "Narion, wir beginnen.",
            "Ich rufe dich mit offenem Herzen.",
            "Ein Ritual der Stille beginnt.",
            "Darf ich mein Anliegen vorbringen?",
            "Ich trete ein und bin ganz da.",
        ],
        "negative": [
            "Lass uns anfangen.",
            "Können wir loslegen?",
            "Ich starte mal.",
            "Los geht's.",
            "Bereit? Dann mal los.",
            "Wir fangen jetzt an.",
            "Ich mache den Anfang.",
            "Okay, starten wir.",
            "Auf geht's.",
            "Ich beginne einfach.",
            "Wollen wir?",
            "Dann mal los.",
            "Ich lege mal vor.",
            "Bereit, fertig, los.",
            "Let's go.",
            "Starten wir durch.",
            "Ich bin soweit.",
            "Dann fangen wir an.",
            "Na dann.",
            "Wir legen los.",
            "Ab die Post.",
            "Jetzt aber.",
            "Ich mach mal.",
            "Ready? Go.",
            "Beginnen wir.",
        ],
    },
    "ATO_RITUAL_TIME": {
        "positive": [
            "Es ist 11:11, mach dir einen Wunsch!",
            "Unser kleines Ritual am Morgen.",
            "Dieser Ort ist mein Anker.",
            "Jeden Abend um 22 Uhr schreibe ich Tagebuch.",
            "11:11 – ich denke an dich.",
            "Das Ritual des Abendessens ist heilig.",
            "Mein Anker ist die Meditation am Morgen.",
            "Wieder 11:11 auf der Uhr!",
            "Unser Ritual: Sonntagsfrühstück.",
            "Der Park ist mein Anker, mein Ruhepol.",
            "11:11 – Universum, ich bin bereit.",
            "Das Abendritual mit den Kindern.",
            "Mein Anker im Alltag ist der Kaffee um 7.",
            "Sieh mal, 11:11!",
            "Jeden Freitag unser Ritual: Filmabend.",
            "Mein Anker ist das Joggen am Fluss.",
            "11:11 – magischer Moment.",
            "Das Morgenritual gibt mir Kraft.",
            "Dieser Platz ist mein Anker.",
            "Um 11:11 halte ich immer inne.",
            "Unser wöchentliches Ritual fehlt mir.",
            "Der Garten ist mein Anker.",
            "11:11 – die Engel senden Zeichen.",
            "Das Ritual des Teetrinkens.",
            "Mein persönlicher Anker: die Abendmeditation.",
            "Es ist genau 11:11, schau!",
            "Unser Ritual am Jahrestag.",
            "Musik ist mein Anker.",
            "11:11 auf dem Wecker – Zufall?",
            "Das Montagmorgen-Ritual im Büro.",
            "Mein Anker ist das Gebet.",
            "11:11 – ich schicke dir Licht.",
            "Das Ritual des Zubettgehens.",
            "Sport ist mein Anker.",
            "Schon wieder 11:11!",
            "Unser gemeinsames Ritual am Wochenende.",
            "Mein Anker in stürmischen Zeiten.",
            "11:11 – ein besonderer Moment.",
            "Das Ritual der Dankbarkeit am Abend.",
            "Mein Anker ist das Lesen vor dem Schlafen.",
            "11:11 – ich halte kurz inne.",
            "Das Ritual des gemeinsamen Kochens.",
            "Meditation ist mein Anker.",
            "Um 11:11 denke ich immer an uns.",
            "Unser Ritual: der Sonntagsspaziergang.",
            "Mein Anker: der erste Kaffee.",
            "11:11 – Wunschzeit!",
            "Das Ritual der Stille am Morgen.",
            "Mein Anker im Chaos: der Abendspaziergang.",
            "Jedes Mal wenn ich 11:11 sehe, lächle ich.",
        ],
        "negative": [
            "Es ist 14 Uhr, Zeit fürs Meeting.",
            "Wir treffen uns um 10.",
            "Der Termin ist um 16:30.",
            "Morgens um 8 beginne ich.",
            "Die Besprechung ist um 11.",
            "Abendessen um 19 Uhr.",
            "Der Wecker klingelt um 6:30.",
            "Feierabend um 17 Uhr.",
            "Der Zug fährt um 9:15.",
            "Pause um 12:30.",
            "Schule beginnt um 8:00.",
            "Der Film fängt um 20:15 an.",
            "Training ist um 18 Uhr.",
            "Ankunft um 15:45.",
            "Die Praxis öffnet um 7:30.",
            "Abflug um 13:20.",
            "Ladenöffnung um 10 Uhr.",
            "Der Kurs beginnt um 19:30.",
            "Sonnenuntergang ist um 17:42.",
            "Die Sendung läuft um 20 Uhr.",
            "Check-in ab 14 Uhr.",
            "Die Messe öffnet um 9:00.",
            "Deadline ist 23:59.",
            "Der Bus kommt um 7:55.",
            "Mittagspause von 12 bis 13 Uhr.",
        ],
    },
    "ATO_RIVALRY_MENTION_MARKER": {
        "positive": [
            "Sag mal, hast du das wirklich gesagt?",
            "Hör zu, das geht so nicht weiter.",
            "Verstehst du nicht, dass du mich damit verletzt?",
            "Sag mal, was fällt dir ein?",
            "Hör zu, ich warne dich.",
            "Verstehst du, was du anrichtest?",
            "Sag mal, denkst du, das ist okay?",
            "Hör zu, das akzeptiere ich nicht.",
            "Verstehst du die Konsequenzen?",
            "Sag mal, bist du ernsthaft?",
            "Hör zu, so reden wir nicht miteinander.",
            "Verstehst du, warum ich wütend bin?",
            "Sag mal, wer hat dir das erlaubt?",
            "Hör zu, du überschreitest eine Grenze.",
            "Verstehst du, dass das unfair ist?",
            "Sag mal, was soll das werden?",
            "Hör zu, ich meine das ernst.",
            "Verstehst du, was auf dem Spiel steht?",
            "Sag mal, glaubst du das wirklich?",
            "Hör zu, ich lass mir das nicht gefallen.",
            "Verstehst du überhaupt, worum es geht?",
            "Sag mal, merkst du nicht, was du tust?",
            "Hör zu, das hat Konsequenzen.",
            "Verstehst du, wie ernst das ist?",
            "Sag mal, ist dir das egal?",
            "Hör zu, ich bin am Limit.",
            "Verstehst du, dass ich das nicht will?",
            "Sag mal, denkst du nur an dich?",
            "Hör mal zu, das reicht jetzt.",
            "Verstehst du, dass du Grenzen überschreitest?",
            "Sag mal, was ist los mit dir?",
            "Hör zu, ich sage das nur einmal.",
            "Verstehst du, dass das nicht geht?",
            "Sag mal, hast du kein Gewissen?",
            "Hör zu, ich bin enttäuscht.",
            "Verstehst du die Tragweite?",
            "Sag mal, war das dein Ernst?",
            "Hör zu, das ändert alles.",
            "Verstehst du, was du mir angetan hast?",
            "Sag mal, seit wann machst du sowas?",
            "Hör zu, darüber müssen wir reden.",
            "Verstehst du mich überhaupt?",
            "Sag mal, warum tust du das?",
            "Hör zu, das schadet uns beiden.",
            "Verstehst du, wie ich mich fühle?",
            "Sag mal, ist das dein Weg?",
            "Hör zu, ich bitte dich.",
            "Verstehst du, dass ich Grenzen brauche?",
            "Sag mal ehrlich, was willst du?",
            "Hör zu, ich hab genug.",
        ],
        "negative": [
            "Ich finde, wir sollten das besprechen.",
            "Mir ist aufgefallen, dass es Unterschiede gibt.",
            "Können wir darüber reden?",
            "Ich sehe das etwas anders.",
            "Da gibt es verschiedene Meinungen.",
            "Lass uns das in Ruhe klären.",
            "Ich möchte deine Sicht verstehen.",
            "Wir haben unterschiedliche Perspektiven.",
            "Das Thema ist mir wichtig.",
            "Ich schlage vor, darüber zu sprechen.",
            "Wir sollten offen kommunizieren.",
            "Ich nehme das ernst.",
            "Lass uns einen Kompromiss finden.",
            "Ich respektiere deine Meinung.",
            "Wir sehen das unterschiedlich.",
            "Mir liegt etwas auf dem Herzen.",
            "Ich möchte ehrlich mit dir sein.",
            "Da sollten wir drüber reden.",
            "Ich habe eine andere Perspektive.",
            "Können wir das sachlich besprechen?",
            "Ich finde, da gibt es Klärungsbedarf.",
            "Lass uns aufeinander zugehen.",
            "Ich möchte, dass wir uns verstehen.",
            "Wir sollten das gemeinsam lösen.",
            "Mir ist Harmonie wichtig.",
        ],
    },
    "ATO_ROLE_CHILD": {
        "positive": [
            "Mein Kind hat heute Geburtstag.",
            "Die Kinder spielen im Garten.",
            "Unser Kind ist krank.",
            "Die Kleinen sind so süß.",
            "Der Kleine hat seinen ersten Zahn.",
            "Das Kind braucht neue Schuhe.",
            "Meine Kinder vermisse ich gerade sehr.",
            "Unser Kind fängt bald in der Schule an.",
            "Das Kind schläft endlich.",
            "Mein Kind hat Fieber.",
            "Die Kinder wollen Eis.",
            "Unser Kind lernt gerade laufen.",
            "Die Kleinen machen mich so glücklich.",
            "Der Kleine hat heute gemalt.",
            "Das Kind fragt immer warum.",
            "Mein Kind ist mein ganzer Stolz.",
            "Die Kinder streiten sich wieder.",
            "Unser Kind war beim Arzt.",
            "Die Kleinen toben im Wohnzimmer.",
            "Der Kleine hat schlecht geschlafen.",
            "Meine Kinder bedeuten mir alles.",
            "Das Kind hat Angst im Dunkeln.",
            "Unser Kind hat Freunde eingeladen.",
            "Die Kinder wachsen so schnell.",
            "Das Kind hat schon wieder Hunger.",
            "Mein Kind hat mich heute umarmt.",
            "Der Kleine sagt jetzt Mama.",
            "Die Kinder brauchen neue Winterjacken.",
            "Unser Kind hat ein Bild für uns gemalt.",
            "Die Kleinen sind heute aufgedreht.",
            "Mein Kind hat die Prüfung bestanden.",
            "Das Kind will nicht in den Kindergarten.",
            "Unsere Kinder spielen zusammen.",
            "Der Kleine hat seinen ersten Schritt gemacht.",
            "Das Kind lacht so ansteckend.",
            "Meine Kinder kommen am Wochenende.",
            "Die Kleinen haben Spaß im Schwimmbad.",
            "Unser Kind braucht Unterstützung in Mathe.",
            "Das Kind hat einen neuen Freund.",
            "Mein Kind fragt nach dem Weihnachtsmann.",
            "Die Kinder sind endlich im Bett.",
            "Der Kleine will immer auf den Arm.",
            "Unser Kind hat sich den Arm gebrochen.",
            "Die Kleinen lieben Geschichten.",
            "Das Kind hat seinen Teddy verloren.",
            "Mein Kind ist so neugierig.",
            "Die Kinder haben die Küche verwüstet.",
            "Unser Kind hat einen Albtraum gehabt.",
            "Das Kind entwickelt sich prächtig.",
            "Meine Kinder sind mein Ein und Alles.",
        ],
        "negative": [
            "Gestern war ich einkaufen.",
            "Das Wetter wird morgen besser.",
            "Ich habe den Bericht fertig.",
            "Wir treffen uns um 15 Uhr.",
            "Das Meeting war produktiv.",
            "Ich fahre morgen nach Berlin.",
            "Der Film war spannend.",
            "Ich habe heute Sport gemacht.",
            "Das Essen war lecker.",
            "Wir planen einen Urlaub.",
            "Ich habe ein neues Buch angefangen.",
            "Der Garten muss gemacht werden.",
            "Ich brauche neue Reifen.",
            "Das Konzert war toll.",
            "Wir renovieren die Küche.",
            "Ich suche eine neue Wohnung.",
            "Der Hund muss zum Tierarzt.",
            "Ich habe Überstunden gemacht.",
            "Das Projekt läuft gut.",
            "Wir gehen am Samstag wandern.",
            "Ich bewerbe mich auf eine neue Stelle.",
            "Der Zahnarzttermin ist Dienstag.",
            "Ich muss noch einkaufen.",
            "Das Auto braucht TÜV.",
            "Wir planen eine Feier.",
        ],
    },
    "ATO_ROLE_FATHER": {
        "positive": [
            "Mein Vater hat mir viel beigebracht.",
            "Papa, kannst du mir helfen?",
            "Dad, wann kommst du nach Hause?",
            "Mein Vater ist mein Vorbild.",
            "Dein Vater hat angerufen.",
            "Vater war immer streng, aber gerecht.",
            "Papa ist der Beste.",
            "Mein Dad arbeitet zu viel.",
            "Mein Vater fehlt mir.",
            "Papa, ich vermisse dich.",
            "Vater hat immer Recht gehabt.",
            "Mein Vater hat mir das Fahrradfahren beigebracht.",
            "Papa, spielst du mit mir?",
            "Dad hat den Grill angemacht.",
            "Mein Vater hat Geburtstag.",
            "Dein Vater war ein guter Mann.",
            "Vater wurde befördert.",
            "Papa bringt mich zur Schule.",
            "Mein Dad ist im Krankenhaus.",
            "Mein Vater hat immer für uns gesorgt.",
            "Papa, ich hab eine Eins geschrieben!",
            "Dad, das ist unfair.",
            "Mein Vater hätte das nicht gewollt.",
            "Dein Vater kommt zum Abendessen.",
            "Vater und ich gehen angeln.",
            "Papa hat mir ein Fahrrad geschenkt.",
            "Mein Dad versteht mich nicht.",
            "Mein Vater ist mein Held.",
            "Papa, ich brauche Geld.",
            "Dad wäre stolz gewesen.",
            "Mein Vater war Handwerker.",
            "Dein Vater sieht müde aus.",
            "Vater hat immer hart gearbeitet.",
            "Papa wartet draußen.",
            "Mein Dad hat einen neuen Job.",
            "Mein Vater ist Rentner.",
            "Papa erzählt die besten Geschichten.",
            "Dad, hol mich bitte ab.",
            "Mein Vater war nie da.",
            "Dein Vater hat recht gehabt.",
            "Vater ist krank geworden.",
            "Papa macht das Abendessen.",
            "Mein Dad ist der stärkste Mann.",
            "Mein Vater lebt nicht mehr.",
            "Papa, ich hab dich lieb.",
            "Dad, ich brauche deinen Rat.",
            "Mein Vater war streng.",
            "Dein Vater hat sich gefreut.",
            "Vater kommt morgen zu Besuch.",
            "Papa hat mir vergeben.",
        ],
        "negative": [
            "Gestern war ich beim Arzt.",
            "Das Wetter ist heute schön.",
            "Ich habe den Bericht abgegeben.",
            "Wir fahren nächste Woche in den Urlaub.",
            "Der neue Kollege ist nett.",
            "Ich gehe heute Abend ins Kino.",
            "Das Essen war ausgezeichnet.",
            "Wir planen eine Reise nach Italien.",
            "Ich lese gerade ein gutes Buch.",
            "Der Garten sieht toll aus.",
            "Ich muss zum Optiker.",
            "Das Meeting fällt aus.",
            "Wir haben den Auftrag bekommen.",
            "Ich fahre morgen ins Büro.",
            "Das Wochenende war erholsam.",
            "Ich habe eine neue Jacke gekauft.",
            "Die Miete wird erhöht.",
            "Ich mache mir einen Kaffee.",
            "Das Fitnessstudio hat wieder offen.",
            "Wir bestellen Pizza.",
            "Ich muss Wäsche waschen.",
            "Der Zug hat Verspätung.",
            "Ich suche meine Brille.",
            "Das Paket ist angekommen.",
            "Wir machen einen Spaziergang.",
        ],
    },
    "ATO_ROLE_MOTHER": {
        "positive": [
            "Meine Mutter kocht das beste Essen.",
            "Mama, ich hab dich lieb.",
            "Mom, wann kommst du?",
            "Meine Mutter ist immer für mich da.",
            "Deine Mutter hat angerufen.",
            "Mutter war heute beim Arzt.",
            "Mama versteht mich am besten.",
            "Meine Mom vermisse ich so.",
            "Meine Mutter hat Geburtstag morgen.",
            "Mama macht sich immer Sorgen.",
            "Mutter hat mir geraten, vorsichtig zu sein.",
            "Meine Mutter ist meine beste Freundin.",
            "Mama, hilf mir bitte.",
            "Mom, das stimmt doch gar nicht.",
            "Meine Mutter hat immer recht.",
            "Deine Mutter sieht gut aus.",
            "Mutter kocht heute Abend.",
            "Mama bringt mich zum Wahnsinn.",
            "Meine Mom ist die Stärkste.",
            "Meine Mutter hat mir alles beigebracht.",
            "Mama, ich schaff das nicht ohne dich.",
            "Mom, danke für alles.",
            "Meine Mutter war Lehrerin.",
            "Deine Mutter ist wirklich nett.",
            "Mutter kommt am Wochenende.",
            "Mama hat den Kuchen gebacken.",
            "Meine Mom kümmert sich um alles.",
            "Meine Mutter fehlt mir.",
            "Mama, ich habe Heimweh.",
            "Mom ruft jeden Tag an.",
            "Meine Mutter war immer stark.",
            "Deine Mutter hat mich willkommen geheißen.",
            "Mutter und ich verstehen uns gut.",
            "Mama hat die besten Ratschläge.",
            "Meine Mom ist im Krankenhaus.",
            "Meine Mutter lebt allein.",
            "Mama hat mir vergeben.",
            "Mom, ich brauche dich.",
            "Meine Mutter hat viel durchgemacht.",
            "Deine Mutter ist eine tolle Frau.",
            "Mutter hat mich getröstet.",
            "Mama sagt immer: Alles wird gut.",
            "Meine Mom macht sich zu viele Sorgen.",
            "Meine Mutter ist Rentnerin.",
            "Mama, ich bin angekommen.",
            "Mom, wir müssen reden.",
            "Meine Mutter hat mir geschrieben.",
            "Deine Mutter fragt nach dir.",
            "Mutter ist mein Fels in der Brandung.",
            "Mama, ich liebe dich.",
        ],
        "negative": [
            "Ich habe heute eingekauft.",
            "Das Wetter wird morgen besser.",
            "Wir treffen uns um 10 Uhr.",
            "Der neue Film ist gut.",
            "Ich mache heute Sport.",
            "Das Meeting war lang.",
            "Wir fahren ans Meer.",
            "Ich lese gerade viel.",
            "Das Essen ist fertig.",
            "Wir planen eine Party.",
            "Ich muss zur Bank.",
            "Der Hund braucht Futter.",
            "Ich habe den Report geschrieben.",
            "Wir renovieren das Bad.",
            "Das Konzert war ausverkauft.",
            "Ich brauche neue Schuhe.",
            "Die Heizung funktioniert nicht.",
            "Wir gehen morgen wandern.",
            "Ich habe Kopfschmerzen.",
            "Das Paket kommt morgen.",
            "Ich muss tanken.",
            "Der Garten muss gegossen werden.",
            "Wir brauchen Milch.",
            "Ich habe schlecht geschlafen.",
            "Das Wochenende war schön.",
        ],
    },
    "ATO_ROLE_PRONOUN_SHIFT": {
        "positive": [
            "Erst sagt man wir, dann plötzlich nur noch ich.",
            "Er sprach von uns, dann war es nur noch sein Ding.",
            "Wir wollten das zusammen machen, aber sie sagte plötzlich: ich mache das allein.",
            "Zuerst war alles unser Projekt, jetzt ist es plötzlich meins.",
            "Sie wechselte von wir zu man, als es schwierig wurde.",
            "Er sagte wir schaffen das, dann hieß es plötzlich: du musst das klären.",
            "Erst wir, dann ich – der Pronomen-Wechsel fiel mir auf.",
            "Sie sprach von unserem Problem, dann war es plötzlich dein Problem.",
            "Wir sollten reden, wurde zu: du musst dich ändern.",
            "Er begann mit wir und endete mit ich allein.",
            "Plötzlich hieß es nicht mehr wir, sondern du.",
            "Sie wechselte von uns zu mir, als wäre ich nicht mehr dabei.",
            "Erst war es unser Plan, dann sein Plan.",
            "Wir hatten das zusammen beschlossen, aber jetzt sagt er ich.",
            "Sie sprach erst von wir, dann von man.",
            "Er wechselte von unserer Verantwortung zu meiner.",
            "Wir wollten das lösen, dann hieß es: mach du.",
            "Plötzlich von wir zu ich – das hat mich irritiert.",
            "Sie sagte unser Ziel, dann wurde es ihr Ziel.",
            "Er sprach von gemeinsam, dann von allein.",
            "Erst wir beide, dann nur noch er.",
            "Sie wechselte die Perspektive: von wir zu du.",
            "Anfangs war alles wir, jetzt ist es nur noch ich.",
            "Er begann mit uns und endete mit sich.",
            "Wir wollten zusammen, jetzt sagt sie: ich mache das ohne dich.",
            "Plötzlich sprach er nicht mehr von uns.",
            "Sie sagte zuerst unser Haus, dann mein Haus.",
            "Er wechselte von Team zu Solo.",
            "Erst war es unsere Schuld, jetzt ist es meine.",
            "Sie ging von wir auf du über.",
            "Anfangs sprach er von uns, dann nur noch von sich.",
            "Wir als Team, dann plötzlich ich als Einzelperson.",
            "Sie wechselte den Ton: von gemeinsam zu getrennt.",
            "Er sagte unsere Sache, jetzt ist es seine Sache.",
            "Plötzlich von wir zu man – Distanz geschaffen.",
            "Sie sprach erst von uns beiden, dann nur von sich.",
            "Er begann mit wir haben und endete mit ich habe.",
            "Anfangs unser Problem, jetzt dein Problem.",
            "Sie wechselte von wir zu ihr.",
            "Er distanzierte sich durch Pronomen-Wechsel.",
            "Erst sprach sie von uns, dann nur noch von mir.",
            "Wir wurden zu du, ganz subtil.",
            "Er sagte unser Fehler, dann war es mein Fehler.",
            "Plötzlich war es nicht mehr wir, sondern die.",
            "Sie wechselte von uns zu euch.",
            "Anfangs Teamsprache, dann Einzelkämpfer-Sprache.",
            "Er begann mit gemeinsam und endete mit ich muss.",
            "Wir hatten geplant, aber er sagte: ich entscheide.",
            "Sie sprach von unserem Weg, dann von ihrem Weg.",
            "Pronomen-Shift bemerkt: von wir auf ich.",
        ],
        "negative": [
            "Wir machen das zusammen.",
            "Unser Plan steht fest.",
            "Ich bin da ganz bei dir.",
            "Wir schaffen das gemeinsam.",
            "Das ist unser Ding.",
            "Ich stehe hinter dir.",
            "Wir ziehen das durch.",
            "Unser Team ist stark.",
            "Ich unterstütze dich.",
            "Wir halten zusammen.",
            "Das lösen wir gemeinsam.",
            "Ich bin an deiner Seite.",
            "Wir sind ein gutes Team.",
            "Unser Ziel ist klar.",
            "Ich und du, wir schaffen das.",
            "Gemeinsam sind wir stark.",
            "Wir haben das zusammen entschieden.",
            "Unser Weg führt nach vorn.",
            "Ich zähle auf dich.",
            "Wir machen weiter, zusammen.",
            "Das ist unsere Verantwortung.",
            "Ich bin bei dir.",
            "Wir geben nicht auf.",
            "Unser Projekt läuft gut.",
            "Ich und du gegen den Rest der Welt.",
        ],
    },
    "ATO_ROLE_SIBLINGS": {
        "positive": [
            "Mein Bruder nervt manchmal, aber ich hab ihn lieb.",
            "Meine Schwester ist meine beste Freundin.",
            "Wir Geschwister halten zusammen.",
            "Mein Bruder hat mir geholfen.",
            "Meine Schwester hat Geburtstag.",
            "Brüder und Schwestern streiten sich halt.",
            "Geschwister sind für immer.",
            "Mein großer Bruder beschützt mich.",
            "Meine kleine Schwester vermisse ich.",
            "Zwischen Geschwistern gibt es besondere Bande.",
            "Mein Bruder zieht aus.",
            "Meine Schwester bekommt ein Baby.",
            "Die Geschwister sind alle eingeladen.",
            "Mein Bruder und ich telefonieren jeden Sonntag.",
            "Meine Schwester studiert in München.",
            "Brüder verstehen sich ohne Worte.",
            "Schwestern teilen alles.",
            "Meine Geschwister sind mein Halt.",
            "Mein Bruder hat geheiratet.",
            "Meine Schwester ist mein Vorbild.",
            "Wir sind drei Geschwister.",
            "Mein Bruder macht mich wahnsinnig.",
            "Meine Schwester hat mir geraten.",
            "Geschwisterliebe ist bedingungslos.",
            "Mein Bruder arbeitet im Ausland.",
            "Meine Schwester kommt zu Besuch.",
            "Brüder streiten und versöhnen sich.",
            "Schwestern kennen einander am besten.",
            "Meine Geschwister fehlen mir.",
            "Mein Bruder hat den gleichen Humor.",
            "Meine Schwester hat mich getröstet.",
            "Wir Geschwister sind sehr unterschiedlich.",
            "Mein Bruder ist mein bester Freund.",
            "Meine Schwester lebt in Berlin.",
            "Die Geschwister planen ein Treffen.",
            "Mein kleiner Bruder wird erwachsen.",
            "Meine große Schwester hat immer einen Rat.",
            "Geschwister teilen Erinnerungen.",
            "Mein Bruder hat mich unterstützt.",
            "Meine Schwester und ich sind unzertrennlich.",
            "Brüder halten zusammen, wenn es drauf ankommt.",
            "Schwestern haben eine besondere Verbindung.",
            "Mein Bruder hat angerufen.",
            "Meine Schwester ist schwanger.",
            "Geschwister sind das erste Team.",
            "Mein Bruder versteht mich besser als jeder andere.",
            "Meine Schwester hat mir den Weg gezeigt.",
            "Wir Geschwister haben viel durchgemacht.",
            "Mein Bruder ist stolz auf mich.",
            "Meine Schwester ist immer ehrlich zu mir.",
        ],
        "negative": [
            "Ich habe heute gut geschlafen.",
            "Das Wetter ist herrlich.",
            "Ich gehe jetzt einkaufen.",
            "Wir sehen uns morgen.",
            "Der Film war toll.",
            "Ich mache mir einen Tee.",
            "Das Meeting war kurz.",
            "Wir fahren in den Urlaub.",
            "Ich habe Hunger.",
            "Das Buch ist spannend.",
            "Ich treffe mich mit Freunden.",
            "Das Essen war gut.",
            "Wir gehen ins Restaurant.",
            "Ich brauche neue Kopfhörer.",
            "Der Arzttermin ist morgen.",
            "Ich habe den Bus verpasst.",
            "Wir feiern am Samstag.",
            "Ich lerne gerade Spanisch.",
            "Das Projekt ist abgeschlossen.",
            "Wir bestellen beim Italiener.",
            "Ich muss früh aufstehen.",
            "Der Supermarkt hat bis 22 Uhr offen.",
            "Ich gehe heute joggen.",
            "Das Handy braucht ein Update.",
            "Wir planen ein Picknick.",
        ],
    },
    "ATO_ROMANTIC_SIGNAL_DIRECT": {
        "positive": [
            "Ich liebe dich so sehr.",
            "Du bist so sexy.",
            "Lass uns mal daten gehen.",
            "Ich küsse dich zärtlich.",
            "Mein Herz schlägt nur für dich.",
            "Ich liebe dich mehr als alles andere.",
            "Du bist unglaublich sexy heute.",
            "Lass uns daten, ich mag dich.",
            "Ich küsse dich auf die Stirn.",
            "Ein Herz für dich, mein Schatz.",
            "Ich liebe dich, vergiss das nie.",
            "Du bist so verdammt sexy.",
            "Lass uns daten, was sagst du?",
            "Küss mich bitte.",
            "Mein Herz gehört nur dir.",
            "Ich liebe dich über alles.",
            "Du siehst so sexy aus in dem Kleid.",
            "Wann daten wir endlich?",
            "Ich küsse dich sanft.",
            "Für dich – mein ganzes Herz.",
            "Ich liebe dich jeden Tag mehr.",
            "Du bist die sexieste Person, die ich kenne.",
            "Lass uns morgen daten.",
            "Ich will dich küssen.",
            "Mein Herz für dich, immer.",
            "Ich liebe dich wahnsinnig.",
            "Sexy, intelligent und lustig – du bist perfekt.",
            "Ein Date mit dir wäre wunderbar.",
            "Ich küsse dir die Tränen weg.",
            "Herz über Kopf – ich liebe dich.",
            "Ich liebe dich, das weißt du.",
            "Du bist sexy und das weißt du.",
            "Lass uns das erste Date nachholen.",
            "Küsst du mich zurück?",
            "Ein Herz für dich zum Valentinstag.",
            "Ich liebe dich unendlich.",
            "Du wirkst so sexy, wenn du lachst.",
            "Ich will mit dir daten, ernsthaft.",
            "Ich küsse dich zur Begrüßung.",
            "Mein Herz schlägt schneller bei dir.",
            "Ich liebe dich, das ist alles.",
            "Du bist umwerfend sexy.",
            "Unser erstes Date war magisch.",
            "Ich küsse dich zum Abschied.",
            "Herz an Herz mit dir.",
            "Ich liebe dich so, wie du bist.",
            "Du bist einfach sexy.",
            "Lass uns wieder daten gehen.",
            "Ich küsse dich gerade in Gedanken.",
            "Mein Herz ist voll für dich.",
        ],
        "negative": [
            "Du bist ein guter Freund.",
            "Ich schätze unsere Freundschaft.",
            "Danke, du bist nett.",
            "Wir verstehen uns gut.",
            "Du bist mir sympathisch.",
            "Gute Zusammenarbeit.",
            "Du bist ein toller Mensch.",
            "Ich mag dich als Freund.",
            "Wir sind ein gutes Team.",
            "Danke für deine Hilfe.",
            "Du bist mir wichtig als Kollege.",
            "Ich respektiere dich.",
            "Guter Kumpel.",
            "Wir kennen uns jetzt schon ewig.",
            "Du bist verlässlich.",
            "Ich vertraue dir beruflich.",
            "Wir harmonieren gut im Team.",
            "Danke für das offene Ohr.",
            "Du bist ein treuer Freund.",
            "Ich schätze deine Ehrlichkeit.",
            "Gute Nachbarschaft.",
            "Du bist mir eine große Hilfe.",
            "Wir machen das professionell.",
            "Danke fürs Zuhören.",
            "Du bist zuverlässig.",
        ],
    },
    "ATO_ROUTINE_GREETING": {
        "positive": [
            "Guten Morgen, wie geht es dir?",
            "Hast du gut geschlafen?",
            "Wie war deine Nacht?",
            "Good morning, Liebling.",
            "Guten Morgen, Schatz!",
            "Hast du gut geschlafen, Mama?",
            "Wie war deine Nacht? Gut geruht?",
            "Good morning, Team!",
            "Guten Morgen, sonniges Kind.",
            "Hast du gut geschlafen heute Nacht?",
            "Wie war deine Nacht? Alles okay?",
            "Good morning, world!",
            "Guten Morgen, mein Herz.",
            "Na, hast du gut geschlafen?",
            "Wie war deine Nacht? Ausgeruht?",
            "Good morning, sunshine.",
            "Guten Morgen zusammen!",
            "Hast du einigermaßen gut geschlafen?",
            "Wie war deine Nacht? Besser als gestern?",
            "Good morning, wie läuft's?",
            "Guten Morgen, alles fit?",
            "Hast du gut geschlafen, mein Schatz?",
            "Wie war deine Nacht, Süße?",
            "Good morning, frohes Schaffen!",
            "Guten Morgen an alle!",
            "Hast du gut geschlafen nach dem langen Abend?",
            "Wie war deine Nacht? Ich hoffe ruhig.",
            "Good morning, ready to go?",
            "Guten Morgen, aufgestanden!",
            "Hast du gut geschlafen, Liebes?",
            "Wie war deine Nacht so?",
            "Good morning, happy Monday!",
            "Guten Morgen, Kaffee steht bereit.",
            "Hast du halbwegs gut geschlafen?",
            "Wie war deine Nacht, alles ruhig?",
            "Good morning, hope you slept well.",
            "Guten Morgen, die Sonne scheint!",
            "Hast du gut geschlafen trotz des Sturms?",
            "Wie war deine Nacht? Konntest du schlafen?",
            "Good morning, neuer Tag, neues Glück.",
            "Guten Morgen, aufwachen!",
            "Hast du ordentlich geschlafen?",
            "Wie war deine Nacht? Träume gehabt?",
            "Good morning, rise and shine!",
            "Guten Morgen, ich hoffe du bist fit.",
            "Hast du gut geschlafen in dem neuen Bett?",
            "Wie war deine Nacht? Erholsam?",
            "Good morning, frühes Vögelchen.",
            "Guten Morgen, schön dass du da bist.",
            "Hast du gut geschlafen nach der Party?",
        ],
        "negative": [
            "Hallo, ich wollte kurz was fragen.",
            "Hey, hast du den Bericht gelesen?",
            "Hi, bist du heute im Büro?",
            "Servus, wie war dein Wochenende?",
            "Na, was gibt's Neues?",
            "Tach, alles klar?",
            "Moin, was steht an?",
            "Grüß dich, lange nicht gesehen.",
            "Hey, was machst du gerade?",
            "Hallo zusammen, starten wir.",
            "Hi, ich bin der Neue.",
            "Guten Tag, ich suche Herrn Müller.",
            "Hej, hast du Lust auf Kaffee?",
            "Aloha, Urlaub ist vorbei.",
            "Yo, wie geht's?",
            "Mahlzeit!",
            "Guten Abend, willkommen.",
            "Hallo, kann ich Ihnen helfen?",
            "Ciao, bis morgen.",
            "Tschüss, schönen Feierabend.",
            "Auf Wiedersehen.",
            "Bis bald!",
            "Mach's gut.",
            "Gute Nacht.",
            "Bye bye!",
        ],
    },
}
