#!/usr/bin/env python3
"""
Enrich ATO markers (batch 5c: TOPIC_BLOCK_SYNTAX through UNCERTAINTY_PHRASE).
50 positive + 25 negative German examples each.
"""

import os
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
yaml.allow_duplicate_keys = True

BASE = Path("/Users/benjaminpoersch/Projects/LeanDeep-annotator/build/markers_rated")
DIRS = [BASE / "1_approved" / "ATO", BASE / "2_good" / "ATO"]


def find_file(marker_id: str) -> Path | None:
    for d in DIRS:
        p = d / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None


ENRICHMENTS = {

"ATO_TOPIC_BLOCK_SYNTAX": {
  "positive": [
    "Ich kann jetzt nicht ueber schwere Sachen reden, lass uns einfach den Abend geniessen.",
    "Du weisst, ich bin nicht gut mit Emotionen ueber Text, koennen wir das aufheben?",
    "Koennen wir bitte nicht jetzt darueber sprechen?",
    "Ich kann gerade nicht ueber meine Gefuehle reden.",
    "Lass uns das nicht jetzt besprechen, ich bin muede.",
    "Wir koennen jetzt nicht ueber das Thema reden, es ist zu spaet.",
    "Koennen wir nicht darueber diskutieren, wenn wir uns sehen?",
    "Ich kann jetzt nicht ueber die Trennung reden.",
    "Bitte, koennen wir gerade nicht darueber sprechen.",
    "Ich kann nicht ueber sowas am Telefon reden.",
    "Koennen wir das jetzt nicht besprechen?",
    "Ich will gerade nicht darueber reden, okay?",
    "Wir koennen jetzt nicht ueber Geld sprechen.",
    "Lass uns nicht jetzt darueber reden, bitte.",
    "Ich kann nicht ueber unsere Beziehung reden, wenn ich gestresst bin.",
    "Koennen wir gerade nicht ueber die Kinder sprechen?",
    "Ich kann jetzt nicht ueber die Arbeit reden.",
    "Bitte nicht jetzt darueber, ich bin nicht in der Stimmung.",
    "Wir koennen das nicht jetzt besprechen, ich muss los.",
    "Ich will nicht gerade ueber den Streit reden.",
    "Koennen wir nicht darueber sprechen, wenn ich mich beruhigt habe?",
    "Ich kann nicht ueber sowas auf WhatsApp reden.",
    "Lass uns das nicht jetzt anfangen.",
    "Koennen wir jetzt nicht darueber diskutieren?",
    "Ich bin nicht in der Lage, gerade darueber zu reden.",
    "Das ist mir jetzt zu schwer, koennen wir das lassen?",
    "Nicht jetzt, ich kann gerade nicht ueber sowas reden.",
    "Koennen wir bitte nicht jetzt ueber die Hochzeit sprechen?",
    "Ich kann gerade nicht darueber nachdenken, geschweige denn reden.",
    "Lass uns spaeter darueber reden, jetzt ist kein guter Zeitpunkt.",
    "Koennen wir nicht ueber schwierige Themen reden, wenn wir uns sehen?",
    "Ich bin zu muede, um jetzt darueber zu sprechen.",
    "Bitte nicht gerade jetzt, das ist mir zu emotional.",
    "Wir koennen gerade nicht darueber diskutieren.",
    "Ich moechte jetzt nicht ueber unsere Probleme reden.",
    "Koennen wir das nicht verschieben?",
    "Ich kann nicht darueber reden, wenn die Kinder da sind.",
    "Lass uns das auf morgen vertagen.",
    "Ich will jetzt nicht ueber Gefuehle sprechen.",
    "Koennen wir gerade nicht ueber den Umzug sprechen?",
    "Das Thema ist mir gerade zu belastend.",
    "Ich brauche Abstand davon, reden wir spaeter.",
    "Nicht jetzt, ich habe gerade keine Kraft fuer dieses Thema.",
    "Koennen wir das besprechen, wenn es uns beiden besser geht?",
    "Ich moechte das Thema gerade nicht anschneiden.",
    "Das ist mir zu heikel fuer eine Textnachricht.",
    "Lass uns das aufschieben, bis wir ruhiger sind.",
    "Ich kann das gerade nicht verarbeiten.",
    "Koennen wir das auf ein persoenliches Gespraech verschieben?",
    "Nicht am Telefon, das ist zu wichtig.",
  ],
  "negative": [
    "Lass uns in Ruhe darueber reden, ich bin bereit.",
    "Ich moechte jetzt gerne ueber unsere Situation sprechen.",
    "Erzaehl mir, was dich beschaeftigt.",
    "Ich bin offen fuer das Gespraech, wann immer du willst.",
    "Lass uns das jetzt klaeren.",
    "Ich hoere dir zu, rede einfach.",
    "Wir koennen ueber alles sprechen.",
    "Ich bin bereit, das Thema anzugehen.",
    "Sag mir, was dich bewegt.",
    "Ich moechte verstehen, was los ist.",
    "Lass uns das offen besprechen.",
    "Ich bin ganz Ohr.",
    "Was beschaeftigt dich gerade?",
    "Ich moechte darueber reden, wenn du magst.",
    "Wir sollten das jetzt klaeren.",
    "Ich bin da, rede einfach.",
    "Lass uns das gemeinsam durchgehen.",
    "Ich will wissen, wie es dir geht.",
    "Sag mir ehrlich, was du denkst.",
    "Ich bin bereit fuer dieses Gespraech.",
    "Wir koennen offen miteinander reden.",
    "Ich moechte dir zuhoeren.",
    "Lass uns das Thema jetzt angehen.",
    "Ich bin emotional verfuegbar.",
    "Wir reden jetzt, okay?",
  ],
},

"ATO_TOPIC_JUMP_MARKER": {
  "positive": [
    "Ach uebrigens, da faellt mir was ein.",
    "Oh Moment, ganz anderes Thema.",
    "Kurze Abschweifung: weisst du was?",
    "Apropos, das erinnert mich an was anderes.",
    "Tangente: warum regnet es eigentlich immer montags?",
    "Zufaelliger Gedanke: ich mag Kekse.",
    "Oh warte, ganz was anderes jetzt.",
    "Bevor ich es vergesse, voellig anderes Thema.",
    "Ach ja, mir faellt gerade ein...",
    "Kompletter Themenwechsel, aber das muss ich dir erzaehlen.",
    "Halt, mir ist gerade was eingefallen.",
    "Random, aber hast du den Film gesehen?",
    "Kleiner Seitenpfad: meine Schwester hat angerufen.",
    "Oh, das erinnert mich an was Lustiges.",
    "Ich spring mal kurz: wie war dein Tag?",
    "Apropos gar nichts, weisst du was ich heute gesehen habe?",
    "Uebrigens, voellig zusammenhangslos...",
    "Ach, da faellt mir noch was ein.",
    "Moment, anderes Thema ganz kurz.",
    "Ich weiss, das passt jetzt nicht, aber...",
    "Zufaellig: ich hab neue Schuhe.",
    "Oh warte, bevor ich abschweife... na gut, ich schweife ab.",
    "Ganz anderer Gedanke gerade.",
    "Ach, und nochwas Unzusammenhaengendes.",
    "Sorry fuer den Themenwechsel, aber...",
    "Mir schiesst gerade was durch den Kopf.",
    "Kleiner Gedankensprung: ich will Pizza.",
    "Achja, eine andere Sache noch...",
    "Warte, das hat nichts damit zu tun, aber...",
    "Bevor ich es vergesse, total random:",
    "Und ganz was anderes: meine Katze hat heute...",
    "Abschweifalarm: gestern im Supermarkt...",
    "Moment, mir kommt gerade was in den Sinn.",
    "Unabhaengig davon, mir ist gerade aufgefallen...",
    "Ich springe gerade, sorry: wie war das Wetter?",
    "Kurze Randbemerkung: das Essen gestern war gut.",
    "Jetzt fang ich schon wieder an zu springen.",
    "Ach, noch ein ganz anderer Punkt.",
    "Oh, ich muss dir noch was erzaehlen, hat aber nix damit zu tun.",
    "Zufaellige Frage: magst du Sushi?",
    "Themenhopping: kennst du den Song?",
    "Wo war ich? Egal, anderes Thema.",
    "Da faellt mir ein, voellig losgeloest...",
    "Ich weiss nicht warum, aber ich muss gerade an die Schule denken.",
    "Uebrigens, ganz am Rande...",
    "Ich weiss, ich springe, aber das ist wichtig.",
    "Oh, bevor wir weitermachen, ganz kurz...",
    "Noch eine Abschweifung, tut mir leid.",
    "Halt, Stopp, ganz anderes Thema.",
    "Puh, mein Kopf springt gerade. Also...",
  ],
  "negative": [
    "Um auf den Punkt zurueckzukommen.",
    "Wie ich gerade sagte...",
    "Zum Thema zurueck:",
    "Bleiben wir beim Thema.",
    "Das passt gut zu dem, was du sagtest.",
    "In dem Zusammenhang...",
    "Das fuehrt uns direkt zum naechsten Punkt.",
    "Wie wir vorhin besprochen haben...",
    "Das ergibt sich logisch aus dem Gesagten.",
    "Daran anknuepfend moechte ich sagen...",
    "Genau, und da sind wir beim Kern.",
    "Das schliesst nahtlos an unser Thema an.",
    "Darauf aufbauend...",
    "Das passt perfekt dazu.",
    "In Bezug auf das, was du erwaehnt hast...",
    "Zum gleichen Thema:",
    "Daran anschliessend:",
    "Das haengt direkt damit zusammen.",
    "Folglich moechte ich sagen...",
    "Genau in dem Kontext...",
    "Das ist ein wichtiger Aspekt davon.",
    "Zusammenfassend zu dem Punkt...",
    "Im selben Zusammenhang:",
    "Daraus ergibt sich...",
    "Bezogen auf unsere Diskussion...",
  ],
},

"ATO_TOPIC_RAISED": {
  "positive": [
    "Neues Thema: Urlaub.",
    "Anderes Thema, Budget.",
    "Lass uns ueber naechste Woche sprechen.",
    "Was anderes: die Praesentation.",
    "Kurzer Themenwechsel: Meeting-Termine.",
    "Ich wuerde gern ein anderes Thema reinbringen.",
    "Neues Thema: Weihnachtsfeier.",
    "Lass uns ueber die Renovierung reden.",
    "Anderes Thema: Kindergarten-Anmeldung.",
    "Was anderes: meine Mutter kommt zu Besuch.",
    "Kurzer Themenwechsel: Steuererklarung.",
    "Neues Thema: Haustier anschaffen?",
    "Lass uns mal ueber Urlaub sprechen.",
    "Anderes Thema bitte: die Kuechensanierung.",
    "Was anderes, ich muss dir was sagen.",
    "Neues Thema: wie geht es dir eigentlich?",
    "Lass uns ueber unsere Plaene fuer naechstes Jahr reden.",
    "Anderes Thema: der Elternabend.",
    "Kurzer Themenwechsel: Geburtstag planen.",
    "Neues Thema: Fitnessstudio-Mitgliedschaft.",
    "Lass uns ueber die Finanzen sprechen.",
    "Was anderes jetzt: die neue Wohnung.",
    "Anderes Thema: Arzttermin morgen.",
    "Neues Thema am Rande: Versicherung wechseln.",
    "Lass uns mal was anderes besprechen.",
    "Themenwechsel: wie laueft es auf der Arbeit?",
    "Was anderes: hast du an den Vertrag gedacht?",
    "Neues Thema: die Hochzeit von Lisa.",
    "Lass uns ueber was Schoenes reden.",
    "Anderes Thema: Auto-Inspektion.",
    "Kurzer Themenwechsel: Internet-Anbieter wechseln.",
    "Neues Thema: Sommerurlaub buchen.",
    "Was anderes ganz kurz: Waschmaschine ist kaputt.",
    "Lass uns ueber den Umzug sprechen.",
    "Anderes Thema: Schultuete basteln.",
    "Neues Thema: Oma besuchen am Wochenende.",
    "Lass uns ueber die Gartenarbeit reden.",
    "Was anderes: ich moechte einen Kurs belegen.",
    "Kurzer Themenwechsel: Dachboden aufraeumen.",
    "Neues Thema: gemeinsame Hobbys.",
    "Lass uns ueber was Positives sprechen.",
    "Anderes Thema: die Party am Samstag.",
    "Neues Thema bitte: Putzplan.",
    "Was anderes: hast du den Brief abgeschickt?",
    "Lass uns ueber die Ferien reden.",
    "Themenwechsel: die Nachbarn haben sich beschwert.",
    "Neues Thema: Balkonpflanzen.",
    "Anderes Thema: Renovierung im Bad.",
    "Lass uns mal ueber Geld sprechen.",
    "Was anderes, ganz wichtig: Zahnarzt-Termin.",
  ],
  "negative": [
    "Ja, da stimme ich dir zu.",
    "Das sehe ich genauso.",
    "Du hast Recht, bleiben wir dabei.",
    "Gut, weiter im Thema.",
    "Okay, zurueck zu dem, was wir besprochen haben.",
    "Genau, und dazu wollte ich noch sagen...",
    "Das passt gut, erzaehl weiter.",
    "Darauf aufbauend moechte ich erwaehnen...",
    "In dem Zusammenhang finde ich...",
    "Genau, da haben wir einen Punkt.",
    "Das Thema ist mir auch wichtig.",
    "Erzaehl weiter, das interessiert mich.",
    "Dazu habe ich auch eine Meinung.",
    "Das gehoert definitiv zum Thema.",
    "Bleiben wir da dran.",
    "Guter Punkt, lass uns das vertiefen.",
    "Das fuehrt uns naemlich zum Kern.",
    "Ich moechte das aufgreifen, was du sagst.",
    "In Bezug darauf habe ich eine Frage.",
    "Genau, lass uns das weiterdenken.",
    "Das ist wichtig, rede weiter.",
    "Darauf moechte ich eingehen.",
    "Wir sollten dabeibleiben.",
    "Das passt nahtlos dazu.",
    "Genau das meinte ich auch.",
  ],
},

"ATO_TOPIC_REFUSAL": {
  "positive": [
    "Ich will nicht darueber reden.",
    "Lass uns bitte nicht dahin gehen.",
    "Ich kann mich daran nicht erinnern.",
    "Bitte wechsel das Thema, mir ist unwohl.",
    "Ich moechte nicht ueber meine Vergangenheit sprechen.",
    "Darauf gehe ich nicht ein.",
    "Das Thema ist fuer mich tabu.",
    "Ich rede nicht ueber sowas.",
    "Frag mich bitte nicht danach.",
    "Ich moechte das nicht besprechen.",
    "Lass uns das Thema aussen vor lassen.",
    "Ich kann darueber nicht sprechen.",
    "Das ist zu schmerzhaft, bitte nicht.",
    "Ich verweigere jede Diskussion darueber.",
    "Dieses Thema ist erledigt fuer mich.",
    "Ich will da nicht dran ruehren.",
    "Bitte lass das, ich mag nicht.",
    "Ich bin nicht bereit, darueber zu reden.",
    "Das Thema macht mir zu schaffen, lass es.",
    "Ich will nicht darueber nachdenken.",
    "Frag mich nicht nach Details.",
    "Dieses Gespraech fuehre ich nicht.",
    "Ich will das nicht aufwaermen.",
    "Vergiss es, ich rede nicht drueber.",
    "Nein, darueber spreche ich nicht.",
    "Bitte akzeptiere, dass ich nicht darueber reden will.",
    "Das Kapitel ist geschlossen.",
    "Ich habe kein Beduerfnis, darueber zu reden.",
    "Lass es einfach, okay?",
    "Darueber moechte ich schweigen.",
    "Ich kann und will das nicht besprechen.",
    "Das Thema ist fuer mich abgehakt.",
    "Bitte draeng mich nicht dazu.",
    "Ich weigere mich, da nochmal drueber zu reden.",
    "Das Thema hat sich fuer mich erledigt.",
    "Nein, ich gehe da nicht drauf ein.",
    "Lass mich damit in Ruhe.",
    "Ich rede da nicht drueber, Punkt.",
    "Keine Diskussion ueber dieses Thema.",
    "Ich moechte nicht zurueckblicken.",
    "Das ist mein wunder Punkt, bitte nicht.",
    "Ich bin nicht in der Lage, das zu besprechen.",
    "Das geht zu tief, lass uns aufhoeren.",
    "Ich sage dazu nichts.",
    "Bitte respektiere, dass ich nicht will.",
    "Das Thema ist mir zu sensibel.",
    "Ich moechte da nicht draengen lassen.",
    "Ich rede nicht drueber, und fertig.",
    "Kein Kommentar zu diesem Thema.",
    "Ich habe Gruende, warum ich nicht darueber rede.",
  ],
  "negative": [
    "Ich moechte offen darueber sprechen.",
    "Lass uns das Thema angehen.",
    "Ich bin bereit, darueber zu reden.",
    "Erzaehl mir mehr davon.",
    "Ich stelle mich dem Gespraech.",
    "Wir sollten das aufarbeiten.",
    "Ich moechte meine Gefuehle teilen.",
    "Lass uns ehrlich miteinander sein.",
    "Ich oeffne mich gerne dafuer.",
    "Das Thema verdient unsere Aufmerksamkeit.",
    "Ich moechte das mit dir besprechen.",
    "Lass uns gemeinsam hinschauen.",
    "Ich will nichts verdraengen.",
    "Wir sollten das Thema nicht meiden.",
    "Ich bin bereit, mich zu stellen.",
    "Lass uns offen sein.",
    "Ich moechte darueber reden, auch wenn es wehtut.",
    "Wir sollten das nicht totschweigen.",
    "Ich oeffne mich fuer dieses Gespraech.",
    "Lass uns mutig sein und reden.",
    "Ich will das klaren.",
    "Das verdient ein ehrliches Gespraech.",
    "Ich stelle mich meinen Gefuehlen.",
    "Wir muessen darueber sprechen.",
    "Ich bin offen und bereit.",
  ],
},

"ATO_TOPIC_SHIFT_TO_TASK": {
  "positive_de": [
    "Zurueck zum Thema: To-do Liste aktualisieren.",
    "Konkret: Schritt 3 heute abschliessen.",
    "Aufgabe: Angebote einholen bis Freitag.",
    "Naechster Punkt: Freigabe einholen.",
    "Liefertermin bleibt der 30.09.",
    "Zurueck zum Thema: wer uebernimmt das Protokoll?",
    "Konkret: Budget bis morgen einreichen.",
    "Aufgabe: Feedback sammeln und weiterleiten.",
    "Schritt 1: Anforderungen definieren.",
    "To-do: Termin mit dem Lieferanten vereinbaren.",
    "Naechster Punkt: Zeitplan ueberarbeiten.",
    "Zurueck zum Thema: Praesentation finalisieren.",
    "Konkret heisst das: drei Optionen ausarbeiten.",
    "Aufgabe fuer morgen: Bericht fertigstellen.",
    "Schritt 2: Prototyp testen.",
    "To-do: Kunden informieren.",
    "Liefertermin ist der 15. Maerz.",
    "Naechster Punkt: Rollenverteilung.",
    "Zurueck zum Thema: Kostenaufstellung.",
    "Konkret: Entwurf bis Mittwoch.",
    "Aufgabe: Meeting-Raum reservieren.",
    "Schritt 4: Ergebnisse zusammenfassen.",
    "To-do: Einladungen verschicken.",
    "Zurueck zum Thema: naechste Meilensteine.",
    "Konkret: Deadline einhalten.",
    "Aufgabe: Status-Update vorbereiten.",
    "Naechster Punkt: Tests durchfuehren.",
    "Schritt 5: Abnahme organisieren.",
    "To-do: Dokumentation aktualisieren.",
    "Zurueck zum Thema: wer kuemmert sich um die Bestellung?",
    "Konkret muessten wir jetzt: die Zahlen pruefen.",
    "Aufgabe fuer diese Woche: Partnerkontakt aufnehmen.",
    "Naechster Punkt: Qualitaetskontrolle.",
    "Zurueck zum eigentlichen Thema: Projektplanung.",
    "Schritt 6: Release vorbereiten.",
    "To-do: Schulungsmaterial erstellen.",
    "Aufgabe: Angebot ueberarbeiten.",
    "Konkret: drei Varianten durchrechnen.",
    "Naechster Punkt: Vertrag unterschreiben.",
    "Zurueck zum Thema: Agenda fuer morgen.",
    "Schritt 7: Feedback einarbeiten.",
    "To-do: Reiseplanung abschliessen.",
    "Aufgabe: Logo-Entwurf pruefen.",
    "Konkret: Website-Texte finalisieren.",
    "Naechster Punkt: Social-Media-Plan.",
    "Zurueck zum Thema: Budgetverteilung.",
    "Schritt 8: Launch-Datum festlegen.",
    "To-do: Inventur machen.",
    "Aufgabe: Vertragsdetails klaeren.",
    "Konkret: den Prototyp dem Team vorstellen.",
  ],
  "negative_de": [
    "Ich fuehle mich gerade ueberfordert.",
    "Das macht mich traurig.",
    "Ich bin enttaeuscht von der Situation.",
    "Meine Gefuehle sind gerade durcheinander.",
    "Ich brauche emotionale Unterstuetzung.",
    "Das verletzt mich.",
    "Ich fuehle mich nicht gehoert.",
    "Das belastet mich sehr.",
    "Ich bin wuetend auf die Situation.",
    "Mein Herz ist schwer.",
    "Ich mache mir Sorgen um uns.",
    "Das aengstigt mich.",
    "Ich fuehle mich alleingelassen.",
    "Das frustriert mich.",
    "Ich bin emotional am Limit.",
    "Meine Gefuehle sind verletzt.",
    "Ich brauche Naehe.",
    "Das Gespraech macht mir Angst.",
    "Ich fuehle mich missverstanden.",
    "Das tut mir im Herzen weh.",
    "Ich bin verunsichert.",
    "Meine Emotionen kochen hoch.",
    "Ich brauche Trost.",
    "Das beruehrt mich zutiefst.",
    "Ich fuehle mich verletzlich gerade.",
  ],
},

"ATO_TOPIC_SPLIT": {
  "positive": [
    "Das trennen wir.",
    "X gehoert hier nicht rein.",
    "Anderes Thema, bitte separat.",
    "Lass uns das separat behandeln.",
    "Den Teil klammern wir aus.",
    "Das gehoert in einen separaten Thread.",
    "Wir sollten das getrennt besprechen.",
    "Das mischen wir jetzt nicht zusammen.",
    "Lass uns das entkoppeln.",
    "Eines nach dem anderen, bitte.",
    "Das ist ein eigenes Thema.",
    "Wir packen das in einen separaten Punkt.",
    "Das klammern wir bewusst aus.",
    "Lass uns die zwei Themen trennen.",
    "Das gehoert nicht in diese Diskussion.",
    "Wir behandeln das unabhaengig voneinander.",
    "Das ist ein anderes Fass, das machen wir spaeter auf.",
    "Lass uns das separat angehen.",
    "Das muss getrennt betrachtet werden.",
    "Wir splitten das auf.",
    "Zwei verschiedene Baustellen.",
    "Lass uns das nicht vermischen.",
    "Das ist ein separater Tagesordnungspunkt.",
    "Wir muessen das sauber trennen.",
    "Das diskutieren wir in einem eigenen Meeting.",
    "Lass uns fokussiert bleiben und das ausklammern.",
    "Das ist ein eigenstaendiges Thema.",
    "Wir packen das auf die Parkliste.",
    "Bitte nicht alles in einen Topf werfen.",
    "Das verdient eine eigene Diskussion.",
    "Lass uns das priorisieren und aufteilen.",
    "Das nehmen wir raus und besprechen es separat.",
    "Wir sollten das nicht miteinander verquicken.",
    "Einzeln betrachten bitte.",
    "Das sind zwei Paar Schuhe.",
    "Lass uns das in Teile zerlegen.",
    "Das braucht eine eigene Agenda.",
    "Wir trennen Operatives von Strategischem.",
    "Das packe ich auf die naechste Agenda.",
    "Getrennt besprechen, gemeinsam entscheiden.",
    "Lass uns das modular angehen.",
    "Das ist ein separates Anliegen.",
    "Wir behandeln das als eigenes Ticket.",
    "Das klammern wir fuer heute aus.",
    "Bitte nicht alles gleichzeitig.",
    "Das nehmen wir als naechstes, nicht jetzt.",
    "Lass uns das in Teilprojekte splitten.",
    "Wir muessen das klar voneinander abgrenzen.",
    "Das gehoert in ein anderes Gespraech.",
    "Erst das eine, dann das andere.",
  ],
  "negative": [
    "Das haengt alles zusammen.",
    "Wir muessen das als Ganzes betrachten.",
    "Das kann man nicht trennen.",
    "Alles gehoert zum gleichen Thema.",
    "Lass uns das im Zusammenhang sehen.",
    "Das eine bedingt das andere.",
    "Wir sollten das ganzheitlich angehen.",
    "Das ist untrennbar verbunden.",
    "Alles auf einmal besprechen.",
    "Das ergibt nur im Ganzen Sinn.",
    "Lass uns alles zusammen diskutieren.",
    "Die Themen bedingen sich gegenseitig.",
    "Wir brauchen den Gesamtblick.",
    "Das kann man nicht isoliert betrachten.",
    "Alles zusammen ergibt erst ein Bild.",
    "Wir muessen das vernetzte Denken anwenden.",
    "Das greift ineinander.",
    "Lass uns alles auf den Tisch legen.",
    "Das sind zwei Seiten derselben Medaille.",
    "Wir besprechen alles jetzt.",
    "Das laesst sich nicht aufteilen.",
    "Alles zusammen, bitte.",
    "Die Punkte gehoeren zusammen.",
    "Wir sehen das als Gesamtpaket.",
    "Das ergibt nur im Kontext Sinn.",
  ],
},

"ATO_TOPIC_SWITCH_ADVERSATIVE": {
  "positive": [
    "Aber koennen wir kurz ueber Budget reden?",
    "Jedoch ist das nicht der Punkt.",
    "Wobei, lass uns anders anfangen.",
    "Trotzdem, was ist mit dem Termin?",
    "Aber zurueck zum eigentlichen Thema.",
    "Jedoch, das war nicht gemeint.",
    "Wobei, vielleicht spaeter.",
    "Trotzdem, ich sehe das anders.",
    "Aber ich wollte eigentlich was anderes sagen.",
    "Jedoch muss ich da widersprechen.",
    "Wobei, einen Moment, da stimmt was nicht.",
    "Trotzdem, lass uns weitermachen.",
    "Aber das ist nicht das Hauptproblem.",
    "Jedoch, das aendert nichts an meiner Meinung.",
    "Wobei, da habe ich eine andere Erfahrung.",
    "Trotzdem bleibt die Frage offen.",
    "Aber warte, ich habe noch einen Punkt.",
    "Jedoch moechte ich hinzufuegen...",
    "Wobei, das stimmt nicht ganz.",
    "Trotzdem finde ich es wichtig zu erwaehnen.",
    "Aber lass uns nicht vom Thema abkommen.",
    "Jedoch sehe ich da ein Problem.",
    "Wobei, vielleicht liegt es an was anderem.",
    "Trotzdem, meine Bedenken bleiben.",
    "Aber ich wollte noch etwas einwerfen.",
    "Jedoch ist das nur die halbe Wahrheit.",
    "Wobei, ueberleg mal andersrum.",
    "Trotzdem, wir muessen das klaeren.",
    "Aber das fuehrt uns woanders hin.",
    "Jedoch gibt es da noch einen Aspekt.",
    "Wobei, ich hab da nochmal drueber nachgedacht.",
    "Trotzdem, mein Eindruck bleibt.",
    "Aber das widerspricht dem, was du vorher gesagt hast.",
    "Jedoch, wenn ich ehrlich bin...",
    "Wobei, Moment mal...",
    "Trotzdem, ich stehe zu meiner Aussage.",
    "Aber lass mich kurz einhaken.",
    "Jedoch moechte ich das relativieren.",
    "Wobei, stimmt auch wieder.",
    "Trotzdem, die Realitaet sieht anders aus.",
    "Aber wir duerfen nicht vergessen...",
    "Jedoch, andererseits...",
    "Wobei, jetzt wo du es sagst...",
    "Trotzdem, das Ergebnis zaehlt.",
    "Aber im Grunde geht es um was anderes.",
    "Jedoch, das ist nicht der springende Punkt.",
    "Wobei, ich will fair bleiben.",
    "Trotzdem, man muss das realistisch sehen.",
    "Aber noch ein Gedanke dazu...",
    "Jedoch, um ehrlich zu sein...",
  ],
  "negative": [
    "Genau, und dazu moechte ich sagen...",
    "Ausserdem finde ich...",
    "Zusaetzlich moechte ich erwaehnen...",
    "Darauf aufbauend...",
    "Das passt gut dazu.",
    "In dem Kontext auch wichtig...",
    "Ergaenzend dazu...",
    "Und daran anknuepfend...",
    "Stimmt, und weiterhin...",
    "Das geht in die gleiche Richtung.",
    "Auch wichtig dabei ist...",
    "Dazu kommt noch...",
    "Genauso sehe ich das auch.",
    "Und um das zu verstaerken...",
    "Ergaenzend moechte ich hinzufuegen...",
    "Genau in die Richtung...",
    "Das unterstuetzt meinen Punkt.",
    "Und weiterhin gilt...",
    "Das ist ein gutes Argument dafuer.",
    "In die gleiche Kerbe schlagend...",
    "Bestaetigt auch meine Erfahrung.",
    "Und darueber hinaus...",
    "Deshalb denke ich...",
    "Entsprechend sehe ich das auch.",
    "Und folglich...",
  ],
},

"ATO_TOPIC_SWITCH_TECH": {
  "positive": [
    "Ich war im Open-Air-Kino.",
    "Ich habe die App deployed.",
    "Die Webseite ist online.",
    "Ich installiere gerade Node.js.",
    "Wir haben eine Releaseparty gemacht.",
    "Das Framework-Design-Tool ist fertig.",
    "Ich habe was auf GitHub gepusht.",
    "Der Build laeuft gerade durch.",
    "Hast du den neuen Film gesehen?",
    "Ich habe das Deployment fertig.",
    "Die Release-Notes sind draussen.",
    "Claude hat mir beim Coden geholfen.",
    "Ich war gestern im Kino, richtig guter Film.",
    "Das neue Framework ist echt stark.",
    "Ich muss noch die Seite updaten.",
    "GitHub Actions laufen jetzt durch.",
    "Ich installiere gerade ein Update.",
    "Der Release-Termin ist naechste Woche.",
    "Ich hab die App fertig programmiert.",
    "Wir waren gestern in einem Open-Air-Konzert.",
    "Der Build ist fehlgeschlagen, ich muss debuggen.",
    "Die Webseite braucht ein Redesign.",
    "Ich hab einen Film auf Netflix geschaut.",
    "Das Deployment auf den Server hat geklappt.",
    "Claude hat einen Bug gefunden.",
    "Ich installiere gerade die Dependencies.",
    "Das Release-Event war cool.",
    "Node.js Version 20 ist jetzt Standard.",
    "Ich war im Open-Air-Theater.",
    "GitHub Copilot macht Vorschlaege.",
    "Die neue Seite ist live.",
    "Ich build gerade das Projekt.",
    "Der Film war richtig spannend.",
    "Ich habe die App im Store veroeffentlicht.",
    "Das Framework-Update bringt neue Features.",
    "Wir hatten eine Releaseparty im Buero.",
    "Ich installiere gerade Python.",
    "Die Webseite laed schneller jetzt.",
    "GitHub Discussions nutze ich jetzt auch.",
    "Der Kino-Abend war toll.",
    "Ich hab den Build optimiert.",
    "Claude kann jetzt auch Code-Reviews.",
    "Das Deployment dauert noch etwas.",
    "Die Release-Version ist stabil.",
    "Ich war auf einem Open-Air-Festival.",
    "Node.js Modules sind installiert.",
    "Die neue Seite sieht gut aus.",
    "Ich hab einen Film empfohlen bekommen.",
    "Das App-Design ist ueberarbeitet.",
    "Wir planen eine Releaseparty fuer Freitag.",
  ],
  "negative": [
    "Ich fuehle mich gerade einsam.",
    "Wir muessen ueber unsere Beziehung reden.",
    "Ich habe Angst, dass wir auseinanderdriften.",
    "Meine Gefuehle fuer dich sind stark.",
    "Ich bin verletzt von dem, was passiert ist.",
    "Wir brauchen mehr Zeit fuereinander.",
    "Ich fuehle mich unverstanden.",
    "Das belastet mich emotional.",
    "Ich moechte ueber meine Aengste reden.",
    "Wir muessen ehrlich zueinander sein.",
    "Ich vermisse die Naehe zwischen uns.",
    "Das Gespraech hat mich aufgewaehlt.",
    "Ich brauche deine Unterstuetzung gerade.",
    "Meine Sorgen werden groesser.",
    "Ich fuehle mich in der Beziehung unsicher.",
    "Das geht mir wirklich nahe.",
    "Ich moechte ueber unsere Zukunft reden.",
    "Meine Emotionen sind gerade intensiv.",
    "Ich brauche Trost.",
    "Das hat mich tief getroffen.",
    "Ich fuehle mich ueberfordert mit meinen Gefuehlen.",
    "Wir sollten ueber unsere Erwartungen sprechen.",
    "Ich bin emotional erschoepft.",
    "Das Thema belastet unsere Beziehung.",
    "Ich moechte mich dir oeffnen.",
  ],
},

"ATO_TRACTION_EVIDENCE": {
  "positive": [
    "Wir sehen 20% MRR-Wachstum pro Monat.",
    "Pilotkunden berichten 90% Retention.",
    "Monatliches Wachstum liegt bei 18%.",
    "Churn gesunken auf 3%.",
    "Retention ueber 85% in den letzten drei Monaten.",
    "Die Conversion-Rate ist auf 12% gestiegen.",
    "Wachstum von 25% gegenueber dem Vorquartal.",
    "Wir haben 500 zahlende Kunden.",
    "Die Demo-Anfragen haben sich verdoppelt.",
    "NPS liegt bei 72.",
    "YoY-Wachstum von 180%.",
    "Pilot-Feedback: 4.8 von 5 Sternen.",
    "Referenzquote bei 40% der Kunden.",
    "+35% Wachstum im letzten Quartal.",
    "Churn unter 2% seit sechs Monaten.",
    "Retention steigt kontinuierlich, jetzt bei 92%.",
    "Monatliche Wachstumsrate: 15%.",
    "Wir gewinnen 50 neue Kunden pro Woche.",
    "Das Wachstum ist organisch, ohne bezahlte Werbung.",
    "Demo-to-Close-Rate bei 35%.",
    "Pilotkunden verlangern alle ihren Vertrag.",
    "MRR hat die 100K-Marke geknackt.",
    "+28% Wachstum seit dem Relaunch.",
    "Kundenbindung liegt bei ueber 88%.",
    "Churn-Rate: historisch niedrig bei 1.5%.",
    "Retention verbessert sich Monat fuer Monat.",
    "Wir haben 20 Referenzkunden.",
    "Wachstumsrate uebersteigt 30% monatlich.",
    "Die Pilotphase zeigt 95% Zufriedenheit.",
    "YoY-Revenue-Growth: +220%.",
    "Jeder dritte Kunde kommt ueber Empfehlung.",
    "Die Conversion hat sich in drei Monaten verdreifacht.",
    "Unser NRR liegt bei 130%.",
    "Churn lag letzten Monat bei nur 0.8%.",
    "Retention der Enterprise-Kunden: 97%.",
    "Wachstum beschleunigt sich: 22% diesen Monat.",
    "Pilotergebnisse uebertreffen unsere Erwartungen.",
    "MRR-Wachstum: +40% in Q3.",
    "Kundenzufriedenheit bei 9.2 von 10.",
    "Referenzprogramm bringt 30% der Neukunden.",
    "+15% Wachstum trotz saisonaler Delle.",
    "Churn sinkt seit fuenf Monaten in Folge.",
    "Retention: staerkstes Quartal bisher.",
    "Demo-Anfragen: +60% gegenueber Vormonat.",
    "Monatliches Wachstum stabil bei ueber 20%.",
    "Pilot-Kunden zeigen 3x hoehere Nutzung als erwartet.",
    "Wir haben 100 aktive Nutzer pro Tag.",
    "Wachstum von 10% im ersten Monat nach Launch.",
    "Retention nach 90 Tagen: 80%.",
    "Die Wachstumszahlen sprechen fuer sich.",
  ],
  "negative": [
    "Wir glauben an das Produkt.",
    "Das Team ist motiviert.",
    "Unser Markt ist gross.",
    "Wir haben eine Vision.",
    "Das Produkt hat Potenzial.",
    "Wir arbeiten hart daran.",
    "Die Idee ueberzeugt.",
    "Wir sind zuversichtlich.",
    "Der Markt waechst allgemein.",
    "Unsere Technologie ist innovativ.",
    "Wir haben gutes Feedback bekommen.",
    "Das Team ist erfahren.",
    "Wir planen gross.",
    "Die Nachfrage ist da.",
    "Unser Ansatz ist einzigartig.",
    "Wir haben einen Plan.",
    "Das Produkt ist fast fertig.",
    "Wir erwarten Wachstum.",
    "Die Pipeline ist vielversprechend.",
    "Unser Pitch ueberzeugt Investoren.",
    "Wir sehen viel Interesse.",
    "Das Timing ist gut.",
    "Wir haben die richtigen Leute.",
    "Der Markt wartet darauf.",
    "Unsere Strategie ist durchdacht.",
  ],
},

"ATO_TREMOLO_VOICE": {
  "positive": [
    "[Stimmzittern erkannt]",
    "[Emotionale Bewegung in der Stimme]",
    "[Vibrato in der Sprechstimme]",
    "[Unsichere Stimmfuehrung]",
    "[Tremolo bei intensiver Emotion]",
    "[Stimme zittert hoerbar]",
    "[Emotionales Beben in der Stimme]",
    "[Brueche in der Stimmfuehrung]",
    "[Stockende, zitternde Stimme]",
    "[Stimmliche Unsicherheit spuerbar]",
    "[Vibrato verstaerkt sich bei diesem Thema]",
    "[Emotionale Stimmschwankung]",
    "[Zittern in der Stimme bei Erwaehnung des Themas]",
    "[Tremolo-Effekt beim Sprechen]",
    "[Stimme wird bruchig]",
    "[Deutliches Stimmzittern]",
    "[Emotionale Modulation in der Stimme]",
    "[Vibrato bei leiser Stimme]",
    "[Unsichere Tonlage]",
    "[Stimme bricht fast]",
    "[Hoerbares Zittern bei emotionalen Inhalten]",
    "[Tremolo verstaerkt sich]",
    "[Stimmfuehrung wird instabil]",
    "[Emotionales Vibrato]",
    "[Bruchige Stimme bei schwierigem Thema]",
    "[Stimme zittert beim Erinnern]",
    "[Wahrnehmbare Stimmunsicherheit]",
    "[Stimmtremolo bei Trauer]",
    "[Vibrato deutet auf Nervositaet]",
    "[Stimme wird zitternd]",
    "[Emotionale Stimme mit Tremolo-Effekt]",
    "[Stimmzittern bei Konfrontation]",
    "[Bruchige, unsichere Stimmfuehrung]",
    "[Vibrato im Redefluss]",
    "[Stimme zittert leicht]",
    "[Emotionale Instabilitaet in der Stimme]",
    "[Tremolo bei erhoehter Aufregung]",
    "[Stimmbeben waehrend der Aeusserung]",
    "[Zittern im Stimmansatz]",
    "[Emotionale Schwingung in der Stimme]",
    "[Vibrato bei Erinnerung an Vergangenes]",
    "[Stimme wird fragil]",
    "[Tremolo bei Angst]",
    "[Stimme zittert vor Wut]",
    "[Bruchige Stimme vor Ruehrung]",
    "[Stimmzittern bei Unsicherheit]",
    "[Vibrato bei innerer Anspannung]",
    "[Emotionale Stimmschwingung hoerbar]",
    "[Tremolo deutet auf tiefe Betroffenheit]",
    "[Stimme zittert unkontrolliert]",
  ],
  "negative": [
    "Ich denke, wir sollten das sachlich betrachten.",
    "Mir geht es gut, danke der Nachfrage.",
    "Das ist ein interessanter Gedanke.",
    "Ich bin gerade entspannt.",
    "Alles in Ordnung bei mir.",
    "Ich fuehle mich heute ruhig und gelassen.",
    "Das ueberrascht mich, aber es ist okay.",
    "[Klare, stabile Stimmfuehrung]",
    "[Ruhige und gleichmaessige Stimme]",
    "[Fester Tonfall]",
    "[Kontrollierte Stimme]",
    "[Gleichmaessige Lautstaerke und Tonhoehe]",
    "Die Praesentation lief gut.",
    "Ich bin zufrieden mit dem Ergebnis.",
    "[Selbstsichere Stimmfuehrung]",
    "[Kein Zittern erkennbar]",
    "Erzaehl mir mehr darueber.",
    "Das klingt nachvollziehbar.",
    "[Warme, ruhige Stimme]",
    "Ich hoere dir aufmerksam zu.",
    "[Stabile Intonation]",
    "Wir finden eine Loesung.",
    "[Klarer, fester Stimmansatz]",
    "Das verstehe ich.",
    "[Gleichmaessiger Redefluss]",
  ],
},

"ATO_TRIBAL_BONDS": {
  "positive": [
    "Unser Stamm haelt zusammen.",
    "Alte Traditionen muessen bewahrt werden.",
    "Eine magische Verbindung zwischen uns.",
    "Clandenken praegt unsere Familie.",
    "Ahnenwissen wird weitergegeben.",
    "In unserem Stamm ist das so ueblich.",
    "Die Tradition verlangt es von uns.",
    "Rituale halten die Gemeinschaft zusammen.",
    "Aberglaube oder nicht, wir halten daran fest.",
    "Unsere Zugehoerigkeit ist tief verwurzelt.",
    "Der Clan erwartet Loyalitaet.",
    "Tradition geht ueber alles.",
    "Das Ritual ist Teil unserer Identitaet.",
    "Magische Verbindungen spuere ich in der Familie.",
    "Stammestraditionen praegen unser Leben.",
    "Ahnenkult gibt uns Halt.",
    "Die Zugehoerigkeit zum Clan definiert mich.",
    "Wir leben nach alten Ritualen.",
    "Die Tradition ist staerker als alles andere.",
    "Unser Stammesdenken bestimmt die Regeln.",
    "Magie verbindet uns ueber Generationen.",
    "Die Clanzugehoerigkeit ist unverhandelbar.",
    "Tradition ist unsere Identitaet.",
    "Rituale geben Struktur und Sicherheit.",
    "Aberglaube hat in unserer Familie seinen Platz.",
    "Die Ahnen wachen ueber uns.",
    "Stammesregeln gelten fuer alle.",
    "Die magische Kraft der Tradition.",
    "Clan-Treffen sind heilig.",
    "Unsere Traditionen sind uralt.",
    "Rituale markieren die wichtigen Momente.",
    "Zugehoerigkeit ist das Hoechste.",
    "Der Stamm schuetzt seine Mitglieder.",
    "Ahnenwissen ist kostbar.",
    "Die Clan-Bindung ist unzerbrechlich.",
    "Tradition wird bei uns grossgeschrieben.",
    "Magie ist Teil unserer Kultur.",
    "Rituale verbinden die Generationen.",
    "In unserem Stamm hilft man einander.",
    "Die alten Traditionen leben weiter.",
    "Aberglaube oder Weisheit, wer weiss das schon.",
    "Zugehoerigkeit zum Clan ist Pflicht.",
    "Stammesrituale pregen die Kindheit.",
    "Magische Traditionen werden weitergegeben.",
    "Der Clan ist die Familie.",
    "Tradition schafft Bindung.",
    "Rituale sind unser Anker.",
    "Ahnenkult gehoert zu uns.",
    "Die Zugehoerigkeit gibt mir Kraft.",
    "Im Stamm ist niemand allein.",
  ],
  "negative": [
    "Ich bin ein individueller Mensch.",
    "Jeder entscheidet fuer sich selbst.",
    "Tradition ist mir nicht so wichtig.",
    "Ich denke unabhaengig.",
    "Gruppendenken liegt mir nicht.",
    "Ich folge meinem eigenen Weg.",
    "Rituale interessieren mich nicht besonders.",
    "Ich bin nicht aberglaeuisch.",
    "Zugehoerigkeit hin oder her, ich bleibe bei meiner Meinung.",
    "Ich definiere mich nicht ueber eine Gruppe.",
    "Tradition ist keine Entschuldigung.",
    "Ich hinterfrage alles.",
    "Clan-Denken finde ich einschraenkend.",
    "Ich mache mein eigenes Ding.",
    "Magie gibt es nicht.",
    "Ich brauche keine Gruppe, um mich sicher zu fuehlen.",
    "Rituale sind mir egal.",
    "Ich denke rational und unabhaengig.",
    "Zugehoerigkeit ist mir nicht so wichtig.",
    "Ich gehe meinen eigenen Weg, ohne Stamm.",
    "Tradition kann man auch hinterfragen.",
    "Ich bin kein Gruppentier.",
    "Aberglaube hat keinen Platz in meinem Leben.",
    "Ich definiere mich selbst, nicht durch andere.",
    "Unabhaengigkeit ist mir wichtiger als Zugehoerigkeit.",
  ],
},

"ATO_TRUST_DEFICIT_STATEMENT": {
  "positive": [
    "Mein Misstrauen kommt nicht aus dem Nichts.",
    "Ich brauche Beweise, sonst glaube ich das nicht.",
    "Ich fuehle mich absichtlich im Unklaren gelassen.",
    "Du verheimlichst mir Dinge.",
    "Es wirkt, als verschweigst du mir etwas.",
    "Warum werde ich nicht einbezogen?",
    "Mir fehlt die Sicherheit, dass du ehrlich bist.",
    "Ich misstraue deinen Absichten.",
    "Du laesst mich bewusst im Unklaren.",
    "Hinter meinem Ruecken ist irgendetwas passiert.",
    "Ich glaube dir nicht mehr ohne Beweis.",
    "Du verheimlichst mir etwas Wichtiges.",
    "Mein Misstrauen waechst mit jedem Schweigen.",
    "Ich fuehle mich im Unklaren gelassen.",
    "Vieles verschweigst du mir.",
    "Ich werde nicht einbezogen in Entscheidungen.",
    "Beweis mir, dass das stimmt.",
    "Ich misstraue dir, und das hat Gruende.",
    "Du hast hinter meinem Ruecken gehandelt.",
    "Verheimlichen ist fuer mich ein Vertrauensbruch.",
    "Ich fuehle Misstrauen, wenn du ausweichst.",
    "Etwas verschweigst du, ich spuere das.",
    "Ich brauche Transparenz, keine Geheimnisse.",
    "Du laesst mich absichtlich im Dunkeln.",
    "Mein Vertrauen ist erschuettert.",
    "Ich glaube nicht, dass du ehrlich warst.",
    "Es fuehlt sich an, als ob du etwas verbirgst.",
    "Ich misstraue der Situation.",
    "Du hast mich nicht einbezogen.",
    "Beweise deine Ehrlichkeit.",
    "Ich fuehle mich belogen.",
    "Im Unklaren zu sein macht mich nervoes.",
    "Vieles bleibt verschwiegen zwischen uns.",
    "Hinter meinem Ruecken passieren Dinge.",
    "Mein Misstrauen hat gute Gruende.",
    "Du verheimlichst mehr, als du zugibst.",
    "Ich frage mich, was du noch verschweigst.",
    "Beweise sind das Einzige, was mich beruhigt.",
    "Ich fuehle mich bewusst ausgeschlossen.",
    "Du bist nicht transparent mit mir.",
    "Ich misstraue deinen Worten.",
    "Absichtlich im Unklaren gehalten, so fuehlt es sich an.",
    "Warum verschweigst du mir das?",
    "Mein Misstrauen ist berechtigt.",
    "Ich brauche Beweise, nicht Worte.",
    "Du verheimlichst mir die Wahrheit.",
    "Hinter meinem Ruecken laufen Dinge.",
    "Ich werde bewusst aussen vor gelassen.",
    "Mein Misstrauen ist groesser als mein Vertrauen.",
    "Du bist nicht ehrlich zu mir.",
  ],
  "negative": [
    "Ich vertraue dir voll und ganz.",
    "Du bist ehrlich zu mir, das weiss ich.",
    "Ich glaube dir.",
    "Transparenz ist deine Staerke.",
    "Ich fuehle mich einbezogen.",
    "Du hast nichts zu verbergen.",
    "Ich vertraue deinen Absichten.",
    "Du bist offen mit mir.",
    "Mein Vertrauen in dich ist unerschuetterlich.",
    "Du verschweigst mir nichts.",
    "Ich weiss, dass du ehrlich bist.",
    "Du beziehst mich immer mit ein.",
    "Ich habe keinen Grund zu misstrauen.",
    "Du bist transparent in allem.",
    "Vertrauen ist das Fundament zwischen uns.",
    "Du bist ein offener Mensch.",
    "Ich glaube an deine guten Absichten.",
    "Du sagst mir immer die Wahrheit.",
    "Mein Vertrauen in dich ist gross.",
    "Du haeltst mich auf dem Laufenden.",
    "Ich fuehle mich sicher bei dir.",
    "Du verbirgst nichts vor mir.",
    "Ehrlichkeit ist zwischen uns selbstverstaendlich.",
    "Ich vertraue deinem Wort.",
    "Du bist mein sicherer Hafen.",
  ],
},

"ATO_TRUST_PHRASE": {
  "positive": [
    "Verlass dich auf mich.",
    "Ich vertrau dir.",
    "Du kannst mir glauben.",
    "Ich halte Wort.",
    "Ehrlich, das meine ich so.",
    "Du kannst dich auf mich verlassen.",
    "Ich bin da fuer dich, wir schaffen das.",
    "Danke dir, fuehle mich gesehen.",
    "Gemeinsam kriegen wir das hin.",
    "Ich hoer dir zu, okay?",
    "Du kannst mir vertrauen, zu 100 Prozent.",
    "Ich verspreche dir, ich halte Wort.",
    "Ehrlich gesagt, ich stehe hinter dir.",
    "Verlass dich drauf, das wird schon.",
    "Ich bin ehrlich zu dir, immer.",
    "Du kannst mir glauben, da hat sich nichts geaendert.",
    "Mein Wort gilt.",
    "Vertrau mir, ich enttaeusche dich nicht.",
    "Ich bin zuverlaessig, das weisst du.",
    "Auf mich ist Verlass.",
    "Ehrlich, ich meine jedes Wort.",
    "Du kannst dich auf mein Wort verlassen.",
    "Ich verspreche es dir.",
    "Vertrauen ist mir wichtig zwischen uns.",
    "Glaub mir, das schaffen wir.",
    "Ich bin treu und ehrlich.",
    "Du kannst mir blind vertrauen.",
    "Ich stehe zu dem, was ich sage.",
    "Verlass dich auf mein Versprechen.",
    "Ehrlich und direkt, so bin ich.",
    "Du kannst mir alles anvertrauen.",
    "Ich halte zu dir, egal was kommt.",
    "Vertrau mir einfach.",
    "Mein Wort ist mein Wort.",
    "Du kannst mir glauben, das ist die Wahrheit.",
    "Ich bin ehrlich, auch wenn es schwer ist.",
    "Auf mich kannst du bauen.",
    "Verlass dich drauf, ich bin da.",
    "Ehrlich gesprochen, du bist mir wichtig.",
    "Du kannst mir vertrauen, ich stehe zu dir.",
    "Ich verspreche Zuverlaessigkeit.",
    "Glaub mir, ich meine es ernst.",
    "Vertrau mir, das kommt von Herzen.",
    "Ich bin ein Mann bzw. eine Frau meines Wortes.",
    "Du kannst dich hundertprozentig auf mich verlassen.",
    "Ehrlich, ich wuerde dich nie belogen.",
    "Verlass dich auf meine Treue.",
    "Mein Versprechen steht.",
    "Du kannst mir vertrauen, das hat sich bewaehrt.",
    "Ich bin aufrichtig, das weisst du.",
  ],
  "negative": [
    "Kannst du mir das Salz reichen?",
    "Der Termin ist um 14 Uhr.",
    "Ich war gestern einkaufen.",
    "Das Wetter soll morgen besser werden.",
    "Hast du die E-Mail gelesen?",
    "Ich muss noch tanken.",
    "Die Besprechung ist im Konferenzraum.",
    "Der Zug hat 10 Minuten Verspaetung.",
    "Ich kaufe nachher Milch.",
    "Die Heizung ist kaputt.",
    "Der Paketbote war schon da.",
    "Morgen ist Muellabfuhr.",
    "Ich brauche neue Schuhe.",
    "Das Restaurant hat heute geschlossen.",
    "Der Akku meines Handys ist leer.",
    "Ich habe den Schlussel vergessen.",
    "Das Meeting wurde verschoben.",
    "Ich fahre morgen frueh los.",
    "Der Supermarkt hat bis 22 Uhr offen.",
    "Ich habe die Wasche aufgehaengt.",
    "Das Auto muss zur Inspektion.",
    "Der Parkplatz war voll.",
    "Ich muss die Rechnung ueberweisen.",
    "Das Paket kommt morgen.",
    "Ich esse heute Abend alleine.",
  ],
},

"ATO_TRUTH_FEEL": {
  "positive": [
    "Dieser Satz fuehlt sich wahr an, auch ohne Zahlen.",
    "Es bleibt fuer mich spuerbar wahr, obwohl wir es nicht messen.",
    "Das fuehlt sich echt an, obwohl es kein Proof ist.",
    "Ich folge dem, weil es sich wahr anfuehlt.",
    "Wahr ohne Definition reicht mir in diesem Rahmen.",
    "Das Narrativ fuehlt sich wahr an, noch bevor wir es erklaeren.",
    "Fuer mich ist das spuerbar wahr, jenseits der Daten.",
    "Es fuehlt sich echt an, wir muessen es nicht beweisen.",
    "Diese Erinnerung bleibt spuerbar wahr, auch ohne Zeugen.",
    "Das fuehlt sich wahr an, tief in mir.",
    "Es ist spuerbar wahr, auch wenn andere zweifeln.",
    "Fuer mich fuehlt sich das echt an, ohne Frage.",
    "Das ist wahr ohne Definition, ich spuere es.",
    "Es fuehlt sich an wie eine tiefe Wahrheit.",
    "Das ist spuerbar wahr fuer mich.",
    "Diese Erkenntnis fuehlt sich wahr an.",
    "Es ist echt, ich fuehle es.",
    "Das bleibt spuerbar wahr, auch im Rueckblick.",
    "Es fuehlt sich wahr an, das reicht mir.",
    "Fuer mich ist das eine gefuehlte Wahrheit.",
    "Das ist wahr ohne Beweis, einfach spuerbar.",
    "Es fuehlt sich echt an in meinem Koerper.",
    "Diese Geschichte fuehlt sich wahr an.",
    "Spuerbar wahr, das sagt mir mein Bauchgefuehl.",
    "Das fuehlt sich echt an, auch wenn es irrational klingt.",
    "Es ist wahr ohne Erklaerung.",
    "Fuer mich ist das spuerbar wahr, Punkt.",
    "Das fuehlt sich an wie die Wahrheit.",
    "Es ist echt, ich weiss es einfach.",
    "Spuerbar wahr, auch wenn die Logik fehlt.",
    "Das bleibt fuer mich wahr, ohne Analyse.",
    "Es fuehlt sich echt an, und das zaehlt fuer mich.",
    "Diese Verbindung ist spuerbar wahr.",
    "Fuer mich hat sich das immer wahr angefuehlt.",
    "Das ist wahr, ich fuehle es im Herzen.",
    "Spuerbar echt, auch ohne Worte.",
    "Es fuehlt sich wahr an, wie eine Gewissheit.",
    "Das ist fuer mich eine erlebte Wahrheit.",
    "Echt und wahr, auch wenn nicht beweisbar.",
    "Es fuehlt sich spuerbar wahr an.",
    "Diese Wahrheit braucht keine Begruendung.",
    "Fuer mich ist es echt, fertig.",
    "Das fuehlt sich wahr an, auf einer tiefen Ebene.",
    "Spuerbar wahr, wie eine innere Stimme.",
    "Es ist echt fuer mich, das genuegt.",
    "Das fuehlt sich wahr an, seit Jahren schon.",
    "Ich spuere die Wahrheit darin.",
    "Das ist echt, mehr brauche ich nicht.",
    "Es fuehlt sich wahr an, auch morgen noch.",
    "Spuerbar wahr, und das ist genug fuer mich.",
  ],
  "negative": [
    "Das kann man mit Daten belegen.",
    "Dafuer gibt es Beweise.",
    "Das ist wissenschaftlich erwiesen.",
    "Die Statistik zeigt es deutlich.",
    "Fakten sprechen eine klare Sprache.",
    "Das ist objektiv nachweisbar.",
    "Die Studie belegt das eindeutig.",
    "Messbare Ergebnisse bestaetigen das.",
    "Das ist rational begruendbar.",
    "Die Evidenz ist eindeutig.",
    "Das laesst sich mathematisch ableiten.",
    "Die Zahlen luegen nicht.",
    "Empirisch gesichert.",
    "Logisch nachvollziehbar.",
    "Das ist falsifizierbar und geprueft.",
    "Die Daten untermauern die These.",
    "Reproduzierbare Ergebnisse.",
    "Wissenschaftlich fundiert.",
    "Objektivitaet ist hier entscheidend.",
    "Die Analyse ist eindeutig.",
    "Messbar, pruefbar, belegbar.",
    "Die Forschung zeigt klar.",
    "Das ist keine Meinung, sondern Fakt.",
    "Evidenzbasiert.",
    "Daten statt Bauchgefuehl.",
  ],
},

"ATO_UFF_DIFFICULT": {
  "positive": [
    "Uff, morgen ist schwierig...",
    "Das wird echt kompliziert bei mir.",
    "Uff, das ist nicht so einfach gerade.",
    "Puh, schwierig schwierig...",
    "Uff, muss ich erstmal schauen.",
    "Das ist echt schwierig, weiss ich nicht.",
    "Uff, das wird eng mit dem Timing.",
    "Ist nicht so einfach, wie es klingt.",
    "Uff, da muss ich nachdenken.",
    "Das wird kompliziert, glaub mir.",
    "Uff, keine Ahnung, wie wir das loesen.",
    "Ist echt schwierig gerade bei mir.",
    "Uff, ich weiss nicht, ob das klappt.",
    "Das ist nicht so einfach mit den Kindern.",
    "Uff, der Zeitplan ist echt schwierig.",
    "Wird kompliziert, wenn ich ehrlich bin.",
    "Uff, das kriege ich kaum hin.",
    "Schwierig, schwierig, so kurzfristig.",
    "Uff, das ueberfordert mich gerade.",
    "Ist echt nicht so einfach, weisst du.",
    "Uff, da sehe ich schwarz.",
    "Das wird kompliziert mit dem Budget.",
    "Uff, ganz schoen viel gerade.",
    "Ist schwierig fuer mich, das zuzugeben.",
    "Uff, ich bin gerade ueberfordert.",
    "Das ist echt schwierig zu erklaeren.",
    "Uff, wo soll ich anfangen?",
    "Wird nicht so einfach, das durchzuziehen.",
    "Uff, die Lage ist schwierig.",
    "Das ist kompliziert, keine schnelle Loesung.",
    "Uff, wenn das mal so einfach waere.",
    "Ist schwierig, da einen Kompromiss zu finden.",
    "Uff, ehrlich gesagt keine Ahnung.",
    "Das wird echt schwierig mit der Planung.",
    "Uff, ich stecke fest.",
    "Nicht so einfach, wie du denkst.",
    "Uff, das macht mir Sorgen.",
    "Ist schwierig gerade, beziehungsmaessig.",
    "Uff, da hab ich kein gutes Gefuehl.",
    "Das wird kompliziert, wenn wir warten.",
    "Uff, ich sehe das kritisch.",
    "Schwierig, da eine Loesung zu finden.",
    "Uff, ganz schoen verfahren, die Situation.",
    "Ist echt nicht einfach, das zu akzeptieren.",
    "Uff, mir wird schwindelig bei dem Gedanken.",
    "Wird schwierig, das mit dem Chef zu klaeren.",
    "Uff, ich brauche erstmal eine Pause.",
    "Das ist kompliziert, weil vieles zusammenhaengt.",
    "Uff, das passt mir gerade gar nicht.",
    "Ist nicht so einfach, einfach Ja zu sagen.",
  ],
  "negative": [
    "Das schaffen wir leicht.",
    "Kein Problem, mache ich gerne.",
    "Das ist machbar, klar.",
    "Einfach, lass uns starten.",
    "Kein Thema, das kriegen wir hin.",
    "Laeuft, alles kein Problem.",
    "Das ist ueberhaupt nicht schwierig.",
    "Easy, machen wir.",
    "Das loesung ist offensichtlich.",
    "Klar, das geht schnell.",
    "Kein Ding, ich kuemmere mich darum.",
    "Simpel, brauchen wir nicht lange fuer.",
    "Das ist unkompliziert.",
    "Ja, super, mach ich.",
    "Ganz einfach zu loesen.",
    "Klar, verstanden, wird gemacht.",
    "Das ist ein Kinderspiel.",
    "Kein Aufwand, schnell erledigt.",
    "Laesst sich leicht umsetzen.",
    "Null Problemo.",
    "Das schaffenwir mit links.",
    "Entspannt, alles gut.",
    "Gar kein Problem damit.",
    "Mache ich sofort.",
    "Klar, das geht.",
  ],
},

"ATO_UNCERTAINTY": {
  "positive": [
    "Ich bin mir nicht sicher, wie ich damit umgehen soll.",
    "Vielleicht sollten wir etwas anderes versuchen.",
    "Es ist mir unklar, was das Richtige ist.",
    "Ich weiss nicht, was die richtige Antwort ist.",
    "Vielleicht gibt es einen anderen Weg.",
    "Ich bin unsicher, ob das stimmt.",
    "Weiss nicht genau, was ich davon halten soll.",
    "Vielleicht irre ich mich auch.",
    "Es ist unklar, was passiert.",
    "Ich bin mir nicht sicher, ob das passt.",
    "Vielleicht habe ich das falsch verstanden.",
    "Ich weiss nicht, wie es weitergeht.",
    "Vielleicht brauchenwir mehr Informationen.",
    "Es ist unklar, wer zustaendig ist.",
    "Ich bin mir nicht sicher, was du meinst.",
    "Vielleicht taeusche ich mich.",
    "Ich weiss nicht, ob das der richtige Zeitpunkt ist.",
    "Es ist mir unklar, wie das funktioniert.",
    "Bin mir nicht sicher, ob ich das schaffe.",
    "Vielleicht habe ich Unrecht.",
    "Ich weiss nicht genau.",
    "Vielleicht ist es besser, zu warten.",
    "Es ist unklar, was als Naechstes kommt.",
    "Bin mir unsicher, ehrlich gesagt.",
    "Vielleicht sehen wir das morgen klarer.",
    "Ich weiss nicht, wie ich reagieren soll.",
    "Vielleicht gibt es da einen Irrtum.",
    "Es ist mir nicht klar, was du willst.",
    "Ich bin mir unsicher ueber meine Entscheidung.",
    "Vielleicht ist das zu frueh.",
    "Weiss nicht, ob ich dem vertrauen kann.",
    "Es ist unklar, wo wir stehen.",
    "Bin mir nicht sicher, ob das Sinn macht.",
    "Vielleicht sollte ich nochmal drueber schlafen.",
    "Ich weiss es wirklich nicht.",
    "Es ist mir unklar, was das bedeutet.",
    "Vielleicht uebertreibe ich auch.",
    "Bin mir nicht sicher, wie du das siehst.",
    "Ich weiss nicht, ob das die Loesung ist.",
    "Vielleicht brauche ich Rat.",
    "Es ist unklar, was erwartet wird.",
    "Ich bin mir unsicher ueber alles gerade.",
    "Vielleicht verstehe ich das falsch.",
    "Weiss nicht, was ich sagen soll.",
    "Es ist mir nicht klar, wohin das fuehrt.",
    "Bin mir unsicher, ob ich richtig liege.",
    "Vielleicht ist das alles ein Missverstaendnis.",
    "Ich weiss nicht, ob ich bereit bin.",
    "Es ist unklar, ob das funktioniert.",
    "Vielleicht muessen wir nochmal reden.",
  ],
  "negative": [
    "Ich bin mir absolut sicher.",
    "Das steht fest.",
    "Ganz klar, so machen wir das.",
    "Ich weiss genau, was ich will.",
    "Da gibt es keinen Zweifel.",
    "Definitiv, das ist der richtige Weg.",
    "Ich bin ueberzeugt davon.",
    "Das ist eindeutig.",
    "Ohne Zweifel.",
    "Ich bin mir hundertprozentig sicher.",
    "Das ist glasklar.",
    "Ja, ganz sicher.",
    "Ich habe keinen Zweifel.",
    "Meine Entscheidung steht fest.",
    "Das ist unbestreitbar.",
    "Ich weiss es mit Sicherheit.",
    "Da bin ich mir ganz sicher.",
    "Eindeutig Ja.",
    "Das ist nicht verhandelbar.",
    "Ich bin felsenfest ueberzeugt.",
    "Kein Zweifel moeglich.",
    "Das ist die einzige Loesung.",
    "Definitiv.",
    "Ich bin mir absolut im Klaren.",
    "Da gibt es nichts zu diskutieren.",
  ],
},

"ATO_UNCERTAINTY_PHRASE": {
  "positive": [
    "Vielleicht mache ich das spaeter.",
    "Mal sehen, ob das klappt.",
    "Ich weiss nicht genau, ob ich dabei bin.",
    "Koennte sein, dass ich nicht schaffe.",
    "Bin mir da gerade nicht sicher.",
    "Vielleicht aendere ich meine Meinung.",
    "Mal sehen, wie es laeuft.",
    "Weiss nicht, ob das eine gute Idee ist.",
    "Koennte sein, dass ich recht habe.",
    "Bin mir nicht sicher, ob ich das will.",
    "Vielleicht warte ich noch.",
    "Mal sehen, was morgen bringt.",
    "Ich weiss nicht, ob ich kommen kann.",
    "Koennte sein, dass sich alles aendert.",
    "Bin mir unsicher, ob das passt.",
    "Vielleicht ist es besser so.",
    "Mal sehen, vielleicht sage ich ja.",
    "Weiss nicht, wie ich das finde.",
    "Koennte sein, dass ich zu spaet komme.",
    "Bin mir nicht sicher, ob das stimmt.",
    "Vielleicht gehe ich doch hin.",
    "Mal sehen, ob ich Lust habe.",
    "Ich weiss nicht, was ich davon halten soll.",
    "Koennte sein, dass wir uns vertan haben.",
    "Bin mir gerade echt unsicher.",
    "Vielleicht war das ein Fehler.",
    "Mal sehen, ich entscheide spontan.",
    "Weiss nicht, ob ich das verdient habe.",
    "Koennte sein, vielleicht auch nicht.",
    "Bin mir nicht sicher, wie du das meinst.",
    "Vielleicht brauche ich mehr Zeit.",
    "Mal sehen, was das Leben bringt.",
    "Ich weiss es einfach nicht.",
    "Koennte sein, ich muss nachdenken.",
    "Bin mir unsicher, ob wir das richtig machen.",
    "Vielleicht aendert sich das noch.",
    "Mal sehen, keine Ahnung ehrlich.",
    "Weiss nicht, ob ich das kann.",
    "Koennte sein, dass ich mich irre.",
    "Bin mir nicht sicher, ob es richtig war.",
    "Vielleicht sollte ich loslassen.",
    "Mal sehen, ob sich eine Tuer oeffnet.",
    "Ich weiss nicht, was ich fuehle.",
    "Koennte sein, dass das nur Angst ist.",
    "Bin mir nicht sicher, ob ich bereit bin.",
    "Vielleicht verstehen wir uns falsch.",
    "Mal sehen, wie die naechste Woche wird.",
    "Weiss nicht, ob ich dem gewachsen bin.",
    "Koennte sein, dass du recht hast.",
    "Bin mir nicht sicher, und das ist okay.",
  ],
  "negative": [
    "Ich bin mir ganz sicher.",
    "Das steht fuer mich fest.",
    "Ganz klar, ich bin dabei.",
    "Definitiv, das mache ich.",
    "Keine Frage, so ist es.",
    "Ich bin entschlossen.",
    "Hundertprozentig ja.",
    "Das ist meine feste Ueberzeugung.",
    "Darauf kannst du dich verlassen.",
    "Ich bin mir absolut sicher.",
    "Ja, ohne Zweifel.",
    "Meine Entscheidung ist gefallen.",
    "Da gibt es kein Wenn und Aber.",
    "Ich weiss genau, was ich will.",
    "Eindeutig.",
    "Sicher ist sicher.",
    "Das ist klar.",
    "Ganz bestimmt.",
    "Ohne jede Unsicherheit.",
    "Mein Entschluss steht.",
    "Das ist fuer mich eindeutig.",
    "Ja, auf jeden Fall.",
    "Ich bin fest entschlossen.",
    "Da bin ich mir sicher.",
    "Klares Ja von mir.",
  ],
},

}


def enrich_marker(marker_id: str, data: dict) -> bool:
    fpath = find_file(marker_id)
    if fpath is None:
        print(f"  SKIP {marker_id}: file not found")
        return False

    with open(fpath, "r") as f:
        doc = yaml.load(f)

    if doc is None:
        print(f"  SKIP {marker_id}: empty YAML")
        return False

    # Handle nested markers list
    if "markers" in doc and isinstance(doc["markers"], list):
        for m in doc["markers"]:
            if isinstance(m, dict) and m.get("id") == marker_id:
                if "examples" in m:
                    nested_examples = m["examples"]
                    if isinstance(nested_examples, list):
                        m["examples"] = data.get("positive", data.get("positive_de", []))[:5]

    if "examples" not in doc:
        doc["examples"] = {}

    examples = doc["examples"]

    # Determine key names based on data dict keys
    if "positive_de" in data:
        pos_key = "positive_de"
        neg_key = "negative_de"
    elif "positive_de" in examples:
        pos_key = "positive_de"
        neg_key = "negative_de"
    else:
        pos_key = "positive"
        neg_key = "negative"

    examples[pos_key] = data.get(pos_key, data.get("positive", []))
    examples[neg_key] = data.get(neg_key, data.get("negative", []))

    with open(fpath, "w") as f:
        yaml.dump(doc, f)

    pos_count = len(examples[pos_key])
    neg_count = len(examples[neg_key])
    print(f"  OK {marker_id}: {pos_count} pos + {neg_count} neg ({pos_key}/{neg_key})")
    return True


def main():
    success = 0
    fail = 0
    for marker_id, data in ENRICHMENTS.items():
        ok = enrich_marker(marker_id, data)
        if ok:
            success += 1
        else:
            fail += 1
    print(f"\nDone: {success} enriched, {fail} failed/skipped")


if __name__ == "__main__":
    main()
