#!/usr/bin/env python3
"""Batch enrich ATO markers with examples - Batch 1 (first ~20 markers)."""

import os
import sys
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
yaml.default_flow_style = False

BASE = Path("/Users/benjaminpoersch/Projects/LeanDeep-annotator/build/markers_rated")
DIRS = [BASE / "1_approved" / "ATO", BASE / "2_good" / "ATO"]

def find_file(marker_id):
    for d in DIRS:
        p = d / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None

def get_example_keys(data):
    """Detect whether marker uses positive/negative or positive_de/negative_de."""
    ex = data.get("examples", {})
    if ex is None:
        return None, None
    if "positive_de" in ex:
        return "positive_de", "negative_de"
    return "positive", "negative"

def current_counts(data):
    ex = data.get("examples", {})
    if ex is None:
        return 0, 0
    pk, nk = get_example_keys(data)
    if pk is None:
        return 0, 0
    pos = ex.get(pk, []) or []
    neg = ex.get(nk, []) or []
    return len(pos), len(neg)

def enrich_marker(filepath, new_positives, new_negatives):
    """Add examples to a marker file, reaching target counts."""
    with open(filepath) as f:
        data = yaml.load(f)

    if "examples" not in data or data["examples"] is None:
        data["examples"] = {}

    pk, nk = get_example_keys(data)
    if pk is None:
        pk, nk = "positive", "negative"

    existing_pos = list(data["examples"].get(pk, []) or [])
    existing_neg = list(data["examples"].get(nk, []) or [])

    # Deduplicate by adding only new ones
    pos_set = set(existing_pos)
    neg_set = set(existing_neg)

    for ex in new_positives:
        if ex not in pos_set and len(existing_pos) < 50:
            existing_pos.append(ex)
            pos_set.add(ex)

    for ex in new_negatives:
        if ex not in neg_set and len(existing_neg) < 25:
            existing_neg.append(ex)
            neg_set.add(ex)

    data["examples"][pk] = existing_pos
    data["examples"][nk] = existing_neg

    with open(filepath, "w") as f:
        yaml.dump(data, f)

    return len(existing_pos), len(existing_neg)


# ============================================================
# MARKER EXAMPLES - Batch 1
# ============================================================

EXAMPLES = {
    "ATO_ABANDONMENT_ANXIETY": {
        "positive": [
            "Bitte verlass mich nicht, ich halte das nicht aus.",
            "Du wirst mich irgendwann verlassen, oder?",
            "Ich kann nicht allein sein, das macht mir Angst.",
            "Bleib bei mir, bitte geh nicht weg.",
            "Alle verlassen mich am Ende.",
            "Ich klammere mich an dich, weil ich Angst habe.",
            "Ohne dich bin ich verloren.",
            "Du wirst mich auch noch im Stich lassen.",
            "Ich habe panische Angst, allein zu sein.",
            "Geh nicht, ich brauche dich so sehr.",
            "Jeder, den ich liebe, geht irgendwann.",
            "Ich bin so verzweifelt, wenn du nicht da bist.",
            "Verlass mich nicht, ich flehe dich an.",
            "Die Angst vor dem Verlassenwerden frisst mich auf.",
            "Ich kann einfach nicht allein klarkommen.",
            "Bitte bleib, ich komme ohne dich nicht zurecht.",
            "Wenn du gehst, bricht alles zusammen.",
            "Ich habe solche Angst, dass du mich verlässt.",
            "Niemand bleibt bei mir, alle gehen.",
            "Ich bin so einsam ohne dich.",
            "Du bist der Einzige, den ich habe, geh nicht.",
            "Ich klammere, weil ich Verlustangst habe.",
            "Bitte sag mir, dass du bleibst.",
            "Ich ertrage es nicht, allein gelassen zu werden.",
            "Wenn du weg bist, fühle ich mich verlassen.",
            "Ich brauche die Gewissheit, dass du bleibst.",
            "Die Vorstellung, allein zu sein, macht mich krank.",
        ],
        "negative": [
            "Ich komme gut allein zurecht.",
            "Nimm dir die Zeit, die du brauchst.",
            "Ich freue mich auf einen Abend für mich.",
            "Wir sehen uns dann morgen, kein Problem.",
            "Ich bin gern auch mal allein zu Hause.",
            "Kein Stress, ich beschäftige mich selbst.",
            "Fahr ruhig, ich manage das hier.",
            "Ich habe heute Abend eigene Pläne.",
            "Allein sein ist manchmal ganz schön.",
            "Mach dir keine Sorgen, mir geht es gut.",
            "Ich vertraue darauf, dass wir uns wiedersehen.",
            "Ein bisschen Abstand tut uns beiden gut.",
            "Ich bin unabhängig und das ist okay so.",
            "Genieß deine Reise, ich freue mich für dich.",
            "Wir haben beide unser eigenes Leben.",
            "Ich brauche auch mal Zeit für mich.",
        ],
    },
    "ATO_ABSOLUTIZER": {
        "positive": [
            "Du machst das immer falsch.",
            "Nie kann man sich auf dich verlassen.",
            "Du vergisst ständig alles.",
            "Auf jeden Fall ist das deine Schuld.",
            "Immer bist du der Letzte.",
            "Du hast nie Zeit für mich.",
            "Ständig muss ich alles alleine machen.",
            "Das ist auf jeden Fall nicht akzeptabel.",
            "Du kommst immer zu spät, immer!",
            "Nie hörst du mir richtig zu.",
            "Ständig gibt es Probleme mit dir.",
            "Auf jeden Fall war das ein Fehler.",
            "Immer muss ich mich um alles kümmern.",
            "Nie funktioniert irgendwas bei uns.",
            "Ständig streiten wir uns wegen Kleinigkeiten.",
            "Das ist immer dasselbe Theater mit dir.",
            "Auf jeden Fall muss sich das ändern.",
            "Du bist immer so stur.",
            "Nie nimmst du meine Gefühle ernst.",
            "Ständig kritisierst du mich.",
            "Auf jeden Fall habe ich recht damit.",
            "Immer wieder der gleiche Mist.",
            "Du versprichst immer alles und hältst nie was.",
            "Ständig bist du am Handy.",
            "Nie bist du zufrieden mit dem, was ich tue.",
            "Auf jeden Fall brauchen wir eine Lösung.",
            "Immer willst du das letzte Wort haben.",
            "Nie zeigst du Verständnis.",
            "Ständig redest du dazwischen.",
            "Auf jeden Fall müssen wir darüber reden.",
            "Immer das Gleiche, es ändert sich nie was.",
            "Du bist ständig gereizt.",
            "Auf jeden Fall war das absichtlich.",
            "Nie gibst du einen Fehler zu.",
            "Immer wenn ich was sage, ignorierst du es.",
            "Ständig hast du eine Ausrede parat.",
            "Auf jeden Fall liegt es nicht an mir.",
        ],
        "negative": [
            "Manchmal vergisst du Dinge, das ist menschlich.",
            "Ab und zu haben wir unterschiedliche Meinungen.",
            "Gelegentlich läuft es nicht so rund.",
            "In letzter Zeit war es etwas stressig.",
            "Heute war es anders als sonst.",
            "Vielleicht könnten wir das nächste Mal anders machen.",
            "Das kommt vor, ist nicht schlimm.",
            "Wir haben unterschiedliche Sichtweisen, das ist normal.",
            "Meistens klappt das gut zwischen uns.",
            "In manchen Situationen sehe ich das anders.",
            "Das passiert gelegentlich, kein Drama.",
            "Wir könnten es mal anders versuchen.",
            "Nicht jedes Mal, aber manchmal schon.",
            "Ich sehe da verschiedene Aspekte.",
            "Das ist teilweise richtig, teilweise nicht.",
            "Es gibt Momente, da stimme ich dir zu.",
            "Oft klappt es, manchmal nicht.",
            "Das war diesmal anders als sonst.",
        ],
    },
    "ATO_ACCEPTANCE_PHRASE": {
        "positive": [
            "Ich akzeptiere das so, wie es ist.",
            "Ich nehme meine Angst an und lasse sie da sein.",
            "Ich akzeptiere, dass ich gerade traurig bin.",
            "Ich stehe zu meinen Gefühlen, auch wenn sie schwer sind.",
            "Es ist okay, dass ich mich so fühle.",
            "Ich nehme an, was gerade in mir passiert.",
            "Ich akzeptiere meine Verletzlichkeit.",
            "Ich stehe dazu, dass ich Hilfe brauche.",
            "Es ist okay, nicht immer stark zu sein.",
            "Ich akzeptiere meine Trauer als Teil von mir.",
            "Ich nehme meine Wut an, ohne sie zu bewerten.",
            "Es ist okay, dass ich unsicher bin.",
            "Ich akzeptiere, dass nicht alles perfekt laufen muss.",
            "Ich stehe zu meiner Erschöpfung.",
            "Es ist okay, dass ich Zeit brauche.",
            "Ich nehme an, dass diese Phase dazugehört.",
            "Ich akzeptiere mich so, wie ich heute bin.",
            "Ich stehe dazu, dass mir das schwerfällt.",
            "Ich akzeptiere meine Reaktion als berechtigt.",
            "Es ist okay, Fehler gemacht zu haben.",
            "Ich nehme die Situation an, wie sie ist.",
            "Ich akzeptiere meine Ängste als Teil meiner Geschichte.",
            "Ich stehe dazu, dass ich mich verletzt fühle.",
            "Es ist okay, nicht alles kontrollieren zu können.",
            "Ich akzeptiere mein Tempo.",
            "Ich nehme an, dass Heilung Zeit braucht.",
            "Ich akzeptiere meine Grenzen heute.",
            "Es ist okay, manchmal überfordert zu sein.",
            "Ich stehe dazu, nicht alles allein schaffen zu müssen.",
            "Ich akzeptiere, was war, und schaue nach vorn.",
            "Ich nehme an, dass auch schwere Gefühle okay sind.",
            "Es ist okay, dass ich gerade nicht weiter weiß.",
            "Ich akzeptiere meine Nervosität vor dem Gespräch.",
            "Ich stehe dazu, sensibel zu sein.",
            "Es ist okay, dass ich heute nicht funktioniere.",
            "Ich akzeptiere mein Bedürfnis nach Ruhe.",
        ],
        "negative": [
            "Der Zug fährt um 15:23 Uhr ab.",
            "Ich hole noch schnell Milch.",
            "Hast du den Bericht schon abgeschickt?",
            "Die Sitzung beginnt gleich.",
            "Kannst du mir die Adresse schicken?",
            "Das Meeting wurde verschoben.",
            "Wir treffen uns um acht.",
            "Der Drucker funktioniert wieder.",
            "Ich bin gleich da.",
            "Hast du schon gegessen?",
            "Das Paket ist angekommen.",
            "Morgen wird es regnen.",
            "Der Film fängt um 20 Uhr an.",
            "Ich muss noch einkaufen gehen.",
            "Die Rechnung liegt auf dem Tisch.",
            "Kannst du den Hund ausführen?",
            "Das WLAN geht nicht.",
            "Ich habe einen Arzttermin um drei.",
        ],
    },
    "ATO_ACCUSATION_OF_CONTROL": {
        "positive": [
            "Du willst mich kontrollieren!",
            "Du bestimmst immer über mein Leben.",
            "Ich fühle mich von dir eingeengt und kontrolliert.",
            "Du manipulierst mich doch nur.",
            "Hör auf, mich zu bevormunden!",
            "Du willst alles unter deiner Kontrolle haben.",
            "Du entscheidest immer alles für mich.",
            "Ich darf ja gar nichts ohne deine Erlaubnis.",
            "Du bist ein totaler Kontrollfreak.",
            "Lass mich endlich in Ruhe, du kontrollierst alles!",
            "Du checkst mein Handy, das ist Kontrolle!",
            "Du sagst mir ständig, was ich tun soll.",
            "Du behandelst mich wie dein Eigentum.",
            "Ich bin nicht deine Marionette.",
            "Du willst nur, dass ich tue, was du sagst.",
            "Hör auf, mich zu überwachen!",
            "Du mischst dich in alles ein.",
            "Du lässt mir keinen Freiraum.",
            "Du willst bestimmen, wen ich treffe.",
            "Das ist reine Kontrolle, was du da machst.",
            "Du versuchst, mich kleinzuhalten.",
            "Ich fühle mich wie in einem Käfig.",
            "Du entscheidest über meinen Kopf hinweg.",
            "Du willst mich isolieren von meinen Freunden.",
            "Hör auf, mir Vorschriften zu machen!",
            "Du kontrollierst mein Geld, meine Zeit, alles.",
            "Ich bin doch kein Kind, das du steuern kannst.",
            "Du manipulierst mich mit deiner Eifersucht.",
            "Du willst nur Macht über mich haben.",
            "Das ist keine Fürsorge, das ist Kontrolle.",
            "Du verbietest mir Dinge, die normal sind.",
            "Ich habe das Gefühl, nichts allein entscheiden zu dürfen.",
            "Du bist besessen davon, alles zu bestimmen.",
            "Du willst mein ganzes Leben diktieren.",
            "Das ist manipulativ, was du da tust.",
            "Du nutzt deine Position aus, um mich zu kontrollieren.",
            "Ich fühle mich unter ständiger Beobachtung.",
            "Du verdrehst alles, damit ich mache, was du willst.",
            "Du benutzt Schuldgefühle, um mich zu steuern.",
            "Das ist emotionale Manipulation.",
            "Du willst mich abhängig von dir machen.",
            "Ich habe kein eigenes Leben mehr durch dich.",
            "Du entscheidest sogar, was ich anziehe.",
            "Du kontrollierst jede meiner Bewegungen.",
            "Das ist keine Beziehung, das ist ein Gefängnis.",
        ],
        "negative": [
            "Können wir das zusammen entscheiden?",
            "Ich schlage vor, wir besprechen das gemeinsam.",
            "Was denkst du, sollen wir heute Abend kochen?",
            "Ich respektiere deine Entscheidung.",
            "Mach das so, wie du es für richtig hältst.",
            "Du kannst dich frei entscheiden.",
            "Ich vertraue deinem Urteil.",
            "Wie möchtest du das handhaben?",
            "Das ist ganz allein deine Sache.",
            "Ich möchte deine Meinung hören.",
            "Wir sind gleichberechtigt in dieser Entscheidung.",
            "Ich unterstütze dich, egal was du wählst.",
            "Triff du die Entscheidung, ich stehe dahinter.",
            "Dein Freiraum ist mir wichtig.",
            "Ich mische mich da nicht ein.",
            "Du weißt am besten, was gut für dich ist.",
            "Ich vertraue dir vollkommen.",
            "Das ist deine Entscheidung, nicht meine.",
        ],
    },
    "ATO_ACHIEVEMENT_DRIVE": {
        "positive": [
            "Ich will das unbedingt schaffen.",
            "Aufgeben kommt für mich nicht infrage.",
            "Ich muss besser werden, egal was es kostet.",
            "Das Ziel ist klar, ich gebe alles dafür.",
            "Ich will an die Spitze.",
            "Scheitern ist keine Option für mich.",
            "Ich arbeite härter als alle anderen.",
            "Erfolg ist alles, was zählt.",
            "Ich bin extrem ehrgeizig und das ist gut so.",
            "Ich habe hohe Ansprüche an mich selbst.",
            "Ich will das Maximum aus mir rausholen.",
            "Leistung definiert meinen Wert.",
            "Ich muss beweisen, was in mir steckt.",
            "Ich gebe nie weniger als hundert Prozent.",
            "Mittelmäßigkeit ist nichts für mich.",
            "Ich treibe mich selbst zu Höchstleistungen an.",
            "Mein Ehrgeiz lässt mich nicht ruhen.",
            "Ich will gewinnen, das ist mein Antrieb.",
            "Ich bin erst zufrieden, wenn ich es geschafft habe.",
            "Ich setze mir immer neue, höhere Ziele.",
            "Ich brauche Herausforderungen, um zu wachsen.",
            "Performance ist mir extrem wichtig.",
            "Ich vergleiche mich ständig mit den Besten.",
            "Ohne Disziplin erreicht man nichts.",
            "Ich arbeite jeden Tag an meinem Erfolg.",
            "Fleiß schlägt Talent, davon bin ich überzeugt.",
            "Ich will der Beste in meinem Bereich sein.",
            "Meine Karriere hat oberste Priorität.",
            "Ich opfere gern Freizeit für meine Ziele.",
            "Durchhalten ist meine größte Stärke.",
            "Ich bin bereit, alles zu geben.",
            "Jeder Rückschlag macht mich stärker.",
            "Ich will mehr erreichen als alle vor mir.",
            "Mein Antrieb ist unerschöpflich.",
            "Ich ruhe mich nicht auf Erfolgen aus.",
            "Ich bin hungrig nach Resultaten.",
            "Stillstand ist für mich Rückschritt.",
            "Ich pushe mich jeden Tag über mein Limit.",
            "Mein Ziel ist klar und ich lasse nicht locker.",
            "Ich bin besessen von Fortschritt.",
            "Ich investiere alles in meinen Erfolg.",
            "Exzellenz ist mein Standard.",
            "Ich werde nicht aufhören, bis ich es geschafft habe.",
            "Mein Ehrgeiz ist mein Motor.",
            "Ich wachse an jeder Herausforderung.",
        ],
        "negative": [
            "Heute nehme ich mir frei und mache gar nichts.",
            "Es muss nicht immer perfekt sein.",
            "Ich bin auch ohne Erfolg wertvoll.",
            "Manchmal reicht einfach gut genug.",
            "Ich genieße den Moment, ohne an Ziele zu denken.",
            "Entspannung ist mir gerade wichtiger als Leistung.",
            "Ich muss niemandem etwas beweisen.",
            "Es ist okay, mal langsamer zu machen.",
            "Nicht alles muss ein Wettbewerb sein.",
            "Ich bin zufrieden mit dem, was ich habe.",
            "Der Weg ist das Ziel, nicht das Ergebnis.",
            "Ich lasse den Druck heute mal los.",
            "Pause machen ist auch produktiv.",
            "Ich vergleiche mich nicht mehr mit anderen.",
            "Mein Wert hängt nicht von Leistung ab.",
            "Heute zählt nur Erholung.",
            "Ich bin gut genug, so wie ich bin.",
            "Es gibt Wichtigeres als Karriere.",
        ],
    },
    "ATO_ACHIEVEMENT_GOAL": {
        "positive": [
            "Bis Ende des Jahres will ich befördert werden.",
            "Mein Ziel ist es, die Prüfung zu bestehen.",
            "Ich will in fünf Jahren mein eigenes Unternehmen haben.",
            "Dieses Quartal will ich die Verkaufszahlen verdoppeln.",
            "Mein nächstes Ziel ist der Marathon unter vier Stunden.",
            "Ich will den Abschluss mit Auszeichnung schaffen.",
            "Bis zum Sommer habe ich zehn Kilo abgenommen.",
            "Mein Karriereziel ist die Teamleitung.",
            "Ich will in drei Monaten fließend Spanisch sprechen.",
            "Das Projekt muss bis Freitag fertig sein.",
            "Mein Plan: Eigenheim bis ich vierzig bin.",
            "Ich will dieses Jahr drei Bücher veröffentlichen.",
            "Mein Ziel ist eine Eins in der Klausur.",
            "Bis nächsten Monat habe ich den Kurs abgeschlossen.",
            "Ich will den Umsatz um zwanzig Prozent steigern.",
            "Mein Ziel ist es, Partnerin in der Kanzlei zu werden.",
            "Ich will bis zum Jahresende schuldenfrei sein.",
            "Mein Plan ist, bis März die Zertifizierung zu haben.",
            "Ich will im nächsten Halbjahr hundert Neukunden gewinnen.",
            "Mein Traum ist ein Platz im Nationalteam.",
            "Dieses Semester schaffe ich alle Prüfungen.",
            "Ich will die Abteilung zur besten im Unternehmen machen.",
            "Mein Ziel ist, bis Herbst den Führerschein zu haben.",
            "Ich will in zwei Jahren Abteilungsleiter sein.",
            "Bis Ende Q3 haben wir den Prototyp fertig.",
            "Mein Ziel ist eine Million Nutzer.",
            "Ich schaffe das in der vorgegebenen Zeit.",
            "Bis Dezember steht das MVP.",
            "Mein nächster Meilenstein ist die Finanzierungsrunde.",
            "Ich will den Preis dieses Jahr gewinnen.",
            "Mein Ziel: Top 10 in der Branche.",
            "Bis zum Sommer will ich fit genug für den Triathlon sein.",
            "Ich will den Master in Regelstudienzeit schaffen.",
            "Mein Plan ist es, dieses Jahr die Weiterbildung abzuschließen.",
            "Ich will bis nächste Woche das Angebot rausschicken.",
            "Bis Jahresende habe ich drei neue Kunden gewonnen.",
            "Mein Ziel ist die Note Eins Komma Null.",
            "Ich will bis Mai den Businessplan fertig haben.",
            "Mein Ziel ist es, jeden Tag eine Stunde zu lesen.",
            "Bis Ende des Monats ist das Projekt abgeschlossen.",
            "Ich will mich bis zum Sommer selbstständig machen.",
            "Mein nächstes Ziel ist die Gehaltsverhandlung.",
            "Ich will bis zum Jahresende zwanzigtausend gespart haben.",
            "Mein Plan: jede Woche drei Workouts.",
            "Ich schaffe den Halbmarathon dieses Jahr.",
        ],
        "negative": [
            "Mal sehen, was sich ergibt.",
            "Ich habe gerade keine konkreten Pläne.",
            "Ich lasse es auf mich zukommen.",
            "Heute mache ich einfach, worauf ich Lust habe.",
            "Ich setze mir bewusst keine Deadlines.",
            "Es kommt, wie es kommt.",
            "Ich habe kein bestimmtes Ziel vor Augen.",
            "Vielleicht klappt es, vielleicht nicht.",
            "Ich plane nicht so gern im Voraus.",
            "Ich genieße den Tag, ohne Ziele.",
            "Was morgen ist, sehe ich dann.",
            "Ich habe keinen Zeitdruck.",
            "Planlos durch den Tag, das ist auch mal schön.",
            "Ich brauche gerade keine Struktur.",
            "Es muss nicht immer ein Ziel geben.",
            "Ich lasse mich treiben.",
            "Ohne Plan ist auch okay.",
            "Ich mache mir keinen Stress mit Vorgaben.",
        ],
    },
    "ATO_ACK": {
        "positive": [
            "Ok, verstanden.",
            "Passt, mache ich.",
            "Gesehen, danke.",
            "Notiert, kümmere mich drum.",
            "Zur Kenntnis genommen.",
            "Ok, alles klar.",
            "Passt so.",
            "Hab ich gesehen.",
            "Ist notiert.",
            "Ok, danke für die Info.",
            "Gesehen und vermerkt.",
            "Passt, machen wir so.",
            "Ok, bin dabei.",
            "Zur Kenntnis, danke.",
            "Notiert, danke dir.",
            "Ok, hab's auf dem Schirm.",
            "Passt mir.",
            "Gesehen, wird erledigt.",
            "Ok, geht klar.",
            "Notiert, kommt auf die Liste.",
            "Passt, ich kümmere mich.",
            "Ok, mache ich gleich.",
            "Gesehen, ist eingeplant.",
            "Zur Kenntnis, wird umgesetzt.",
            "Passt, ich handle das.",
            "Ok, nehme ich mit.",
            "Notiert, wird bearbeitet.",
            "Gesehen, danke fürs Bescheid sagen.",
            "Ok, steht.",
            "Passt, ist gebongt.",
            "Zur Kenntnis, alles klar.",
            "Notiert, melde mich wenn es fertig ist.",
            "Ok, check.",
            "Gesehen und gespeichert.",
            "Passt so für mich.",
            "Ok, übernehme ich.",
            "Notiert, steht auf meiner Liste.",
            "Gesehen, kein Problem.",
            "Passt, läuft.",
            "Ok, danke.",
            "Zur Kenntnis genommen, danke.",
            "Notiert, alles klar soweit.",
            "Gesehen, super.",
            "Ok, abgehakt.",
        ],
        "negative": [
            "Das sehe ich komplett anders.",
            "Ich bin nicht einverstanden damit.",
            "Das müssen wir nochmal besprechen.",
            "Ich habe da ernsthafte Bedenken.",
            "So einfach ist das nicht.",
            "Können wir das nochmal durchgehen?",
            "Ich verstehe nicht, was du meinst.",
            "Das funktioniert so nicht.",
            "Da muss ich widersprechen.",
            "Das überzeugt mich nicht.",
            "Ich habe noch offene Fragen dazu.",
            "So hatte ich das nicht verstanden.",
            "Das weiche ich erst mal ab.",
            "Ich bin skeptisch bei dem Vorschlag.",
            "Lass uns das nochmal überdenken.",
            "Da stimmt was nicht.",
            "Ich brauche mehr Informationen.",
            "Das kann ich so nicht akzeptieren.",
        ],
    },
    "ATO_ACKNOWLEDGE": {
        "positive": [
            "Verstanden, mache ich.",
            "Zur Kenntnis genommen.",
            "Notiert, danke.",
            "Gesehen, alles klar.",
            "Ist angekommen, danke dir.",
            "Ok, hab's verstanden.",
            "Ist vermerkt.",
            "Zur Kenntnis, wird erledigt.",
            "Verstanden, kümmere mich drum.",
            "Gesehen und notiert.",
            "Angekommen, danke für die Info.",
            "Ok, ist angekommen.",
            "Verstanden, danke für den Hinweis.",
            "Notiert, steht auf der Liste.",
            "Gesehen, wird umgesetzt.",
            "Zur Kenntnis, danke.",
            "Verstanden, bin dran.",
            "Notiert, übernehme ich.",
            "Gesehen, kein Problem.",
            "Angekommen, ich handle das.",
            "Ok, ist vermerkt.",
            "Verstanden, alles klar.",
            "Zur Kenntnis, melde mich.",
            "Notiert, danke fürs Bescheid geben.",
            "Gesehen, mache ich morgen.",
            "Angekommen und verstanden.",
            "Ok, hab ich auf dem Schirm.",
            "Verstanden, erledige ich heute noch.",
            "Notiert, passt.",
            "Gesehen, danke.",
            "Zur Kenntnis genommen, wird bearbeitet.",
            "Angekommen, alles klar bei mir.",
            "Verstanden, geht klar.",
            "Notiert, bin informiert.",
            "Ok, nehme ich zur Kenntnis.",
            "Gesehen, eingeplant.",
            "Verstanden, wird gemacht.",
            "Notiert, ist gebongt.",
            "Zur Kenntnis, übernommen.",
            "Angekommen, läuft.",
            "Ok, hab ich.",
            "Gesehen, steht.",
            "Verstanden, check.",
            "Notiert, erledigt sich.",
        ],
        "negative": [
            "Ich habe grundsätzliche Einwände dagegen.",
            "Das ist mir zu oberflächlich erklärt.",
            "So kann ich dem nicht zustimmen.",
            "Ich brauche mehr Details, bevor ich das annehme.",
            "Das widerspricht meiner Erfahrung.",
            "Ich sehe das Problem anders.",
            "Das erscheint mir unvollständig.",
            "Können wir das vertiefen?",
            "Das beantwortet meine Frage nicht.",
            "Ich habe Rückfragen zu diesem Punkt.",
            "Das leuchtet mir nicht ein.",
            "Ich möchte das hinterfragen.",
            "Das klingt nicht ganz richtig.",
            "Ich bin da anderer Meinung.",
            "Das ergibt für mich keinen Sinn.",
            "Ich zweifle an dieser Darstellung.",
            "Das muss ich erst prüfen.",
            "Ich bin nicht überzeugt davon.",
        ],
    },
    "ATO_ACK_MICRO": {
        "positive": [
            "Mhm.",
            "Ja.",
            "Ok.",
            "Aha.",
            "Hmm.",
            "Jap.",
            "Genau.",
            "Stimmt.",
            "Klar.",
            "Schon.",
            "Sicher.",
            "Richtig.",
            "Absolut.",
            "Wohl.",
            "Eben.",
            "Jo.",
            "Mm.",
            "Jep.",
            "Gut.",
            "Yep.",
            "Na klar.",
            "Logo.",
            "Aber sicher.",
            "Jawohl.",
            "Exakt.",
            "Ganz genau.",
            "So ist es.",
            "Stimmt genau.",
            "Kann ich bestätigen.",
            "Sehe ich auch so.",
            "Hm, ja.",
            "Stimmt, ja.",
            "Ja, genau.",
            "Richtig, ja.",
            "Ok, ja.",
            "Aha, verstehe.",
            "Mhm, klar.",
            "Jo, passt.",
            "Genau so.",
            "Ja klar.",
            "Na sicher.",
            "Stimmt schon.",
            "Klar doch.",
            "Sicher, ja.",
        ],
        "negative": [
            "Ich möchte dir gerne ausführlich erklären, warum ich das anders sehe als du.",
            "Das ist ein komplexes Thema, über das wir länger sprechen müssen.",
            "Ich habe da eine ganz andere Perspektive drauf.",
            "Lass mich kurz ausholen, um meinen Standpunkt zu erklären.",
            "Das führt jetzt zu weit, aber grundsätzlich bin ich skeptisch.",
            "Ich möchte dazu eine längere Stellungnahme abgeben.",
            "Das bedarf einer ausführlichen Diskussion.",
            "Nein, das sehe ich überhaupt nicht so.",
            "Ich widerspreche dir in diesem Punkt entschieden.",
            "Das stimmt so nicht, und zwar aus folgenden Gründen.",
            "Da muss ich ausführlicher nachhaken.",
            "Ich habe eine komplett andere Einschätzung.",
            "Das können wir so nicht stehen lassen.",
            "Ich habe ernsthafte Einwände gegen diesen Vorschlag.",
            "Nein, das geht gar nicht.",
            "Ich bin grundsätzlich anderer Meinung.",
            "Das muss ich erst genauer analysieren.",
            "Ich bin da sehr skeptisch, ehrlich gesagt.",
        ],
    },
    "ATO_ACTION_ORIENTATION": {
        "positive": [
            "Lass uns das jetzt sofort angehen.",
            "Ich mache das direkt.",
            "Wir müssen handeln, nicht reden.",
            "Pack an, statt zu grübeln.",
            "Ich setze das heute noch um.",
            "Weniger reden, mehr machen.",
            "Ich starte sofort damit.",
            "Das erledige ich auf der Stelle.",
            "Handeln ist besser als Planen.",
            "Ich warte nicht länger, ich fange an.",
            "Los geht's, packen wir es an!",
            "Ich brauche Resultate, keine Diskussionen.",
            "Taten statt Worte.",
            "Ich kümmere mich sofort darum.",
            "Das Problem löst sich nicht von allein, ich handle jetzt.",
            "Reden bringt nichts, wir müssen was tun.",
            "Ich nehme das selbst in die Hand.",
            "Jetzt wird gehandelt.",
            "Ich setze mich direkt dran.",
            "Komm, wir machen das einfach.",
            "Kein Zögern, direkt umsetzen.",
            "Ich bin ein Macher, kein Grübler.",
            "Statt zu planen, fange ich einfach an.",
            "Ich will Ergebnisse sehen, nicht Konzepte.",
            "Das wird jetzt gemacht, Punkt.",
            "Ich reagiere sofort auf das Problem.",
            "Schnelle Umsetzung ist mir wichtig.",
            "Ich warte nicht auf Erlaubnis, ich handle.",
            "Das packe ich jetzt an.",
            "Ich bin pragmatisch und handle direkt.",
            "Lass uns loslegen statt zu diskutieren.",
            "Ich setze Prioritäten und handle danach.",
            "Das muss jetzt passieren, nicht morgen.",
            "Ich bin der Typ, der einfach macht.",
            "Sofort umsetzen, das ist mein Motto.",
            "Reden können wir später, jetzt wird gearbeitet.",
            "Ich bin bereit, sofort zu starten.",
            "Kein Abwarten, direkt loslegen.",
            "Ich ergreife die Initiative.",
            "Das Problem wird gelöst, und zwar jetzt.",
            "Ich scheue mich nicht, sofort anzufangen.",
            "Machen ist wie wollen, nur krasser.",
            "Ich handle proaktiv statt reaktiv.",
            "Direkt in die Umsetzung gehen.",
            "Ich bin entschlossen, das durchzuziehen.",
        ],
        "negative": [
            "Lass uns erstmal in Ruhe darüber nachdenken.",
            "Ich möchte das gründlich analysieren, bevor wir anfangen.",
            "Vielleicht sollten wir noch eine Nacht drüber schlafen.",
            "Ich bin mir unsicher, ob wir das jetzt schon angehen sollten.",
            "Erstmal planen, dann umsetzen.",
            "Wir brauchen mehr Informationen, bevor wir handeln.",
            "Abwarten und Tee trinken.",
            "Das hat noch Zeit, kein Grund zur Eile.",
            "Ich möchte das erst mit dem Team besprechen.",
            "Lass uns nichts überstürzen.",
            "Geduld ist hier gefragt.",
            "Ich warte erstmal ab, wie sich die Situation entwickelt.",
            "Hektik bringt nichts, lass uns sorgfältig vorgehen.",
            "Ich möchte alle Optionen abwägen.",
            "Erstmal die Lage sondieren.",
            "Das eilt nicht, wir haben genug Zeit.",
            "Ich denke lieber zweimal nach, bevor ich handle.",
            "Planvolles Vorgehen ist mir wichtiger als Schnelligkeit.",
        ],
    },
}

# ============================================================
# MAIN
# ============================================================

def main():
    total_enriched = 0
    for marker_id, examples in EXAMPLES.items():
        filepath = find_file(marker_id)
        if filepath is None:
            print(f"SKIP {marker_id}: file not found")
            continue

        pos_count, neg_count = current_counts(
            yaml.load(open(filepath))
        )
        print(f"{marker_id}: before={pos_count}p/{neg_count}n", end="")

        p, n = enrich_marker(filepath, examples["positive"], examples["negative"])
        print(f" -> after={p}p/{n}n")
        total_enriched += 1

    print(f"\nEnriched {total_enriched} markers in batch 1.")


if __name__ == "__main__":
    main()
