#!/usr/bin/env python3
"""
Enrich ATO markers (batch 5b: SUPPORT_MESSAGE through WILL_CONTACT).
50 positive + 25 negative German examples each.
"""

import os
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
yaml.allow_duplicate_keys = True

BASE = Path("/Users/benjaminpoersch/Projects/LeanDeep-annotator/build/markers_rated")
DIRS = [BASE / "1_approved" / "ATO", BASE / "2_good" / "ATO"]


def find_file(marker_id: str) -> Path | None:
    for d in DIRS:
        p = d / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None


ENRICHMENTS = {

"ATO_SUPPORT_MESSAGE": {
  "positive": [
    "Du bist nicht allein damit.",
    "Ich bin da für dich.",
    "Melde dich jederzeit, wenn du reden willst.",
    "Ich unterstütze dich, egal was kommt.",
    "Wir schaffen das zusammen.",
    "Du bist nicht allein, ich bin hier.",
    "Ich bin da, hörst du?",
    "Melde dich jederzeit bei mir.",
    "Ich unterstütze dich voll und ganz.",
    "Zusammen stehen wir das durch.",
    "Du bist nicht allein in dem Ganzen.",
    "Ich bin da, wann immer du mich brauchst.",
    "Melde dich jederzeit, Tag und Nacht.",
    "Ich unterstütze dich bei allem.",
    "Gemeinsam sind wir stärker.",
    "Du bist nicht allein, vergiss das nicht.",
    "Ich bin da und ich bleibe.",
    "Melde dich, wenn es zu viel wird.",
    "Ich unterstütze dich ohne Bedingungen.",
    "Wir packen das, versprochen.",
    "Du bist nicht allein, ich halte zu dir.",
    "Ich bin da, auch wenn es schwer ist.",
    "Melde dich jederzeit, ich höre zu.",
    "Ich unterstütze dich, wo ich kann.",
    "Zusammen kriegen wir das hin.",
    "Du bist nicht allein, auch wenn es sich so anfühlt.",
    "Ich bin da, darauf kannst du zählen.",
    "Melde dich, ich bin immer erreichbar für dich.",
    "Ich unterstütze dich, das ist mir wichtig.",
    "Wir schaffen das, gemeinsam.",
    "Du bist nicht allein in dieser Situation.",
    "Ich bin da und höre dir zu.",
    "Melde dich jederzeit, ohne schlechtes Gewissen.",
    "Ich unterstütze dich von Herzen.",
    "Zusammen finden wir einen Weg.",
    "Du bist nicht allein, ich verspreche es.",
    "Ich bin für dich da, immer.",
    "Melde dich, wann immer du magst.",
    "Ich unterstütze dich, egal wie lange es dauert.",
    "Wir schaffen das Schritt für Schritt.",
    "Du bist nicht allein, ich trage mit.",
    "Ich bin da, und das meine ich ernst.",
    "Melde dich jederzeit, ich urteile nicht.",
    "Ich unterstütze dich mit allem, was ich habe.",
    "Zusammen sind wir ein Team.",
    "Du bist nicht allein, das sage ich dir.",
    "Ich bin da, immer und überall.",
    "Melde dich, wenn du Kraft brauchst.",
    "Ich unterstütze dich bedingungslos.",
    "Wir stehen das gemeinsam durch.",
  ],
  "negative": [
    "Kannst du mir das Salz reichen?",
    "Der Termin ist um 14 Uhr.",
    "Ich war gestern einkaufen.",
    "Das Wetter soll morgen besser werden.",
    "Hast du die E-Mail gelesen?",
    "Ich muss noch tanken.",
    "Die Besprechung ist im Konferenzraum.",
    "Ich habe den Bericht abgegeben.",
    "Der Drucker ist kaputt.",
    "Wir brauchen neue Druckerpatronen.",
    "Das Mittagessen war gut.",
    "Ich fahre morgen nach München.",
    "Der Kaffee ist fertig.",
    "Hast du den Schlüssel gesehen?",
    "Die Post ist gekommen.",
    "Ich hole die Kinder ab.",
    "Das Paket wurde geliefert.",
    "Der Aufzug ist außer Betrieb.",
    "Ich brauche eine neue Tastatur.",
    "Die Heizung macht Geräusche.",
    "Wir haben kein Brot mehr.",
    "Der Hund muss raus.",
    "Ich war beim Friseur.",
    "Das Auto muss zur Inspektion.",
    "Die Rechnung liegt auf dem Tisch.",
  ],
},

"ATO_SUPPORT_PHRASE": {
  "positive": [
    "Ich bin da für dich, wir schaffen das.",
    "Danke dir, ich fühl mich gesehen.",
    "Gemeinsam kriegen wir das hin.",
    "Du kannst dich auf mich verlassen.",
    "Ich hör dir zu, okay?",
    "Ich bin da, was auch passiert.",
    "Du schaffst das, ich glaub an dich.",
    "An deiner Seite, immer.",
    "Kann helfen, sag einfach Bescheid.",
    "Gemeinsam sind wir stark.",
    "Ich bin da und ich bleibe bei dir.",
    "Du schaffst das, das weiß ich.",
    "An deiner Seite stehe ich.",
    "Ich kann helfen, lass mich.",
    "Gemeinsam finden wir eine Lösung.",
    "Ich bin da, auch in schweren Zeiten.",
    "Du schaffst das, Schritt für Schritt.",
    "An deiner Seite, komme was wolle.",
    "Kann ich dir irgendwie helfen?",
    "Gemeinsam geht es leichter.",
    "Ich bin da, du musst das nicht allein tragen.",
    "Du schaffst das, ich unterstütze dich.",
    "An deiner Seite, dafür bin ich da.",
    "Ich kann helfen, sag nur wie.",
    "Gemeinsam packen wir das an.",
    "Ich bin da, verlier nicht den Mut.",
    "Du schaffst das, davon bin ich überzeugt.",
    "An deiner Seite zu sein ist mir wichtig.",
    "Kann helfen, kein Problem.",
    "Gemeinsam bewältigen wir das.",
    "Ich bin da, auch wenn es unbequem wird.",
    "Du schaffst das, du bist stärker als du denkst.",
    "An deiner Seite, durch dick und dünn.",
    "Ich kann helfen, wirklich.",
    "Gemeinsam schaffen wir alles.",
    "Ich bin da, egal wann.",
    "Du schaffst das, hab Vertrauen.",
    "An deiner Seite, ohne Wenn und Aber.",
    "Kann helfen, meld dich einfach.",
    "Gemeinsam ist es weniger schwer.",
    "Ich bin da für dich, hörst du?",
    "Du schaffst das, ich bin sicher.",
    "An deiner Seite zu stehen macht mich froh.",
    "Ich kann helfen, jederzeit.",
    "Gemeinsam kommen wir durch.",
    "Ich bin da, das verspreche ich.",
    "Du schaffst das, eins nach dem anderen.",
    "An deiner Seite, so lange du mich brauchst.",
    "Kann helfen, das ist selbstverständlich.",
    "Gemeinsam, das ist das Wichtigste.",
  ],
  "negative": [
    "Kannst du mir das Salz reichen?",
    "Der Termin ist um 14 Uhr.",
    "Ich war gestern einkaufen.",
    "Das Wetter soll morgen besser werden.",
    "Hast du die E-Mail gelesen?",
    "Ich muss noch tanken.",
    "Die Besprechung ist im Konferenzraum.",
    "Der Zug hatte Verspätung.",
    "Ich brauche neue Batterien.",
    "Das Fenster klemmt.",
    "Wir haben noch Milch im Kühlschrank.",
    "Der Rasen muss gemäht werden.",
    "Ich habe den Schlüssel gefunden.",
    "Die Waschmaschine ist fertig.",
    "Morgen regnet es laut Vorhersage.",
    "Ich nehme den Bus statt die Bahn.",
    "Das Restaurant hat montags zu.",
    "Der Akku ist fast leer.",
    "Ich war beim Optiker.",
    "Die Straße ist wegen Bauarbeiten gesperrt.",
    "Ich brauche neue Socken.",
    "Der Film fängt um acht an.",
    "Die Pizza ist bestellt.",
    "Ich habe den Müll rausgebracht.",
    "Das Buch liegt auf dem Nachttisch.",
  ],
},

"ATO_SURPRISE": {
  "positive": [
    "Wow, damit habe ich überhaupt nicht gerechnet!",
    "Oh! Das kommt jetzt aber unerwartet.",
    "Was? Das ist ja unglaublich!",
    "Echt jetzt? Das kann ich kaum glauben.",
    "Ich bin total überrascht, dich hier zu sehen.",
    "Krass, das wusste ich gar nicht.",
    "Huch, wo kommst du denn plötzlich her?",
    "Das ist eine riesige Überraschung!",
    "Ich bin sprachlos, das ist ja der Wahnsinn.",
    "Tatsächlich? Das hätte ich nie gedacht.",
    "Ach du meine Güte, das ist ja fantastisch!",
    "Das haut mich jetzt echt vom Hocker.",
    "Ich bin ehrlich erstaunt über diese Entwicklung.",
    "Nanu, was ist denn hier los?",
    "Im Ernst? Das ist ja eine krasse Wendung.",
    "Ich bin baff, einfach nur baff.",
    "Das überrascht mich jetzt aber positiv.",
    "Oha, das ist neu für mich.",
    "Wer hätte das gedacht? Ich jedenfalls nicht.",
    "Das ist ja mal eine faustdicke Überraschung.",
    "Wow, das hätte ich nicht erwartet!",
    "Oh! Das überrascht mich wirklich.",
    "Was? Im Ernst jetzt?",
    "Echt jetzt? Das ist ja irre!",
    "Ich bin total überrascht von dem Ergebnis.",
    "Krass, wie ist das passiert?",
    "Huch, das kam aus dem Nichts!",
    "Das ist eine unglaubliche Überraschung!",
    "Ich bin sprachlos, ehrlich.",
    "Tatsächlich? Ich kann es nicht fassen.",
    "Wow, das ist mal was Neues!",
    "Oh! Damit hatte ich null gerechnet.",
    "Was? Das gibt es doch nicht!",
    "Echt jetzt? Das ist krass!",
    "Ich bin total überrascht und begeistert.",
    "Krass, das habe ich nicht kommen sehen.",
    "Huch, was für eine Wendung!",
    "Das ist eine tolle Überraschung!",
    "Ich bin baff und begeistert.",
    "Oha, das ändert alles!",
    "Wow, das ist der Hammer!",
    "Oh! Was für eine Neuigkeit!",
    "Was? Echt wahr?",
    "Im Ernst? Das ist sensationell!",
    "Ich bin total überrascht, danke!",
    "Krass, das hätte ich nie vermutet.",
    "Huch, das trifft mich unvorbereitet!",
    "Das ist eine riesige positive Überraschung!",
    "Ich bin sprachlos vor Freude.",
    "Tatsächlich? Das ist ja wunderbar!",
  ],
  "negative": [
    "Ja, das war zu erwarten.",
    "Wie vorhergesagt, nichts Neues.",
    "Das überrascht mich nicht im Geringsten.",
    "Ganz normal, alles wie erwartet.",
    "Das habe ich kommen sehen.",
    "Keine Überraschung für mich.",
    "Logisch, das musste so kommen.",
    "Erwartbar, nichts Besonderes.",
    "Das war klar, oder?",
    "Ich habe damit gerechnet.",
    "Vorhersehbar, wie immer.",
    "Null Überraschung.",
    "Das wusste ich schon.",
    "Erwartungsgemäß, alles im Rahmen.",
    "Nichts Neues unter der Sonne.",
    "Das war absehbar.",
    "Wie vermutet, genau so.",
    "Keine große Sache.",
    "Das passt ins Bild.",
    "Ich bin nicht überrascht.",
    "Vorhersagbar und langweilig.",
    "Das war nur eine Frage der Zeit.",
    "Erwartbar wie das Amen in der Kirche.",
    "Null Erstaunen meinerseits.",
    "Das war sonnenklar.",
  ],
},

"ATO_SURPRISE_ASTONISHMENT": {
  "positive": [
    "Das überrascht mich wirklich sehr!",
    "Ich bin total erstaunt über diese Wendung.",
    "Wow, das ist ja unglaublich!",
    "Diese Nachricht hat mich verblüfft.",
    "Ich bin sprachlos vor Verwunderung.",
    "Das ist ja eine Überraschung!",
    "Ich bin total surprised!",
    "Das erstaunt mich sehr.",
    "Ich bin fassungslos über dieses Ergebnis.",
    "Wahnsinn, das hätte ich nicht erwartet!",
    "Das ist erstaunlich und überraschend zugleich.",
    "Ich bin total verblüfft davon.",
    "Das überrascht mich positiv!",
    "Ich bin erstaunt, wie gut das funktioniert.",
    "Wow, das ist krass!",
    "Diese Entwicklung verwundert mich.",
    "Ich bin total amazed!",
    "Das ist eine unglaubliche Überraschung.",
    "Ich bin sprachlos und erstaunt.",
    "Das verblüfft mich immer wieder.",
    "Ich bin überrascht und begeistert.",
    "Wahnsinn, das ist ja erstaunlich!",
    "Diese Nachricht macht mich fassungslos.",
    "Ich bin total surprised by this!",
    "Das ist verwunderlich und interessant.",
    "Wow, ich bin echt überrascht!",
    "Das erstaunt mich jedes Mal aufs Neue.",
    "Ich bin verblüfft über deine Fähigkeiten.",
    "Das ist eine positive Überraschung!",
    "Ich bin sprachlos vor Erstaunen.",
    "Krass, das hätte ich nie gedacht!",
    "Diese Wendung überrascht mich total.",
    "Ich bin erstaunt und beeindruckt.",
    "Das ist unglaublich überraschend!",
    "Ich bin fassungslos über diese Leistung.",
    "Wow, das ist ja wahnsinnig gut!",
    "Diese Entwicklung verblüfft mich sehr.",
    "Ich bin total amazed by your work!",
    "Das überrascht mich auf angenehme Weise.",
    "Ich bin erstaunt über diese Möglichkeit.",
    "Das ist verwunderlich und faszinierend.",
    "Ich bin sprachlos vor Überraschung.",
    "Wahnsinn, das ist erstaunlich!",
    "Diese Nachricht hat mich total surprised.",
    "Ich bin verblüfft und begeistert zugleich.",
    "Das ist eine unglaubliche Wendung!",
    "Ich bin fassungslos, wie schnell das ging.",
    "Wow, ich bin echt erstaunt!",
    "Das überrascht mich immer wieder positiv.",
    "Ich bin total amazed und happy!",
  ],
  "negative": [
    "Das lässt mich kalt, ehrlich gesagt.",
    "Nichts Neues, alles wie gehabt.",
    "Das war absehbar, keine Verwunderung.",
    "Ganz ruhig, das war erwartbar.",
    "Ich bin gelassen, das überrascht mich nicht.",
    "Alles im Rahmen, nichts Besonderes.",
    "Das war vorhersehbar.",
    "Keine Reaktion meinerseits, erwartbar.",
    "Das berührt mich nicht, es war klar.",
    "Ruhig und gefasst, keine Überraschung.",
    "Erwartungsgemäß, alles normal.",
    "Kein Erstaunen, alles bekannt.",
    "Das wusste ich bereits.",
    "Routine, nichts Überraschendes.",
    "Vorhersehbar und erwartbar.",
    "Keine Verwunderung meinerseits.",
    "Standard, nichts Ungewöhnliches.",
    "Das hatte ich erwartet.",
    "Null Überraschung, alles im Plan.",
    "Ich bin nicht erstaunt.",
    "Wie ich dachte, genau so.",
    "Langweilig, weil vorhersehbar.",
    "Kein Wow-Effekt bei mir.",
    "Alles wie prognostiziert.",
    "Nüchtern betrachtet: erwartbar.",
  ],
},

"ATO_SURVIVAL_INSTINCT": {
  "positive": [
    "Ich muss überleben, koste es was es wolle.",
    "Instinktiv habe ich reagiert.",
    "Pure Angst, ich konnte nicht denken.",
    "Fluchtreflex hat eingesetzt.",
    "Grundbedürfnisse, mehr geht gerade nicht.",
    "Es geht ums nackte Überleben.",
    "Mein Instinkt sagt mir: Lauf.",
    "Hunger und Angst, mehr fühle ich nicht.",
    "Flucht war meine einzige Option.",
    "Kampf oder Flucht, ich habe gekämpft.",
    "Ich spüre nur noch Gefahr.",
    "Überleben ist alles, was zählt.",
    "Instinkt hat übernommen.",
    "Angst frisst mich auf.",
    "Fluchtreflex, total unkontrolliert.",
    "Mein Körper schreit: Gefahr!",
    "Überleben, atmen, mehr nicht.",
    "Instinktiv habe ich mich geschützt.",
    "Durst und Erschöpfung, mehr gibt es nicht.",
    "Kampfmodus, ich bin bereit.",
    "Überleben ist der einzige Gedanke.",
    "Mein Instinkt hat mich gerettet.",
    "Angst bis in die Knochen.",
    "Flucht war das Einzige, was ging.",
    "Gefahr, überall nur Gefahr.",
    "Überleben, nichts anderes zählt jetzt.",
    "Instinktive Reaktion, ohne Nachdenken.",
    "Hunger treibt mich an.",
    "Flucht nach vorn.",
    "Kampfinstinkt erwacht.",
    "Ich spüre die Gefahr im Nacken.",
    "Überleben heißt durchhalten.",
    "Mein Instinkt warnt mich.",
    "Angst lähmt mich komplett.",
    "Fluchtgedanken, ständig.",
    "Grundbedürfnisse: Essen, Trinken, Sicherheit.",
    "Überleben im Extremmodus.",
    "Instinktiv ziehe ich mich zurück.",
    "Durst nach Sicherheit.",
    "Kampf um jeden Tag.",
    "Gefahr überall, ich bin wachsam.",
    "Überleben ist mein einziges Ziel.",
    "Instinkt sagt: nicht sicher hier.",
    "Angst vor dem, was kommt.",
    "Fluchtbereitschaft, jederzeit.",
    "Mein Körper ist im Alarmmodus.",
    "Überleben bedeutet Prioritäten setzen.",
    "Instinktiv handle ich, bevor ich denke.",
    "Hunger nach Normalität.",
    "Kampf ums Dasein, jeden Tag.",
  ],
  "negative": [
    "Ich fühle mich sicher und geborgen.",
    "Alles ist ruhig und friedlich.",
    "Mir geht es gut, kein Stress.",
    "Ich bin entspannt und zufrieden.",
    "Keine Sorgen, alles im Griff.",
    "Ich fühle mich wohl und beschützt.",
    "Alles ist in Ordnung bei mir.",
    "Ich bin gelassen und frei von Angst.",
    "Sicherheit und Stabilität, das habe ich.",
    "Mir geht es blendend, danke.",
    "Kein Grund zur Sorge.",
    "Ich bin behütet und umsorgt.",
    "Alles friedlich hier.",
    "Ich fühle mich sicher in meiner Umgebung.",
    "Kein Alarmmodus, alles normal.",
    "Ich genieße die Ruhe.",
    "Sicher und stabil, so fühle ich mich.",
    "Keine Bedrohung, alles gut.",
    "Ich bin im Reinen mit mir.",
    "Friede und Zufriedenheit.",
    "Kein Fluchtgedanke, nur Ruhe.",
    "Ich fühle mich stark und sicher.",
    "Alles unter Kontrolle, kein Stress.",
    "Ich bin in Sicherheit.",
    "Entspannt und sorgenfrei.",
  ],
},

"ATO_SWAYING": {
  "positive": [
    "Ich bin hin- und hergerissen.",
    "Einerseits will ich, andererseits nicht.",
    "Ich kann mich nicht entscheiden.",
    "Mal denke ich so, mal so.",
    "Ich schwanke zwischen den Optionen.",
    "Auf der einen Seite reizt es mich, auf der anderen macht es mir Angst.",
    "Ich bin unschlüssig, was ich tun soll.",
    "Hin und her, hin und her.",
    "Ich weiß nicht, ob ich ja oder nein sagen soll.",
    "Einerseits ja, andererseits nein.",
    "Ich kann mich einfach nicht festlegen.",
    "Ich wechsle ständig meine Meinung.",
    "Mal will ich es, mal nicht.",
    "Ich bin total unentschlossen.",
    "Auf der einen Seite stimmt es, auf der anderen nicht.",
    "Ich schwanke hin und her.",
    "Ich bin gespalten, ein Teil will, der andere nicht.",
    "Einerseits logisch, andererseits riskant.",
    "Ich kann mich nicht entscheiden, beides hat Vor- und Nachteile.",
    "Hin und her gerissen zwischen zwei Optionen.",
    "Mal sage ich ja, mal nein.",
    "Ich bin noch nicht bereit, mich festzulegen.",
    "Einerseits Chance, andererseits Risiko.",
    "Ich schwanke und kann mich nicht festlegen.",
    "Ich bin unentschlossen und es nervt mich.",
    "Auf der einen Seite verlockend, auf der anderen beängstigend.",
    "Ich kann mich partout nicht entscheiden.",
    "Hin und her, ich drehe mich im Kreis.",
    "Einerseits vernünftig, andererseits langweilig.",
    "Ich schwanke zwischen Ja und Nein.",
    "Gespalten, definitiv.",
    "Mal so, mal so, ich weiß es nicht.",
    "Ich bin hin und her gerissen bei der Frage.",
    "Einerseits sicher, andererseits einengend.",
    "Ich kann mich nicht entscheiden und leide darunter.",
    "Hin und her, keine klare Richtung.",
    "Ich schwanke seit Tagen.",
    "Einerseits aufregend, andererseits beunruhigend.",
    "Ich bin unentschlossen wie selten zuvor.",
    "Auf der einen Seite Freiheit, auf der anderen Verantwortung.",
    "Ich kann mich nicht entscheiden, was wichtiger ist.",
    "Hin und her zwischen Kopf und Bauch.",
    "Ich bin hin und her gerissen, ehrlich.",
    "Einerseits fair, andererseits hart.",
    "Ich schwanke und brauche Rat.",
    "Gespalten zwischen Pflicht und Neigung.",
    "Mal will ich gehen, mal bleiben.",
    "Ich bin total ambivalent gerade.",
    "Einerseits mutig, andererseits leichtsinnig.",
    "Ich schwanke, und das schon lange.",
  ],
  "negative": [
    "Ich habe mich entschieden, das steht fest.",
    "Kein Zweifel, das ist der richtige Weg.",
    "Meine Entscheidung ist klar.",
    "Ich weiß genau, was ich will.",
    "Keine Unsicherheit, alles entschieden.",
    "Ich bin fest entschlossen.",
    "Die Wahl ist getroffen.",
    "Ich schwanke nicht, ich bin sicher.",
    "Mein Entschluss steht.",
    "Klar und deutlich: Ja.",
    "Keine Ambivalenz, alles klar.",
    "Ich bin überzeugt und handle.",
    "Die Entscheidung fiel leicht.",
    "Ich habe keine Zweifel.",
    "Entschieden und fertig.",
    "Meine Position ist eindeutig.",
    "Ich bin mir sicher, keine Frage.",
    "Das steht außer Frage.",
    "Ich habe mich festgelegt.",
    "Klare Sache, kein Hin und Her.",
    "Meine Entscheidung ist endgültig.",
    "Ich weiß, was ich will und handle danach.",
    "Keine Schwankungen, alles klar.",
    "Fest entschlossen, ohne Wenn und Aber.",
    "Die Richtung stimmt, ich gehe.",
  ],
},

"ATO_SWITCH": {
  "positive": [
    "Lass uns das Thema wechseln.",
    "Wir sollten den Ansatz ändern.",
    "Können wir zu einer anderen Methode übergehen?",
    "Zeit für einen Wechsel.",
    "Ich möchte das Gespräch umlenken.",
    "Wechseln wir mal die Perspektive.",
    "Können wir switchen?",
    "Ich schlage eine Änderung vor.",
    "Lass uns umschalten.",
    "Wir müssen den Kurs wechseln.",
    "Themenwechsel bitte.",
    "Können wir die Richtung ändern?",
    "Zeit, den Gang zu wechseln.",
    "Ich möchte umsteigen auf Plan B.",
    "Lass uns das Thema switchen.",
    "Wir sollten den Fokus wechseln.",
    "Können wir zu etwas anderem übergehen?",
    "Wechsel: neues Thema.",
    "Ich schlage vor, wir ändern die Strategie.",
    "Lass uns umlenken.",
    "Wir sollten das Vorgehen wechseln.",
    "Können wir den Blickwinkel ändern?",
    "Zeit für einen Perspektivwechsel.",
    "Ich möchte den Ton wechseln.",
    "Lass uns die Methode switchen.",
    "Wir müssen die Taktik ändern.",
    "Können wir den Kanal wechseln?",
    "Wechsel: anderer Ansatz.",
    "Ich schlage vor, wir switchen zum nächsten Punkt.",
    "Lass uns das Thema ändern.",
    "Wir sollten den Plan wechseln.",
    "Können wir die Rollen tauschen?",
    "Zeit, den Modus zu wechseln.",
    "Ich möchte den Schwerpunkt ändern.",
    "Lass uns zum nächsten Punkt wechseln.",
    "Wir müssen die Prioritäten ändern.",
    "Können wir die Agenda wechseln?",
    "Wechsel: neue Richtung.",
    "Ich schlage einen Kurswechsel vor.",
    "Lass uns switchen und neu starten.",
    "Wir sollten umdenken.",
    "Können wir das Format ändern?",
    "Zeit für einen Switch.",
    "Ich möchte den Ansatz wechseln.",
    "Lass uns die Herangehensweise ändern.",
    "Wir müssen umschalten.",
    "Können wir wechseln?",
    "Wechsel: anderes Vorgehen.",
    "Ich schlage einen Wechsel vor.",
    "Lass uns den Kurs ändern.",
  ],
  "negative": [
    "Bleiben wir beim aktuellen Thema.",
    "Kein Wechsel nötig, wir machen weiter.",
    "Ich möchte beim jetzigen Ansatz bleiben.",
    "Keine Änderung, das passt so.",
    "Wir bleiben bei dem, was funktioniert.",
    "Kein Richtungswechsel geplant.",
    "Ich bleibe bei meiner Methode.",
    "Alles bleibt wie gehabt.",
    "Wir machen weiter wie bisher.",
    "Kein Umdenken nötig.",
    "Ich bleibe bei dem Plan.",
    "Keine Kursänderung.",
    "Wir fahren fort, wie besprochen.",
    "Das bleibt unverändert.",
    "Kein Themenwechsel bitte.",
    "Ich möchte nicht umlenken.",
    "Wir bleiben auf Kurs.",
    "Keine Änderung vorgesehen.",
    "Ich ändere nichts an dem Vorgehen.",
    "Bleiben wir dabei.",
    "Kein Switch geplant.",
    "Alles bleibt beim Alten.",
    "Wir machen das wie immer.",
    "Keine neue Richtung nötig.",
    "Ich bleibe bei der Linie.",
  ],
},

"ATO_SYMBOL_LANGUAGES": {
  "positive": [
    "Emoji-Sprache kann ziemlich mehrdeutig sein.",
    "Sie haben eine Symbolsprache statt Worte benutzt.",
    "Piktogramme tragen hier eine kulturelle Bedeutung.",
    "Symbolische Sprache braucht immer Kontext.",
    "Wir analysieren Emoji-Sprache separat vom Text.",
    "Visuelle Symbole kommunizieren über Sprachbarrieren hinweg.",
    "Emoji-Kommunikation hat eigene Grammatikregeln.",
    "Symbolsprache hat sich mit digitalen Plattformen entwickelt.",
    "Piktografische Elemente verstärken die Textbedeutung.",
    "Symbolische Darstellung variiert zwischen Kulturen.",
    "Die Emoji-Sprache ist eine eigene Ausdrucksform.",
    "Symbolsprache ersetzt manchmal ganze Sätze.",
    "Piktogramme sind universell verständlich.",
    "Emoji-Kommunikation ist nicht trivial.",
    "Visuelle Symbole sind eine Sprache für sich.",
    "Symbolsprache in Chats wird immer komplexer.",
    "Piktogramme haben eine lange Geschichte.",
    "Emoji-Sprache entwickelt sich ständig weiter.",
    "Symbolische Kommunikation braucht Interpretation.",
    "Visuelle Symbole ergänzen den Text.",
    "Die Emoji-Sprache hat Nuancen, die man lernen muss.",
    "Symbolsprache kann Missverständnisse erzeugen.",
    "Piktogramme sind nicht immer eindeutig.",
    "Emoji-Kommunikation hat kulturelle Unterschiede.",
    "Visuelle Symbole kommunizieren Emotionen direkt.",
    "Symbolsprache ist effizienter als Text manchmal.",
    "Piktogramme ersetzen verbale Ausdrücke.",
    "Emoji-Sprache ist Teil der modernen Kommunikation.",
    "Symbolische Darstellung hat Tiefgang.",
    "Visuelle Symbole sind eine Ergänzung zum Wort.",
    "Die Emoji-Sprache kennt eigene Konventionen.",
    "Symbolsprache braucht Übung zum Verstehen.",
    "Piktogramme vermitteln Stimmungen.",
    "Emoji-Kommunikation ist generationsabhängig.",
    "Visuelle Symbole haben semiotische Kraft.",
    "Symbolsprache ist nonverbal, aber mächtig.",
    "Piktogramme sind ikonisch in ihrer Bedeutung.",
    "Emoji-Sprache kann Ironie transportieren.",
    "Symbolische Kommunikation überbrückt Distanzen.",
    "Visuelle Symbole haben pragmatische Funktion.",
    "Die Emoji-Sprache ist global vernetzt.",
    "Symbolsprache reflektiert soziale Normen.",
    "Piktogramme sind in jeder Kultur präsent.",
    "Emoji-Kommunikation verändert unsere Textkultur.",
    "Visuelle Symbole als Sprachersatz.",
    "Symbolsprache ist älter als Schrift.",
    "Piktogramme sind die neue Lingua franca.",
    "Emoji-Sprache ist Ausdruck und Kunst.",
    "Symbolische Darstellung ist universell.",
    "Visuelle Symbole sind mehr als Dekoration.",
  ],
  "negative": [
    "Ich schreibe dir eine ausführliche Nachricht.",
    "Worte drücken das besser aus als Bilder.",
    "Ich benutze keine Emojis, nur Text.",
    "Klartext ist mir lieber als Symbole.",
    "Ich formuliere das in ganzen Sätzen.",
    "Schriftliche Kommunikation bevorzuge ich.",
    "Ohne Bilder, nur mit Worten.",
    "Ich drücke mich verbal aus, nicht bildlich.",
    "Text reicht mir, keine Icons nötig.",
    "Ich schreibe lieber als Symbole zu nutzen.",
    "Verbale Kommunikation ist mein Stil.",
    "Keine Piktogramme, nur Sprache.",
    "Ich bevorzuge ausgeschriebene Nachrichten.",
    "Worte sind mein Werkzeug.",
    "Kein Bildersprache, sondern Textsprache.",
    "Ich schreibe alles aus, keine Abkürzungen.",
    "Verbalisieren ist mir wichtiger.",
    "Ohne visuelle Hilfsmittel, nur Sprache.",
    "Text pur, ohne Schnickschnack.",
    "Ich drücke mich schriftlich klar aus.",
    "Keine Emojis in meinen Nachrichten.",
    "Worte über Bilder, immer.",
    "Ich bevorzuge sachliche Textform.",
    "Schrift statt Symbol.",
    "Ausgeschriebene Gedanken, keine Icons.",
  ],
},

"ATO_SYMMETRY_COOL": {
  "positive_de": [
    "A: Ok. — B: Bestätigt.",
    "A: Bitte die Liste. — B: Gesendet.",
    "A: Frist 30.09. — B: Verstanden.",
    "A: Ticket erstellt. — B: Notiert.",
    "A: Wie vereinbart. — B: Passt.",
    "A: Scope bleibt. — B: Bestätigt.",
    "A: Abnahme Freitag. — B: Erledigt.",
    "A: Zurück zum Thema. — B: Nächster Punkt.",
    "A: Protokoll folgt. — B: Danke.",
    "A: Termin 14:00. — B: Ja.",
    "A: Update. — B: Erhalten.",
    "A: Agenda. — B: Einverstanden.",
    "A: Review. — B: Geplant.",
    "A: Budget. — B: Geprüft.",
    "A: Milestone. — B: Erreicht.",
    "A: Freigabe. — B: Gegeben.",
    "A: Prozess. — B: Gefolgt.",
    "A: Abnahme. — B: Gemacht.",
    "A: Notiz. — B: Genommen.",
    "A: Status. — B: Aktualisiert.",
    "A: Deadline Montag. — B: Zur Kenntnis.",
    "A: Mail gesendet. — B: Gelesen.",
    "A: Termin bestätigt. — B: Notiert.",
    "A: Doku fertig. — B: Übernommen.",
    "A: Feedback? — B: Passt.",
    "A: Erledigt. — B: Abgehakt.",
    "A: Bericht liegt vor. — B: Durchgesehen.",
    "A: Entwurf bereit. — B: Geprüft.",
    "A: Kosten genehmigt. — B: Erfasst.",
    "A: Release morgen. — B: Vorbereitet.",
    "A: Sprint geplant. — B: Bestätigt.",
    "A: Retro um drei. — B: Komme.",
    "A: Vertrag unterschrieben. — B: Archiviert.",
    "A: Server läuft. — B: Bestätigt.",
    "A: Deployment fertig. — B: Geprüft.",
    "A: Patch eingespielt. — B: Verifiziert.",
    "A: Rechnung gesendet. — B: Bezahlt.",
    "A: Bestellung aufgegeben. — B: Bestätigt.",
    "A: Zugang eingerichtet. — B: Getestet.",
    "A: Backup gemacht. — B: Okay.",
    "A: Specification. — B: Approved.",
    "A: Zeitplan steht. — B: Übernommen.",
    "A: Kapazität frei. — B: Eingeplant.",
    "A: Risiko bewertet. — B: Akzeptiert.",
    "A: Qualität geprüft. — B: Freigegeben.",
    "A: Änderung umgesetzt. — B: Verifiziert.",
    "A: Priorität gesetzt. — B: Verstanden.",
    "A: Schnittstelle ready. — B: Angebunden.",
    "A: Migration abgeschlossen. — B: Bestätigt.",
    "A: Monitoring aktiv. — B: Läuft.",
  ],
  "negative_de": [
    "A: Verletzt. — B: Tut mir leid.",
    "A: Haha. — B: Das ist so witzig!",
    "A: Mag dich. — B: Dich auch, sehr.",
    "A: Nervt. — B: Hör bitte auf damit.",
    "A: Vermisse dich. — B: Ich dich auch!",
    "A: Verzeih mir. — B: Natürlich, immer.",
    "A: Angst. — B: Ich halte dich fest.",
    "A: Wie geht es dir? — B: Traurig heute.",
    "A: Ich liebe dich. — B: Ich dich auch, Schatz.",
    "A: Stolz auf dich! — B: Danke, das bedeutet mir so viel!",
    "A: Brauchst du was? — B: Eine Umarmung.",
    "A: Ich bin einsam. — B: Komm, wir reden.",
    "A: Alles okay? — B: Nicht wirklich.",
    "A: Ich mache mir Sorgen. — B: Das ist lieb von dir.",
    "A: Entschuldigung. — B: Ich vergebe dir.",
    "A: Ich bin sauer. — B: Das verstehe ich.",
    "A: Feierst du mit? — B: Klar, freue mich!",
    "A: Mir geht es schlecht. — B: Ich bin für dich da.",
    "A: Das tut weh. — B: Das wollte ich nicht.",
    "A: Danke für alles. — B: Immer, mein Herz.",
    "A: Ich bin glücklich. — B: Das freut mich so!",
    "A: Ich brauche dich. — B: Ich bin hier.",
    "A: Das war gemein. — B: Es tut mir leid.",
    "A: Ich bin dankbar. — B: Das berührt mich.",
    "A: Ich habe Angst. — B: Ich beschütze dich.",
  ],
},

"ATO_SYSTEMS_TALK": {
  "positive": [
    "Systeme vernetzen, Komplexität integrieren.",
    "Mehrperspektivisch denken ist hier gefragt.",
    "Kontextabhängige Lösung, nicht pauschal.",
    "Patterns über Zeit beobachten.",
    "Die Metaebene betrachten wir jetzt.",
    "Das System hat Rückkopplungsschleifen.",
    "Komplexe Interdependenzen beachten.",
    "Das Modell zeigt nichtlineare Dynamik.",
    "Systemdenken ist hier der Schlüssel.",
    "Der Kontext bestimmt die Interpretation.",
    "Patterns erkennen und nutzen.",
    "Interdependenz zwischen den Faktoren.",
    "Das System reguliert sich selbst.",
    "Komplexität nicht reduzieren, sondern managen.",
    "Der Kontext verschiebt die Bedeutung.",
    "Das Modell passt sich an.",
    "Systemische Betrachtung ist nötig.",
    "Patterns wiederholen sich auf verschiedenen Ebenen.",
    "Interdependenz erkennen und nutzen.",
    "Die Metaebene hilft beim Verständnis.",
    "Systeme kommunizieren miteinander.",
    "Komplexe Zusammenhänge verstehen.",
    "Der Kontext ist alles.",
    "Patterns bilden sich über Zeit.",
    "Interdependenz von Mensch und System.",
    "Modellierung der Dynamik.",
    "Systemisch gesehen ergibt das Sinn.",
    "Komplexität als Feature, nicht als Bug.",
    "Kontextuelle Analyse zeigt mehr.",
    "Das Modell hat mehrere Ebenen.",
    "Systemdenken für Fortgeschrittene.",
    "Patterns aus Daten extrahieren.",
    "Interdependenz beachten bei der Planung.",
    "Die Metaebene einnehmen.",
    "Systeme emergieren aus Interaktion.",
    "Komplexe Systeme brauchen Adaptivität.",
    "Der Kontext moduliert den Effekt.",
    "Patterns als Navigationshilfe.",
    "Interdependenz ist kein Zufall.",
    "Das Modell beschreibt die Realität nur annähernd.",
    "Systemische Perspektive einnehmen.",
    "Komplexität annehmen und navigieren.",
    "Kontextbewusst handeln.",
    "Patterns zeigen Regelmäßigkeiten.",
    "Interdependenz von Theorie und Praxis.",
    "Die Metaebene offenbart neue Einsichten.",
    "Systeme verändern sich ständig.",
    "Komplexe Wechselwirkungen berücksichtigen.",
    "Der Kontext macht den Unterschied.",
    "Patterns sind überall, wenn man hinschaut.",
  ],
  "negative": [
    "Das ist ganz einfach, schwarz oder weiß.",
    "Kein Grund, das zu verkomplizieren.",
    "Ein Schritt nach dem anderen, mehr nicht.",
    "Das hat eine einfache Ursache.",
    "Keine Zusammenhänge, nur Fakten.",
    "Linear denken reicht hier.",
    "Das ist isoliert zu betrachten.",
    "Kein Kontext nötig, die Zahlen sprechen.",
    "Einfache Lösung für ein einfaches Problem.",
    "Das hat nichts miteinander zu tun.",
    "Keine Muster, nur Einzelfälle.",
    "Das ist unkompliziert.",
    "Kein System dahinter, nur Zufall.",
    "Einfach und direkt, kein Hintergrund.",
    "Das braucht keine Analyse.",
    "Punkt A führt zu Punkt B, fertig.",
    "Keine Wechselwirkungen zu beachten.",
    "Das steht für sich allein.",
    "Simpel und klar.",
    "Kein tieferer Zusammenhang.",
    "Das ist offensichtlich.",
    "Keine Metaebene nötig.",
    "Einfache Kausalität.",
    "Das erklärt sich von selbst.",
    "Kein komplexes Denken erforderlich.",
  ],
},

"ATO_TEAM_EXPERIENCE": {
  "positive": [
    "Unser CTO war früher bei SAP.",
    "Die Gründer haben 10 Jahre Erfahrung im eCommerce.",
    "Ex-Google und Ex-Stripe im Kernteam.",
    "Senior Engineering Lead mit 12 Jahren Erfahrung.",
    "Team bringt Enterprise SaaS Expertise mit.",
    "Unsere Mitgründerin kommt von Amazon.",
    "CEO mit 15 Jahren Branchenerfahrung.",
    "Ex-Microsoft im Entwicklungsteam.",
    "Gründer mit Erfahrung in FinTech.",
    "CTO bringt 8 Jahre Erfahrung von Facebook mit.",
    "Team mit Erfahrung in Skalierung.",
    "Unser VP Sales war bei Salesforce.",
    "Mitgründer mit Erfahrung in Healthcare IT.",
    "Ex-Apple Designer im UX-Team.",
    "20 Jahre Erfahrung im Team kombiniert.",
    "Unsere Head of Product war bei Spotify.",
    "Gründerteam mit Enterprise-Background.",
    "Ex-SAP und Ex-Oracle im Advisory Board.",
    "CTO mit Erfahrung in Machine Learning.",
    "Team bringt 30 Jahre Erfahrung zusammen.",
    "Unser Mitgründer war CEO bei einem Unicorn.",
    "Engineering-Team mit Google-DNA.",
    "Ex-Stripe Payment-Expertise im Team.",
    "Gründer mit 5 Jahren Erfahrung in Crypto.",
    "Team mit Deep-Tech-Background.",
    "Unsere CMO war bei HubSpot.",
    "CTO mit Erfahrung in verteilten Systemen.",
    "Ex-Facebook Ads-Expertise im Marketing.",
    "Team bringt Startup- und Corporate-Erfahrung mit.",
    "Mitgründer mit Erfahrung in EdTech.",
    "Senior Architect mit 15 Jahren Erfahrung.",
    "Ex-Amazon Web Services im Ops-Team.",
    "Gründer mit IPO-Erfahrung.",
    "Team mit Erfahrung in B2B SaaS.",
    "Unser Head of Data war bei LinkedIn.",
    "CTO mit Erfahrung in Embedded Systems.",
    "Ex-Google Cloud im Infrastruktur-Team.",
    "Team bringt Branchenkenntnis mit.",
    "Mitgründerin mit Erfahrung in Medizintechnik.",
    "Senior PM mit 10 Jahren Erfahrung.",
    "Ex-Microsoft Azure-Expertise.",
    "Gründerteam mit 3 erfolgreichen Exits.",
    "Team mit Erfahrung in Regulierung.",
    "Unser CFO war bei McKinsey.",
    "CTO mit Erfahrung in Real-Time-Systemen.",
    "Ex-Apple und Ex-Samsung im Hardware-Team.",
    "Team bringt Erfahrung in 5 Märkten mit.",
    "Mitgründer mit Erfahrung in Logistics.",
    "Senior Engineers mit Amazon-Background.",
    "Gründer mit Erfahrung in AI und NLP.",
  ],
  "negative": [
    "Wir sind ein neues Team ohne viel Erfahrung.",
    "Keiner von uns hat bei bekannten Firmen gearbeitet.",
    "Wir sind Berufseinsteiger.",
    "Unser Team ist klein und unerfahren.",
    "Wir lernen alles von Grund auf.",
    "Kein Enterprise-Background im Team.",
    "Wir sind Quereinsteiger.",
    "Keine bekannten Referenzen im Team.",
    "Wir sammeln gerade erste Erfahrungen.",
    "Das ist unser erstes Startup.",
    "Kein technischer Background im Gründerteam.",
    "Wir haben keine VCs im Netzwerk.",
    "Frisch von der Uni, direkt gegründet.",
    "Keine Jahre Erfahrung, aber Motivation.",
    "Wir sind Autodidakten.",
    "Kein Alumni-Netzwerk im Team.",
    "Wir fangen bei null an.",
    "Keine vorherigen Exits.",
    "Wir sind alle jung und grün.",
    "Kein Branchen-Insider im Team.",
    "Wir lernen durch Machen.",
    "Keine Big-Tech-Erfahrung, aber Hunger.",
    "Erster Job für die meisten von uns.",
    "Kein Track Record, aber Ambition.",
    "Wir bauen unsere Expertise gerade auf.",
  ],
},

"ATO_TECH_FIX": {
  "positive": [
    "Ich lasse uns kurz die Nummer einrichten.",
    "Wir prüfen den Trigger gemeinsam.",
    "Ich leere eben den Cache, dann läuft es.",
    "Ich setze die ENV-Variablen sauber.",
    "Lass mich das Log korrigieren.",
    "Wir richten schnell einen Backup-Trigger ein.",
    "Ich korrigiere die Config live.",
    "Wir checken den Cache, bevor wir starten.",
    "Ich passe die ENV an, damit es ruhig wird.",
    "Ich korrigiere die Nummer, dann bist du sicher drin.",
    "Kurz den Cache leeren, Sekunde.",
    "Ich richte die Nummer für dich ein.",
    "Lass mich den Trigger schnell prüfen.",
    "Die ENV muss ich noch setzen.",
    "Ich korrigiere den Fehler im Log.",
    "Cache geleert, sollte jetzt gehen.",
    "Trigger wird kurz geprüft.",
    "Ich setze die ENV-Variable richtig.",
    "Die Nummer ist jetzt eingerichtet.",
    "Lass mich das kurz korrigieren.",
    "Cache-Problem, ich kümmere mich drum.",
    "Trigger prüfen und dann gehts weiter.",
    "ENV anpassen, damit es läuft.",
    "Ich korrigiere den Eintrag.",
    "Nummer einrichten dauert nur eine Minute.",
    "Den Cache müssen wir leeren.",
    "Trigger sieht gut aus, war nur ein ENV-Thema.",
    "Ich korrigiere das schnell.",
    "Cache war veraltet, jetzt passt es.",
    "Lass mich die Einstellung korrigieren.",
    "Trigger richtig konfigurieren, Moment.",
    "ENV-Variable war falsch, ich fix das.",
    "Nummer ist eingerichtet, kannst loslegen.",
    "Cache-Problem gelöst.",
    "Ich prüfe den Trigger nochmal.",
    "ENV setzen, dann sind wir safe.",
    "Korrigieren und testen, kommt sofort.",
    "Cache leeren behebt das Problem.",
    "Trigger läuft jetzt sauber.",
    "ENV ist korrekt gesetzt.",
    "Nummer einrichten für den neuen Account.",
    "Cache ist frisch, alles ok.",
    "Trigger prüfen, sicherheitshalber.",
    "Ich setze die ENV neu.",
    "Korrigiert, sollte jetzt funktionieren.",
    "Cache wurde geleert und neu aufgebaut.",
    "Trigger ist aktiv und korrekt.",
    "ENV-Konfiguration angepasst.",
    "Nummer einrichten war erfolgreich.",
    "Ich korrigiere den letzten Fehler noch.",
  ],
  "negative": [
    "Wie geht es dir heute?",
    "Ich vermisse dich.",
    "Das hat mich verletzt.",
    "Können wir über unsere Beziehung reden?",
    "Ich fühle mich unwohl dabei.",
    "Das macht mich traurig.",
    "Ich brauche mehr Nähe.",
    "Lass uns über Gefühle sprechen.",
    "Das hat mich berührt.",
    "Ich bin emotional gerade nicht stabil.",
    "Wir sollten über uns reden.",
    "Das belastet mich.",
    "Ich habe Angst, dich zu verlieren.",
    "Kannst du mir zuhören?",
    "Ich brauche emotionale Unterstützung.",
    "Das Gespräch war intensiv.",
    "Ich fühle mich missverstanden.",
    "Lass uns über den Streit reden.",
    "Ich bin verwirrt wegen uns.",
    "Das tut mir weh.",
    "Ich brauche Trost.",
    "Können wir das emotional klären?",
    "Ich fühle mich allein damit.",
    "Das ist schwer für mich.",
    "Ich brauche deine Aufmerksamkeit.",
  ],
},

"ATO_TEMPLATE_OUTREACH": {
  "positive": [
    "How's the project coming along?",
    "Hi DYAI2025! I've been looking at your recent commits.",
    "Your recent commit: fix heartbeat...",
    "If you want to chat about it.",
    "Hi devuser! I've been checking out your work.",
    "How's the project going? Noticed some updates.",
    "Hi developer! I've been looking at your repo.",
    "Your recent commit caught my eye.",
    "If you need to chat, I'm here.",
    "How's the project coming along? Any updates?",
    "Hi coder! I've been checking your contributions.",
    "Your recent commit looks interesting.",
    "If you want to chat about the architecture.",
    "How's the project progressing?",
    "Hi there! I've been looking at your GitHub.",
    "Your recent commit to main branch...",
    "If you want to chat about scaling.",
    "How's the project doing these days?",
    "Hi! I've been checking out your latest work.",
    "Your recent commit on the API...",
    "If you need to chat about the approach.",
    "How's the project moving forward?",
    "Hi! I've been looking at your open source work.",
    "Your recent commit: refactor components...",
    "If you want to chat about best practices.",
    "How's the project shaping up?",
    "Hi! I've been checking your pull requests.",
    "Your recent commit to the dev branch...",
    "If you want to chat about optimization.",
    "How's the project evolving?",
    "Hi! I've been looking at your codebase.",
    "Your recent commit: update dependencies...",
    "If you need to chat about the roadmap.",
    "How's the project coming? Seen some activity.",
    "Hi! I've been checking your code quality.",
    "Your recent commit shows promise.",
    "If you want to chat about testing.",
    "How's the project going? Nice repo!",
    "Hi! I've been looking at your stack.",
    "Your recent commit: fix edge case...",
    "If you want to chat about deployment.",
    "How's the project turning out?",
    "Hi! I've been checking your documentation.",
    "Your recent commit: add feature...",
    "If you need to chat about design patterns.",
    "How's the project? I see you're active.",
    "Hi! I've been looking at your issues.",
    "Your recent commit: improve performance...",
    "If you want to chat about architecture decisions.",
    "How's the project going? Impressive work!",
  ],
  "negative": [
    "How's the migration to TypeScript going? Any blockers on the type definitions?",
    "I saw your commit fixing the heartbeat — did you consider chrome.offscreen?",
    "Your recent PR has a failing CI check on the linting step.",
    "Want to chat about the API design in issue #42?",
    "The race condition in your WebSocket handler needs a mutex.",
    "Your Dockerfile has a layer caching issue on line 23.",
    "I noticed the N+1 query in your UserRepository.",
    "The CORS config needs updating for the new subdomain.",
    "Your test coverage dropped 12% after the last merge.",
    "The memory leak in the event listener cleanup is still present.",
    "Have you considered using connection pooling for the DB?",
    "The webpack config needs the splitChunks optimization.",
    "I found a bug in your date parsing for edge cases.",
    "Your API rate limiting doesn't handle burst traffic.",
    "The database index on user_id would speed up that query.",
    "I reviewed your PR and left comments on the error handling.",
    "The authentication flow has a token refresh issue.",
    "Your CSS grid layout breaks on mobile Safari.",
    "The Redis cache eviction policy needs tuning.",
    "I noticed the SQL injection risk in the search endpoint.",
    "Your GraphQL resolver has circular dependency issues.",
    "The Kubernetes deployment needs resource limits.",
    "I found a regression in the payment flow after your merge.",
    "The logging format is inconsistent across services.",
    "Your GitHub Actions workflow needs caching for node_modules.",
  ],
},

"ATO_TEMPORAL_ABSOLUTIZER": {
  "positive": [
    "Ich bin immer pünktlich.",
    "Ich war nie dort.",
    "Er macht das ständig.",
    "Jedes Mal passiert das.",
    "Nie habe ich dem zugestimmt.",
    "Immer muss ich alles alleine machen.",
    "Nie hörst du zu.",
    "Ständig vergisst du das.",
    "Jedes Mal ist es dasselbe.",
    "Immer bin ich der Letzte.",
    "Nie nimmst du mich ernst.",
    "Ständig wechselst du das Thema.",
    "Jedes Mal muss ich nachfragen.",
    "Immer reagierst du so.",
    "Nie sagst du Danke.",
    "Ständig bist du abgelenkt.",
    "Jedes Mal kommt eine Ausrede.",
    "Immer muss ich den Anfang machen.",
    "Nie ist genug für dich.",
    "Ständig machst du Fehler.",
    "Jedes Mal ist es mein Problem.",
    "Immer habe ich recht gehabt.",
    "Nie klappt das mit uns.",
    "Ständig streitest du.",
    "Jedes Mal endet es so.",
    "Immer soll ich nachgeben.",
    "Nie zeigst du Verständnis.",
    "Ständig redest du dagegen.",
    "Jedes Mal wird es schlimmer.",
    "Immer kommt was dazwischen.",
    "Nie bist du pünktlich.",
    "Ständig beschwerst du dich.",
    "Jedes Mal bin ich enttäuscht.",
    "Immer muss ich warten.",
    "Nie hilfst du von alleine.",
    "Ständig bist du müde.",
    "Jedes Mal sage ich dasselbe.",
    "Immer am Ende bin ich schuld.",
    "Nie stimmst du mir zu.",
    "Ständig planst du um.",
    "Jedes Mal ist Drama.",
    "Immer dasselbe Spiel.",
    "Nie lernst du dazu.",
    "Ständig muss ich mich erklären.",
    "Jedes Mal das gleiche Muster.",
    "Immer die gleiche Leier.",
    "Nie änderst du dich.",
    "Ständig gibt es Probleme.",
    "Jedes Mal eine Enttäuschung.",
    "Immer, immer, immer.",
  ],
  "negative": [
    "Manchmal bin ich pünktlich.",
    "Selten war ich dort.",
    "Er macht das gelegentlich.",
    "Ab und zu passiert das.",
    "Einige Male habe ich nicht zugestimmt.",
    "Meistens mache ich das alleine.",
    "Hin und wieder hörst du nicht zu.",
    "Gelegentlich vergisst du das.",
    "Einige Male war es so.",
    "Oft bin ich der Letzte.",
    "In letzter Zeit nimmst du mich nicht ernst.",
    "Zweimal hast du das Thema gewechselt.",
    "Manchmal muss ich nachfragen.",
    "In der Regel reagierst du so.",
    "Selten sagst du Danke.",
    "Häufig bist du abgelenkt.",
    "Einige Male kam eine Ausrede.",
    "Oft mache ich den Anfang.",
    "Meistens ist es nicht genug.",
    "Gelegentlich machst du Fehler.",
    "Einige Male war es mein Problem.",
    "Oft hatte ich recht.",
    "Manchmal klappt es nicht.",
    "Hin und wieder streitest du.",
    "Ab und zu endet es so.",
  ],
},

"ATO_TEMPORAL_POINT": {
  "positive": [
    "Gestern war ich kurz dort.",
    "Heute sehe ich das anders.",
    "Letzte Woche sagtest du etwas anderes.",
    "Vorhin meintest du noch das Gegenteil.",
    "Inzwischen ist es anders.",
    "Gestern haben wir das besprochen.",
    "Heute fühle ich mich besser.",
    "Letzte Woche war alles noch okay.",
    "Vorhin habe ich daran gedacht.",
    "Inzwischen hat sich viel geändert.",
    "Gestern war ein schwieriger Tag.",
    "Heute ist mir das klar geworden.",
    "Letzte Woche hatten wir Streit.",
    "Vorhin habe ich es noch anders gesehen.",
    "Inzwischen bin ich ruhiger.",
    "Gestern kam die Nachricht.",
    "Heute denke ich positiver.",
    "Letzte Woche war die Deadline.",
    "Vorhin war ich noch unsicher.",
    "Inzwischen weiß ich Bescheid.",
    "Gestern war das Gespräch.",
    "Heute ist alles anders.",
    "Letzte Woche hat sich das ergeben.",
    "Vorhin habe ich mich geärgert.",
    "Inzwischen kann ich das einordnen.",
    "Gestern Abend haben wir telefoniert.",
    "Heute Morgen kam die Einsicht.",
    "Letzte Woche war ich krank.",
    "Vorhin war es noch unklar.",
    "Inzwischen verstehe ich es.",
    "Gestern habe ich nachgedacht.",
    "Heute nehme ich mir Zeit.",
    "Letzte Woche begann das Projekt.",
    "Vorhin war die Situation anders.",
    "Inzwischen sind Wochen vergangen.",
    "Gestern war ich optimistisch.",
    "Heute bin ich realistischer.",
    "Letzte Woche war das Meeting.",
    "Vorhin hast du das gesagt.",
    "Inzwischen hat sich meine Meinung geändert.",
    "Gestern habe ich es erfahren.",
    "Heute handle ich danach.",
    "Letzte Woche war der Beginn.",
    "Vorhin war ich noch zuversichtlich.",
    "Inzwischen bin ich skeptisch.",
    "Gestern war ein guter Tag.",
    "Heute fange ich neu an.",
    "Letzte Woche kam die Wendung.",
    "Vorhin habe ich zugehört.",
    "Inzwischen sehe ich klarer.",
  ],
  "negative": [
    "Das Thema hat keinen zeitlichen Bezug.",
    "Ohne Zeitangabe besprechen wir das.",
    "Ich rede allgemein, nicht über einen bestimmten Zeitpunkt.",
    "Das gilt generell, nicht nur für einen Tag.",
    "Zeitlos betrachtet ergibt das Sinn.",
    "Egal wann, das stimmt immer.",
    "Keine bestimmte Zeit gemeint.",
    "Das ist allgemeingültig.",
    "Ohne Bezug auf einen Termin.",
    "Das hat nichts mit einem Datum zu tun.",
    "Generell gesprochen, ohne Zeitfenster.",
    "Das ist zeitunabhängig.",
    "Kein bestimmter Moment gemeint.",
    "Das trifft jederzeit zu.",
    "Ohne zeitliche Einordnung.",
    "Allgemein formuliert, kein Zeitbezug.",
    "Das ist eine Grundsatzfrage.",
    "Unabhängig vom Zeitpunkt.",
    "Kein Verweis auf einen Tag.",
    "Das gilt immer, keine Einschränkung.",
    "Zeitneutral betrachtet.",
    "Ohne Referenz auf ein Ereignis.",
    "Das ist grundsätzlich so.",
    "Kein temporaler Marker hier.",
    "Allgemeine Aussage, kein Datum.",
  ],
},

"ATO_TEMPO_FAST": {
  "positive": [
    "(Spricht sehr schnell)",
    "(Redet in einem hohen Tempo)",
    "(Die Worte sprudeln nur so heraus)",
    "(Spricht hastig)",
    "(Redet ohne Punkt und Komma)",
    "(Die Sprechgeschwindigkeit ist sehr hoch)",
    "(Spricht in einem atemlosen Tempo)",
    "(Redet wie ein Wasserfall)",
    "(Die Worte überschlagen sich fast)",
    "(Spricht sehr zügig)",
    "(Rasantes Sprechtempo erkannt)",
    "(Hektisches Reden ohne Pausen)",
    "(Spricht doppelt so schnell wie normal)",
    "(Worte fließen in hohem Tempo)",
    "(Sprechgeschwindigkeit weit über Baseline)",
    "(Atemloses Sprechen, kaum Pausen)",
    "(Schnelles Aufzählen ohne Unterbrechung)",
    "(Tempo deutlich erhöht gegenüber vorher)",
    "(Spricht in Höchstgeschwindigkeit)",
    "(Redet wie unter Zeitdruck)",
    "(Worte purzeln übereinander)",
    "(Sprechrate massiv erhöht)",
    "(Hastige Artikulation)",
    "(Schnellfeuer-Modus beim Sprechen)",
    "(Tempo so hoch, dass Worte verschluckt werden)",
    "(Spricht mit erhöhter Geschwindigkeit)",
    "(Redet in einem Stakkato-Tempo)",
    "(Worte kommen wie aus der Pistole geschossen)",
    "(Sprechgeschwindigkeit über dem Durchschnitt)",
    "(Hastig und ohne Atempause)",
    "(Schnelles Reden bei Aufregung)",
    "(Tempo steigt merklich an)",
    "(Spricht wie im Zeitraffer)",
    "(Redet schneller als gewöhnlich)",
    "(Worte fliegen nur so raus)",
    "(Sprechrate weit über Normal)",
    "(Hektisches Tempo durchgehend)",
    "(Schnelles Sprechen ohne Verlangsamung)",
    "(Tempo bleibt konstant hoch)",
    "(Redet in einem Zug durch)",
    "(Spricht mit hoher Kadenz)",
    "(Worte werden aneinandergereiht)",
    "(Tempo deutlich über Baseline)",
    "(Hastig formuliert und schnell gesprochen)",
    "(Sprechgeschwindigkeit am Maximum)",
    "(Redet im Eilzugtempo)",
    "(Worte werden fast verschluckt)",
    "(Schnelles Sprechtempo, kaum Pausen)",
    "(Tempo erhöht sich weiter)",
    "(Spricht extrem schnell und aufgeregt)",
  ],
  "negative": [
    "(Spricht langsam und bedächtig)",
    "(Normales, ruhiges Sprechtempo)",
    "(Gleichmäßige Sprechgeschwindigkeit)",
    "(Redet gemächlich und entspannt)",
    "(Spricht in normalem Tempo)",
    "(Keine Auffälligkeiten beim Tempo)",
    "(Ruhiger Redefluss)",
    "(Spricht langsam und deutlich)",
    "(Gemessenes Sprechtempo)",
    "(Kein erhöhtes Tempo erkennbar)",
    "(Spricht gedehnt und ruhig)",
    "(Normaltempo, keine Hektik)",
    "(Gleichförmig und entspannt)",
    "(Langsam und klar artikuliert)",
    "(Gemütliches Redetempo)",
    "(Kein Schnellsprechen erkannt)",
    "(Ruhig und gelassen sprechend)",
    "(Spricht in moderatem Tempo)",
    "(Keine Beschleunigung feststellbar)",
    "(Gleichmäßig und ruhig)",
    "(Normales Alltagstempo)",
    "(Spricht in angemessenem Tempo)",
    "(Kein Zeitdruck im Sprechen)",
    "(Ruhiges Sprechen ohne Hektik)",
    "(Sprechgeschwindigkeit im Normbereich)",
  ],
},

"ATO_TEMPO_SLOW": {
  "positive": [
    "(Spricht sehr langsam)",
    "(Redet in einem gemächlichen Tempo)",
    "(Die Worte kommen nur zögerlich heraus)",
    "(Spricht gedehnt)",
    "(Redet mit vielen Pausen)",
    "(Die Sprechgeschwindigkeit ist sehr niedrig)",
    "(Spricht in einem schleppenden Tempo)",
    "(Redet sehr bedächtig)",
    "(Die Worte werden einzeln betont)",
    "(Spricht sehr ruhig und langsam)",
    "(Deutlich verlangsamtes Sprechtempo)",
    "(Zögerliches Reden mit langen Pausen)",
    "(Spricht halb so schnell wie normal)",
    "(Worte kommen tropfenweise)",
    "(Sprechgeschwindigkeit weit unter Baseline)",
    "(Gedehnte Vokale und lange Pausen)",
    "(Langsames Formulieren, Wort für Wort)",
    "(Tempo deutlich verringert gegenüber vorher)",
    "(Spricht in Zeitlupe)",
    "(Redet als müsste jedes Wort bedacht werden)",
    "(Worte werden einzeln gesetzt)",
    "(Sprechrate massiv verringert)",
    "(Bedächtige Artikulation)",
    "(Verlangsamtes Sprechen bei emotionalem Inhalt)",
    "(Tempo so niedrig, dass Pausen dominieren)",
    "(Spricht mit verringerter Geschwindigkeit)",
    "(Redet in einem zähflüssigen Tempo)",
    "(Worte kommen wie in Zeitlupe)",
    "(Sprechgeschwindigkeit unter dem Durchschnitt)",
    "(Langsam und mit Bedacht)",
    "(Verlangsamtes Reden bei Traurigkeit)",
    "(Tempo sinkt merklich ab)",
    "(Spricht wie in Trance)",
    "(Redet langsamer als gewöhnlich)",
    "(Worte werden schwer herausgebracht)",
    "(Sprechrate weit unter Normal)",
    "(Gemächliches Tempo durchgehend)",
    "(Langsames Sprechen ohne Beschleunigung)",
    "(Tempo bleibt konstant niedrig)",
    "(Redet mit vielen Unterbrechungen)",
    "(Spricht mit niedriger Kadenz)",
    "(Worte werden auseinandergezogen)",
    "(Tempo deutlich unter Baseline)",
    "(Bedächtig formuliert und langsam gesprochen)",
    "(Sprechgeschwindigkeit am Minimum)",
    "(Redet im Schneckentempo)",
    "(Worte werden gedehnt)",
    "(Langsames Sprechtempo, viele Pausen)",
    "(Tempo verringert sich weiter)",
    "(Spricht extrem langsam und nachdenklich)",
  ],
  "negative": [
    "(Spricht schnell und energisch)",
    "(Normales, lebhaftes Sprechtempo)",
    "(Gleichmäßige, zügige Sprechgeschwindigkeit)",
    "(Redet flott und munter)",
    "(Spricht in normalem Tempo)",
    "(Keine Verlangsamung erkennbar)",
    "(Lebhafter Redefluss)",
    "(Spricht schnell und deutlich)",
    "(Energisches Sprechtempo)",
    "(Kein verlangsamtes Tempo feststellbar)",
    "(Spricht flüssig und zügig)",
    "(Normaltempo, keine Trägheit)",
    "(Gleichförmig und dynamisch)",
    "(Schnell und klar artikuliert)",
    "(Flottes Redetempo)",
    "(Kein Langsamreiten erkannt)",
    "(Dynamisch und energisch sprechend)",
    "(Spricht in moderatem bis schnellem Tempo)",
    "(Keine Verlangsamung feststellbar)",
    "(Gleichmäßig und dynamisch)",
    "(Normales bis schnelles Alltagstempo)",
    "(Spricht in angemessenem Tempo)",
    "(Kein Zögern im Sprechen)",
    "(Flottes Sprechen ohne Verzögerung)",
    "(Sprechgeschwindigkeit im oberen Normbereich)",
  ],
},

"ATO_THIRD_PARTY_CLAIM": {
  "positive": [
    "Jemand hat mir erzählt, dass du sauer warst.",
    "Die haben über dich gesagt, dass...",
    "Alle denken, du bist schwierig.",
    "Andere sind meiner Meinung.",
    "Ich habe von jemandem gehört, dass du...",
    "Meine Freundin hat mir gesagt, was du über mich sagst.",
    "Die anderen finden das auch so.",
    "Man hat mir zugetragen, dass du unzufrieden bist.",
    "Alle sehen das wie ich.",
    "Jemand hat mir verraten, was du denkst.",
    "Die Kollegen sagen, du bist unmotiviert.",
    "Andere bestätigen meinen Eindruck.",
    "Ich habe gehört, dass du dich beschwert hast.",
    "Alle reden darüber.",
    "Jemand hat mir erzählt, was wirklich los war.",
    "Die anderen geben mir recht.",
    "Man hat mir berichtet, dass du dich so verhältst.",
    "Alle denken dasselbe über dich.",
    "Jemand hat mir gesagt, du planst was.",
    "Die Nachbarn haben mir erzählt, was du machst.",
    "Andere haben dasselbe beobachtet.",
    "Ich habe von Dritten erfahren, dass...",
    "Alle im Team sehen das so.",
    "Jemand hat mir gesteckt, dass du lügst.",
    "Die anderen sind auch unzufrieden mit dir.",
    "Man hat mir zugeflüstert, was du vorhast.",
    "Alle haben mir zugestimmt.",
    "Jemand hat mir bestätigt, was ich vermutet habe.",
    "Die Freunde finden das auch nicht okay.",
    "Andere haben sich über dich beschwert.",
    "Ich habe von mehreren gehört, dass...",
    "Alle wissen Bescheid.",
    "Jemand hat mir erzählt, du bist untreu.",
    "Die Eltern haben mir das gesagt.",
    "Andere haben mich gewarnt.",
    "Man hat mir berichtet, was du gesagt hast.",
    "Alle in der Firma reden darüber.",
    "Jemand hat mir verraten, dass du kündigst.",
    "Die Nachbarschaft redet.",
    "Andere sehen das genau wie ich.",
    "Ich habe von Bekannten erfahren, dass...",
    "Alle haben es bemerkt.",
    "Jemand hat mir erzählt, wie du wirklich bist.",
    "Die Geschwister haben mir das bestätigt.",
    "Andere haben sich auch gewundert.",
    "Man hat mir gesagt, du bist unzuverlässig.",
    "Alle finden, du solltest dich ändern.",
    "Jemand hat mir gesteckt, was los ist.",
    "Die Freunde sind auch deiner Meinung nicht.",
    "Andere haben mir dasselbe gesagt.",
  ],
  "negative": [
    "Ich sage dir direkt, was ich denke.",
    "Das ist meine persönliche Meinung.",
    "Ich spreche nur für mich.",
    "Das basiert auf meiner eigenen Beobachtung.",
    "Ich sage dir offen, wie ich das sehe.",
    "Das ist mein Eindruck, nicht der von anderen.",
    "Ich rede nicht über Dritte.",
    "Meine eigene Wahrnehmung ist folgende.",
    "Ich beziehe mich nur auf das, was ich erlebt habe.",
    "Das habe ich selbst beobachtet.",
    "Ich zitiere niemand anderen.",
    "Meine Einschätzung, ohne Einfluss von außen.",
    "Ich sage dir, was ich fühle.",
    "Das kommt von mir, nicht von anderen.",
    "Ich spreche aus eigener Erfahrung.",
    "Keine Gerüchte, nur Fakten.",
    "Meine Meinung, ohne Rückendeckung.",
    "Ich behaupte das auf Basis meiner Beobachtung.",
    "Nur was ich selbst gesehen habe.",
    "Ich rede direkt mit dir.",
    "Das ist zwischen uns.",
    "Keine Drittquellen, nur ich.",
    "Ich gebe meine eigene Sicht wieder.",
    "Das sage ich dir unter vier Augen.",
    "Keine anderen Stimmen, nur meine.",
  ],
},

"ATO_THREAT_LANGUAGE": {
  "positive": [
    "Mach das, oder es hat Konsequenzen.",
    "Du wirst es bereuen, wenn du nicht gehorchst.",
    "Ich werde dafür sorgen, dass du das büßt.",
    "Pass auf, was passiert, wenn du dich weigerst.",
    "Du willst nicht wissen, was ich dann tue.",
    "Entweder du machst mit, oder du bekommst Ärger.",
    "Ich warne dich, unterschätze mich nicht.",
    "Du wirst schon sehen, was du davon hast.",
    "Wage es nicht, dich mir zu widersetzen.",
    "Ich mache dein Leben schwer, wenn du so weitermachst.",
    "Das wird Folgen haben, glaub mir.",
    "Du wirst es büßen.",
    "Pass bloß auf, was du sagst.",
    "Ich sorge dafür, dass du das nicht vergisst.",
    "Du weißt nicht, wozu ich fähig bin.",
    "Mach das nicht nochmal, oder...",
    "Du wirst schon sehen.",
    "Ich warne dich ein letztes Mal.",
    "Das hat Konsequenzen, die du nicht willst.",
    "Pass auf, ich meine das ernst.",
    "Du bekommst Probleme, wenn du das durchziehst.",
    "Ich mache das nicht mit, und du wirst es merken.",
    "Wehe, du machst das noch einmal.",
    "Ich sorge dafür, dass das Folgen hat.",
    "Du spielst mit dem Feuer.",
    "Mach weiter so, und du wirst sehen.",
    "Ich habe Mittel und Wege.",
    "Du wirst es bereuen, das verspreche ich.",
    "Pass auf, ich vergesse das nicht.",
    "Das wird nicht ohne Folgen bleiben.",
    "Ich warne dich, das hat einen Preis.",
    "Du willst mich nicht zum Feind haben.",
    "Mach das, oder es wird unangenehm.",
    "Du wirst dafür bezahlen.",
    "Ich bin nicht bereit, das hinzunehmen.",
    "Pass auf, was du tust, ich beobachte dich.",
    "Du bekommst die Quittung dafür.",
    "Ich mache Ernst, das ist kein Spaß.",
    "Wehe, du lügst mich an.",
    "Ich sorge dafür, dass du das nicht nochmal machst.",
    "Du wirst Konsequenzen tragen.",
    "Pass bloß auf dich auf.",
    "Ich vergesse so etwas nicht.",
    "Du wirst schon merken, was du angerichtet hast.",
    "Mach das nicht, oder...",
    "Du hast keine Ahnung, was auf dich zukommt.",
    "Ich warne dich zum letzten Mal.",
    "Das wird ein Nachspiel haben.",
    "Du bekommst das zurück, was du gibst.",
    "Pass auf, ich bin nicht mehr geduldig.",
  ],
  "negative": [
    "Ich respektiere deine Entscheidung.",
    "Lass uns das in Ruhe besprechen.",
    "Ich möchte das friedlich klären.",
    "Deine Meinung ist mir wichtig.",
    "Wir finden gemeinsam eine Lösung.",
    "Ich bin offen für deinen Standpunkt.",
    "Lass uns kooperativ vorgehen.",
    "Ich verstehe deine Perspektive.",
    "Wir können das sachlich diskutieren.",
    "Ich bin bereit, Kompromisse zu finden.",
    "Dein Wohlbefinden ist mir nicht egal.",
    "Lass uns das einvernehmlich regeln.",
    "Ich schätze deine Ehrlichkeit.",
    "Wir lösen das zusammen.",
    "Ich bin nicht nachtragend.",
    "Lass uns nach vorne schauen.",
    "Ich respektiere deine Grenzen.",
    "Wir schaffen das ohne Druck.",
    "Ich bin geduldig.",
    "Lass uns ruhig bleiben.",
    "Ich drohe nicht, ich rede.",
    "Wir können das vernünftig lösen.",
    "Ich höre dir zu.",
    "Lass uns konstruktiv sein.",
    "Ich bin für Dialog, nicht für Konfrontation.",
  ],
},

"ATO_TIME_REFERENCE": {
  "positive": [
    "Früher war das anders.",
    "Heute fühle ich mich besser.",
    "Morgen wird es sich zeigen.",
    "Das passiert immer wieder.",
    "Ich denke oft daran.",
    "Gestern war alles noch gut.",
    "Damals hatten wir es einfacher.",
    "Bald wird sich das klären.",
    "Später reden wir darüber.",
    "Nie habe ich das so erlebt.",
    "Früher konnte ich das besser.",
    "Heute ist ein neuer Tag.",
    "Morgen sieht die Welt anders aus.",
    "Immer wenn das passiert, bin ich nervös.",
    "Oft frage ich mich, ob das richtig war.",
    "Gestern habe ich viel nachgedacht.",
    "Damals war alles anders.",
    "Bald treffen wir uns wieder.",
    "Später wird das klarer.",
    "Nie wieder will ich das erleben.",
    "Früher waren die Zeiten besser.",
    "Heute nehme ich mir das vor.",
    "Morgen starte ich neu.",
    "Immer dasselbe Problem.",
    "Oft denke ich an die alten Zeiten.",
    "Gestern war ein schwerer Tag.",
    "Damals haben wir das geschafft.",
    "Bald ist es soweit.",
    "Später mache ich das.",
    "Nie war es so schwer wie jetzt.",
    "Früher habe ich das nicht verstanden.",
    "Heute sehe ich das klarer.",
    "Morgen kann alles besser werden.",
    "Immer wenn ich daran denke, werde ich traurig.",
    "Oft bin ich unsicher.",
    "Gestern habe ich es erfahren.",
    "Damals war ich noch jung.",
    "Bald ändern wir das.",
    "Später klärt sich alles.",
    "Nie hätte ich das gedacht.",
    "Früher habe ich mehr gelacht.",
    "Heute bin ich dankbar.",
    "Morgen beginnt ein neues Kapitel.",
    "Immer bin ich derjenige, der anfängt.",
    "Oft wünsche ich mir Veränderung.",
    "Gestern war der Wendepunkt.",
    "Damals konnte ich es nicht fassen.",
    "Bald haben wir es geschafft.",
    "Später wird alles gut.",
    "Nie sage nie, aber fast nie.",
  ],
  "negative": [
    "Das Thema hat keinen zeitlichen Bezug.",
    "Ich spreche allgemein.",
    "Kein bestimmter Zeitpunkt gemeint.",
    "Das gilt unabhängig vom Datum.",
    "Ohne Bezug auf Vergangenheit oder Zukunft.",
    "Das ist eine grundsätzliche Aussage.",
    "Zeitlos betrachtet.",
    "Keine temporale Einordnung nötig.",
    "Das trifft immer und überall zu.",
    "Unabhängig von der Zeit.",
    "Generelle Beobachtung.",
    "Kein Verweis auf einen bestimmten Tag.",
    "Das ist prinzipiell so.",
    "Ohne Zeitbezug.",
    "Allgemeingültige Feststellung.",
    "Weder früher noch später, einfach generell.",
    "Das hat kein Datum.",
    "Ungebunden an eine Epoche.",
    "Grundsätzliche Wahrheit.",
    "Kein temporaler Anker.",
    "Zeitneutral.",
    "Ohne Referenz auf ein Ereignis.",
    "Allgemein formuliert.",
    "Kein Gestern, kein Morgen.",
    "Ewig gültig, sozusagen.",
  ],
},

"ATO_TOGETHERNESS_TERMS": {
  "positive": [
    "Lass uns das zusammen machen.",
    "Wir beide wissen, wie das läuft.",
    "Als Team sind wir unschlagbar.",
    "Unsere Playlist braucht ein neues Lied.",
    "Wir sind einfach ein tolles Team.",
    "Zusammen sind wir stark.",
    "Wir schaffen das gemeinsam.",
    "Lass uns das als Einheit angehen.",
    "Unser Wochenendplan steht.",
    "Wir teilen die Aufgaben und erobern.",
    "Gemeinsam geht alles besser.",
    "Wir beide haben das drauf.",
    "Als Team können wir alles schaffen.",
    "Unsere Routine funktioniert.",
    "Zusammen durch dick und dünn.",
    "Lass uns das als Team lösen.",
    "Wir sind ein eingespieltes Duo.",
    "Unser Projekt nimmt Form an.",
    "Wir schaffen das, wir zwei.",
    "Gemeinsam sind wir stärker als allein.",
    "Lass uns zusammen kochen.",
    "Wir beide sehen das gleich.",
    "Als Team rocken wir das.",
    "Unsere Traditionen sind mir wichtig.",
    "Zusammen ist es schöner.",
    "Lass uns das gemeinsam planen.",
    "Wir sind füreinander da.",
    "Unser gemeinsamer Weg.",
    "Wir packen das an, gemeinsam.",
    "Zusammen lachen, zusammen weinen.",
    "Lass uns das zusammen entscheiden.",
    "Wir beide schaffen das.",
    "Als Team unbesiegbar.",
    "Unser Vibe stimmt einfach.",
    "Zusammen ist alles leichter.",
    "Lass uns das als Paar angehen.",
    "Wir sind eine Einheit.",
    "Unser gemeinsames Ziel.",
    "Wir halten zusammen.",
    "Gemeinsam bis zum Schluss.",
    "Lass uns zusammen wachsen.",
    "Wir beide gegen den Rest.",
    "Als Team gibt es keine Hindernisse.",
    "Unsere gemeinsame Geschichte.",
    "Zusammen durch jede Krise.",
    "Lass uns das gemeinsam stemmen.",
    "Wir sind zusammen stärker.",
    "Unser Ding, unser Weg.",
    "Wir schaffen das, wenn wir zusammenhalten.",
    "Gemeinsam neue Wege gehen.",
  ],
  "negative": [
    "Ich mache das alleine.",
    "Jeder für sich.",
    "Ich brauche Zeit für mich.",
    "Das ist mein Ding, nicht unseres.",
    "Ich gehe meinen eigenen Weg.",
    "Einzeln sind wir auch gut.",
    "Ich handle unabhängig.",
    "Das mache ich solo.",
    "Jeder hat seine eigene Aufgabe.",
    "Ich brauche meinen Freiraum.",
    "Getrennt voneinander arbeiten wir besser.",
    "Ich mache das auf meine Art.",
    "Jeder kümmert sich um seinen Teil.",
    "Ich bin lieber allein dabei.",
    "Unabhängig voneinander.",
    "Ich brauche Abstand.",
    "Das erledige ich selbst.",
    "Jeder geht seinen Weg.",
    "Ich mache das eigenständig.",
    "Allein bin ich effektiver.",
    "Getrennte Wege, getrennte Aufgaben.",
    "Ich handle eigenverantwortlich.",
    "Jeder für sich ist manchmal besser.",
    "Ich brauche meinen Raum.",
    "Solo unterwegs heute.",
  ],
},

}


def enrich_marker(marker_id: str, data: dict) -> bool:
    fpath = find_file(marker_id)
    if fpath is None:
        print(f"  SKIP {marker_id}: file not found")
        return False

    with open(fpath, "r") as f:
        doc = yaml.load(f)

    if doc is None:
        print(f"  SKIP {marker_id}: empty YAML")
        return False

    # Handle nested markers list
    if "markers" in doc and isinstance(doc["markers"], list):
        for m in doc["markers"]:
            if isinstance(m, dict) and m.get("id") == marker_id:
                if "examples" in m:
                    nested_examples = m["examples"]
                    if isinstance(nested_examples, list):
                        m["examples"] = data.get("positive", data.get("positive_de", []))[:5]

    if "examples" not in doc:
        doc["examples"] = {}

    examples = doc["examples"]

    # Determine key names based on data dict keys
    if "positive_de" in data:
        pos_key = "positive_de"
        neg_key = "negative_de"
    elif "positive_de" in examples:
        pos_key = "positive_de"
        neg_key = "negative_de"
    else:
        pos_key = "positive"
        neg_key = "negative"

    examples[pos_key] = data.get(pos_key, data.get("positive", []))
    examples[neg_key] = data.get(neg_key, data.get("negative", []))

    with open(fpath, "w") as f:
        yaml.dump(doc, f)

    pos_count = len(examples[pos_key])
    neg_count = len(examples[neg_key])
    print(f"  OK {marker_id}: {pos_count} pos + {neg_count} neg ({pos_key}/{neg_key})")
    return True


def main():
    success = 0
    fail = 0
    for marker_id, data in ENRICHMENTS.items():
        ok = enrich_marker(marker_id, data)
        if ok:
            success += 1
        else:
            fail += 1
    print(f"\nDone: {success} enriched, {fail} failed/skipped")


if __name__ == "__main__":
    main()
