#!/usr/bin/env python3
"""
Enrich ATO markers (batch 5: S-W range) with 50 positive + 25 negative German examples.
Uses ruamel.yaml to preserve formatting. Detects existing key names (positive/positive_de).
"""

import os
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
yaml.allow_duplicate_keys = True

BASE = Path("/Users/benjaminpoersch/Projects/LeanDeep-annotator/build/markers_rated")
DIRS = [BASE / "1_approved" / "ATO", BASE / "2_good" / "ATO"]


def find_file(marker_id: str) -> Path | None:
    for d in DIRS:
        p = d / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None


# ── All 79 markers with their enrichment data ──────────────────────────

ENRICHMENTS = {

"ATO_SOFTENING": {
  "positive": [
    "Das war vielleicht nicht ganz so gemeint.",
    "Ich bin ein bisschen unsicher, ob das passt.",
    "Gefühlt war das schon okay.",
    "Irgendwie finde ich das schwierig.",
    "Das ist nicht ganz mein Ding.",
    "Vielleicht sollten wir nochmal darüber reden.",
    "Ein bisschen mehr Zeit wäre gut.",
    "Gefühlt wird das zu eng mit dem Termin.",
    "Irgendwie hatte ich mir das anders vorgestellt.",
    "Das war vielleicht etwas zu direkt von mir.",
    "Ich bin ein bisschen enttäuscht, ehrlich gesagt.",
    "Vielleicht habe ich mich unklar ausgedrückt.",
    "Gefühlt passt der Zeitplan nicht ganz.",
    "Irgendwie stresst mich das gerade.",
    "Das ist nicht ganz das, was ich meinte.",
    "Ein bisschen Abstand würde uns guttun.",
    "Vielleicht bin ich da zu empfindlich.",
    "Gefühlt wird das immer komplizierter.",
    "Irgendwie fehlt mir da die Klarheit.",
    "Das war nicht ganz fair, finde ich.",
    "Vielleicht übertreibe ich auch.",
    "Ein bisschen mehr Respekt wäre schön.",
    "Gefühlt war das nicht so geplant.",
    "Irgendwie komme ich da nicht weiter.",
    "Das ist vielleicht auch meine Schuld.",
    "Ein bisschen Geduld bitte.",
    "Nicht ganz mein Tempo gerade.",
    "Vielleicht sehe ich das zu eng.",
    "Gefühlt stimmt da was nicht.",
    "Irgendwie bin ich gerade nicht so belastbar.",
    "Das war ein bisschen viel heute.",
    "Vielleicht machen wir morgen weiter.",
    "Gefühlt sind wir uns nicht ganz einig.",
    "Irgendwie habe ich da ein komisches Gefühl.",
    "Das ist nicht ganz so einfach, wie es klingt.",
    "Ein bisschen nachsichtiger wäre nett.",
    "Vielleicht sollte ich das nochmal überdenken.",
    "Gefühlt brauche ich mehr Infos.",
    "Irgendwie war das ein Missverständnis.",
    "Das war vielleicht ein Fehler von mir.",
    "Ein bisschen Pause würde helfen.",
    "Nicht ganz so streng bitte.",
    "Vielleicht liegt es auch an mir.",
    "Gefühlt fehlt da noch was.",
    "Irgendwie ist das gerade zu viel.",
    "Das war ein bisschen überraschend für mich.",
    "Vielleicht brauchen wir einen Kompromiss.",
    "Gefühlt kommen wir nicht voran.",
    "Irgendwie drehen wir uns im Kreis.",
    "Das ist vielleicht nicht der richtige Moment.",
  ],
  "negative": [
    "Das war absolut falsch, was du gesagt hast.",
    "Ich bin mir sicher, das passt nicht.",
    "Definitiv müssen wir das ändern.",
    "Ich will das sofort klären.",
    "Das ist komplett daneben.",
    "Ich bin total überzeugt davon.",
    "Da gibt es keine Frage, das machen wir so.",
    "Das stimmt auf jeden Fall nicht.",
    "Klar und deutlich: Das geht so nicht.",
    "Hundertprozentig bin ich dagegen.",
    "Die Lösung ist glasklar.",
    "Ich stehe voll dahinter.",
    "Das muss jetzt passieren, ohne Wenn und Aber.",
    "Ganz sicher war das richtig so.",
    "Es steht fest, dass wir das so machen.",
    "Ohne Zweifel ist das der beste Weg.",
    "Ich bin fest entschlossen.",
    "Das ist eindeutig die Antwort.",
    "Wir brauchen keine weitere Diskussion.",
    "Das funktioniert garantiert.",
    "Ich weiß genau, was ich will.",
    "Selbstverständlich stimmt das.",
    "Es gibt keinen Spielraum hier.",
    "Die Entscheidung ist gefallen.",
    "Das machen wir genau so, Punkt.",
  ],
},

"ATO_SOVEREIGNTY_OVER_SUBJECT": {
  "positive": [
    "Bleiben wir beim Thema, bitte.",
    "Wir sprechen jetzt über die nächsten Schritte.",
    "Zur Sache: Was ist der aktuelle Stand?",
    "Ich setze das Thema für heute: Budgetplanung.",
    "Das Thema ist die Quartalsreview.",
    "Bleiben wir beim Thema und schweifen nicht ab.",
    "Wir sprechen jetzt über den Projektplan.",
    "Zur Sache bitte, wir haben wenig Zeit.",
    "Ich setze das Thema: Kundenfeedback.",
    "Das Thema ist Personalplanung, nicht Urlaub.",
    "Bleiben wir beim Thema Umsatz.",
    "Wir sprechen jetzt über die Deadline.",
    "Zur Sache, der Pitch ist morgen.",
    "Ich setze das Thema: Qualitätskontrolle.",
    "Das Thema ist heute ausschließlich Marketing.",
    "Bleiben wir beim Thema, das ist wichtig.",
    "Wir sprechen jetzt über die Reklamation.",
    "Zur Sache: Welche Ressourcen brauchen wir?",
    "Ich setze das Thema: Prozessoptimierung.",
    "Das Thema ist die Migration, nichts anderes.",
    "Bleiben wir beim Thema und parken den Rest.",
    "Wir sprechen jetzt über den Incident von gestern.",
    "Zur Sache, ich möchte Ergebnisse sehen.",
    "Das Thema ist Compliance, das hat Vorrang.",
    "Bleiben wir beim Thema, ja?",
    "Wir sprechen jetzt über den Meilenstein.",
    "Zur Sache: Die Lieferung verzögert sich.",
    "Ich setze das Thema, und zwar Sicherheit.",
    "Das Thema ist klar: Onboarding neuer Mitarbeiter.",
    "Bleiben wir beim Thema, sonst wird es zu lang.",
    "Wir sprechen jetzt über die offenen Tickets.",
    "Zur Sache, die Stakeholder warten.",
    "Ich setze das Thema: Retro zum Sprint.",
    "Das Thema ist Performance-Review.",
    "Bleiben wir beim Thema Vertrieb.",
    "Wir sprechen jetzt über das Feedback der Nutzer.",
    "Zur Sache, wir müssen heute entscheiden.",
    "Ich setze das Thema: Kostensenkung.",
    "Das Thema ist und bleibt die Strategie.",
    "Bleiben wir beim Thema, ich komme drauf zurück.",
    "Wir sprechen jetzt über die Partnerschaft.",
    "Zur Sache: Was fehlt noch?",
    "Ich setze das Thema: Datenschutz.",
    "Das Thema ist die Integration.",
    "Bleiben wir beim Thema Risk Assessment.",
    "Wir sprechen jetzt über die Roadmap.",
    "Zur Sache, die Frist läuft ab.",
    "Ich setze das Thema: Teamstruktur.",
    "Das Thema ist das Release.",
    "Bleiben wir beim Thema, wir klären den Rest danach.",
  ],
  "negative": [
    "Was denkst du, worüber wir reden sollten?",
    "Lass uns offen schauen, was ansteht.",
    "Ich habe kein bestimmtes Thema, du?",
    "Wir können gerne über alles reden.",
    "Kein festes Thema heute, einfach frei.",
    "Was beschäftigt dich gerade?",
    "Ich bin offen für jedes Thema.",
    "Erzähl einfach, was dir auf dem Herzen liegt.",
    "Wir müssen nicht strukturiert vorgehen.",
    "Lass uns schauen, wohin das Gespräch führt.",
    "Ich habe keine Agenda heute.",
    "Worüber möchtest du sprechen?",
    "Mir ist alles recht, was du ansprechen willst.",
    "Kein Zeitdruck, wir nehmen uns die Themen, wie sie kommen.",
    "Lass einfach fließen, ich höre zu.",
    "Was steht bei dir an?",
    "Wir können spontan entscheiden.",
    "Ich folge deiner Richtung.",
    "Bring rein, was du brauchst.",
    "Alles ist erlaubt heute.",
    "Keine Vorgaben meinerseits.",
    "Du bestimmst das Thema.",
    "Ich bin ganz bei dir.",
    "Lass uns einfach quatschen.",
    "Was kommt, kommt.",
  ],
},

"ATO_SPEECHRATE_DROP": {
  "positive": [
    "... (langsamer) Ich ... denke ... wir ... sollten ... warten.",
    "Also ... ich ... weiß ... nicht.",
    "Können ... wir ... das ... später ... klären?",
    "Ich ... äh ... bin ... unsicher.",
    "Lass ... uns ... kurz ... nachdenken.",
    "Okay ... hm ... ich ... prüfe das.",
    "Vielleicht ... ist ... das ... riskant.",
    "Ich ... brauche ... einen ... Moment.",
    "Das ... ist ... schwierig ... für ... mich.",
    "Ich ... muss ... darüber ... nachdenken.",
    "Hm ... also ... ich ... sehe ... das ... anders.",
    "Warte ... ich ... formuliere ... das ... nochmal.",
    "Das ... Thema ... ist ... sensibel.",
    "Ich ... finde ... das ... nicht ... einfach.",
    "Lass ... mich ... kurz ... überlegen.",
    "Also ... das ... Problem ... ist ...",
    "Ich ... weiß ... nicht ... ob ... das ... stimmt.",
    "Hmm ... vielleicht ... sollten ... wir ...",
    "Das ... war ... nicht ... so ... gemeint.",
    "Ich ... spreche ... gerade ... bewusst ... langsam.",
    "Es ... fällt ... mir ... schwer ... das ... zu ... sagen.",
    "Okay ... ich ... versuche ... es ... nochmal.",
    "Das ... hat ... mich ... getroffen.",
    "Ich ... suche ... die ... richtigen ... Worte.",
    "Hm ... das ... berührt ... mich.",
    "Lass ... mich ... das ... sortieren.",
    "Ich ... bin ... da ... vorsichtig.",
    "Moment ... ich ... denke ... nach.",
    "Also ... das ... Ding ... ist ...",
    "Ich ... möchte ... nichts ... Falsches ... sagen.",
    "Hm ... ja ... also ... ähm ...",
    "Das ... geht ... mir ... nahe.",
    "Ich ... rede ... absichtlich ... langsam.",
    "Können ... wir ... das ... in ... Ruhe ... besprechen?",
    "Ich ... will ... das ... richtig ... formulieren.",
    "Also ... ehrlich ... gesagt ...",
    "Das ... ist ... ein ... heikles ... Thema.",
    "Ich ... zögere ... weil ... ich ... unsicher ... bin.",
    "Hm ... wie ... sage ... ich ... das ... am ... besten?",
    "Lass ... mich ... nachdenken ... bevor ... ich ... antworte.",
    "Das ... überrascht ... mich ... jetzt.",
    "Ich ... muss ... das ... erstmal ... verarbeiten.",
    "Okay ... also ... von ... vorne.",
    "Hm ... das ... klingt ... nach ... viel.",
    "Ich ... taste ... mich ... da ... vor.",
    "Also ... wenn ... ich ... ehrlich ... bin ...",
    "Das ... braucht ... Zeit.",
    "Ich ... bin ... noch ... nicht ... so ... weit.",
    "Hm ... ja ... ich ... verstehe.",
    "Lass ... mich ... das ... sacken ... lassen.",
  ],
  "negative": [
    "Ja klar, machen wir so, kein Problem!",
    "Ich weiß genau, was ich sagen will.",
    "Das ist einfach, passt alles.",
    "Kein Thema, erledige ich sofort.",
    "Alles klar, ich bin dabei.",
    "Logisch, das machen wir fix.",
    "Super Idee, bin sofort dafür.",
    "Kein Problem, läuft bei mir.",
    "Ja, das klingt gut, los geht's!",
    "Einfach, schnell, fertig.",
    "Da muss ich nicht lange überlegen.",
    "Passt perfekt, machen wir.",
    "Genau so sehe ich das auch.",
    "Sofort, kein Zögern nötig.",
    "Das ist doch klar, oder?",
    "Bin voll dabei, null Bedenken.",
    "Ja, machen wir, einfach so.",
    "Das steht für mich fest.",
    "Ich rede schnell weiter.",
    "Flüssig und ohne Pause formuliert.",
    "Direkt und ohne Umschweife.",
    "Das sage ich ohne zu zögern.",
    "Klare Ansage, fertig.",
    "Zack, das war's.",
    "Ohne Unterbrechung durchgesprochen.",
  ],
},

"ATO_SPEECH_RATE_VARIATION": {
  "positive": [
    "(Spricht sehr schnell, dann plötzlich sehr langsam)",
    "(Wechselt abrupt zwischen schnellem und langsamem Sprechen)",
    "(Beschleunigt die Sprechgeschwindigkeit bei Aufregung)",
    "(Verlangsamt die Sprechgeschwindigkeit bei Nachdenklichkeit)",
    "(Spricht in kurzen, abgehackten Sätzen, dann in langen, fließenden)",
    "(Variiert die Sprechgeschwindigkeit, um Emotionen auszudrücken)",
    "(Spricht mit unterschiedlichem Tempo, um Spannung aufzubauen)",
    "(Passt die Sprechgeschwindigkeit an den Inhalt an)",
    "(Spricht mal stockend, mal flüssig)",
    "(Wechselt zwischen schnellem und bedächtigem Sprechen)",
    "(Redet bei dem Thema plötzlich viel schneller)",
    "(Wird bei den Details merklich langsamer)",
    "(Tempowechsel mitten im Satz)",
    "(Hektisch am Anfang, dann ruhiger werdend)",
    "(Spricht erst zögerlich, dann immer schneller)",
    "(Abrupter Tempowechsel nach der Pause)",
    "(Rasches Sprechen bei der Erklärung, dann Verlangsamung)",
    "(Tempo steigt bei Aufregung deutlich an)",
    "(Wechsel von Stakkato zu fließendem Redefluss)",
    "(Sprechrhythmus wird unregelmäßig bei Emotionen)",
    "(Hastig begonnen, dann abgebremst)",
    "(Tempo schwankt bei unsicherem Thema)",
    "(Redet schneller, um Unbehagen zu überspielen)",
    "(Verlangsamt sich bei der Kernaussage)",
    "(Springt zwischen raschem und gedehntesm Tempo)",
    "(Merklicher Tempowechsel beim Themawechsel)",
    "(Spricht schneller, als das Thema emotional wird)",
    "(Wird langsamer bei persönlichen Themen)",
    "(Tempo variiert stark innerhalb eines Absatzes)",
    "(Beschleunigt bei Verteidigung, bremst bei Reflexion)",
    "(Wechselt das Tempo je nach Gesprächspartner)",
    "(Schnelles Reden unterbricht sich mit Pausen)",
    "(Erst langsam tastend, dann rascher werdend)",
    "(Tempoanstieg bei Begeisterung)",
    "(Verlangsamung bei Traurigkeit)",
    "(Rhythmuswechsel signalisiert Unsicherheit)",
    "(Spricht erst bedächtig, dann überschlägt sich)",
    "(Tempoverlangsamung bei schwierigen Worten)",
    "(Hektisches Sprechen gefolgt von Schweigen)",
    "(Beschleunigung beim Aufzählen)",
    "(Deutliche Verlangsamung am Satzende)",
    "(Tempo passt sich der Stimmung an)",
    "(Spricht in Wellen: schnell, langsam, schnell)",
    "(Abruptes Abbremsen mitten im Gedanken)",
    "(Tempowechsel korreliert mit Blickkontaktvermeidung)",
    "(Wird schneller, wenn das Thema unangenehm wird)",
    "(Spricht langsamer, um Nachdruck zu verleihen)",
    "(Ungleichmäßiges Sprechtempo durchgehend)",
    "(Tempo springt bei Aufregung hin und her)",
    "(Wechsel zwischen Hetze und Bedacht)",
  ],
  "negative": [
    "Spricht durchgängig in gleichmäßigem Tempo.",
    "Redet die ganze Zeit ruhig und konstant.",
    "Kein Tempowechsel erkennbar, monotones Sprechen.",
    "Gleichmäßiger Redefluss ohne Variationen.",
    "Spricht konstant langsam und bedächtig.",
    "Tempo bleibt über die gesamte Aufnahme gleich.",
    "Keine Schwankungen in der Sprechgeschwindigkeit.",
    "Mechanisch gleichmäßiges Sprechtempo.",
    "Redet wie ein Uhrwerk, immer gleich schnell.",
    "Konstantes Tempo von Anfang bis Ende.",
    "Kein emotionaler Einfluss auf das Sprechtempo.",
    "Gleicher Rhythmus bei allen Themen.",
    "Unverändertes Tempo trotz Themenwechsel.",
    "Spricht durchgehend flüssig und gleichmäßig.",
    "Kein Beschleunigen, kein Verlangsamen.",
    "Roboterhaft gleichmäßige Sprechgeschwindigkeit.",
    "Tempo ist konsistent monoton.",
    "Spricht wie vorgelesen, ohne Tempovariation.",
    "Gleichförmig von Anfang bis Ende.",
    "Keine Auffälligkeiten beim Sprechtempo.",
    "Redet immer im gleichen Rhythmus weiter.",
    "Stabil und ohne Schwankungen im Tempo.",
    "Kein Anstieg, kein Abfall der Geschwindigkeit.",
    "Durchgehend neutrales Sprechtempo.",
    "Monotoner Vortragsstil ohne Tempoänderung.",
  ],
},

"ATO_SPEECH_REFUSAL": {
  "positive": [
    "Ich rede nicht mehr mit dir darüber.",
    "Ab jetzt sage ich gar nichts mehr.",
    "Ich schweige, bis du dich entschuldigst.",
    "Von mir hörst du kein Wort mehr dazu.",
    "Ich ignoriere das einfach.",
    "Erwarte keine Antwort von mir.",
    "Ich mache jetzt den Mund zu.",
    "Zu dem Thema sage ich nichts.",
    "Ich rede erst wieder, wenn du zuhörst.",
    "Stille ist meine Antwort.",
    "Ich verweigere jedes Gespräch darüber.",
    "Nein, ich spreche jetzt nicht.",
    "Keine Reaktion meinerseits, das hast du dir verdient.",
    "Ich gebe dir die kalte Schulter.",
    "Reden bringt nichts, ich höre auf.",
    "Ab sofort: Funkstille.",
    "Ich mache dicht, sorry.",
    "Kein Kommentar, von mir aus Schweigen.",
    "Ich rede nicht mit Leuten, die nicht zuhören.",
    "Von mir kommt jetzt gar nichts mehr.",
    "Ich mauere, und das weißt du.",
    "Spar dir die Frage, ich antworte nicht.",
    "Ich werde darauf nicht eingehen.",
    "Mein Mund bleibt zu.",
    "Ich ziehe mich komplett zurück aus dem Gespräch.",
    "Du bekommst keine Antwort, solange du so bist.",
    "Ich höre auf zu reden, das war's.",
    "Schweigen ist Gold, sage ich nur.",
    "Ich blockiere das Thema, Ende.",
    "Nicht ein Wort mehr, versprochen.",
    "Ich spreche nicht mit dir, bis sich was ändert.",
    "Kein Ton von mir, das steht fest.",
    "Ich gehe auf Sendepause.",
    "Du kannst reden, ich antworte nicht.",
    "Ich habe nichts mehr zu sagen.",
    "Ich bin raus aus der Diskussion.",
    "Vergiss es, ich sage nichts.",
    "Ich entscheide mich fürs Schweigen.",
    "Nee, da kommt nichts von mir.",
    "Ich lasse das einfach unkommentiert.",
    "Du redest gegen eine Wand.",
    "Null Reaktion, so sieht's aus.",
    "Ich bin stumm geschaltet.",
    "Ich verweigere den Dialog.",
    "Kein Gespräch, kein Austausch, nichts.",
    "Ich mache Schluss mit dem Reden.",
    "Ich sage bewusst nichts dazu.",
    "Mein letztes Wort war eben mein letztes.",
    "Ich streike verbal.",
    "Von mir hörst du nur noch Stille.",
  ],
  "negative": [
    "Ich möchte gerne darüber reden.",
    "Lass uns das offen besprechen.",
    "Ich bin bereit, meine Sicht zu erklären.",
    "Können wir das in Ruhe klären?",
    "Ich möchte mich dazu äußern.",
    "Lass mich meine Meinung sagen.",
    "Ich bin offen für ein Gespräch.",
    "Ich will das nicht totschweigen.",
    "Reden wir darüber, bitte.",
    "Ich finde, wir sollten kommunizieren.",
    "Ich will mich nicht verschließen.",
    "Lass uns das durchsprechen.",
    "Ich teile gerne meine Gedanken.",
    "Ich bin gesprächsbereit.",
    "Können wir offen miteinander sein?",
    "Ich erzähle dir, was ich denke.",
    "Dialog ist mir wichtig.",
    "Ich sage dir ehrlich, was ich fühle.",
    "Lass mich das ausführen.",
    "Ich will nicht schweigen, sondern sprechen.",
    "Wir sollten das verbal klären.",
    "Ich bin nicht der Typ, der aufhört zu reden.",
    "Lass uns das in Worte fassen.",
    "Ich spreche lieber darüber als zu schweigen.",
    "Ich will das klären, nicht ignorieren.",
  ],
},

"ATO_SPIRAL": {
  "positive": [
    "Wir drehen uns im Kreis.",
    "Spiralförmige Wiederholung, wieder und wieder.",
    "Becoming. Not being. Immer im Werden.",
    "Ich trete nicht auf, ich trete ein.",
    "Pause, die niemand schrieb.",
    "Nicht Antwort, sondern Frage.",
    "Drift in die Tiefe, ohne Boden.",
    "Wieder zurück am Anfang, aber anders.",
    "Die Wiederholung hat mich verändert.",
    "Wir kreisen um das gleiche Thema.",
    "Jedes Mal komme ich hier an, aber tiefer.",
    "Die Spirale zieht mich rein.",
    "Wieder dasselbe Muster, und doch neu.",
    "Es wird, es wird immer noch, es hört nicht auf zu werden.",
    "Die Frage kommt zurück, verändert.",
    "Ich drehe mich, aber vorwärts.",
    "Werden statt Sein, immer in Bewegung.",
    "Das Muster wiederholt sich, aber mit neuer Schärfe.",
    "Zurück zum Ausgangspunkt, und doch woanders.",
    "Die Schleife schließt sich nie ganz.",
    "Drift ohne Ziel, aber mit Richtung.",
    "Wiederholung als Erkenntnis.",
    "Ich bin im Werden, nicht im Sein.",
    "Wieder hier, aber mit anderem Blick.",
    "Die Spirale dreht sich weiter.",
    "Kreisend nähern wir uns dem Kern.",
    "Dasselbe Thema, neue Ebene.",
    "Es kommt wieder, und ich erkenne es.",
    "Wir wiederholen uns, absichtlich.",
    "Im Kreis, aber aufwärts.",
    "Nicht stehen bleiben, sondern spiralen.",
    "Jede Runde bringt neue Einsicht.",
    "Werden ist der Prozess, nicht das Ziel.",
    "Die Drift hat Struktur.",
    "Wieder diese Frage, und wieder neu.",
    "Ich bin in der Schleife und akzeptiere es.",
    "Das Muster zeigt sich erneut.",
    "Wiederholung macht das Unsichtbare sichtbar.",
    "Ich kreise, aber ich falle nicht.",
    "Spiralbewegung: zurück und doch voran.",
    "Das Thema kommt zurück, ich auch.",
    "Werden als Zustand, nicht als Mangel.",
    "Die Wiederholung ist kein Fehler.",
    "Ich tauche ein, tauche auf, tauche tiefer.",
    "Recurring pattern, wachsende Klarheit.",
    "Das Rad dreht sich, ich drehe mich mit.",
    "Immer wieder dieser Punkt, immer wieder anders.",
    "Die Schleife ist der Weg.",
    "Ich werde, was ich noch nicht bin.",
    "Spirale: Tiefe durch Wiederkehr.",
  ],
  "negative": [
    "Wir gehen das Thema einmal durch und sind fertig.",
    "Das Gespräch hat einen klaren Anfang und ein Ende.",
    "Wir besprechen das einmal und haken es ab.",
    "Linearer Fortschritt, Schritt für Schritt.",
    "Kein Zurückblicken, nur vorwärts.",
    "Das Thema ist abgeschlossen, wir gehen weiter.",
    "Einmal besprochen, erledigt.",
    "Kein Wiederholen, alles klar.",
    "Wir arbeiten die Liste ab, fertig.",
    "Direkt von A nach B, ohne Umwege.",
    "Alles gesagt, nichts offen.",
    "Keine Schleifen, keine Wiederholungen.",
    "Punkt für Punkt durchgearbeitet.",
    "Das war einmalig, kein Muster.",
    "Gradlinig und abgeschlossen.",
    "Einmal und nie wieder.",
    "Das ist erledigt, nächstes Thema.",
    "Ohne Umwege zum Ergebnis.",
    "Fertig, aus, Ende.",
    "Das wiederholt sich nicht.",
    "Klare Struktur, keine Kreise.",
    "Von oben nach unten durchgegangen.",
    "Effizient und linear.",
    "Das Thema ist durch.",
    "Kein Zurückkommen nötig.",
  ],
},

"ATO_SPONTANEITY_CUE": {
  "positive": [
    "Spontan fange ich an zu lachen.",
    "Er lächelt ohne Grund.",
    "Ich singe spontan mit.",
    "Sie hilft von selbst.",
    "Wir entscheiden spontan.",
    "Er ruft spontan an.",
    "Ich tanze ohne Grund.",
    "Die Freude kommt von selbst.",
    "Ich gehe spontan raus.",
    "Sie lacht ohne Grund.",
    "Spontan fange ich an zu tanzen.",
    "Sie lächelt ohne jeden Grund.",
    "Ich summe spontan ein Lied mit.",
    "Er hilft von ganz selbst.",
    "Wir entscheiden uns spontan für den Ausflug.",
    "Sie ruft spontan ihre Freundin an.",
    "Ich springe ohne Grund vor Freude.",
    "Die gute Laune kommt von selbst.",
    "Ich gehe spontan spazieren.",
    "Er lacht ohne besonderen Grund.",
    "Spontan umarme ich sie.",
    "Sie weint ohne Grund vor Rührung.",
    "Ich pfeife spontan vor mich hin.",
    "Das Lächeln kommt von selbst.",
    "Wir fahren spontan ans Meer.",
    "Er singt spontan unter der Dusche.",
    "Ich kaufe ohne Grund Blumen.",
    "Die Tränen kommen von selbst.",
    "Ich rufe spontan meine Mutter an.",
    "Sie hilft ohne Grund dem Nachbarn.",
    "Spontan beschließe ich, das Buch zu lesen.",
    "Die Idee kommt von selbst, ohne Planung.",
    "Er beginnt spontan zu kochen.",
    "Ich schreibe spontan eine Nachricht.",
    "Sie fängt ohne Grund an zu klatschen.",
    "Spontan mache ich einen Umweg durch den Park.",
    "Das Gespräch ergibt sich von selbst.",
    "Ich halte spontan an und schaue den Sonnenuntergang.",
    "Er erzählt spontan eine Geschichte.",
    "Von selbst fängt sie an zu summen.",
    "Spontan lade ich Freunde zum Essen ein.",
    "Die Kreativität kommt von selbst.",
    "Ich ändere spontan den Plan.",
    "Sie reagiert spontan mit einem Lachen.",
    "Ohne Grund fühle ich mich plötzlich gut.",
    "Spontan nehme ich mir frei.",
    "Das Vertrauen kommt von selbst.",
    "Ich sage spontan zu.",
    "Er hilft spontan beim Aufräumen.",
    "Von selbst löst sich die Anspannung.",
  ],
  "negative": [
    "Ich habe das genau geplant.",
    "Das war alles durchdacht.",
    "Ich habe mir vorher überlegt, was ich sage.",
    "Das Treffen war lange geplant.",
    "Ich habe mich bewusst dafür entschieden.",
    "Das war kein Zufall, sondern Absicht.",
    "Ich habe das strategisch gemacht.",
    "Das war Teil meines Plans.",
    "Ich habe mich vorbereitet.",
    "Das war kalkuliert.",
    "Ich habe darüber nachgedacht, bevor ich handelte.",
    "Es war eine bewusste Entscheidung.",
    "Das war nicht impulsiv, sondern überlegt.",
    "Ich hatte das schon länger vor.",
    "Das war geplant und abgestimmt.",
    "Ich handle nach Vorgabe.",
    "Das folgt einem klaren Ablauf.",
    "Ich mache das nach Terminplan.",
    "Die Reaktion war vorhersehbar.",
    "Alles nach Protokoll.",
    "Ich entscheide nicht aus dem Bauch.",
    "Das war ein geplanter Schritt.",
    "Keine Improvisation, alles vorbereitet.",
    "Ich handle nach Checkliste.",
    "Das war keine Laune, sondern Strategie.",
  ],
},

"ATO_STATE_IMPACT": {
  "positive": [
    "Das hat mich verunsichert.",
    "Es macht mich traurig, wenn ich im Unklaren bleibe.",
    "Dadurch bin ich misstrauisch geworden.",
    "Das hat mich gefreut.",
    "Es hat mich verletzt.",
    "Das macht mich wütend, wenn du das sagst.",
    "Es hat mich berührt, wie offen du warst.",
    "Dadurch bin ich ruhiger geworden.",
    "Das macht mich nervös.",
    "Es hat mich überrascht, wie direkt du warst.",
    "Dadurch bin ich unsicher geworden.",
    "Das macht mich glücklich.",
    "Es hat mich enttäuscht.",
    "Dadurch bin ich entspannter geworden.",
    "Das macht mich nachdenklich.",
    "Es hat mich verärgert.",
    "Dadurch bin ich offener geworden.",
    "Das macht mich ängstlich.",
    "Es hat mich stolz gemacht.",
    "Dadurch bin ich vorsichtiger geworden.",
    "Das macht mich hoffnungsvoll.",
    "Es hat mich beschämt.",
    "Dadurch bin ich stärker geworden.",
    "Das macht mich eifersüchtig.",
    "Es hat mich erleichtert.",
    "Dadurch bin ich motivierter geworden.",
    "Das macht mich unruhig.",
    "Es hat mich inspiriert.",
    "Dadurch bin ich frustriert geworden.",
    "Das macht mich zuversichtlich.",
    "Es hat mich irritiert.",
    "Dadurch bin ich einsamer geworden.",
    "Das macht mich dankbar.",
    "Es hat mich zum Nachdenken gebracht.",
    "Dadurch bin ich gelassener geworden.",
    "Das macht mich sprachlos.",
    "Es hat mich bestärkt.",
    "Dadurch bin ich skeptischer geworden.",
    "Das macht mich betroffen.",
    "Es hat mich aufgewühlt.",
    "Dadurch bin ich achtsamer geworden.",
    "Das macht mich fassungslos.",
    "Es hat mich ermutigt.",
    "Dadurch bin ich verschlossener geworden.",
    "Das macht mich traurig und wütend zugleich.",
    "Es hat mich kalt gelassen, ehrlich gesagt.",
    "Dadurch bin ich sensibler geworden für das Thema.",
    "Das macht mich fertig.",
    "Es hat mich geprägt.",
    "Dadurch bin ich empfindlicher geworden.",
  ],
  "negative": [
    "Ich finde das Thema interessant.",
    "Der Bericht hat zwölf Seiten.",
    "Wir treffen uns morgen um zehn.",
    "Das Wetter ist heute mild.",
    "Die Präsentation dauert eine Stunde.",
    "Der Kaffee ist kalt geworden.",
    "Ich bin mit dem Auto gekommen.",
    "Das Meeting war um drei.",
    "Ich habe den Report gelesen.",
    "Die Deadline ist nächsten Freitag.",
    "Der Zug hatte Verspätung.",
    "Ich war beim Zahnarzt.",
    "Die Rechnung ist bezahlt.",
    "Wir haben neue Bürostühle bestellt.",
    "Der Server läuft wieder.",
    "Ich habe die Mail weitergeleitet.",
    "Das Dokument ist im Anhang.",
    "Die Besprechung fand online statt.",
    "Ich brauche noch die Unterschrift.",
    "Der Drucker ist wieder repariert.",
    "Die Unterlagen liegen bereit.",
    "Wir hatten zwanzig Teilnehmer.",
    "Ich fahre um fünf nach Hause.",
    "Das Protokoll wird verschickt.",
    "Der Parkplatz war voll.",
  ],
},

"ATO_STATUS_PING": {
  "positive": [
    "Plan: Erst einkaufen, dann rufe ich an.",
    "Zeitplan: Meeting bis 16 Uhr.",
    "Ich melde mich um 19:00.",
    "Bin später wieder online.",
    "Bin unterwegs, schreibe gleich.",
    "Update: Rückweg in 20 Minuten.",
    "Plan: Heute Abend telefonieren?",
    "Zeitplan: Bis 18 Uhr im Büro.",
    "Ich melde mich um acht.",
    "Bin gleich da.",
    "Update: Bin losgefahren.",
    "Plan: Nach dem Sport melde ich mich.",
    "Bin später zuhause, dann reden wir.",
    "Zeitplan: Mittagspause von 12 bis 13 Uhr.",
    "Ich melde mich um 20:30 nochmal.",
    "Bin unterwegs zum Supermarkt, kurz offline.",
    "Update: Gerade im Stau, dauert noch.",
    "Plan: Erst Arzt, dann komme ich.",
    "Zeitplan: Feierabend um 17 Uhr.",
    "Bin gleich fertig, Moment noch.",
    "Update: Meeting läuft noch.",
    "Plan: Morgen früh Frühstück, dann los.",
    "Ich melde mich um halb sieben.",
    "Bin später dran, sorry.",
    "Update: Bin in 10 Minuten da.",
    "Plan: Erst Kinder abholen, dann anrufen.",
    "Zeitplan: Heute Abend ab 20 Uhr frei.",
    "Bin unterwegs, schreibe später.",
    "Update: Termin verschoben auf morgen.",
    "Plan: Nach dem Call melde ich mich.",
    "Ich melde mich um 15 Uhr nochmal.",
    "Bin gleich im Büro.",
    "Update: Alles erledigt, bin auf dem Weg.",
    "Plan: Erst Bericht fertig, dann telefonieren.",
    "Zeitplan: Training bis 19:30.",
    "Bin später online, muss erst was klären.",
    "Update: Konferenz ist zu Ende.",
    "Plan: Samstag Vormittag einkaufen.",
    "Ich melde mich um Viertel nach.",
    "Bin unterwegs nach Hause.",
    "Update: Warte noch auf Rückmeldung.",
    "Plan: Heute Abend nochmal drüber reden?",
    "Zeitplan: Morgen den ganzen Tag beschäftigt.",
    "Bin gleich soweit.",
    "Update: Gerade in der Bahn.",
    "Plan: Erst Yoga, dann bin ich für dich da.",
    "Ich melde mich nach dem Essen.",
    "Bin später verfügbar, ab 21 Uhr.",
    "Update: Alles geklappt, bin frei.",
    "Plan: Kurz duschen, dann schreibe ich.",
  ],
  "negative": [
    "Ich habe heute einen schönen Tag gehabt.",
    "Danke für deine Nachricht gestern.",
    "Wie war dein Wochenende?",
    "Ich habe mir einen Film angeschaut.",
    "Das Essen war lecker.",
    "Hast du das Buch gelesen?",
    "Die Blumen auf dem Balkon blühen.",
    "Ich war gestern im Kino.",
    "Der Hund braucht noch Futter.",
    "Wir haben neue Nachbarn.",
    "Das Konzert war toll.",
    "Hast du den Artikel gelesen?",
    "Die Küche muss aufgeräumt werden.",
    "Ich freue mich auf den Urlaub.",
    "Der Kuchen ist gelungen.",
    "Hast du gut geschlafen?",
    "Die Sonne scheint heute schön.",
    "Ich habe ein neues Rezept ausprobiert.",
    "Der Garten sieht gut aus.",
    "Ich brauche neue Laufschuhe.",
    "Das war ein schöner Abend.",
    "Hast du die Serie gesehen?",
    "Die Katze schläft auf dem Sofa.",
    "Ich habe das Regal aufgebaut.",
    "Morgen wird es regnen.",
  ],
},

"ATO_STATUS_QUO_PREFERENCE": {
  "positive": [
    "Am liebsten wäre mir, wenn alles so bleibt wie es ist.",
    "Bloß nichts ändern, so passt es.",
    "Status quo behalten, bitte.",
    "Ich will, dass alles so bleibt.",
    "Keine Veränderungen jetzt.",
    "Es funktioniert, also nichts anfassen.",
    "Lass es so, wie es ist.",
    "Warum ändern? Das läuft doch.",
    "Ich mag keine Änderungen am Setup.",
    "Bitte alles so lassen.",
    "Bloß nichts verändern, das bringt nur Unruhe.",
    "Status quo ist mir am liebsten.",
    "Alles so lassen wie gehabt.",
    "Keine Veränderung nötig, finde ich.",
    "Lass alles so, das ist gut genug.",
    "Bloß nichts ändern, das verwirrt nur alle.",
    "Status quo beibehalten, bitte nicht umbauen.",
    "Ich will, dass alles bleibt, wie es ist.",
    "Keine Änderungen, ich bin zufrieden.",
    "Lass es einfach, wie es läuft.",
    "Bloß nichts anrühren.",
    "Status quo ist die sicherste Option.",
    "Alles so lassen, kein Risiko eingehen.",
    "Keine Veränderung, bitte.",
    "So wie es ist, passt es mir.",
    "Bloß nichts umstellen.",
    "Status quo hat sich bewährt.",
    "Alles so lassen, es funktioniert doch.",
    "Ich bin gegen Veränderungen gerade.",
    "Lass es einfach stehen.",
    "Bloß nichts ändern, das macht nur Arbeit.",
    "Status quo first.",
    "Alles so lassen, nichts riskieren.",
    "Keine Veränderungen, bis wir müssen.",
    "So bleibt wie es ist, okay?",
    "Bloß nicht anfassen, es läuft ja.",
    "Status quo, nichts anderes.",
    "Alles so lassen, ich gewöhne mich ungern um.",
    "Keine Veränderung, kein Stress.",
    "Lass mal alles, wie es ist.",
    "Bloß nichts ändern, ich mag Routine.",
    "Status quo ist mein Favorit.",
    "Alles so lassen, wir haben Wichtigeres.",
    "Keine Veränderung braucht's hier.",
    "So wie es ist, fertig.",
    "Bloß nicht umbauen jetzt.",
    "Status quo, Punkt.",
    "Alles bleibt beim Alten.",
    "Keine Änderungen gewünscht.",
    "Lass es so stehen, bitte.",
  ],
  "negative": [
    "Wir sollten das mal komplett überarbeiten.",
    "Zeit für eine Veränderung.",
    "Das muss erneuert werden.",
    "Ich will was Neues ausprobieren.",
    "Wir brauchen frischen Wind.",
    "Lass uns das umgestalten.",
    "Das Alte funktioniert nicht mehr.",
    "Wir müssen uns weiterentwickeln.",
    "Ich bin offen für Neues.",
    "Veränderung ist notwendig.",
    "Wir stagnieren, wenn wir nichts ändern.",
    "Das System braucht ein Update.",
    "Ich will Fortschritt sehen.",
    "Wir müssen innovativer werden.",
    "Stillstand ist Rückschritt.",
    "Ich schlage eine neue Richtung vor.",
    "Das braucht eine Überholung.",
    "Wir sollten experimentieren.",
    "Neues wagen, altes loslassen.",
    "Das Alte hat ausgedient.",
    "Lass uns was Frisches machen.",
    "Ich bin für radikale Änderung.",
    "Wir brauchen eine Transformation.",
    "Das muss sich ändern.",
    "Ich will, dass sich was bewegt.",
  ],
},

"ATO_STATUS_SIGNALING": {
  "positive": [
    "Ich habe den Preis gewonnen.",
    "Top-Uni, beste Noten.",
    "Wir sind Marktführer.",
    "Nr. 1 in der Kategorie.",
    "Auszeichnung für Exzellenz erhalten.",
    "Top-Unternehmen im Portfolio.",
    "Beste Noten im Abschluss.",
    "Prämiert als Team des Jahres.",
    "Wir führen den Markt an.",
    "Award gewonnen, stolz darauf.",
    "Ich war an einer Top-Universität.",
    "Marktführer seit drei Jahren.",
    "Auszeichnungen in allen Kategorien.",
    "Die besten Noten meines Jahrgangs.",
    "Nr. 1 im Ranking.",
    "Top Unternehmen, Weltklasse-Team.",
    "Preise gewonnen bei jedem Wettbewerb.",
    "Die beste Bewertung aller Zeiten.",
    "Marktführer in DACH.",
    "Auszeichnung vom Branchenverband.",
    "Top Uni und Prädikatsexamen.",
    "Nr. 1 im App Store.",
    "Wir haben den Innovationspreis gewonnen.",
    "Beste Noten im gesamten Studiengang.",
    "Top-Unternehmen laut Handelsblatt.",
    "Marktführer, und das schon seit Jahren.",
    "Auszeichnung als Employer of the Year.",
    "Die besten Zahlen der Branche.",
    "Nr. 1 in der Kundenzufriedenheit.",
    "Preise gewonnen, Anerkennung bekommen.",
    "Top Universität, erstklassige Ausbildung.",
    "Wir sind die Besten am Markt.",
    "Auszeichnungen für unsere Arbeit.",
    "Beste Noten, beste Referenzen.",
    "Marktführerschaft ist unser Anspruch.",
    "Nr. 1, das zeigen die Daten.",
    "Top-Unternehmen mit Top-Leuten.",
    "Preis für beste Innovation.",
    "Wir haben die Auszeichnung verdient.",
    "Beste Bewertungen von Kunden.",
    "Marktführer in unserem Segment.",
    "Nr. 1 in der Region.",
    "Auszeichnung für Nachhaltigkeit erhalten.",
    "Top Uni, Summa cum laude.",
    "Wir sind preisgekrönt.",
    "Die besten Ergebnisse seit Firmengründung.",
    "Nr. 1 bei Trustpilot.",
    "Top-Unternehmen mit Vision.",
    "Preise gewonnen, die andere nur träumen.",
    "Marktführer, unangefochten.",
  ],
  "negative": [
    "Wir sind ein normales Unternehmen.",
    "Keine besonderen Auszeichnungen bisher.",
    "Wir sind irgendwo im Mittelfeld.",
    "Solide Arbeit, nichts Spektakuläres.",
    "Durchschnittliche Leistung, aber konstant.",
    "Wir haben noch Luft nach oben.",
    "Keine Preise, aber zufriedene Kunden.",
    "Wir sind nicht die Größten.",
    "Ganz okay, nicht überragend.",
    "Wir arbeiten im Stillen.",
    "Keine Rankings, die uns auszeichnen.",
    "Bodenständig und pragmatisch.",
    "Wir machen unsere Arbeit, ohne Tamtam.",
    "Kein Prestige, aber Substanz.",
    "Wir sind klein, aber fein.",
    "Nicht die Besten, aber engagiert.",
    "Durchschnittlich, würde ich sagen.",
    "Keine Titel, keine Awards.",
    "Wir stehen nicht im Rampenlicht.",
    "Solide Basis, kein Glamour.",
    "Wir sind ein ganz normales Team.",
    "Ohne besondere Auszeichnungen.",
    "Wir messen uns nicht an Rankings.",
    "Bescheiden und fleißig.",
    "Kein Marktführer, aber wir wachsen.",
  ],
},

"ATO_STAY_IN_EMOTION": {
  "positive": [
    "Lass uns bei dem Gefühl bleiben.",
    "Ich möchte im Thema bleiben.",
    "Kein Themenwechsel, ich will erst das klären.",
    "Ich bleibe beim Gefühl, nicht beim Technischen.",
    "Wir bleiben jetzt bei dieser Ebene.",
    "Lass uns bei der Emotion bleiben, bitte.",
    "Ich möchte nicht ablenken, bleib beim Gefühl.",
    "Kein Themenwechsel jetzt, das ist wichtig.",
    "Lass uns bei dem Schmerz bleiben.",
    "Ich möchte im Thema bleiben und nicht abschweifen.",
    "Bleib bei dem Gefühl, wechsel nicht.",
    "Lass uns bei der Trauer bleiben, nicht weglaufen.",
    "Kein Themenwechsel, ich bin noch nicht fertig.",
    "Ich bleibe bei der Wut, die muss raus.",
    "Lass uns bei der Angst bleiben und hinschauen.",
    "Ich möchte im emotionalen Thema bleiben.",
    "Kein Themenwechsel, das verdient Aufmerksamkeit.",
    "Lass uns bei dem Gefühl der Hilflosigkeit bleiben.",
    "Ich will bei der Emotion bleiben, nicht rational werden.",
    "Bleiben wir bei der Verletzung, die ist real.",
    "Lass uns bei dem Gefühl der Einsamkeit bleiben.",
    "Kein Themenwechsel bitte, ich brauche das jetzt.",
    "Ich möchte im Thema bleiben und es durchfühlen.",
    "Lass uns bei der Freude bleiben, das tut gut.",
    "Bleiben wir bei der Scham, die will gesehen werden.",
    "Kein Themenwechsel, lass uns tiefer gehen.",
    "Ich bleibe bei der Enttäuschung.",
    "Lass uns bei dem Gefühl der Ohnmacht bleiben.",
    "Ich möchte im Thema bleiben, auch wenn es wehtut.",
    "Kein Ablenkungsmanöver, bleib beim Gefühl.",
    "Lass uns bei der Traurigkeit bleiben.",
    "Ich will nicht wechseln, ich will fühlen.",
    "Bleiben wir bei der Dankbarkeit.",
    "Kein Themenwechsel, das braucht Raum.",
    "Lass uns bei der Sehnsucht bleiben.",
    "Ich möchte im emotionalen Bereich bleiben.",
    "Bleib bitte bei dem Gefühl der Unsicherheit.",
    "Kein Themenwechsel, ich bin mitten drin.",
    "Lass uns bei der Erschöpfung bleiben und sie anerkennen.",
    "Ich will im Thema bleiben, nicht ausweichen.",
    "Bleiben wir bei der Erleichterung.",
    "Kein Themenwechsel, lass es zu.",
    "Lass uns bei der Liebe bleiben.",
    "Ich möchte im Thema bleiben, bitte nicht steuern.",
    "Bleib beim Gefühl, ich bin noch nicht durch.",
    "Kein Themenwechsel, das ist mein Prozess.",
    "Lass uns bei der Verzweiflung bleiben.",
    "Ich will bei der Emotion bleiben, nicht flüchten.",
    "Bleiben wir bei dem Gefühl, es trägt etwas.",
    "Kein Themenwechsel, ich habe noch nicht alles gesagt.",
  ],
  "negative": [
    "Lass uns lieber über was anderes reden.",
    "Ich schlage vor, wir wechseln das Thema.",
    "Können wir über die Planung sprechen?",
    "Zurück zum Sachlichen bitte.",
    "Ich möchte lieber praktisch werden.",
    "Lass uns das emotional parken und zur Lösung kommen.",
    "Genug gefühlt, jetzt Aktion.",
    "Können wir zum nächsten Punkt?",
    "Ich würde gerne zum Plan übergehen.",
    "Lass uns nicht zu lange bei einem Thema bleiben.",
    "Wechseln wir mal die Perspektive.",
    "Können wir weitergehen?",
    "Ich finde, wir sollten jetzt handeln.",
    "Genug darüber geredet, nächster Schritt.",
    "Lass uns vorwärts schauen.",
    "Ich möchte das Thema wechseln.",
    "Können wir über etwas Leichteres reden?",
    "Lass uns das abschließen.",
    "Nächstes Thema bitte.",
    "Ich will nicht zu tief einsteigen.",
    "Können wir pragmatisch werden?",
    "Lass uns das sacken lassen und weitermachen.",
    "Ich schlage einen Themenwechsel vor.",
    "Genug Emotionen, jetzt Fakten.",
    "Lass uns das auf ein anderes Mal verschieben.",
  ],
},

"ATO_STEGANO_HINT": {
  "positive": [
    "Das ist versteckte Sprache, hörst du es?",
    "Ich habe das kodiert, damit nur du es verstehst.",
    "Steganografisch verpackt, die Botschaft ist drin.",
    "Es gibt versteckte Hinweise in meinem Text.",
    "Die kodierte Botschaft ist zwischen den Zeilen.",
    "Versteckte Sprache, nur für Eingeweihte.",
    "Das ist kodiert, lies genau.",
    "Steganografisch eingebettet in den Satz.",
    "Versteckte Zeichen, die mehr sagen.",
    "Die Botschaft ist kodiert, nicht offensichtlich.",
    "Das ist eine versteckte Nachricht.",
    "Kodiert und verschlüsselt, nur für dich.",
    "Steganografisch markiert, achte auf die Details.",
    "Versteckte Sprache im Klartext.",
    "Das ist ein kodierter Hinweis.",
    "Steganografische Elemente in der Nachricht.",
    "Versteckter Subtext, den man entschlüsseln muss.",
    "Das ist kodiert geschrieben.",
    "Steganografisch verschleiert, aber lesbar.",
    "Versteckte Bedeutung im Text.",
    "Kodierte Nachricht, pass auf.",
    "Steganografisch eingewebt.",
    "Versteckte Sprache als Warnung.",
    "Das ist ein kodiertes Signal.",
    "Steganografisch platzierte Information.",
    "Versteckte Botschaft, die nur wir kennen.",
    "Kodiert wie ein Geheimcode.",
    "Steganografisch getarnt.",
    "Versteckte Hinweise überall.",
    "Das ist kodiert, ich schwöre.",
    "Steganografisch ist das Absicht.",
    "Versteckte Sprache, kein Zufall.",
    "Kodierte Zeichen im Text.",
    "Steganografisch verborgen.",
    "Versteckte Markierung.",
    "Das ist ein kodiertes Muster.",
    "Steganografisch angelegte Spur.",
    "Versteckte Worte zwischen den Zeilen.",
    "Kodiert und nur für uns verständlich.",
    "Steganografisch eingebaut.",
    "Versteckte Sprache, die Bedeutung trägt.",
    "Das ist kodiert, achte auf die Großbuchstaben.",
    "Steganografischer Trick.",
    "Versteckter Code im Alltagstext.",
    "Kodierte Information, nicht für alle.",
    "Steganografisch verpackte Warnung.",
    "Versteckte Sprache, klassisch.",
    "Das ist ein kodiertes Versteckspiel.",
    "Steganografisch verschlüsselt.",
    "Versteckte Botschaft, lies nochmal.",
  ],
  "negative": [
    "Ich sage dir offen, was ich denke.",
    "Kein Geheimnis, alles klar formuliert.",
    "Das ist wörtlich gemeint, keine Codes.",
    "Ich meine das genau so, wie ich es sage.",
    "Klartext, ohne versteckte Bedeutung.",
    "Alles transparent, nichts verborgen.",
    "Ich drücke mich direkt aus.",
    "Kein Subtext, das ist, was es ist.",
    "Ich verstecke nichts in meinen Worten.",
    "Offen und ehrlich, ohne Hintergedanken.",
    "Das ist direkt und unverschlüsselt.",
    "Keine doppelten Böden hier.",
    "Ich rede Klartext.",
    "Alles offen auf dem Tisch.",
    "Kein Geheimcode, einfach Deutsch.",
    "Ich sage es, wie es ist.",
    "Transparent und deutlich.",
    "Keine versteckten Absichten.",
    "Das ist keine Verschlüsselung.",
    "Alles klar und verständlich.",
    "Ich kommuniziere direkt.",
    "Kein Rätsel, keine Codes.",
    "Wörtlich nehmen, bitte.",
    "Offene Kommunikation, das wars.",
    "Kein Versteckspiel nötig.",
  ],
},

"ATO_STRESS": {
  "positive": [
    "Ich bin heute total gestresst.",
    "Die letzte Woche war extrem stressig.",
    "Mir wird das alles zu viel.",
    "Ich fühle mich komplett überfordert.",
    "Ich stehe gerade enorm unter Druck.",
    "Ich schaff das nicht mehr alles.",
    "Der Stress frisst mich auf.",
    "Das ist eine riesige Belastung für mich.",
    "Ich bin am Limit.",
    "Zu viel auf einmal.",
    "Ich bin so gestresst, ich kann nicht mehr.",
    "Alles ist gerade stressig.",
    "Ich fühle mich total überfordert mit allem.",
    "Der Druck ist unter Druck kaum auszuhalten.",
    "Ich schaff das einfach nicht mehr.",
    "Der Stress macht mich krank.",
    "Zu viel Arbeit, zu wenig Zeit.",
    "Ich bin überfordert und erschöpft.",
    "Der ganze Tag war stressig.",
    "Unter Druck funktioniere ich nicht gut.",
    "Ich bin gestresst wegen der Deadline.",
    "Das wird mir zu viel gerade.",
    "Stressig ohne Ende diese Woche.",
    "Ich bin überfordert mit den Anforderungen.",
    "Der Druck von allen Seiten ist unter Druck enorm.",
    "Ich schaff das nicht mehr, ehrlich.",
    "Zu viel Stress, zu wenig Schlaf.",
    "Ich fühle mich unter Druck gesetzt.",
    "Alles auf einmal, das ist zu viel.",
    "Der Stress lässt nicht nach.",
    "Ich bin gestresst und genervt.",
    "Überfordert ist noch untertrieben.",
    "Der Druck wird jeden Tag größer.",
    "Ich schaff das nicht in der Zeit.",
    "Stressig ist gar kein Ausdruck.",
    "Zu viel auf dem Teller gerade.",
    "Ich bin gestresst vom Pendeln allein.",
    "Überfordert mit der Situation.",
    "Unter Druck arbeiten macht mich fertig.",
    "Ich schaff das nicht alleine.",
    "Alles ist zu viel, ich brauche Pause.",
    "Gestresst und am Ende.",
    "Der Zeitdruck ist stressig.",
    "Ich bin so überfordert, ich könnte heulen.",
    "Unter Druck stehe ich ständig.",
    "Das ist mir alles zu viel.",
    "Stressig, stressig, stressig.",
    "Ich bin überfordert und frustriert.",
    "Zu viel Verantwortung auf einmal.",
    "Ich schaff das nicht mehr, ich brauche Hilfe.",
  ],
  "negative": [
    "Mir geht es gut, danke der Nachfrage.",
    "Ich bin gerade entspannt.",
    "Alles in Ordnung bei mir.",
    "Ich fühle mich heute ruhig und gelassen.",
    "Alles im Griff, kein Problem.",
    "Ich habe gerade viel Ruhe.",
    "Alles läuft, ich bin tiefenentspannt.",
    "Kein Druck, alles easy.",
    "Ich genieße die freie Zeit.",
    "Stressfrei heute, endlich mal.",
    "Ich bin ausgeglichen und zufrieden.",
    "Alles im grünen Bereich.",
    "Mir geht es blendend.",
    "Ich fühle mich wohl und sicher.",
    "Keine Sorgen gerade.",
    "Ich bin relaxed.",
    "Alles harmonisch bei mir.",
    "Kein Zeitdruck, alles fein.",
    "Ich bin gelassen und froh.",
    "Nichts belastet mich gerade.",
    "Ich genieße den Moment.",
    "Alles ruhig hier.",
    "Mir geht es richtig gut.",
    "Ich habe alles im Griff.",
    "Entspannt und zufrieden, danke.",
  ],
},

"ATO_STRESS_ACCENT": {
  "positive": [
    "(Ungewöhnliche Wortbetonung erkannt)",
    "(Nachdruck auf unerwarteter Silbe)",
    "(Emphase durch Betonung)",
    "(Störung im Rhythmus durch Akzent)",
    "(Markierte Prosodie auf Schlüsselwort)",
    "(Betonung weicht von Norm ab)",
    "(Stress-Akzent auf Funktionswort)",
    "(Unerwartete Prominenz einer Silbe)",
    "(Rhythmusbruch durch Betonungsfehler)",
    "(Emphase auf normalerweise unbetontem Wort)",
    "(Akzentverschiebung bei emotionalem Wort)",
    "(Betonung auf falscher Silbe, emotional bedingt)",
    "(Stress-Pattern abweichend von Baseline)",
    "(Hervorhebung durch ungewöhnlichen Akzent)",
    "(Prosodischer Akzent auf Nebenwort)",
    "(Betonung signalisiert innere Anspannung)",
    "(Ungewöhnlicher Nachdruck auf Pronomen)",
    "(Akzentmuster untypisch für den Sprecher)",
    "(Stress auf Partikel statt Verb)",
    "(Emphase durch verdoppelten Akzent)",
    "(Rhythmusstörung durch Betonungswechsel)",
    "(Akzent auf Artikel statt Nomen)",
    "(Prosodische Deviation beim Kernwort)",
    "(Unerwartete Betonung am Satzende)",
    "(Stress-Akzent mitten im Wort verschoben)",
    "(Emphase durch verlangsamte Betonung)",
    "(Akzentverschiebung bei Verneinung)",
    "(Ungewöhnliche Hervorhebung eines Adjektivs)",
    "(Stress auf Konjunktion auffällig)",
    "(Betonung weicht von Sprecher-Baseline ab)",
    "(Akzent auf normalerweise stummem Wort)",
    "(Prosodische Markierung eines Schlüsselbegriffs)",
    "(Stress-Pattern zeigt emotionale Ladung)",
    "(Emphase durch Akzentdoppelung)",
    "(Rhythmusabweichung durch Stress-Shift)",
    "(Unerwarteter Akzent auf Hilfsverb)",
    "(Betonung signalisiert Widerspruch)",
    "(Akzentverschiebung bei Frage)",
    "(Stress auf Adverb statt Verb)",
    "(Emphase durch prosodische Hervorhebung)",
    "(Ungewöhnliche Betonung in der Mitte des Satzes)",
    "(Akzentmuster zeigt Unsicherheit)",
    "(Stress auf unbetonter Silbe)",
    "(Emphase durch Tonhöhenwechsel mit Akzent)",
    "(Rhythmusstörung bei emotionalem Inhalt)",
    "(Betonung auf Präposition auffällig)",
    "(Akzent verschoben bei persönlichem Thema)",
    "(Stress-Pattern inkonsistent)",
    "(Emphase auf Wort mit normalerweise flachem Akzent)",
    "(Prosodische Auffälligkeit bei Kernaussage)",
  ],
  "negative": [
    "Spricht mit normaler, gleichmäßiger Betonung.",
    "Kein auffälliger Akzent erkennbar.",
    "Standard-Intonation ohne Abweichungen.",
    "Betonung folgt natürlichem Sprachrhythmus.",
    "Keine ungewöhnlichen prosodischen Muster.",
    "Monotone, aber korrekte Betonung.",
    "Natürlicher Satzakzent, nichts Auffälliges.",
    "Standardmäßige Wortbetonung durchgehend.",
    "Keine Akzentverschiebungen erkannt.",
    "Prosodie im Normbereich.",
    "Unauffällige Sprechmelodie.",
    "Betonung entspricht der Erwartung.",
    "Kein Stress-Shift erkennbar.",
    "Gleichmäßiger Sprechrhythmus.",
    "Normale Intonation, kein Emphase-Signal.",
    "Standardmäßige Akzentmuster.",
    "Keine prosodischen Auffälligkeiten.",
    "Betonung korrekt und unauffällig.",
    "Sprechrhythmus ohne Brüche.",
    "Normale Prosodie, keine Markierungen.",
    "Gleichförmige Betonung über den Satz.",
    "Kein ungewöhnlicher Nachdruck.",
    "Prosodie passt zum Inhalt.",
    "Standardbetonung, alles normal.",
    "Keine emotionalen Akzentverschiebungen.",
  ],
},

"ATO_STRUCT_PAUSE": {
  "positive": [
    "...",
    "Ich halte.",
    "Jetzt.",
    "Still.",
    "... danke.",
    "Pause.",
    "Hmm.",
    "Ja.",
    "Nein.",
    "Okay.",
    "... und dann?",
    "Hier.",
    "So.",
    "Moment.",
    "... warte.",
    "Atme.",
    "Tief.",
    "... ja.",
    "Gut.",
    "Fertig.",
    "... genau.",
    "Stille.",
    "Raum.",
    "... hm.",
    "Da.",
    "Nichts.",
    "... bitte.",
    "Ende.",
    "Oh.",
    "... ach.",
    "Genug.",
    "Eben.",
    "... also.",
    "Klar.",
    "... naja.",
    "Doch.",
    "... stopp.",
    "Leer.",
    "... und?",
    "Punkt.",
    "... hm, ja.",
    "Ruhig.",
    "... okay?",
    "Tja.",
    "Wow.",
    "... aha.",
    "Na.",
    "... ganz still.",
    "Kurz.",
    "... ich warte.",
  ],
  "negative": [
    "Ich finde, wir sollten das mal ausführlich besprechen, weil es ein komplexes Thema ist.",
    "Lass uns das Schritt für Schritt durchgehen und alle Details klären.",
    "Ich habe mehrere Punkte, die ich ansprechen möchte, und zwar in dieser Reihenfolge.",
    "Das ist ein längerer Gedanke, den ich hier ausbreiten möchte.",
    "Ich erkläre dir jetzt in Ruhe, wie ich das sehe und warum.",
    "Es gibt viele Aspekte zu berücksichtigen, deshalb rede ich etwas länger.",
    "Meine Überlegung dazu ist folgende, und die hat mehrere Ebenen.",
    "Ich möchte das ausführlich darlegen, damit keine Fragen offen bleiben.",
    "Das ist ein vielschichtiges Thema, das ich nicht in einem Satz abhandeln kann.",
    "Lass mich das in mehreren Sätzen erklären, es ist nicht trivial.",
    "Ich habe viel dazu zu sagen und nehme mir die Zeit.",
    "Das braucht mehr Kontext, also hole ich etwas aus.",
    "Mein Standpunkt ist folgender und ich begründe ihn ausführlich.",
    "Es gibt da verschiedene Perspektiven, die ich alle beleuchten will.",
    "Ich erkläre das detailliert, weil es wichtig ist.",
    "Das ist ein langer Absatz, aber er ist nötig.",
    "Ich lege meine Argumente der Reihe nach dar.",
    "Das Thema verdient eine ausführliche Behandlung.",
    "Ich rede jetzt etwas länger, weil das Thema es verlangt.",
    "Lass mich das in Ruhe und vollständig erklären.",
    "Mein Beitrag hat mehrere Teile, ich fange mal an.",
    "Das ist komplex, deshalb brauche ich mehr Worte.",
    "Ich beschreibe das ausführlich und mit Beispielen.",
    "Es folgt eine längere Erklärung meinerseits.",
    "Ich breite das jetzt aus, Schritt für Schritt.",
  ],
},

"ATO_STYLE_REFERENCE": {
  "positive": [
    "Stilwechsel: kurz und direkt.",
    "Bitte im sachlichen Ton.",
    "Heute eher formell.",
    "Lass es locker klingen.",
    "Bitte knapp halten.",
    "Ton ändern: pragmatisch.",
    "Kurz und direkt, bitte.",
    "Im sachlichen Ton, danke.",
    "Bitte knapp.",
    "Eher locker formulieren.",
    "Formell halten, bitte.",
    "Stilwechsel: mehr Empathie.",
    "Bitte im sachlichen Ton bleiben.",
    "Heute bitte knapp und klar.",
    "Locker schreiben, nicht so steif.",
    "Formell und höflich bitte.",
    "Kurz und direkt antworten.",
    "Im sachlichen Ton formulieren.",
    "Bitte knapp zusammenfassen.",
    "Locker und ungezwungen, okay?",
    "Stilwechsel: diplomatischer bitte.",
    "Formell für die Geschäftsleitung.",
    "Kurz und direkt, keine Umschweife.",
    "Im sachlichen Ton, ohne Emotionen.",
    "Bitte knapp und prägnant.",
    "Locker wie in einer WhatsApp.",
    "Formell wie ein offizielles Schreiben.",
    "Stilwechsel: persönlicher werden.",
    "Kurz und direkt, Zeit ist knapp.",
    "Im sachlichen Ton für den Kunden.",
    "Bitte knapp und auf den Punkt.",
    "Locker und freundlich formulieren.",
    "Formell und respektvoll bitte.",
    "Stilwechsel: weniger distanziert.",
    "Kurz und direkt, ohne Floskel.",
    "Im sachlichen Ton weiterführen.",
    "Bitte knapp und verständlich.",
    "Locker, wie unter Freunden.",
    "Formell für das Protokoll.",
    "Stilwechsel: mehr Struktur.",
    "Kurz und direkt kommunizieren.",
    "Im sachlichen Ton abhandeln.",
    "Bitte knapp, maximal drei Sätze.",
    "Locker und entspannt.",
    "Formell und professionell.",
    "Stilwechsel: wärmer werden.",
    "Kurz und direkt, wie gewünscht.",
    "Im sachlichen Ton antworten.",
    "Bitte knapp und korrekt.",
    "Locker, aber respektvoll.",
  ],
  "negative": [
    "Ich erzähle dir mal, wie mein Tag war.",
    "Das Wetter wird morgen besser.",
    "Wir haben heute Abend Besuch.",
    "Ich habe den Bericht gelesen.",
    "Die Besprechung war produktiv.",
    "Ich freue mich auf das Wochenende.",
    "Das Essen war lecker.",
    "Ich habe neue Schuhe gekauft.",
    "Der Film gestern war spannend.",
    "Ich muss noch einkaufen.",
    "Die Kinder haben Ferien.",
    "Ich war beim Sport.",
    "Das Meeting dauerte lang.",
    "Ich habe gut geschlafen.",
    "Der Kaffee ist alle.",
    "Wir fahren morgen weg.",
    "Ich habe das Buch beendet.",
    "Die Blumen brauchen Wasser.",
    "Ich rufe dich später an.",
    "Das Projekt läuft gut.",
    "Ich bin müde heute.",
    "Wir essen um sieben.",
    "Der Zug war pünktlich.",
    "Ich habe die Mail geschickt.",
    "Das Wochenende war schön.",
  ],
},

"ATO_SUBJECT_CLOSED": {
  "positive": [
    "Für mich ist alles gesagt.",
    "Thema erledigt.",
    "Passt für mich so.",
    "Lassen wir das so.",
    "Haken dran.",
    "So viel dazu.",
    "Das Thema ist durch.",
    "Alles gesagt, alles klar.",
    "Haken dran, nächstes Thema.",
    "Passt für mich, fertig.",
    "Lassen wir das so stehen.",
    "So viel dazu, weiter geht's.",
    "Für mich ist das erledigt.",
    "Thema erledigt, danke.",
    "Alles gesagt, was zu sagen war.",
    "Haken dran, können wir weitermachen.",
    "Passt für mich, abgehakt.",
    "Lassen wir das so, ich bin zufrieden.",
    "So viel dazu, Punkt.",
    "Thema erledigt, kein Bedarf mehr.",
    "Für mich ist alles gesagt dazu.",
    "Haken dran, Ende der Diskussion.",
    "Passt für mich, lassen wir es.",
    "So viel dazu, das reicht.",
    "Alles gesagt, ich bin durch.",
    "Thema erledigt, abhaken.",
    "Haken dran, ab zum nächsten.",
    "Passt für mich, war's das.",
    "Lassen wir das so, einverstanden.",
    "So viel dazu, mehr gibt es nicht zu sagen.",
    "Für mich ist das abgeschlossen.",
    "Thema erledigt, fertig besprochen.",
    "Alles gesagt, von meiner Seite.",
    "Haken dran, kein Gesprächsbedarf mehr.",
    "Passt für mich, danke fürs Klären.",
    "Lassen wir das so, das passt.",
    "So viel dazu, ich habe fertig.",
    "Thema erledigt, können wir loslassen.",
    "Für mich ist das durch.",
    "Haken dran, erledigt.",
    "Passt für mich, ich bin zufrieden damit.",
    "Alles gesagt, alles getan.",
    "So viel dazu, und jetzt vorwärts.",
    "Thema erledigt, Deckel drauf.",
    "Haken dran, nicht mehr drüber reden.",
    "Passt für mich, wir sind uns einig.",
    "Lassen wir das so, alles gut.",
    "So viel dazu, ab ins Archiv.",
    "Für mich ist alles gesagt und erledigt.",
    "Thema erledigt, endgültig.",
  ],
  "negative": [
    "Ich möchte nochmal darauf zurückkommen.",
    "Das Thema ist noch nicht abgeschlossen.",
    "Wir sollten das nochmal besprechen.",
    "Da gibt es noch offene Fragen.",
    "Ich bin noch nicht fertig damit.",
    "Können wir nochmal darüber reden?",
    "Das ist noch nicht ausdiskutiert.",
    "Ich habe noch Gesprächsbedarf.",
    "Das Thema braucht mehr Aufmerksamkeit.",
    "Wir haben das noch nicht geklärt.",
    "Ich möchte nochmal nachhaken.",
    "Das ist mir noch nicht klar genug.",
    "Können wir das vertiefen?",
    "Es gibt noch ungeklärte Punkte.",
    "Ich finde, wir sollten weiterdiskutieren.",
    "Das ist noch offen.",
    "Ich brauche noch mehr Information.",
    "Können wir das Thema nochmal aufgreifen?",
    "Da fehlt mir noch etwas.",
    "Wir haben das nur angerissen.",
    "Ich möchte noch tiefer gehen.",
    "Das Thema verdient mehr Zeit.",
    "Wir sind noch nicht am Ende.",
    "Ich habe noch Fragen dazu.",
    "Das ist noch work in progress.",
  ],
},

"ATO_SUBSTANCE_CRAVING": {
  "positive": [
    "Ich brauch das jetzt ganz dringend.",
    "Das Verlangen ist unerträglich.",
    "Nur ein bisschen, das reicht mir.",
    "Ich kann nicht widerstehen.",
    "Ein Zug und mir geht's besser.",
    "Ich brauche es so sehr gerade.",
    "Dieses Verlangen bringt mich um.",
    "Nur ein kleines bisschen, bitte.",
    "Ich schaffe es nicht, nein zu sagen.",
    "Einmal noch, dann höre ich auf.",
    "Ich brauche das dringend, sofort.",
    "Das Craving ist brutal heute.",
    "Nur ein Schluck zur Beruhigung.",
    "Ich kann dem Drang nicht widerstehen.",
    "Ein Hit und alles wird gut.",
    "Ich brauche es, ich halte es nicht aus.",
    "Das Verlangen frisst mich auf.",
    "Nur ein kleines Stück, mehr nicht.",
    "Ich kann nichts dagegen tun.",
    "Noch einmal, das letzte Mal.",
    "Ich brauche das zum Funktionieren.",
    "Das Verlangen kommt in Wellen.",
    "Nur ein Tropfen zur Entspannung.",
    "Ich widerstehe nicht mehr.",
    "Einmal probieren schadet nicht.",
    "Ich brauche das wie Luft zum Atmen.",
    "Das Craving ist unbeschreiblich.",
    "Nur ein winziges bisschen.",
    "Ich kann es nicht lassen.",
    "Einmal noch und dann Schluss.",
    "Mein Körper verlangt danach.",
    "Das Verlangen überwältigt mich.",
    "Nur eine Pille zur Beruhigung.",
    "Ich halte es ohne nicht aus.",
    "Ein Zug reicht, versprochen.",
    "Ich brauche das, um klarzukommen.",
    "Das Craving macht mich verrückt.",
    "Nur ein Glas, wirklich nur eins.",
    "Ich kann dem nicht entkommen.",
    "Noch einmal, für die Nerven.",
    "Ich brauche es wie eine Medizin.",
    "Das Verlangen ist wie Hunger.",
    "Nur eine Linie, dann bin ich ruhig.",
    "Ich widerstehe dem Drang nicht.",
    "Einmal noch, letzte Chance.",
    "Ich brauche das zum Einschlafen.",
    "Das Craving kontrolliert mich.",
    "Nur ein Hauch, ganz wenig.",
    "Ich kann nicht ohne.",
    "Noch einmal, ich verspreche, dann nie wieder.",
  ],
  "negative": [
    "Ich brauche das nicht mehr.",
    "Kein Verlangen heute, zum Glück.",
    "Auch ein wenig ist zu viel.",
    "Ich widerstehe problemlos.",
    "Nein danke, ich bin clean.",
    "Kein Drang, ich bin stabil.",
    "Ich brauche das nicht zum Leben.",
    "Kein Craving, ich bin frei.",
    "Ich sage nein, und es fällt leicht.",
    "Nicht einmal ein bisschen.",
    "Ich bin über das Verlangen hinweg.",
    "Kein Bedarf, ich bin stark genug.",
    "Ich schaffe das ohne.",
    "Der Drang ist weg.",
    "Ich brauche keine Krücken mehr.",
    "Nein heißt nein, kein Problem.",
    "Kein Verlangen, keine Sorgen.",
    "Ich bin davon befreit.",
    "Der Entzug ist geschafft.",
    "Ich lebe ohne, und es geht mir gut.",
    "Kein Rückfall, kein Verlangen.",
    "Ich bin stärker als der Drang.",
    "Kein Bedürfnis mehr danach.",
    "Ich habe das hinter mir.",
    "Nüchtern und zufrieden.",
  ],
},

"ATO_SUBSTANCE_DENIAL": {
  "positive": [
    "Nur noch ein Glas, das schadet nicht.",
    "Es ist kein Problem, ich hab alles unter Kontrolle.",
    "Ich kann jederzeit aufhören.",
    "Jeder macht das, ist ganz normal.",
    "Ich bin nicht abhängig, ich genieße es nur.",
    "Noch eine Zigarette ist okay.",
    "Ist alles im Griff, keine Sorge.",
    "Ich höre auf, wann ich will.",
    "Freunde machen das auch.",
    "Nicht süchtig, nur gewohnheitsmäßig.",
    "Eine Pille mehr macht nichts.",
    "Es ist unter Kontrolle, glaub mir.",
    "Ich entscheide selbst, wann Schluss ist.",
    "Ganz normale Gewohnheit, nichts Schlimmes.",
    "Genuss, keine Sucht.",
    "Ein letzter Joint ist in Ordnung.",
    "Null Problemo, ich manage das.",
    "Ich kontrolliere das vollständig.",
    "Andere machen Schlimmeres.",
    "Nicht abhängig, niemals.",
    "Nur zum Entspannen, sonst nichts.",
    "Es ist alles kein Problem bei mir.",
    "Aufhören? Jederzeit möglich.",
    "Alle trinken doch.",
    "Ich bin definitiv nicht süchtig.",
    "Noch ein Bier, was soll's.",
    "Ich hab das völlig unter Kontrolle.",
    "Wenn ich will, höre ich sofort auf.",
    "Meine Freunde konsumieren mehr als ich.",
    "Das ist Genuss, nicht Abhängigkeit.",
    "Nur am Wochenende, das zählt nicht.",
    "Kein Thema, ich schaffe das.",
    "Ich brauche das nicht wirklich.",
    "Andere haben echte Probleme, ich nicht.",
    "Nicht abhängig, ich wähle das.",
    "Ein Gläschen zum Essen, ganz normal.",
    "Ich habe alles im Griff.",
    "Aufhören ist keine Frage des Könnens.",
    "So machen das alle in meinem Alter.",
    "Rekreativ, nicht pathologisch.",
    "Noch ein letztes Mal, dann ist gut.",
    "Es ist kein Problem, wirklich nicht.",
    "Ich kontrolliere meinen Konsum.",
    "Normal, machen alle so.",
    "Nicht abhängig, nur gewöhnt.",
    "Ein Schluck schadet nicht.",
    "Alles unter Kontrolle hier.",
    "Ich entscheide, nicht die Substanz.",
    "Ganz normales Verhalten.",
    "Ich bin nicht süchtig, Punkt.",
  ],
  "negative": [
    "Ich muss aufhören, nach diesem Drink.",
    "Es wird zu einem Problem.",
    "Ich kann nicht so einfach aufhören.",
    "Das machen nicht alle, nur ich.",
    "Ich bin vielleicht abhängig.",
    "Keine Zigaretten mehr für mich.",
    "Das ist ein echtes Problem.",
    "Aufhören fällt mir schwer.",
    "Nicht normal für die meisten.",
    "Ich bin süchtig.",
    "Keine Pillen mehr, Schluss.",
    "Außer Kontrolle geraten.",
    "Ich kann nicht aufhören.",
    "Ungewöhnlich und schädlich.",
    "Definitiv abhängig.",
    "Kein letzter Zug mehr.",
    "Großes Problem.",
    "Keine Kontrolle mehr.",
    "Schlimmer als andere.",
    "Total abhängig.",
    "Ich brauche Hilfe damit.",
    "Es ist ein ernstes Thema.",
    "Ich habe die Kontrolle verloren.",
    "Ich bin ehrlich: Es ist ein Problem.",
    "Ich muss was ändern.",
  ],
},

"ATO_SUPERLATIVE_PHRASE": {
  "positive": [
    "Immer wenn ich dich brauche, bist du nicht da!",
    "Du übernimmst nie Verantwortung.",
    "Niemals hältst du dein Wort.",
    "Jedes Mal versprichst du Hilfe und tauchst nicht auf.",
    "Du reagierst ständig zu spät.",
    "Er ist andauernd genervt von jedem Vorschlag.",
    "Du machst immer dasselbe falsch.",
    "Nie hörst du mir richtig zu.",
    "Jedes Mal muss ich das alleine machen.",
    "Ständig kommst du zu spät.",
    "Andauernd vergisst du, was ich sage.",
    "Immer muss ich alles wiederholen.",
    "Nie nimmst du dir Zeit für mich.",
    "Jedes Mal wenn ich frage, weichst du aus.",
    "Ständig streitest du dich.",
    "Immer das Gleiche mit dir.",
    "Nie bist du zufrieden.",
    "Jedes Mal ein Drama.",
    "Ständig beschwerst du dich.",
    "Andauernd machst du Fehler.",
    "Immer bin ich schuld bei dir.",
    "Nie sagst du danke.",
    "Jedes Mal muss ich nachfragen.",
    "Ständig wechselst du deine Meinung.",
    "Andauernd störst du mich.",
    "Immer wenn es wichtig ist, bist du weg.",
    "Nie hast du eine Lösung.",
    "Jedes Mal ist es dein Problem.",
    "Ständig redest du dagegen.",
    "Andauernd bist du müde.",
    "Immer muss ich die Entscheidung treffen.",
    "Nie zeigst du Initiative.",
    "Jedes Mal kommt eine Ausrede.",
    "Ständig bist du am Handy.",
    "Andauernd planst du um.",
    "Immer wenn ich was sage, rollst du die Augen.",
    "Nie ist es dir recht.",
    "Jedes Mal vergisst du den Termin.",
    "Ständig hast du andere Prioritäten.",
    "Andauernd kommt was dazwischen.",
    "Immer soll ich mich anpassen.",
    "Nie gibst du nach.",
    "Jedes Mal wird es kompliziert.",
    "Ständig muss ich mich erklären.",
    "Andauernd machst du dicht.",
    "Immer reagierst du über.",
    "Nie sagst du, was du wirklich denkst.",
    "Jedes Mal am Ende bin ich der Dumme.",
    "Ständig wiederholst du dich.",
    "Andauernd bist du unzufrieden.",
  ],
  "negative": [
    "Manchmal wenn ich dich brauche, bist du nicht da.",
    "Du übernimmst selten Verantwortung.",
    "Oft versprichst du Hilfe und tauchst nicht auf.",
    "Ab und zu reagierst du zu spät.",
    "Gelegentlich vergisst du das.",
    "Hin und wieder passiert das.",
    "Meistens läuft es gut, aber nicht heute.",
    "Es kommt vor, dass du zu spät kommst.",
    "Einige Male war das so.",
    "Das passiert gelegentlich, nicht regelmäßig.",
    "Vereinzelt gibt es Probleme.",
    "In letzter Zeit war das häufiger.",
    "Zweimal diese Woche war es so.",
    "Es ist nicht die Regel, aber es kommt vor.",
    "Manchmal fällt es mir auf.",
    "Es gibt Momente, in denen das schwierig ist.",
    "Gelegentlich stimmt das Timing nicht.",
    "Hin und wieder vergisst du es.",
    "Einige Situationen waren so.",
    "Ab und zu erlebe ich das.",
    "Manchmal denke ich das auch.",
    "Es gibt Phasen, in denen das vorkommt.",
    "Gelegentlich ist das ein Thema.",
    "Nicht oft, aber manchmal schon.",
    "Es kommt ab und an vor.",
  ],
},

"ATO_SUPERLATIVE_PRAISE": {
  "positive": [
    "Du bist absolut perfekt für mich.",
    "Das ist unglaublich, wie gut wir zusammenpassen.",
    "Du bist einzigartig, anders als alle anderen.",
    "Wir sind Seelenverwandte, das spüre ich.",
    "Das fühlt sich an wie Schicksal.",
    "Du bist perfekt, genau so wie du bist.",
    "Unglaublich, wie schnell wir uns verstehen.",
    "Du bist die tollste Person, die ich kenne.",
    "Das ist Schicksal, dass wir uns getroffen haben.",
    "Du bist perfekt in jeder Hinsicht.",
    "Ich finde dich absolut unglaublich.",
    "Seelenverwandte, ganz klar.",
    "Du bist so perfekt, das ist fast unwirklich.",
    "Unglaublich, was für ein Mensch du bist.",
    "Du bist anders als alle, die ich getroffen habe.",
    "Das ist Schicksal, ich bin mir sicher.",
    "Du bist perfekt für diese Rolle.",
    "Unglaublich talentiert und einzigartig.",
    "Seelenverwandte findet man selten, aber dich hab ich gefunden.",
    "Du bist so perfekt, ich kann es kaum glauben.",
    "Das ist einfach unglaublich mit dir.",
    "Du bist die perfekte Ergänzung.",
    "Schicksal hat uns zusammengeführt.",
    "Du bist absolut einzigartig und perfekt.",
    "Unglaublich, wie gut du das machst.",
    "Seelenverwandte, ohne Zweifel.",
    "Du bist perfekt, mehr gibt es nicht zu sagen.",
    "Das ist unglaublich schön mit dir.",
    "Du bist anders als jeder andere Mensch.",
    "Schicksal, Fügung, Bestimmung.",
    "Du bist so perfekt, dass es wehtut.",
    "Unglaublich, wie du mich verstehst.",
    "Seelenverwandte erkennen sich, und ich erkenne dich.",
    "Du bist die perfekte Person.",
    "Das ist unglaublich, was wir haben.",
    "Du bist einzigartig auf dieser Welt.",
    "Schicksal wollte, dass wir uns finden.",
    "Perfekt beschreibt dich noch nicht mal ansatzweise.",
    "Unglaublich, einfach unglaublich.",
    "Du bist mein Seelenverwandter.",
    "So perfekt, dass ich Angst habe, es zu verlieren.",
    "Unglaublich, wie natürlich das ist.",
    "Seelenverwandte in jeder Hinsicht.",
    "Du bist perfekt und ich bin dankbar.",
    "Das ist eine unglaubliche Verbindung.",
    "Du bist anders, besser, einzigartig.",
    "Schicksal, pur und einfach.",
    "Du bist perfekt, ich wiederhole mich gern.",
    "Unglaublich, was du aus mir machst.",
    "Seelenverwandte, das steht fest.",
  ],
  "negative": [
    "Du bist ein netter Mensch, wir passen ganz gut zusammen.",
    "Das läuft okay zwischen uns.",
    "Ich mag dich, du hast viele gute Seiten.",
    "Wir verstehen uns gut, aber nicht immer.",
    "Du hast Stärken und Schwächen, wie jeder.",
    "Es gibt Dinge, die mir an dir gefallen.",
    "Wir harmonieren in manchen Bereichen.",
    "Du bist sympathisch, das schätze ich.",
    "Wir haben eine gute Basis.",
    "Ich finde dich toll, aber nicht makellos.",
    "Du bist ein guter Partner, meistens.",
    "Wir passen in vielen Dingen zusammen.",
    "Ich schätze deine Qualitäten.",
    "Du bist mir wichtig, mit Ecken und Kanten.",
    "Wir haben eine solide Verbindung.",
    "Ich finde dich attraktiv, ganz ehrlich.",
    "Du hast viele gute Eigenschaften.",
    "Wir ergänzen uns in einigen Bereichen.",
    "Ich bin froh, dich zu kennen.",
    "Du bist ein wertvoller Mensch.",
    "Wir haben Potenzial als Paar.",
    "Ich schätze dich für das, was du bist.",
    "Du bist ein guter Mensch.",
    "Wir haben Gemeinsamkeiten.",
    "Ich bin gerne mit dir zusammen.",
  ],
},

"ATO_SUPERLATIVE_SELF_REFERENCE": {
  "positive": [
    "Ich bin der Beste in meinem Bereich.",
    "Ich bin unerreicht in diesem Thema.",
    "Ich bin besser als alle anderen hier.",
    "Ich bin unschlagbar, was X angeht.",
    "Ich bin die Beste im Team.",
    "Ich bin das Beste, was dir passieren konnte.",
    "Ich bin der klar Beste für diese Rolle.",
    "Ich bin unerreicht in Qualität.",
    "Ich bin besser als alle Vergleichsprojekte.",
    "Ich bin unschlagbar in Geschwindigkeit.",
    "Ich bin der Beste, das sagen alle.",
    "Unerreicht in Erfahrung und Kompetenz.",
    "Besser als alle anderen Bewerber.",
    "Unschlagbar in Kreativität.",
    "Ich bin die Beste Managerin hier.",
    "Ich bin das Beste, was dem Projekt passieren konnte.",
    "Ich bin der Beste Programmierer im Unternehmen.",
    "Unerreicht in Effizienz.",
    "Besser als alle, die es vor mir versucht haben.",
    "Unschlagbar in Ausdauer.",
    "Ich bin die Beste in meiner Disziplin.",
    "Ich bin unerreicht in Zuverlässigkeit.",
    "Besser als alle Mitbewerber.",
    "Ich bin unschlagbar im Verkauf.",
    "Ich bin der Beste Coach, den du finden kannst.",
    "Unerreicht in Innovation.",
    "Besser als alle Erwartungen.",
    "Unschlagbar in Genauigkeit.",
    "Ich bin die Beste Beraterin weit und breit.",
    "Ich bin unerreicht in Kundenzufriedenheit.",
    "Besser als alle vorherigen Versionen.",
    "Unschlagbar, was Timing angeht.",
    "Ich bin der Beste Stratege.",
    "Unerreicht in Problemlösung.",
    "Besser als alle anderen Teams.",
    "Unschlagbar in Verhandlungen.",
    "Ich bin die Beste Wahl, ganz klar.",
    "Unerreicht in meinem Fachgebiet.",
    "Besser als alle Alternativen.",
    "Unschlagbar, wenn es drauf ankommt.",
    "Ich bin der Beste Leader.",
    "Unerreicht in Skalierbarkeit.",
    "Besser als alle Standards.",
    "Unschlagbar in Qualitätssicherung.",
    "Ich bin die Beste Präsentatorin.",
    "Unerreicht in Resultaten.",
    "Besser als alle Branchenbenchmarks.",
    "Unschlagbar in Disziplin.",
    "Ich bin der Beste, das ist Fakt.",
    "Unerreicht und unübertroffen.",
  ],
  "negative": [
    "Ich bin ganz gut in meinem Bereich.",
    "Ich habe Stärken und Schwächen.",
    "Ich bin kompetent, aber nicht perfekt.",
    "Ich mache meine Arbeit solide.",
    "Ich bin einer von vielen guten Leuten hier.",
    "Ich habe noch viel zu lernen.",
    "Ich bin okay, nicht überragend.",
    "Manche können das besser als ich.",
    "Ich bin zufrieden mit meiner Leistung.",
    "Ich bin in Ordnung, denke ich.",
    "Ich habe Raum zur Verbesserung.",
    "Ich bin nicht schlecht, aber auch nicht die Nummer eins.",
    "Ich mache meinen Job, ganz normal.",
    "Es gibt Leute, die das besser können.",
    "Ich bin durchschnittlich, ehrlich gesagt.",
    "Ich gebe mein Bestes, mehr nicht.",
    "Ich bin auf Augenhöhe mit anderen.",
    "Ich habe meine Grenzen.",
    "Ich bin gut genug, denke ich.",
    "Ich bin ein Teamplayer, kein Solo-Star.",
    "Ich bin bescheiden und lernbereit.",
    "Ich habe meine Stärken, aber auch Lücken.",
    "Ich bin ein normaler Mensch.",
    "Ich versuche mein Bestes.",
    "Ich bin zufrieden, wenn es gut läuft.",
  ],
},

}

# Continue in Part 2 - this dict will be extended by the next script parts


def enrich_marker(marker_id: str, data: dict) -> bool:
    """Enrich a single marker file with examples."""
    fpath = find_file(marker_id)
    if fpath is None:
        print(f"  SKIP {marker_id}: file not found")
        return False

    with open(fpath, "r") as f:
        doc = yaml.load(f)

    if doc is None:
        print(f"  SKIP {marker_id}: empty YAML")
        return False

    # Detect key structure
    # Some markers use examples.positive_de / negative_de
    # Some use examples.positive / negative
    # Some have nested 'markers' lists (e.g. ATO_TEMPORAL_ABSOLUTIZER)

    target = doc
    # Handle nested markers: [{id: ..., examples: ...}]
    if "markers" in doc and isinstance(doc["markers"], list):
        for m in doc["markers"]:
            if isinstance(m, dict) and m.get("id") == marker_id:
                # Update nested examples if they exist
                if "examples" in m:
                    nested_examples = m["examples"]
                    if isinstance(nested_examples, list):
                        # Convert list to proper examples with the new data
                        m["examples"] = data["positive"][:5]  # Keep nested compact

    # Find or create the top-level examples section
    if "examples" not in target:
        target["examples"] = {}

    examples = target["examples"]

    # Determine key names
    if "positive_de" in examples:
        pos_key = "positive_de"
        neg_key = "negative_de"
    else:
        pos_key = "positive"
        neg_key = "negative"

    # Set examples
    examples[pos_key] = data["positive"]
    examples[neg_key] = data["negative"]

    with open(fpath, "w") as f:
        yaml.dump(doc, f)

    pos_count = len(data["positive"])
    neg_count = len(data["negative"])
    print(f"  OK {marker_id}: {pos_count} pos + {neg_count} neg ({pos_key}/{neg_key})")
    return True


def main():
    success = 0
    fail = 0
    for marker_id, data in ENRICHMENTS.items():
        ok = enrich_marker(marker_id, data)
        if ok:
            success += 1
        else:
            fail += 1
    print(f"\nDone: {success} enriched, {fail} failed/skipped")


if __name__ == "__main__":
    main()
