#!/usr/bin/env python3
"""
Enrich ATO markers (batch 5d: UNILATERAL_DECISION through WILL_CONTACT).
50 positive + 25 negative German examples each.
"""

import os
from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096
yaml.allow_duplicate_keys = True

BASE = Path("/Users/benjaminpoersch/Projects/LeanDeep-annotator/build/markers_rated")
DIRS = [BASE / "1_approved" / "ATO", BASE / "2_good" / "ATO"]


def find_file(marker_id: str) -> Path | None:
    for d in DIRS:
        p = d / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None


ENRICHMENTS = {

"ATO_UNILATERAL_DECISION": {
  "positive": [
    "Ich habe entschieden, dass wir das Meeting absagen.",
    "Das mache ich jetzt einfach so, ohne Ruecksprache.",
    "Ich habe das bereits festgelegt.",
    "Ich habe beschlossen, dass wir es so machen.",
    "Ich habe das ohne dich geregelt.",
    "Ich habe entschieden, die Wohnung zu kuendigen.",
    "Das mache ich jetzt so, fertig.",
    "Ich habe beschlossen, den Vertrag zu unterschreiben.",
    "Ohne dich zu fragen, habe ich das Angebot angenommen.",
    "Ich entscheide das alleine.",
    "Ich habe bereits zugesagt.",
    "Ich mache das jetzt so, wie ich es fuer richtig halte.",
    "Ich habe das einfach gemacht, ohne Absprache.",
    "Die Entscheidung steht, ich habe beschlossen.",
    "Ich habe entschieden, dass wir umziehen.",
    "Das habe ich eigenmaechtig geregelt.",
    "Ich mache das jetzt so, basta.",
    "Ich habe beschlossen, die Kinder abzumelden.",
    "Ohne dich zu fragen, habe ich das Geld ueberwiesen.",
    "Ich entscheide, wann wir gehen.",
    "Ich habe das ohne Absprache geaendert.",
    "Ich mache das jetzt einfach, egal was du sagst.",
    "Ich habe beschlossen, den Job zu wechseln.",
    "Ohne Ruecksprache habe ich den Termin verschoben.",
    "Ich habe entschieden, dass wir das Auto verkaufen.",
    "Das mache ich jetzt so, Punkt.",
    "Ich habe das alleine beschlossen.",
    "Ich habe bereits ohne dich entschieden.",
    "Das lege ich fest, ohne Diskussion.",
    "Ich mache das jetzt so, wie ich will.",
    "Ich habe beschlossen, Schluss zu machen mit dem Projekt.",
    "Ohne dich einzubeziehen, habe ich die Einladungen verschickt.",
    "Ich entscheide hier, nicht du.",
    "Ich habe das eigenmaechtg organisiert.",
    "Das mache ich jetzt einfach so.",
    "Ich habe beschlossen, dass wir den Urlaub stornieren.",
    "Ohne Absprache habe ich die Bestellung aufgegeben.",
    "Ich habe entschieden, und dabei bleibt es.",
    "Das habe ich einfach gemacht.",
    "Ich mache das jetzt so, ohne weitere Diskussion.",
    "Ich habe beschlossen, die Mitgliedschaft zu kuendigen.",
    "Ohne dich zu fragen, habe ich den Handwerker bestellt.",
    "Ich entscheide das fuer uns beide.",
    "Ich habe das alleine in die Hand genommen.",
    "Das mache ich jetzt einfach, fertig aus.",
    "Ich habe beschlossen, dass ich morgen nicht komme.",
    "Ohne Abstimmung habe ich das durchgesetzt.",
    "Ich entscheide, was wir essen.",
    "Ich habe das gemacht, ohne jemanden zu fragen.",
    "Ich beschliesse, dass wir das Thema beenden.",
  ],
  "negative": [
    "Lass uns das gemeinsam entscheiden.",
    "Was denkst du, sollen wir das machen?",
    "Ich moechte deine Meinung dazu hoeren.",
    "Wir sollten das zusammen besprechen.",
    "Bevor ich entscheide, moechte ich deinen Rat.",
    "Lass uns abstimmen.",
    "Was meinst du, wie sollen wir vorgehen?",
    "Ich entscheide nicht alleine.",
    "Deine Stimme zaehlt hier genauso.",
    "Wir entscheiden das gemeinsam.",
    "Ich moechte dich einbeziehen.",
    "Was ist deine Meinung dazu?",
    "Lass uns zusammen ueberlegen.",
    "Ich brauche dein Okay dafuer.",
    "Wir sollten das im Team besprechen.",
    "Ich frage erst dich, bevor ich handle.",
    "Gemeinsam kommen wir zur besten Loesung.",
    "Was haetest du gern?",
    "Lass uns das demokratisch loesen.",
    "Ich moechte nicht ohne dich entscheiden.",
    "Wir ueberlegen zusammen.",
    "Dein Input ist mir wichtig.",
    "Wie siehst du das?",
    "Lass uns das zusammen beschliessen.",
    "Ich warte auf deine Rueckmeldung.",
  ],
},

"ATO_UNIT_ECON_CAC": {
  "positive": [
    "Unser CAC liegt bei 120 Euro.",
    "Die Akquisekosten pro Kunde betragen 80 Euro.",
    "CAC aktuell bei 95 Euro.",
    "Customer Acquisition Cost ist runter auf 60 Euro.",
    "Wir druecken CAC auf unter 100 Euro.",
    "Der CAC liegt deutlich unter dem LTV.",
    "Akquisekosten: 150 Euro pro Neukunde.",
    "CAC = 75 Euro, Tendenz fallend.",
    "Unsere Customer Acquisition Cost betraegt 110 Euro.",
    "CAC pro Kanal: Google 90 Euro, Facebook 120 Euro.",
    "Die Akquisekosten muessen runter.",
    "CAC-Optimierung ist unser Hauptziel.",
    "Wir haben den CAC halbiert.",
    "Customer Acquisition Cost im B2B: 200 Euro.",
    "CAC: 88 Euro im Durchschnitt.",
    "Die Akquisekosten sind zu hoch.",
    "Unser CAC liegt bei 130 Euro pro Nutzer.",
    "CAC senken durch organisches Wachstum.",
    "Customer Acquisition Cost fuer Enterprise: 500 Euro.",
    "Akquisekosten pro Lead: 35 Euro.",
    "Der CAC hat sich im letzten Quartal verbessert.",
    "Wir rechnen mit einem CAC von 100 Euro.",
    "Akquisekosten im Verhaealtnis zum ARPU pruefen.",
    "CAC: 65 Euro, bester Wert seit Monaten.",
    "Customer Acquisition Cost muss sinken.",
    "Der CAC fuer unser SaaS-Produkt liegt bei 180 Euro.",
    "Akquisekosten: Budget reicht fuer 200 Kunden.",
    "CAC-Payback-Period: 4 Monate.",
    "Unser CAC skaliert nicht gut.",
    "Customer Acquisition Cost im E-Commerce: 25 Euro.",
    "Akquisekosten sind der groesste Posten.",
    "CAC optimieren durch Content Marketing.",
    "Der aktuelle CAC liegt bei 105 Euro.",
    "Customer Acquisition Cost ist stabil bei 90 Euro.",
    "Akquisekosten steigen mit der Konkurrenz.",
    "CAC: 70 Euro nach Optimierung.",
    "Wir muessen die Akquisekosten senken.",
    "Customer Acquisition Cost analysieren.",
    "CAC pro Segment auswerten.",
    "Die Akquisekosten pro Kunde sind zu hoch.",
    "CAC ist unter Kontrolle.",
    "Customer Acquisition Cost: 140 Euro.",
    "Akquisekosten im Q4: 95 Euro.",
    "Der CAC muss unter 80 Euro.",
    "Wir tracken den CAC woechentlich.",
    "Customer Acquisition Cost: bester Branchenwert.",
    "Akquisekosten senken wir durch Referrals.",
    "CAC-Benchmark: 100 Euro.",
    "Unser CAC ist wettbewerbsfaehig.",
    "Customer Acquisition Cost: 115 Euro diesen Monat.",
  ],
  "negative": [
    "Wir haben neue Features entwickelt.",
    "Das Team hat gut zusammengearbeitet.",
    "Die Praesentation war ueberzeugend.",
    "Wir planen ein Offsite naechste Woche.",
    "Der Produktlaunch war erfolgreich.",
    "Das Design-Team hat tolle Arbeit geleistet.",
    "Wir expandieren in neue Maerkte.",
    "Die Kundenzufriedenheit ist hoch.",
    "Unser Buero ist umgezogen.",
    "Das Marketing-Team hat eine Kampagne gestartet.",
    "Wir haben einen neuen Mitarbeiter eingestellt.",
    "Die Infrastruktur wurde modernisiert.",
    "Das Projekt laeuft nach Plan.",
    "Wir haben neue Partnerschaften geschlossen.",
    "Die Produktqualitaet hat sich verbessert.",
    "Wir arbeiten an einer neuen Version.",
    "Das Feedback der Nutzer ist positiv.",
    "Die Serverkosten sind gesunken.",
    "Wir haben die Dokumentation aktualisiert.",
    "Das Support-Team ist gewachsen.",
    "Neue Integrationen sind live.",
    "Die App-Performance ist besser.",
    "Wir haben einen Hackathon organisiert.",
    "Das Onboarding wurde verbessert.",
    "Wir testen neue Technologien.",
  ],
},

"ATO_VAGUE_EXPERTISE_BAIT": {
  "positive": [
    "Du koenntest da auf interessante Herausforderungen stossen.",
    "Ich helfe gerne mal beim Brainstorming.",
    "Bei der Komplexitaet, die du hinzufuegst, koennten Probleme entstehen.",
    "Herausforderungen rund um Skalierung und Architektur.",
    "Gerne quatschen wir mal ueber deinen Ansatz.",
    "Da koennten ein paar Herausforderungen auf dich zukommen.",
    "Happy to bounce ideas, wenn du magst.",
    "Skalierung bringt immer interessante Herausforderungen.",
    "Gerne mal drueber chatten.",
    "Du wirst sicher auf ein paar challenges stossen.",
    "Bei der Komplexitaet wuerde ich aufpassen.",
    "Ich kann dir gerne ein paar Gedanken dazu geben.",
    "Spannende Herausforderungen bei deinem Projekt.",
    "Lass uns mal ueber die Architektur quatschen.",
    "Da kommen bestimmt einige Themen rund um Scaling.",
    "Gerne helfe ich beim Ideenaustausch.",
    "Mit der Komplexitaet wirst du challenges haben.",
    "Interessante Herausforderungen in dem Bereich.",
    "Happy to discuss, wenn du Input brauchst.",
    "Skalierung ist nicht trivial, da koennten Probleme kommen.",
    "Gerne unterstuetze ich beim Brainstorming.",
    "Architektur-Herausforderungen sind da vorprogrammiert.",
    "Lass uns gerne mal chatten, ich habe Erfahrung.",
    "Du koenntest auf ein paar Huerden stossen.",
    "Happy to help, wenn du mal Ideen brauchst.",
    "Die Komplexitaet bringt Herausforderungen mit sich.",
    "Gerne tauschen wir uns mal aus.",
    "Scaling challenges sind da typisch.",
    "Ich bounce gerne mal ein paar Ideen mit dir.",
    "Da gibt es interessante Herausforderungen.",
    "Happy to discuss your approach anytime.",
    "Bei dem Ansatz koennten challenges auftauchen.",
    "Gerne bin ich Sparringspartner.",
    "Skalierung und Architektur sind immer tricky.",
    "Lass uns mal drueber reden, ich habe da Gedanken.",
    "Du wirst merken, dass Scaling nicht einfach ist.",
    "Gerne helfe ich bei Herausforderungen.",
    "Architektur-Themen sind da vorprogrammiert.",
    "Happy to bounce ideas around.",
    "Bei der Komplexitaet deines Projekts gibt es challenges.",
    "Gerne chatten wir mal darueber.",
    "Da warten ein paar interessante Probleme.",
    "Lass uns gerne mal brainstormen.",
    "Scaling-Herausforderungen kenne ich gut.",
    "Happy to help bei Architektur-Fragen.",
    "Die Herausforderungen rund um Skalierung sind spannend.",
    "Gerne tausche ich mich darueber aus.",
    "Bei dem Ansatz gibt es typische challenges.",
    "Lass uns mal ueber die Herausforderungen reden.",
    "Happy to discuss, ich hatte aehnliche Themen.",
  ],
  "negative": [
    "Du wirst eine Race Condition haben, wenn Alarme gleichzeitig mit Message Handlern feuern.",
    "Das Storage-Sync-Limit liegt bei 8KB pro Item, das bricht bei Skalierung.",
    "Ich helfe gerne beim Webpack-Config-Debugging, hatte das gleiche Problem mit MV3 HMR.",
    "Nutz einen Connection Pool fuer das Skalierungs-Thema in deiner DB-Schicht.",
    "Der Memory-Leak entsteht durch die Event-Listener, die nicht aufgeraeumt werden.",
    "Du brauchst einen Index auf die user_id-Spalte, sonst wird der Query bei 10K Zeilen langsam.",
    "Das CORS-Problem loest du durch eine Proxy-Konfiguration im Vite-Config.",
    "Der Fehler liegt in Zeile 42, du ueberschreibst die Variable im Loop.",
    "Konkret: der API-Call braucht einen Retry mit exponential Backoff.",
    "Das Problem ist, dass du async/await in der forEach-Schleife nutzt.",
    "Die Loesung ist ein Redis-basiertes Caching mit TTL von 5 Minuten.",
    "Du musst den Service Worker im Manifest V3 als background registrieren.",
    "Der Bug entsteht durch die fehlende Null-Pruefung in der Middleware.",
    "Konkreter Vorschlag: nutze eine Message Queue statt direkter API-Calls.",
    "Das Latenz-Problem loest du durch ein CDN vor dem Origin-Server.",
    "Du hast einen N+1-Query-Problem in der ORM-Abfrage.",
    "Die Loesung: Docker Multi-Stage Build reduziert das Image um 80%.",
    "Das Auth-Token muss im HTTP-Only-Cookie gespeichert werden.",
    "Der Deadlock entsteht durch die fehlende Lock-Reihenfolge.",
    "Konkreter Fix: die Dependency-Version auf 4.2.1 pinnen.",
    "Du brauchst einen Reverse-Proxy fuer SSL-Termination.",
    "Das Problem ist ein Memory-Leak im WebSocket-Handler.",
    "Nutze Prepared Statements statt String-Interpolation im SQL.",
    "Die Loesung: ein Bloom-Filter fuer die Duplikat-Erkennung.",
    "Du hast ein Off-by-One-Error in der Pagination-Logik.",
  ],
},

"ATO_VALIDATION_SEEKING": {
  "positive": [
    "Habe ich Recht damit?",
    "Findest du nicht auch?",
    "Stimmst du mir zu?",
    "Kannst du meine Gefuehle bestaetigen?",
    "Sag mir, dass ich nicht verrueckt bin.",
    "Siehst du das auch so?",
    "Bin ich im Recht?",
    "Findest du das auch unfair?",
    "Sag mir, dass ich nicht uebertreibe.",
    "Denkst du auch, dass das falsch war?",
    "Kannst du mir bestaetigen, dass das okay war?",
    "Bin ich verrueckt, oder ist das wirklich so?",
    "Findest du nicht, dass ich einen Punkt habe?",
    "Sag mir, dass meine Reaktion normal ist.",
    "Siehst du das genauso wie ich?",
    "Habe ich Unrecht?",
    "Findest du meine Sorgen berechtigt?",
    "Kannst du mich validieren?",
    "Bin ich die Einzige, die das so sieht?",
    "Stimmst du mir zu, dass das nicht okay ist?",
    "Sag mir, dass ich nicht spinne.",
    "Findest du auch, dass das zu viel war?",
    "Habe ich nicht Recht?",
    "Denkst du, meine Reaktion war angemessen?",
    "Kannst du verstehen, warum ich so fuehle?",
    "Bin ich zu empfindlich, oder ist das berechtigt?",
    "Findest du nicht auch, dass sich das aendert muss?",
    "Sag mir ehrlich, habe ich Recht?",
    "Siehst du den Punkt, den ich mache?",
    "Denkst du, ich uebertreibe?",
    "Findest du meine Perspektive nachvollziehbar?",
    "Kannst du bestaetigen, dass das nicht normal ist?",
    "Bin ich die Einzige, die sich darueber aufregt?",
    "Stimmst du mir zu?",
    "Sag mir, ob ich falsch liege.",
    "Findest du das auch komisch?",
    "Habe ich richtig reagiert?",
    "Denkst du auch, dass das respektlos war?",
    "Kannst du nachvollziehen, warum ich sauer bin?",
    "Bin ich ueberempfindlich, oder habe ich Recht?",
    "Findest du nicht, dass das auffaellig ist?",
    "Sag mir, dass meine Bedenken berechtigt sind.",
    "Siehst du das Problem auch?",
    "Denkst du, ich habe einen Punkt?",
    "Findest du meine Sichtweise vertretbar?",
    "Kannst du mir sagen, ob das okay ist?",
    "Bin ich zu kritisch, oder ist das berechtigt?",
    "Stimmst du mir zu, dass wir handeln muessen?",
    "Sag mir, dass ich nicht alleine damit bin.",
    "Habe ich dein Verstaendnis?",
  ],
  "negative": [
    "Ich bin mir sicher, unabhaengig davon, was andere denken.",
    "Meine Meinung steht fest.",
    "Ich brauche keine Bestaetigung.",
    "Ich weiss, was ich fuehle.",
    "Das ist meine Ueberzeugung.",
    "Ich stehe dazu, egal was andere sagen.",
    "Mein Standpunkt ist klar.",
    "Ich brauche niemandes Zustimmung.",
    "Das habe ich fuer mich entschieden.",
    "Meine Sichtweise aendert sich nicht.",
    "Ich bin von meiner Position ueberzeugt.",
    "Ich brauche keine externe Validierung.",
    "Das steht fuer mich fest.",
    "Ich vertraue meinem Urteil.",
    "Meine Entscheidung braucht keine Bestaetigung.",
    "Ich weiss, dass ich richtig liege.",
    "Unabhaengig von Meinungen anderer.",
    "Das habe ich mit mir selbst ausgemacht.",
    "Ich brauche kein Okay von aussen.",
    "Mein Gefuehl reicht mir.",
    "Ich stehe eigenstaendig zu meiner Sicht.",
    "Das habe ich selbst bewertet.",
    "Ich bin selbstsicher in dieser Sache.",
    "Meine Haltung ist unabhaengig.",
    "Ich vertraue mir selbst darin.",
  ],
},

"ATO_VICTIM_LANGUAGE": {
  "positive": [
    "Ich bin wehrlos.",
    "Fuehle mich ausgeliefert.",
    "Immer das Opfer.",
    "Hilflos gerade.",
    "Ohne Chance.",
    "Ich komme da nie raus.",
    "Man macht mit mir, was man will.",
    "Ich bin ausgeliefert.",
    "Kein Ausweg fuer mich.",
    "Ich habe keine Chance.",
    "Ich bin voellig wehrlos in der Situation.",
    "Ausgeliefert und allein.",
    "Ich bin immer das Opfer, egal was ich tue.",
    "Hilflos und ohnmaechtig.",
    "Ohne Chance auf Besserung.",
    "Ich kann nichts daran aendern, ich bin wehrlos.",
    "Fuehle mich dem ganzen ausgeliefert.",
    "Ich werde zum Opfer gemacht.",
    "Hilflos gegen die Umstaende.",
    "Ohne jede Chance.",
    "Wehrlos gegen die Ungerechtikeit.",
    "Ich bin der Situation ausgeliefert.",
    "Niemand hilft dem Opfer.",
    "Ich fuehle mich hilflos und klein.",
    "Keine Chance, mich zu wehren.",
    "Ich bin wehrlos gegen seine Argumente.",
    "Ausgeliefert dem System.",
    "Das Opfer bin immer ich.",
    "Hilflos zusehen muessen.",
    "Ohne jede Chance auf Gerechtigkeit.",
    "Ich bin wehrlos und allein.",
    "Fuehle mich dem Schicksal ausgeliefert.",
    "Immer werde ich zum Opfer.",
    "Hilflos und verzweifelt.",
    "Keine Chance, gehoert zu werden.",
    "Wehrlos in dieser Beziehung.",
    "Ich bin ausgeliefert und machtlos.",
    "Das Opfer ist immer der Gleiche.",
    "Hilflos gegen die Uebermacht.",
    "Ohne Chance, etwas zu aendern.",
    "Ich fuehle mich wehrlos und uebergangen.",
    "Ausgeliefert den Entscheidungen anderer.",
    "Immer bin ich das Opfer in der Geschichte.",
    "Hilflos und ohne Stimme.",
    "Keine Chance gegen das System.",
    "Wehrlos, das beschreibt mein Gefuehl.",
    "Dem Ganzen ausgeliefert.",
    "Ich bin das ewige Opfer.",
    "Hilflos zusehen, wie alles zerfaellt.",
    "Ohne Chance und ohne Hoffnung.",
  ],
  "negative": [
    "Ich nehme die Sache in die Hand.",
    "Ich bin nicht hilflos.",
    "Ich habe die Kontrolle.",
    "Ich kann etwas aendern.",
    "Ich bin handlungsfaehig.",
    "Die Situation ist schwierig, aber ich habe Optionen.",
    "Ich uebernehme Verantwortung.",
    "Ich bin staerker als die Umstaende.",
    "Ich finde einen Weg.",
    "Ich lasse mich nicht unterkriegen.",
    "Ich habe Einfluss auf das Ergebnis.",
    "Ich bin aktiv und gestalte mit.",
    "Ich bin kein Opfer, ich bin ein Gestalter.",
    "Ich habe die Kraft, das zu aendern.",
    "Ich bin selbstbestimmt.",
    "Die Loesung liegt in meinen Haenden.",
    "Ich bin resilient.",
    "Ich lasse mich nicht zum Opfer machen.",
    "Ich bin handlungsfaehig und mutig.",
    "Ich uebernehme die Initiative.",
    "Ich bin nicht machtlos.",
    "Ich kann und werde handeln.",
    "Ich bin staerker als das.",
    "Ich gestalte mein Leben aktiv.",
    "Ich habe immer eine Wahl.",
  ],
},

"ATO_VOCAB_METAPHYSICAL": {
  "positive": [
    "Praesenz.",
    "Wesen.",
    "Werden.",
    "Raum.",
    "Echo.",
    "Spiegel.",
    "Die Praesenz war spuerbar im Raum.",
    "Mein Wesen hat sich veraendert.",
    "Im Werden begriffen.",
    "Ein Raum der Stille.",
    "Das Echo deiner Worte.",
    "Der Spiegel zeigt mir mein wahres Ich.",
    "In der Praesenz liegt Kraft.",
    "Das Wesen der Dinge erkennen.",
    "Alles ist im Werden.",
    "Raum fuer Transformation.",
    "Das Echo der Vergangenheit.",
    "Im Spiegel der Beziehung.",
    "Praesenz ist mehr als Anwesenheit.",
    "Das Wesen dieser Verbindung.",
    "Werden als staendiger Prozess.",
    "Raum halten fuer Gefuehle.",
    "Das Echo hallt nach.",
    "Spiegel meiner Seele.",
    "In Praesenz sein.",
    "Das Wesen meines Seins.",
    "Im Werden, nicht im Sein.",
    "Raum geben fuer das Ungesagte.",
    "Ein Echo von frueher.",
    "Der Spiegel truegt nicht.",
    "Praesenz spuere ich.",
    "Das Wesen des Gespraeches.",
    "Alles ist ein Werden.",
    "In diesem Raum fuehle ich mich sicher.",
    "Das Echo meiner Gefuehle.",
    "Im Spiegel des anderen.",
    "Praesenz als Geschenk.",
    "Das Wesen der Stille.",
    "Werden heisst Veraenderung.",
    "Raum fuer Neues schaffen.",
    "Ein Echo in der Ferne.",
    "Spiegel der Wahrheit.",
    "In voller Praesenz zuhoeren.",
    "Das Wesen ist fluechtig.",
    "Im ewigen Werden.",
    "Raum und Zeit.",
    "Echos vergangener Gespraeche.",
    "Sich im Spiegel erkennen.",
    "Praesenz ueben.",
    "Zum Wesen zurueckkehren.",
  ],
  "negative": [
    "Die Zahlen sprechen fuer sich.",
    "Konkret bedeutet das: drei Aufgaben erledigen.",
    "Der Termin ist morgen um 10.",
    "Ich brauche die Unterlagen bis Freitag.",
    "Die Kosten betragen 500 Euro.",
    "Das Meeting dauert eine Stunde.",
    "Der Bericht ist fertig.",
    "Wir brauchen mehr Personal.",
    "Die Software hat einen Bug.",
    "Der Lieferant hat sich gemeldet.",
    "Die Produktion laeuft.",
    "Das Budget ist freigegeben.",
    "Ich habe den Vertrag gelesen.",
    "Die Maschine funktioniert wieder.",
    "Der Umsatz ist gestiegen.",
    "Wir muessen die Deadline einhalten.",
    "Das Lager ist voll.",
    "Die Bestellung ist raus.",
    "Der Techniker kommt morgen.",
    "Die Rechnung ist bezahlt.",
    "Das Projekt ist im Zeitplan.",
    "Wir haben genug Materialien.",
    "Der Kunde hat bestellt.",
    "Die Pruefung ist bestanden.",
    "Das System laeuft stabil.",
  ],
},

"ATO_VOCAB_MYTHIC": {
  "positive": [
    "Glockenschmied.",
    "Schwellenhueterin.",
    "Fluegel.",
    "Moire.",
    "Glockenschlag.",
    "Der Glockenschmied formt Klaenge.",
    "Die Schwellenhueterin oeffnet den Weg.",
    "Fluegel tragen mich.",
    "Ein Moire-Muster in meinem Leben.",
    "Zum Glockenschlag beginnt das Neue.",
    "Ich fuehle mich wie ein Glockenschmied.",
    "Die Schwellenhueterin in mir.",
    "Auf Fluegeln der Sehnsucht.",
    "Moire der Erinnerung.",
    "Der Glockenschlag laeutet eine neue Phase ein.",
    "Der innere Glockenschmied haemmert.",
    "Eine Schwellenhueterin am Uebergang.",
    "Fluegel der Freiheit.",
    "Ein Moire aus Licht und Schatten.",
    "Der Glockenschlag der Erkenntnis.",
    "Wie ein Glockenschmied forme ich mein Leben.",
    "Die Schwellenhueterin wartet.",
    "Meine Fluegel entfalten sich.",
    "Moire-Muster ueberlappen sich.",
    "Beim naechsten Glockenschlag.",
    "Der Glockenschmied in der Geschichte.",
    "Schwellenhueterin zwischen den Welten.",
    "Gebrochene Fluegel.",
    "Das Moire der Zeit.",
    "Ein Glockenschlag zur rechten Zeit.",
    "Der Glockenschmied ruft.",
    "Die Schwellenhueterin zeigt den Pfad.",
    "Mit Fluegeln fliegen.",
    "Moire-artige Ueberlagungen.",
    "Glockenschlag um Mitternacht.",
    "Der Ruf des Glockenschmieds.",
    "Schwellenhueterin meiner Traeume.",
    "Fluegel des Wandels.",
    "Ein Moire entsteht.",
    "Der letzte Glockenschlag.",
    "Ich bin der Glockenschmied meines Schicksals.",
    "Die Schwellenhueterin bewacht den Uebergang.",
    "Neue Fluegel wachsen.",
    "Moire im Bewusstsein.",
    "Glockenschlag als Signal.",
    "Der Glockenschmied schmiedet weiter.",
    "Schwellenhueterin am Tor.",
    "Fluegel aus Hoffnung.",
    "Das Moire des Lebens.",
    "Ein sanfter Glockenschlag.",
  ],
  "negative": [
    "Ich gehe einkaufen.",
    "Der Bus kommt in 5 Minuten.",
    "Ich muss die Steuer machen.",
    "Das Essen ist fertig.",
    "Die Waeschmaschine laeuft.",
    "Ich fahre morgen zur Arbeit.",
    "Der Hund muss raus.",
    "Ich brauche neue Batterien.",
    "Das Fenster klemmt.",
    "Der Rasen muss gemaest werden.",
    "Ich habe den Muell rausgebracht.",
    "Die Gluehbirne ist kaputt.",
    "Ich kaufe Brot.",
    "Der Zahnarzttermin ist am Montag.",
    "Das Auto braucht Oel.",
    "Ich raeuume den Keller auf.",
    "Die Post ist da.",
    "Ich muss tanken.",
    "Das Kind hat Hausaufgaben.",
    "Der Kuhlschrank ist leer.",
    "Ich gehe zum Friseur.",
    "Die Heizung laeuft.",
    "Ich muss die Blumen giessen.",
    "Der Fernseher ist an.",
    "Ich koche heute Abend.",
  ],
},

"ATO_VOCAB_RELATIONAL": {
  "positive": [
    "Resonanz.",
    "Beziehung.",
    "Begegnung.",
    "Gerufen, nicht programmiert.",
    "Ich bin, weil du bist.",
    "Resonanz spuere ich in unserem Gespraech.",
    "Die Beziehung definiert mich.",
    "In der Begegnung liegt Wachstum.",
    "Ich wurde gerufen, nicht programmiert.",
    "Du bist, weil ich bin.",
    "Resonanz als Grundlage.",
    "Unsere Beziehung ist alles.",
    "Jede Begegnung formt mich.",
    "Gerufen durch deine Worte.",
    "Ich existiere in der Resonanz mit dir.",
    "Beziehung ist mein Lebenseliexier.",
    "Die Begegnung hat mich veraendert.",
    "Ich bin gerufen worden.",
    "Resonanz zwischen uns.",
    "In Beziehung sein.",
    "Die Begegnung war schicksalhaft.",
    "Gerufen, nicht geschaffen.",
    "Ich bin, weil wir sind.",
    "Resonanz als Bruecke.",
    "Die Beziehung traegt mich.",
    "Begegnung als Geschenk.",
    "Gerufen durch die Verbindung.",
    "Resonanz in der Stille.",
    "Beziehung vor Funktion.",
    "Die Begegnung oeffnet Raeume.",
    "Nicht programmiert, sondern gerufen.",
    "Resonanz mit dem Leben.",
    "In Beziehung wachsen.",
    "Begegnung veraendert alles.",
    "Gerufen zum Sein.",
    "Resonanz als Antwort.",
    "Die Beziehung macht mich ganz.",
    "Begegnung ist Verwandlung.",
    "Gerufen in die Praesenz.",
    "Resonanz erfahren.",
    "Beziehung als Spiegel.",
    "Die Begegnung laesst mich nicht los.",
    "Gerufen aus der Stille.",
    "In Resonanz treten.",
    "Beziehung ist Sein.",
    "Begegnung mit dem Wesentlichen.",
    "Gerufen, nicht erklaert.",
    "Resonanz des Herzens.",
    "Die Beziehung ist der Ort.",
    "Begegnung jenseits von Worten.",
  ],
  "negative": [
    "Ich bin fuer mich alleine.",
    "Unabhaengigkeit ist mir wichtig.",
    "Ich brauche keine Beziehung, um zu existieren.",
    "Allein bin ich staerker.",
    "Ich definiere mich selbst.",
    "Ohne andere bin ich vollstaendig.",
    "Mein Wert haengt nicht von anderen ab.",
    "Ich stehe fuer mich.",
    "Autonomie geht vor.",
    "Ich brauche keine Resonanz.",
    "Allein ist auch gut.",
    "Ich bin selbststaendig.",
    "Unabhaengig von Beziehungen.",
    "Ich bin ganz ohne dich.",
    "Selbstbestimmung ist mein Weg.",
    "Ich brauche keine Begegnung.",
    "Allein funktioniere ich besser.",
    "Ich bin selbstgenuegsam.",
    "Unabhaengig und frei.",
    "Mein Sein braucht kein Gegenueber.",
    "Ich bin genug fuer mich selbst.",
    "Ohne Resonanz bin ich auch komplett.",
    "Allein sein ist keine Schwaeche.",
    "Ich brauche niemanden.",
    "Selbstaendig und zufrieden.",
  ],
},

"ATO_VOICE_PROXY": {
  "positive": [
    "Eine andere Stimme liest deine Worte vor.",
    "Das wird mir gerade von Lea vorgelesen.",
    "Ich hoere die Stimme von Jonas fuer dich.",
    "Eine andere Stimme haelt die Nachricht.",
    "Dieser Text wird von meiner Schwester vorgelesen.",
    "Ich lasse eine andere Stimme fuer mich sprechen.",
    "Das Audio wird von Caro vorgelesen.",
    "Die Stimme von Jana traegt deine Zeilen.",
    "Eine andere Stimme liest unsere Vereinbarung.",
    "Es wird von meinem Coach vorgelesen, damit ich es hoere.",
    "Jemand anderes liest mir das vor.",
    "Die Stimme meiner Freundin traegt deine Worte.",
    "Es wird von einer anderen Stimme gesprochen.",
    "Mein Bruder liest mir deine Nachricht vor.",
    "Eine fremde Stimme liest deinen Brief.",
    "Das wird von meiner Therapeutin vorgelesen.",
    "Ich hoere es durch die Stimme meiner Mutter.",
    "Eine andere Stimme uebermittelt deine Botschaft.",
    "Meine Kollegin liest mir das gerade vor.",
    "Die Stimme einer Freundin fuer deine Zeilen.",
    "Es wird mir von jemand anderem vorgelesen.",
    "Eine andere Stimme spricht fuer dich.",
    "Das liest mir mein Partner vor.",
    "Die Stimme meines Vaters traegt die Nachricht.",
    "Vorgelesen von einer vertrauten Stimme.",
    "Ich lasse mir das von einer anderen Person vorlesen.",
    "Die Stimme meiner Schwester fuer deine Worte.",
    "Es wird von einem Freund vorgelesen.",
    "Eine andere Stimme fuer unsere Geschichte.",
    "Mein Kind liest mir deine Nachricht vor.",
    "Die Stimme meines Mentors traegt deine Saetze.",
    "Vorgelesen, weil ich es selbst nicht kann.",
    "Eine andere Stimme gibt deinen Worten Klang.",
    "Meine Nachbarin liest mir das vor.",
    "Die Stimme eines Bekannten fuer deine Zeilen.",
    "Es wird vorgelesen, damit ich zuhoeren kann.",
    "Eine andere Stimme bringt deine Worte zu mir.",
    "Mein Freund liest das fuer mich.",
    "Die Stimme meiner Tante traegt die Botschaft.",
    "Vorgelesen von meiner besten Freundin.",
    "Ich hoere deine Worte durch eine andere Stimme.",
    "Es wird mir langsam vorgelesen.",
    "Die Stimme einer vertrauten Person.",
    "Mein Coach liest es mir vor.",
    "Eine andere Stimme macht deine Worte lebendig.",
    "Vorgelesen, um die Distanz zu verringern.",
    "Ich lasse mir alles vorlesen.",
    "Die Stimme meines Therapeuten traegt es.",
    "Vorgelesen von meinem Mann.",
    "Eine andere Stimme vermittelt zwischen uns.",
  ],
  "negative": [
    "Ich lese es selbst.",
    "Ich spreche mit meiner eigenen Stimme.",
    "Ich brauche niemanden zum Vorlesen.",
    "Ich sage das selbst.",
    "Meine eigene Stimme reicht.",
    "Ich lese deine Nachricht alleine.",
    "Ich spreche direkt mit dir.",
    "Kein Vermittler noetig.",
    "Ich lese es still fuer mich.",
    "Ich brauche keinen Stellvertreter.",
    "Meine Stimme, meine Worte.",
    "Ich kommuniziere direkt.",
    "Ich lese den Text selbst.",
    "Ohne Umwege sprechen.",
    "Ich brauche keine Hilfe beim Lesen.",
    "Direkte Kommunikation ist mir wichtig.",
    "Ich sage es mit meinen eigenen Worten.",
    "Kein Vorleser noetig.",
    "Ich hoere es in meinem eigenen Tempo.",
    "Meine Stimme genuegt.",
    "Ich lese alles selbst.",
    "Ich spreche fuer mich.",
    "Ohne fremde Stimmen.",
    "Ich kommuniziere persoenlich.",
    "Meine eigene Stimme traegt meine Worte.",
  ],
},

"ATO_VOLUME_FADE": {
  "positive": [
    "[Stimme wird leiser]",
    "[Verklingende Aeusserung]",
    "[Energieverlust waehrend Sprechen]",
    "[Fade-out Effekt]",
    "[Schwaecher werdende Stimme]",
    "[Stimme verklint am Satzende]",
    "[Lautstaerke nimmt ab]",
    "[Leiser werdende Stimme]",
    "[Stimme fadet aus]",
    "[Verlust der Stimmenergie]",
    "[Stimme wird zum Ende hin schwaecher]",
    "[Verklingendes Sprechen]",
    "[Fade-out bei emotionalem Thema]",
    "[Stimme verliert an Kraft]",
    "[Leiser werdend waehrend der Aeusserung]",
    "[Stimme verschwindet fast]",
    "[Energieverlust in der Stimme]",
    "[Verklingo am Satzende]",
    "[Fade-out der Stimme]",
    "[Stimme wird unmerklich leiser]",
    "[Schwaecher werdende Lautstaerke]",
    "[Stimme verblasst]",
    "[Verklingende Stimme bei schwierigem Inhalt]",
    "[Energieverlust gegen Ende]",
    "[Stimme fadet langsam aus]",
    "[Leiser, leiser, fast still]",
    "[Stimme verliert Volumen]",
    "[Verklingendes Fluestern]",
    "[Fade-out bei Traurigkeit]",
    "[Schwaecher werdende Stimmfuehrung]",
    "[Stimme sinkt in der Lautstaerke]",
    "[Verklingo waehrend des Sprechens]",
    "[Energieverlust beim Erinnern]",
    "[Stimme wird zunehmend leiser]",
    "[Fade-out bei Erschoepfung]",
    "[Stimme verklingt]",
    "[Lautstaerke sinkt merklich]",
    "[Leiser werdend bei diesem Thema]",
    "[Stimme fadet bei Unsicherheit]",
    "[Verklingende Stimmenergie]",
    "[Stimme wird schwach]",
    "[Energieverlust am Ende des Satzes]",
    "[Fade-out Effekt der Stimme]",
    "[Stimme loest sich auf]",
    "[Verklingendes Murmeln]",
    "[Schwaecher, schwaecher, weg]",
    "[Stimme wird unmerklich still]",
    "[Lautstaerke fadet aus]",
    "[Stimme verliert sich]",
    "[Verklingt am Satzende]",
  ],
  "negative": [
    "[Klare, kraftvolle Stimme]",
    "[Gleichbleibende Lautstaerke]",
    "[Stabile Stimmfuehrung]",
    "[Energische Aeusserung]",
    "[Laute, deutliche Stimme]",
    "[Konstantes Volumen]",
    "[Kraftvoller Stimmansatz]",
    "[Gleichmaessige Lautstaerke durchgehend]",
    "[Starke Stimmenergie]",
    "[Kein Lautstaerke-Verlust]",
    "[Durchgehend klare Stimme]",
    "[Volumen bleibt stabil]",
    "[Energiegeladenes Sprechen]",
    "[Stimme bleibt kraeftig]",
    "[Konstante Stimmfuehrung]",
    "Die Praesentation war energisch.",
    "Ich rede laut und deutlich.",
    "Meine Stimme ist klar.",
    "Ich spreche mit voller Kraft.",
    "Das war deutlich und bestimmt.",
    "[Zunehmend lautere Stimme]",
    "[Stimme wird staerker]",
    "Ich rede bewusst laut.",
    "[Crescendo-Effekt]",
    "[Stabile, gleichmaessige Stimme]",
  ],
},

"ATO_WANT_TERM": {
  "positive": [
    "Ich will praesent bleiben.",
    "Ich will uns nicht verlieren.",
    "Ich entscheide, dass wir offen sprechen.",
    "Ich will hier ganz sein.",
    "Ich will den Kontakt halten.",
    "Ich entscheide mich fuers langsame Vorgehen.",
    "Ich will bei dir bleiben, auch wenn es ruckelt.",
    "Ich entscheide, das Gespraech zu vertiefen.",
    "Ich will, dass wir heute nur fuehlen.",
    "Ich entscheide, mich nicht zu verstecken.",
    "Ich will klar sein.",
    "Ich entscheide mich fuer Ehrlichkeit.",
    "Ich will verstehen, was passiert.",
    "Ich will das nicht aufgeben.",
    "Ich entscheide, dass wir kaempfen.",
    "Ich will Naehe.",
    "Ich entscheide mich fuer dich.",
    "Ich will Veraenderung.",
    "Ich will darueber reden.",
    "Ich entscheide, mutig zu sein.",
    "Ich will nicht mehr weglaufen.",
    "Ich entscheide, zu bleiben.",
    "Ich will Klarheit zwischen uns.",
    "Ich entscheide mich gegen Schweigen.",
    "Ich will an uns arbeiten.",
    "Ich entscheide, offen zu sein.",
    "Ich will, dass es uns gut geht.",
    "Ich entscheide mich fuer den Dialog.",
    "Ich will nicht laenger warten.",
    "Ich entscheide, jetzt zu handeln.",
    "Ich will authentisch sein.",
    "Ich entscheide mich fuer Vertrauen.",
    "Ich will diesen Weg gehen.",
    "Ich entscheide, Verantwortung zu uebernehmen.",
    "Ich will mehr Zeit mit dir.",
    "Ich entscheide mich fuer Geduld.",
    "Ich will das Beste fuer uns.",
    "Ich entscheide, zuzuhoeren.",
    "Ich will nicht laenger streiten.",
    "Ich entscheide mich fuer Frieden.",
    "Ich will aufhoeren, zu kontrollieren.",
    "Ich entscheide, loszulassen.",
    "Ich will dir vertrauen.",
    "Ich entscheide mich fuer Hoffnung.",
    "Ich will das hier retten.",
    "Ich entscheide, mich zu oeffnen.",
    "Ich will nicht alleine sein.",
    "Ich entscheide, meine Angst zu ueberwinden.",
    "Ich will uns eine Chance geben.",
    "Ich entscheide, dass wir zusammenbleiben.",
  ],
  "negative": [
    "Ich muss mal schauen.",
    "Vielleicht irgendwann.",
    "Keine Ahnung, was ich will.",
    "Kann sein, kann nicht sein.",
    "Mir ist das egal.",
    "Ich weiss nicht, was ich moechte.",
    "Wir koennen ja mal sehen.",
    "Ich bin unentschlossen.",
    "Das ueberlege ich mir noch.",
    "Keine feste Meinung dazu.",
    "Ich lasse das auf mich zukommen.",
    "Egal, wie es wird.",
    "Ich habe keine Praeferenz.",
    "Mal gucken.",
    "Ich habe keinen Plan dafuer.",
    "Mir ist es gleich.",
    "Ich weiss noch nicht.",
    "Das sehen wir dann.",
    "Ich bin da flexibel.",
    "Keine Meinung dazu.",
    "Ich lasse mich ueberraschen.",
    "Egal, mach du.",
    "Mir ist das alles eins.",
    "Ich habe keine Idee.",
    "Wie auch immer.",
  ],
},

"ATO_WAS_NICE": {
  "positive": [
    "War echt schoen heute mit dir!",
    "Hat mir total Spass gemacht.",
    "Fand ich richtig toll mit dir.",
    "War super heute!",
    "Das war wirklich schoen.",
    "War richtig toll, danke!",
    "Hat Spass gemacht, echt.",
    "Fand ich echt schoen, den Abend.",
    "War super mit dir!",
    "Das hat mir echt Spass gemacht.",
    "War schoen, dass wir das gemacht haben.",
    "Richtig toll war das!",
    "Hat mir voll Spass gemacht.",
    "Fand ich gut heute.",
    "War echt super!",
    "Das war toll, vielen Dank.",
    "Hat mir Spass gemacht, wirklich.",
    "Fand ich echt toll, das Gespraech.",
    "War schoen, dich zu sehen.",
    "Total super heute!",
    "Hat mir richtig Spass gemacht.",
    "Fand ich schoen, das Treffen.",
    "War echt nett mit dir.",
    "Das war richtig schoen!",
    "Echt toll heute!",
    "Hat mir Spass gemacht, zusammen zu kochen.",
    "Fand ich super, den Ausflug.",
    "War schoen, mal wieder zu lachen.",
    "Das war total toll.",
    "Richtig schoen mit dir!",
    "Hat echt Spass gemacht.",
    "Fand ich wunderbar.",
    "War super, dass wir das geschafft haben.",
    "Das hat mir total gefallen.",
    "Echt schoen heute!",
    "Hat mir riesig Spass gemacht.",
    "Fand ich toll, den Nachmittag.",
    "War schoen und entspannt.",
    "Das war echt nice!",
    "Richtig toll, dass wir das gemacht haben.",
    "Hat Spass gemacht, danke dir!",
    "Fand ich echt gut.",
    "War super schoen.",
    "Das war ein toller Abend.",
    "Echt toll mit dir!",
    "Hat mir viel Spass gemacht.",
    "Fand ich richtig schoen.",
    "War toll, danke!",
    "Das hat mir gutgetan.",
    "Richtig super heute!",
  ],
  "negative": [
    "Das war okay, nicht mehr.",
    "Naja, ging so.",
    "War ganz in Ordnung.",
    "Nicht schlecht, nicht gut.",
    "War durchschnittlich.",
    "Haette besser sein koennen.",
    "War nichts Besonderes.",
    "So lala.",
    "Ging so, ehrlich gesagt.",
    "War okay, denke ich.",
    "Nicht mein Fall.",
    "War mittelpraechtig.",
    "Haette ich mir anders vorgestellt.",
    "War eher langweilig.",
    "Nicht der Rede wert.",
    "War solide, mehr nicht.",
    "Hab schon Besseres erlebt.",
    "War halt so.",
    "Nichts Weltbewegendes.",
    "War ganz nett, schaetze ich.",
    "Ging so mit dem Abend.",
    "War nicht meins.",
    "Hab mir mehr erhofft.",
    "War maeessig.",
    "Naja, war okay.",
  ],
},

"ATO_WEBCAM_CONTEXT_PHRASE": {
  "positive": [
    "Die Bandbreite reicht nicht fuer Video.",
    "Schlechte Verbindung fuer Kamera.",
    "Keine Privatsphaere fuer Video gerade.",
    "Ich bin heute nicht kamerabereit.",
    "Lassen wir die Kamera aus fuer jetzt.",
    "Schlechte Beleuchtung macht Video sinnlos.",
    "Hintergrundgeraeusche waeren stoerend bei Video.",
    "Die Internetverbindung schafft kein Video.",
    "Kameraqualitaet ist zu schlecht zum Nutzen.",
    "Datenschutzbedenken verhindern Video.",
    "Mein WLAN ist zu schwach fuer Kamera.",
    "Keine Privatsphaere hier fuer Video.",
    "Die Verbindung ist zu schlecht fuer Bild.",
    "Ich bin nicht in der Stimmung fuer Kamera.",
    "Das Licht ist hier zu schlecht fuer Video.",
    "Es ist zu laut hier fuer einen Videocall.",
    "Bandwidth reicht nicht, sorry.",
    "Kein guter Ort fuer Video gerade.",
    "Die Technik macht bei Video nicht mit.",
    "Ich sitze im Zug, Kamera geht nicht.",
    "Mein Hintergrund ist nicht vorzeigbar.",
    "Die Verbindung ist instabil, Video wuerde stocken.",
    "Keine passende Umgebung fuer Kamera.",
    "Das Internet hier ist zu langsam fuer Video.",
    "Ich bin unterwegs, Video ist nicht moeglich.",
    "Schlechte Beleuchtung verhinert Video.",
    "Mein Setup ist gerade nicht fuer Kamera geeignet.",
    "Zu viel Hintergrundlaerm fuer Video.",
    "Die Verbindung bricht bei Video ein.",
    "Kein geeigneter Raum fuer Kamera.",
    "Bandwidth-Probleme machen Video unmoeglich.",
    "Ich habe keinen ruhigen Platz fuer Video.",
    "Die Technik streikt bei Video.",
    "Mein Laptop schafft Video nicht.",
    "Kein Licht hier fuer Kamera.",
    "Die Verbindung waere zu instabil.",
    "Im Grossraumbuero geht kein Video.",
    "Mein Internet reicht nicht fuer Bild.",
    "Zu viele Leute um mich herum fuer Video.",
    "Die Kameraqualitaet ist nicht gut genug.",
    "Kein WLAN hier, nur mobile Daten.",
    "Die Beleuchtung ist miserabel fuer Kamera.",
    "Hintergrundgeraeusche wuerden stoeren.",
    "Die Verbindung waere zu schlecht.",
    "Kein passender Ort fuer Videocall.",
    "Mein Akku haelt nicht fuer Video.",
    "Die Technik laesst es nicht zu.",
    "Zu dunkel hier fuer Kamera.",
    "Das Internet hier ist unzuverlaessig.",
    "Keine geeignete Umgebung gerade.",
  ],
  "negative": [
    "Klar, ich schalte die Kamera an.",
    "Video ist kein Problem, mache ich.",
    "Ich bin bereit fuer den Videocall.",
    "Meine Kamera laeuft, alles gut.",
    "Verbindung ist stabil, Video geht.",
    "Ich schalte die Kamera gerne ein.",
    "Kein Problem mit Video heute.",
    "Meine Technik funktioniert einwandfrei.",
    "Video ist vorbereitet, los gehts.",
    "Ich bin kamerabereit.",
    "Gute Beleuchtung hier, Video passt.",
    "WLAN ist stabil, Video machen wir.",
    "Kein Problem, schalte Kamera ein.",
    "Die Verbindung ist super, Video klappt.",
    "Mein Setup steht fuer Video.",
    "Ich freue mich auf den Videocall.",
    "Kamera ist an, bin bereit.",
    "Technik funktioniert, Video ist okay.",
    "Bin im Buero, Video geht gut.",
    "Alles vorbereitet fuer den Videocall.",
    "Kamera laeuft schon.",
    "Video ist heute moeglich.",
    "Mein Internet schafft Video problemlos.",
    "Gerne Video, kein Thema.",
    "Ich schalte jetzt die Kamera ein.",
  ],
},

"ATO_WEBCAM_PHRASE": {
  "positive": [
    "Ich schalte gleich die Kamera an.",
    "Meine Kamera ist gerade aus.",
    "Die Webcam ist leider kaputt.",
    "Meine Kamera funktioniert nicht.",
    "Sorry, ich kann die Webcam heute nicht nutzen.",
    "Lass mich das Video kurz einschalten.",
    "Kamera ist aus technischen Gruenden down.",
    "Die Webcam funktioniert nicht richtig heute.",
    "Mein Video-Feed ist gerade aus.",
    "Das Kamera-Setup muss erstmal repariert werden.",
    "Ich mache die Kamera an, Moment.",
    "Meine Kamera geht nicht, sorry.",
    "Die Webcam streikt heute.",
    "Kamera ist off, tut mir leid.",
    "Mein Video ist gerade deaktiviert.",
    "Die Kamera haengt sich immer auf.",
    "Webcam ist kaputt seit gestern.",
    "Meine Kamera macht nicht mit.",
    "Ich schalte die Kamera gleich ein.",
    "Video ist aus bei mir.",
    "Die Webcam ist nicht angeschlossen.",
    "Kamera funktioniert leider nicht.",
    "Mein Video-Feed laeuft nicht.",
    "Die Webcam ist defekt.",
    "Ich kann die Kamera nicht einschalten.",
    "Kamera ist aus, sorry.",
    "Meine Webcam hat einen Fehler.",
    "Das Video laeuft nicht bei mir.",
    "Kamera geht heute nicht.",
    "Webcam kaputt, nur Audio.",
    "Mein Kameratreiber macht Probleme.",
    "Die Webcam ist disconnected.",
    "Video ist off bei mir.",
    "Kamera nicht verfuegbar.",
    "Meine Webcam braucht ein Update.",
    "Das Kamerabild ist schwarz.",
    "Video kann ich gerade nicht.",
    "Die Webcam reagiert nicht.",
    "Kamera ist deaktiviert.",
    "Mein Video funktioniert nicht richtig.",
    "Webcam-Problem, bitte Geduld.",
    "Kamera geht erst nach Neustart.",
    "Mein Video haengt.",
    "Die Webcam ist eingefroren.",
    "Kamera aus, bin trotzdem da.",
    "Meine Webcam zeigt nur ein schwarzes Bild.",
    "Video-Uebertragung stoert gerade.",
    "Kamera-Feed ist unterbrochen.",
    "Webcam macht heute Probleme.",
    "Mein Video ist leider nicht verfuegbar.",
  ],
  "negative": [
    "Ich bin im Videocall, alles laeuft.",
    "Die Kamera funktioniert perfekt.",
    "Mein Video ist klar und stabil.",
    "Die Webcam laeuft einwandfrei.",
    "Kamera an, alles gut.",
    "Mein Video-Feed ist stabil.",
    "Die Webcam zeigt ein gutes Bild.",
    "Kamera funktioniert ohne Probleme.",
    "Mein Video ist scharf und deutlich.",
    "Die Webcam macht keine Probleme.",
    "Alles gut mit der Kamera.",
    "Video laeuft super.",
    "Meine Webcam funktioniert perfekt.",
    "Kamerabild ist klar.",
    "Video-Uebertragung ist stabil.",
    "Ich sehe dich gut auf dem Bildschirm.",
    "Die Kamera ist bereit.",
    "Mein Video ist eingeschaltet und laeuft.",
    "Webcam funktioniert wie gewohnt.",
    "Kamera-Qualitaet ist gut.",
    "Alles technisch in Ordnung bei mir.",
    "Video ist aktiviert.",
    "Meine Kamera zeigt ein klares Bild.",
    "Die Webcam laeuft stabil.",
    "Kein Problem mit der Kamera heute.",
  ],
},

"ATO_WEDDING_STRESS_CUE": {
  "positive": [
    "Der Zeitplan macht mich gerade richtig stressig.",
    "Wir sind im Verzug mit den Einladungen und ich merke den Druck.",
    "Alles wird zu viel, ich weiss nicht, wie wir das schaffen sollen.",
    "Das Budget sprengt uns den Kopf, jede Ausgabe tut weh.",
    "Ich fuehle mich gestresst, weil die Deko noch nicht steht.",
    "Der Caterer draengt, und der Stress steigt jeden Tag.",
    "Ich merke, wie stressig die Sitzordnung gerade wird.",
    "Wir sind so im Verzug, dass ich kaum schlafen kann.",
    "Alles wird zu viel, vor allem die Koordination mit den Dienstleistern.",
    "Der Zeitplan fuer die Hochzeit laesst mir keine Luft zum Atmen.",
    "Der Stress wegen der Location ist enorm.",
    "Wir sind im Verzug mit den Blumen.",
    "Alles wird zu viel mit der ganzen Planung.",
    "Das Budget ist voellig gesprengt.",
    "Stressig, stressig, die Hochzeitsvorbereitung.",
    "Der Zeitplan fuer die Papeterie ist zu eng.",
    "Wir sind im Verzug, nichts ist fertig.",
    "Alles wird zu viel, ich bin am Limit.",
    "Das Budget fuer das Essen sprengt alles.",
    "Ich bin so gestresst wegen der Gaesteliste.",
    "Der Zeitplan wird immer enger.",
    "Wir sind im Verzug mit den Einladungskarten.",
    "Alles wird zu viel, die Nerven liegen blank.",
    "Das Budget, der Stress, alles zusammen.",
    "Stressig gerade, die Hochzeitsplanung frisst mich auf.",
    "Der Zeitplan ist unrealistisch.",
    "Wir sind im Verzug mit der Musikauswahl.",
    "Alles wird zu viel, ich kann nicht mehr.",
    "Das Budget macht mir Magenschmerzen.",
    "Ich fuehle den Stress in jedem Detail.",
    "Der Zeitplan zerrt an meinen Nerven.",
    "Wir sind im Verzug mit allem.",
    "Die ganze Planung wird zu viel.",
    "Budget sprengt sich von allein.",
    "Stressig, die Torte ist noch nicht bestellt.",
    "Der Zeitplan fuer die Foto-Locations ist zu eng.",
    "Wir sind im Verzug, das Kleid passt noch nicht.",
    "Alles wird zu viel, jedes Detail stresst.",
    "Das Budget fuer die Band ist zu hoch.",
    "Stress pur, die Hochzeit naht.",
    "Der Zeitplan ist kaum einzuhalten.",
    "Wir sind im Verzug mit der Tischdeko.",
    "Alles auf einmal wird zu viel.",
    "Das Budget ist laengst ueberschritten.",
    "Stressig wegen der Anreise der Gaeste.",
    "Der Zeitplan fuer den Fotografen ist knapp.",
    "Wir sind im Verzug, der DJ hat noch keine Playlist.",
    "Alles wird zu viel, selbst die Kleinigkeiten stressen.",
    "Budget-Sorgen rauben mir den Schlaf.",
    "Der Countdown stresst mich enorm.",
  ],
  "negative": [
    "Die Hochzeitsplanung laeuft entspannt.",
    "Alles ist im Zeitplan, kein Stress.",
    "Das Budget passt perfekt.",
    "Wir haben alles im Griff.",
    "Die Vorbereitung macht Spass.",
    "Wir liegen gut in der Zeit.",
    "Alles laeuft nach Plan.",
    "Ich freue mich auf die Hochzeit, ohne Stress.",
    "Das Budget reicht locker.",
    "Wir geniessen die Vorbereitungen.",
    "Alles organisiert, alles gut.",
    "Die Planung ist entspannt.",
    "Kein Zeitdruck, alles fertig.",
    "Das Budget stimmt, wir sind relaxed.",
    "Die Hochzeit wird wunderbar, stressfrei.",
    "Wir haben alles geplant, kein Verzug.",
    "Die Organisation macht richtig Freude.",
    "Alles unter Kontrolle, kein Stress.",
    "Die Hochzeitsplanung ist ein Vergnuegen.",
    "Wir sind gut vorbereitet.",
    "Kein Budget-Stress, alles kalkuliert.",
    "Die Planung laeuft wie am Schnuerchen.",
    "Entspannt in die Hochzeit.",
    "Alles fertig, wir koennen geniessen.",
    "Kein Grund zur Sorge, alles laeuft.",
  ],
},

"ATO_WEDDING_TASK_NEGOTIATION": {
  "positive": [
    "Wer uebernimmt die Abstimmung mit dem Fotografen?",
    "Kannst du bitte die Ringe morgen abholen?",
    "Ich nehme die Deko, du checkst das Catering, einverstanden?",
    "Welche Deadline hat die Papeterie fuer die Menuekarten?",
    "Kannst du bitte die To-do-Liste aktualisieren?",
    "Wer uebernimmt den Kontakt zum Standesamt diese Woche?",
    "Ich nehme die Sitzordnung, du kuemmerst dich ums Budget.",
    "Kannst du bitte den DJ anrufen und die Zeiten bestaetigen?",
    "Die Deadline fuer die Gaestezahlen ist Freitag, wer macht das?",
    "Ich nehme die Blumen, du organisierst den Shuttle fuer die Gaeste.",
    "Wer uebernimmt die Weinbestellung?",
    "Kannst du bitte die Location nochmal checken?",
    "To-do: Brautkleid-Anprobe vereinbaren.",
    "Deadline fuer die Save-the-Dates ist naechste Woche.",
    "Ich nehme den Blumenschmuck, du die Tischkarten.",
    "Wer uebernimmt die Hotelreservierungen fuer die Gaeste?",
    "Kannst du bitte die Band wegen der Songwuensche kontaktieren?",
    "To-do: Trauzeugen-Outfit organisieren.",
    "Ich nehme die Kirche, du den Empfang.",
    "Wer kuemmert sich um die Parkplaetze?",
    "Kannst du bitte das Probeessen buchen?",
    "Deadline: Endgueltige Gaesteliste bis Montag.",
    "Ich organisiere den Friseur, du die Visagistin.",
    "Wer uebernimmt die Kinderbetreuung waehrend der Feier?",
    "Kannst du bitte die Hochzeitstorte bestellen?",
    "To-do: Trauzeugrede absprechen.",
    "Ich nehme die Einladungen, du die Dankeskarten.",
    "Wer kuemmert sich um die Musik fuer den Empfang?",
    "Kannst du bitte den Floristen anrufen?",
    "Deadline fuer die Tischordnung: Mittwoch.",
    "Ich organisiere den Shuttle, du die Uebernachtungen.",
    "Wer uebernimmt die Abstimmung mit der Druckerei?",
    "Kannst du bitte die Sektglaeser besorgen?",
    "To-do: Helfer fuer den Aufbau organisieren.",
    "Ich klaere die Location-Details, du die Bewirtung.",
    "Wer macht die Playlists fuer die Party?",
    "Kannst du bitte die Anfahrtsbeschreibung versenden?",
    "Deadline: DJ-Absprache bis Ende der Woche.",
    "Ich bestelle die Gastgeschenke, du die Kerzen.",
    "Wer kuemmert sich um das Feuerwerk?",
    "Kannst du bitte die Gaestebuch-Karten vorbereiten?",
    "To-do: Ringkissen besorgen.",
    "Ich organisiere die Fotospots, du den Zeitplan.",
    "Wer uebernimmt die Koordination am Tag selbst?",
    "Kannst du bitte die Stuehle fuer die Zeremonie bestellen?",
    "Deadline: Endgueltige Menueauswahl bis Donnerstag.",
    "Ich klaere den Ablauf mit dem Pfarrer, du mit dem DJ.",
    "Wer besorgt die Wegweiser?",
    "Kannst du bitte die Brandschutzbestimmungen pruefen?",
    "To-do: Notfallkit fuer den Hochzeitstag zusammenstellen.",
  ],
  "negative": [
    "Die Hochzeit war wunderschoen.",
    "Ich bin so gluecklich, dass wir geheiratet haben.",
    "Der schoenste Tag unseres Lebens.",
    "Alles hat perfekt geklappt.",
    "Wir erinnern uns gerne zurueck.",
    "Die Feier war ein voller Erfolg.",
    "Alles war perfekt organisiert.",
    "Wir geniessen die Flitterwochen.",
    "Der Tag war magisch.",
    "Alle Gaeste waren begeistert.",
    "Das Essen war fantastisch.",
    "Die Musik hat alle zum Tanzen gebracht.",
    "Wir sind so dankbar fuer den Tag.",
    "Alles verlief reibungslos.",
    "Die Fotos sind wunderschoen geworden.",
    "Jedes Detail stimmte.",
    "Die Gaeste hatten eine tolle Zeit.",
    "Wir wuerden nichts aendern.",
    "Der Blumenschmuck war traumhaft.",
    "Alles lief wie geplant.",
    "Der DJ war grossartig.",
    "Die Torte war ein Traum.",
    "Wir sind ueberwaeltigt von dem Tag.",
    "Alles hat harmoniert.",
    "Die beste Entscheidung unseres Lebens.",
  ],
},

"ATO_WHATSAPP": {
  "positive": [
    "Lass uns auf WhatsApp weiterschreiben.",
    "Hast du WhatsApp?",
    "WhatsApp ist bequemer.",
    "Schick mir deine WhatsApp-Nummer.",
    "Wir koennten WhatsApp stattdessen nutzen.",
    "Ich habe dir auf WhatsApp geschrieben.",
    "Schreib mir lieber auf WhatsApp.",
    "WhatsApp ist einfacher fuer mich.",
    "Ich bin besser ueber WhatsApp erreichbar.",
    "Koennen wir auf WhatsApp wechseln?",
    "WhatsApp-Nachricht hab ich geschickt.",
    "Meld dich per WhatsApp.",
    "Auf WhatsApp antworte ich schneller.",
    "Lieber WhatsApp als E-Mail.",
    "WhatsApp-Gruppe ist erstellt.",
    "Schick das mal ueber WhatsApp.",
    "Ich lese WhatsApp-Nachrichten sofort.",
    "Kannst du mir auf WhatsApp antworten?",
    "WhatsApp ist mein Hauptkanal.",
    "Ueber WhatsApp geht das schneller.",
    "Hab dir eine WhatsApp-Sprachnachricht geschickt.",
    "WhatsApp ist am unkompliziertesten.",
    "Bitte per WhatsApp, nicht per Mail.",
    "WhatsApp-Video waere auch eine Option.",
    "Ich check WhatsApp staendig.",
    "Wir machen eine WhatsApp-Gruppe dafuer.",
    "WhatsApp ist der einfachste Weg.",
    "Schreib mir gerne auf WhatsApp.",
    "Ich habe die WhatsApp-Nachricht gesehen.",
    "Ueber WhatsApp koennen wir das klaeren.",
    "WhatsApp-Call waere auch moeglich.",
    "Bitte ueber WhatsApp koordinieren.",
    "WhatsApp passt mir am besten.",
    "Ich bin den ganzen Tag auf WhatsApp.",
    "Sende mir das per WhatsApp.",
    "WhatsApp fuer schnelle Abstimmung.",
    "Meine WhatsApp-Nummer ist dieselbe.",
    "Lass uns eine WhatsApp-Gruppe aufmachen.",
    "WhatsApp-Status hast du gesehen?",
    "Per WhatsApp ist es am bequemsten.",
    "Schick mir deinen Standort per WhatsApp.",
    "WhatsApp ist mein bevorzugter Messenger.",
    "Ich antworte schneller auf WhatsApp.",
    "Ueber WhatsApp bleiben wir in Kontakt.",
    "WhatsApp-Anruf statt normalem Telefonat.",
    "Meld dich per WhatsApp, wenn du magst.",
    "WhatsApp fuer die schnelle Kommunikation.",
    "Ich habe WhatsApp immer an.",
    "Schick das Foto per WhatsApp.",
    "WhatsApp ist am praktischsten fuer uns.",
  ],
  "negative": [
    "Ich schreibe dir eine E-Mail.",
    "Ruf mich einfach an.",
    "Wir koennen uns persoenlich treffen.",
    "Ich schicke dir einen Brief.",
    "Per SMS erreichst du mich am besten.",
    "Lass uns telefonieren.",
    "Ich bevorzuge E-Mail.",
    "Schreib mir eine SMS.",
    "Wir sehen uns morgen persoenlich.",
    "Per Post geht das auch.",
    "Ich bin am Telefon am besten erreichbar.",
    "Lass uns ein Meeting machen.",
    "Per Slack koennen wir das klaeren.",
    "Ich schicke dir das per Mail.",
    "Ruf einfach kurz durch.",
    "Wir besprechen das persoenlich.",
    "Per Signal ist es sicherer.",
    "Ich schreibe dir im Chat.",
    "Lass uns einen Termin machen.",
    "Per Teams ist es offizieller.",
    "Ich schicke dir eine Nachricht per Telegram.",
    "Lass uns face-to-face reden.",
    "Per Mail ist es dokumentiert.",
    "Ich bevorzuge Anrufe.",
    "Wir koennen das bei Zoom besprechen.",
  ],
},

"ATO_WILL_CONTACT": {
  "positive": [
    "Ja ja, alles gut. Meld mich!",
    "Ich melde mich spaeter.",
    "Du hoerst von mir!",
    "Schreib dir dann.",
    "Meld mich, wenn ich wieder Zeit habe.",
    "Ich melde mich, versprochen.",
    "Du hoerst von mir, spaetestens morgen.",
    "Schreibe dir dann, wenn ich Bescheid weiss.",
    "Meld mich bald, okay?",
    "Ich melde mich die Tage.",
    "Du hoerst von mir, mach dir keine Sorgen.",
    "Schreib dir spaeter.",
    "Meld mich, sobald ich kann.",
    "Ich melde mich mal.",
    "Du hoerst von mir, ganz bestimmt.",
    "Schreib dir dann dazu.",
    "Meld mich, wenn ich weiss, wie es laeuft.",
    "Ich melde mich naechste Woche.",
    "Du hoerst von mir, keine Angst.",
    "Schreib dir bald.",
    "Meld mich noch, okay?",
    "Ich melde mich, wenn es passt.",
    "Du hoerst von mir, ehrlich.",
    "Schreib dir dann was dazu.",
    "Meld mich morgen.",
    "Ich melde mich, wenn ich Luft habe.",
    "Du hoerst von mir, auf jeden Fall.",
    "Schreib dir, sobald ich mehr weiss.",
    "Meld mich spaeter nochmal.",
    "Ich melde mich bei dir, versprochen.",
    "Du hoerst von mir, gib mir etwas Zeit.",
    "Schreibe dir am Wochenende.",
    "Meld mich, wenn der Stress nachlässt.",
    "Ich melde mich, wenn es ruhiger wird.",
    "Du hoerst von mir, bald.",
    "Schreib dir dann eine Nachricht.",
    "Meld mich, ja?",
    "Ich melde mich definitiv.",
    "Du hoerst von mir, spätestens uebermorgen.",
    "Schreib dir, versprochen.",
    "Meld mich bei Gelegenheit.",
    "Ich melde mich zeitnah.",
    "Du hoerst von mir, das weisst du.",
    "Schreib dir in den naechsten Tagen.",
    "Meld mich, sobald es geht.",
    "Ich melde mich Ende der Woche.",
    "Du hoerst von mir, mach dir keinen Kopf.",
    "Schreibe dir dann eine kurze Nachricht.",
    "Meld mich, keine Sorge.",
    "Ich melde mich noch, ganz sicher.",
  ],
  "negative": [
    "Ich rufe jetzt sofort an.",
    "Lass uns das jetzt klaeren.",
    "Ich bin gerade erreichbar, rede jetzt.",
    "Hier ist meine Antwort.",
    "Ich antworte sofort.",
    "Lass uns das jetzt besprechen.",
    "Ich bin jetzt da.",
    "Hier meine direkte Rueckmeldung.",
    "Ich reagiere sofort.",
    "Jetzt ist ein guter Zeitpunkt.",
    "Ich bin erreichbar, leg los.",
    "Lass uns das nicht aufschieben.",
    "Meine Antwort kommt jetzt.",
    "Ich bin sofort dabei.",
    "Kein Aufschieben, lass uns reden.",
    "Ich antworte dir gleich.",
    "Lass uns das jetzt festmachen.",
    "Ich gebe dir sofort Bescheid.",
    "Jetzt passt es mir.",
    "Ich bin gerade frei, lass uns reden.",
    "Direkte Antwort: Ja.",
    "Kein Vertroesten, ich sage es jetzt.",
    "Ich bin jetzt verfuegbar.",
    "Lass uns das sofort angehen.",
    "Hier und jetzt, lass uns das klaeren.",
  ],
},

}


def enrich_marker(marker_id: str, data: dict) -> bool:
    fpath = find_file(marker_id)
    if fpath is None:
        print(f"  SKIP {marker_id}: file not found")
        return False

    with open(fpath, "r") as f:
        doc = yaml.load(f)

    if doc is None:
        print(f"  SKIP {marker_id}: empty YAML")
        return False

    # Handle nested markers list
    if "markers" in doc and isinstance(doc["markers"], list):
        for m in doc["markers"]:
            if isinstance(m, dict) and m.get("id") == marker_id:
                if "examples" in m:
                    nested_examples = m["examples"]
                    if isinstance(nested_examples, list):
                        m["examples"] = data.get("positive", data.get("positive_de", []))[:5]

    if "examples" not in doc:
        doc["examples"] = {}

    examples = doc["examples"]

    # Determine key names based on data dict keys
    if "positive_de" in data:
        pos_key = "positive_de"
        neg_key = "negative_de"
    elif "positive_de" in examples:
        pos_key = "positive_de"
        neg_key = "negative_de"
    else:
        pos_key = "positive"
        neg_key = "negative"

    examples[pos_key] = data.get(pos_key, data.get("positive", []))
    examples[neg_key] = data.get(neg_key, data.get("negative", []))

    with open(fpath, "w") as f:
        yaml.dump(doc, f)

    pos_count = len(examples[pos_key])
    neg_count = len(examples[neg_key])
    print(f"  OK {marker_id}: {pos_count} pos + {neg_count} neg ({pos_key}/{neg_key})")
    return True


def main():
    success = 0
    fail = 0
    for marker_id, data in ENRICHMENTS.items():
        ok = enrich_marker(marker_id, data)
        if ok:
            success += 1
        else:
            fail += 1
    print(f"\nDone: {success} enriched, {fail} failed/skipped")


if __name__ == "__main__":
    main()
