#!/usr/bin/env python3
"""
LeanDeep V6.0 - Enrich ATO markers with German-language examples.
Each marker gets exactly 50 positive and 25 negative examples.
Preserves YAML formatting via ruamel.yaml.
"""

from pathlib import Path
from ruamel.yaml import YAML

yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096  # prevent line wrapping

BASE = Path("build/markers_rated")
DIRS = ["1_approved", "2_good", "3_needs_work"]

TARGET_POS = 50
TARGET_NEG = 25

# ──────────────────────────────────────────────────────────────────────
# Example data: 50 positive + 25 negative per marker, all German,
# realistic conversational style (WhatsApp, therapy, couple arguments, business)
# ──────────────────────────────────────────────────────────────────────

EXAMPLES = {
    "ATO_ABANDONMENT_ANXIETY": {
        "positive": [
            "Bitte geh nicht, ich halt das nicht aus.",
            "Du wirst mich irgendwann verlassen, ich spüre es.",
            "Ich kann nicht allein sein, bitte bleib.",
            "Jeder verlässt mich am Ende.",
            "Ohne dich bin ich verloren.",
            "Bitte verlass mich nicht, ich brauche dich.",
            "Die Angst, dass du gehst, macht mich fertig.",
            "Ich klammere mich an dich, weil ich Angst habe.",
            "Wenn du gehst, breche ich zusammen.",
            "Du wirst mich auch im Stich lassen.",
            "Ich bin so verzweifelt, bitte bleib bei mir.",
            "Allein sein ist unerträglich für mich.",
            "Du gehst und kommst nie wieder.",
            "Ich brauche dich hier, bitte geh nicht weg.",
            "Alle Menschen in meinem Leben verlassen mich.",
            "Die Vorstellung, verlassen zu werden, lähmt mich.",
            "Bitte sag, dass du bleibst.",
            "Ich kann ohne dich nicht existieren.",
            "Du wirst mich verstoßen wie alle anderen.",
            "Ich bin so einsam, wenn du nicht da bist, ich halt das nicht aus.",
            "Geh nicht zur Tür, bitte, ich flehe dich an.",
            "Ich bin wie verlassen, wenn du abends nicht schreibst.",
            "Ich klammere, weil ich dich nicht verlieren will.",
            "Warum antwortest du nicht? Willst du mich loswerden?",
            "Ich hab Angst, dass du jemand Besseres findest und mich verlässt.",
            "Sag mir, dass du mich nicht allein lässt.",
            "Jedes Mal wenn du gehst, denke ich, du kommst nicht wieder.",
            "Ich bin verzweifelt ohne dich.",
            "Du lässt mich im Stich, genau wie mein Vater.",
            "Bitte gib mich nicht auf.",
            "Ich brauche die Bestätigung, dass du bei mir bleibst.",
            "Wenn du schweigst, denke ich sofort, du willst mich nicht mehr.",
            "Ich kann einfach nicht allein sein, das ist zu viel.",
            "Die Angst verlassen zu werden frisst mich auf.",
            "Bitte verlass mich nicht, ich tu alles was du willst.",
            "Ohne dich ist alles dunkel und leer.",
            "Du bist die einzige Person, die bleibt – oder?",
            "Ich hab panische Angst, dass du mich aufgibst.",
            "Jedes Mal wenn wir streiten, denke ich, jetzt ist es vorbei.",
            "Ich bin so abhängig von dir, dass der Gedanke ans Verlassenwerden unerträglich ist.",
            "Ruf mich bitte an, ich brauche dich jetzt.",
            "Warum warst du so lange weg? Ich dachte, du kommst nicht zurück.",
            "Ich kann nicht schlafen, wenn ich weiß, dass du sauer bist – vielleicht gehst du.",
            "Lass mich nicht allein mit meinen Gedanken, bitte.",
            "Die Verlassenheitsangst macht mich kaputt.",
            "Ich klammere mich an jede Beziehung, weil ich Angst habe, allein zu sein.",
            "Bitte versprich mir, dass du bleibst.",
            "Wenn du gehst, bleibt nichts mehr übrig von mir.",
            "Ich halt die Einsamkeit nicht aus, komm bitte zurück.",
            "Nicht noch jemand, der mich verlässt – bitte nicht du.",
        ],
        "negative": [
            "Ich verstehe, wenn du heute Abend nicht kannst.",
            "Kein Problem, wir sehen uns morgen.",
            "Nimm dir ruhig deine Zeit, ich komm klar.",
            "Ich bin ganz zufrieden allein heute.",
            "Mach dir keinen Stress, das passt schon.",
            "Ich genieße den Abend für mich.",
            "Wir können auch morgen reden, ist nicht schlimm.",
            "Ich vertraue dir, dass du wiederkommst.",
            "Es ist okay, wenn du mal was allein machst.",
            "Ich brauche auch mal Zeit für mich.",
            "Du musst nicht immer da sein.",
            "Ich hab heute Abend was Eigenes vor, ist voll okay.",
            "Ruf an, wann es dir passt, ich bin entspannt.",
            "Kein Drama, wir sehen uns, wenn es klappt.",
            "Ich freue mich auf dich, aber ich kann auch warten.",
            "Bis morgen dann, schlaf gut.",
            "Mach dein Ding, wir hören uns.",
            "Ich verbringe gern mal einen Abend allein.",
            "Alles gut, ich bin nicht aus Zucker.",
            "Du kannst ruhig am Wochenende mit Freunden feiern.",
            "Klar kannst du fahren, ich halt die Stellung.",
            "Ich schaff das auch ohne dich, aber schön wenn du dabei bist.",
            "Geh ruhig, ich lese noch was und schlaf dann.",
            "Das ist dein Abend, genieß ihn.",
            "Ich bin eigenständig genug für einen Abend.",
        ],
    },

    "ATO_APOLOGY": {
        "positive_de": [
            "Tut mir leid, dass ich so spät dran bin.",
            "Entschuldige, das war nicht okay von mir.",
            "Verzeih mir bitte, ich hab Mist gebaut.",
            "Mein Fehler, sorry.",
            "Das war dumm von mir, tut mir echt leid.",
            "Es tut mir leid, ich hätte das nicht sagen sollen.",
            "Ich entschuldige mich für mein Verhalten.",
            "Sorry, ich war echt daneben gestern.",
            "Verzeih mir, ich hab nicht nachgedacht.",
            "Das war ein Fehler, tut mir leid.",
            "Ich bereue das wirklich, entschuldige.",
            "Tut mir aufrichtig leid, das ging zu weit.",
            "Sorry für die Verspätung.",
            "Es war nicht richtig, was ich getan hab. Tut mir leid.",
            "Bitte nimm meine Entschuldigung an.",
            "Das war unangemessen, verzeih mir.",
            "Ich hab überreagiert, sorry.",
            "Entschuldigung für meinen Ton vorhin.",
            "Tut mir leid, ich hätte besser zuhören sollen.",
            "Sorry, das war voll daneben.",
            "Mein Fehler, ich stehe dazu und entschuldige mich.",
            "Das war nicht fair von mir, verzeih mir bitte.",
            "Es tut mir so leid, dass ich dich verletzt hab.",
            "Ich muss mich entschuldigen, das war total unangebracht.",
            "Sorry, ich war gestresst und hab es an dir ausgelassen.",
            "Entschuldige bitte, ich hab's vermasselt.",
            "Tut mir leid wegen gestern Abend.",
            "Das war mein Fehler, ich entschuldige mich.",
            "Verzeih mir, das hätte nicht passieren dürfen.",
            "Sorry, ich war unfair zu dir.",
            "Tut mir wahnsinnig leid, das wollte ich nicht.",
            "Ich bitte um Entschuldigung für das, was passiert ist.",
            "Es tut mir leid, dass ich vergessen hab anzurufen.",
            "Mein Fehler, entschuldige bitte.",
            "Sorry, ich hab's echt verbockt.",
            "Verzeih mir den Ausrutscher.",
            "Tut mir leid, ich hätte nachfragen sollen.",
            "Entschuldige, das war gedankenlos.",
            "Tut mir leid, ich war zu hart.",
            "Sorry, das war unsensibel von mir.",
            "Ich entschuldige mich vielmals.",
            "Verzeih mir bitte, ich war im Unrecht.",
            "Das tut mir von Herzen leid.",
            "Sorry, ich war egoistisch.",
            "Entschuldigung, ich hätte dich fragen müssen.",
            "Tut mir leid, dass ich nicht da war, als du mich gebraucht hast.",
            "Mein Fehler komplett, sorry dafür.",
            "Verzeih mir, ich weiß, dass das wehgetan hat.",
            "Entschuldige meinen Ausraster.",
            "Es tut mir leid, ich mache es wieder gut.",
        ],
        "negative_de": [
            "Das war völlig in Ordnung so.",
            "Ich hab alles richtig gemacht.",
            "Du bist derjenige, der sich entschuldigen sollte.",
            "Wieso sollte ich mich entschuldigen?",
            "Ich stehe zu meiner Aussage.",
            "Kein Grund für eine Entschuldigung.",
            "Das muss ich nicht bedauern.",
            "Ist mir egal, ob dir das nicht passt.",
            "Ich hab nichts falsch gemacht.",
            "Du übertreibst völlig.",
            "Das war doch nicht schlimm.",
            "Sei nicht so empfindlich.",
            "Stell dich nicht so an.",
            "Ich hab recht gehabt.",
            "Da gibt es nichts zu entschuldigen.",
            "Ich würde es wieder so machen.",
            "Selber schuld.",
            "Nicht mein Problem.",
            "Das war notwendig.",
            "Ich bereue nichts.",
            "Du hast angefangen.",
            "Mach dir keinen Kopf, war eh egal.",
            "Wo ist da das Problem?",
            "Ich seh nicht ein, mich dafür zu entschuldigen.",
            "Das war normal, kein Fehler.",
        ],
    },

    "ATO_COMPASSION": {
        "positive": [
            "Tut mir leid, das zu hören.",
            "Ich fühle mit dir, das muss wirklich hart sein.",
            "Das muss schwer sein für dich gerade.",
            "Ich kann gut nachvollziehen, wie du dich fühlst.",
            "Mein Mitgefühl ist bei dir.",
            "Ich wünschte, ich könnte dir den Schmerz abnehmen.",
            "Das tut mir in der Seele weh für dich.",
            "Ich bin für dich da, egal was kommt.",
            "Es tut mir so leid, dass du das durchmachen musst.",
            "Ich fühle mich dir verbunden in diesem Moment.",
            "Du musst das nicht allein durchstehen.",
            "Mir bricht das Herz, wenn ich das höre.",
            "Ich kann verstehen, warum dich das belastet.",
            "Das muss wirklich schlimm für dich sein.",
            "Ich fühl mit dir, ehrlich.",
            "Ich wünschte, ich könnte mehr tun für dich.",
            "Das klingt unglaublich schmerzhaft, tut mir leid.",
            "Ich bin bei dir, auch wenn ich nicht alles verstehe.",
            "Mein Mitgefühl hast du.",
            "Das muss sich furchtbar anfühlen.",
            "Ich kann mir vorstellen, wie belastend das ist.",
            "Ich fühle mit dir und bin an deiner Seite.",
            "Wenn ich das höre, macht mich das traurig für dich.",
            "Du verdienst es nicht, so zu leiden.",
            "Es tut mir leid, dass du gerade so kämpfst.",
            "Ich hab großes Mitgefühl für das, was du durchmachst.",
            "Das muss wirklich schwer sein, das alles zu tragen.",
            "Ich fühle deinen Schmerz.",
            "Es tut mir so leid, ich kann verstehen, dass das wehtut.",
            "Mein Herz ist bei dir.",
            "Ich denke an dich und fühle mit.",
            "Du bist nicht allein damit, ich bin hier.",
            "Das klingt so belastend, tut mir aufrichtig leid.",
            "Ich kann nachfühlen, wie schlimm das sein muss.",
            "Du tust mir leid, das ist einfach zu viel.",
            "Ich bin da für dich, wenn du reden willst.",
            "Mir tut es weh, dich so zu sehen.",
            "Ich empfinde echtes Mitgefühl für deine Situation.",
            "Es muss schrecklich sein, damit umgehen zu müssen.",
            "Du hast mein vollstes Mitgefühl.",
            "Ich spüre, wie sehr dich das mitnimmt.",
            "Tut mir leid, ich wünschte, es wäre anders.",
            "Ich bin hier und höre dir zu, das muss so schwer sein.",
            "Mein Beileid, das ist wirklich furchtbar.",
            "Ich kann verstehen, dass du am Boden bist.",
            "Das muss dich innerlich zerreißen.",
            "Ich fühle mit dir und wünsche dir Kraft.",
            "Das muss so schmerzhaft sein gerade.",
            "Ich bin bei dir im Herzen.",
            "Mir tut es aufrichtig leid, was du erleben musst.",
        ],
        "negative": [
            "Stell dich nicht so an.",
            "Jeder hat Probleme, du bist nicht besonders.",
            "Das ist doch nicht so schlimm.",
            "Hör auf zu jammern.",
            "Du übertreibst mal wieder.",
            "Andere haben es viel schlimmer.",
            "Reiß dich mal zusammen.",
            "Das geht mich nichts an.",
            "Sei nicht so weinerlich.",
            "Ist halt so, kann man nichts machen.",
            "Mach kein Drama draus.",
            "Du bist selbst schuld.",
            "Das interessiert mich nicht wirklich.",
            "Geht mich nichts an, ist dein Problem.",
            "Jammer nicht rum.",
            "Damit musst du allein klarkommen.",
            "Ich hab eigene Probleme.",
            "Stell dich nicht so fragil dar.",
            "Da hab ich jetzt kein Mitleid.",
            "Willst du bemitleidet werden oder was?",
            "Das wird schon, mach dir mal keinen Kopf.",
            "Hör auf, so ein Opfer zu spielen.",
            "Das Leben ist halt kein Ponyhof.",
            "Mimimi, immer du.",
            "Ich kann da wenig mit anfangen ehrlich gesagt.",
        ],
    },

    "ATO_CONTRADICTION_LEX": {
        "positive": [
            "Das widerspricht dem, was du vorher gesagt hast.",
            "Im Gegensatz zu deiner Aussage gestern ist das was anderes.",
            "Das ist nicht wie vorher besprochen.",
            "Aber inzwischen sagst du plötzlich das Gegenteil.",
            "Doch, du hast das anders formuliert letzte Woche.",
            "Das widerspricht sich total.",
            "Im Gegensatz dazu hast du letztens behauptet...",
            "Das stimmt nicht mit dem überein, was du vorher meintest.",
            "Aber inzwischen hat sich deine Meinung um 180 Grad gedreht.",
            "Doch, das hast du ganz anders gesagt.",
            "Das widerspricht allem, was wir vereinbart hatten.",
            "Im Gegensatz zu deinem Versprechen machst du jetzt das Gegenteil.",
            "Das ist nicht wie vorher abgemacht.",
            "Aber inzwischen passt dir was anderes besser, oder?",
            "Doch, vorige Woche war deine Position eine komplett andere.",
            "Das widerspricht deiner eigenen Logik.",
            "Im Gegensatz zu dem, was du mir erzählt hast.",
            "Das ist aber nicht wie vorher, oder?",
            "Aber inzwischen hast du die Spielregeln geändert.",
            "Doch, vorhin hast du noch was ganz anderes behauptet.",
            "Das widerspricht sich hinten und vorne.",
            "Im Gegensatz dazu stand in deiner Nachricht...",
            "Das passt nicht zu vorher, merkst du das nicht?",
            "Aber inzwischen ist plötzlich alles anders.",
            "Doch, du hast dich total widersprochen.",
            "Das widerspricht komplett deiner Aussage von gestern.",
            "Im Gegensatz zu dem, was du am Telefon gesagt hast.",
            "Das war vorher noch ganz anders, oder nicht?",
            "Aber inzwischen drehst du alles um.",
            "Doch, ganz genau das hast du gesagt, und jetzt das Gegenteil.",
            "Das widerspricht jeder Vereinbarung, die wir hatten.",
            "Im Gegensatz zu deiner Mail stimmt das überhaupt nicht.",
            "Das ist aber nicht wie vorher beschrieben, Moment mal.",
            "Aber inzwischen kommt eine ganz neue Version.",
            "Doch, das war definitiv anders, ich hab's mir notiert.",
            "Das widerspricht sich, und du weißt das.",
            "Im Gegensatz dazu hast du mir versichert...",
            "Nicht wie vorher, das ist eine völlig neue Geschichte.",
            "Aber inzwischen willst du davon nichts mehr wissen.",
            "Doch, das Gegenteil hast du behauptet.",
            "Das widerspricht fundamental dem, worauf wir uns geeinigt haben.",
            "Im Gegensatz zu dem, was im Protokoll steht.",
            "Das ist nicht das, was du vorher versprochen hast.",
            "Aber inzwischen sind die Regeln anscheinend andere.",
            "Doch, ich erinnere mich ganz genau, das war anders.",
            "Das widerspricht deiner Aussage vom letzten Gespräch.",
            "Im Gegensatz zu dem, was du mir geschrieben hast.",
            "Das ist nicht wie vorher, du hast deine Meinung geändert.",
            "Aber inzwischen bist du völlig umgeschwenkt.",
            "Doch, genau das Gegenteil hast du mir versprochen.",
        ],
        "negative": [
            "Das passt gut zu dem, was wir besprochen haben.",
            "Ja, das sehe ich genauso wie du.",
            "Stimmt, das hast du schon immer so gesagt.",
            "Wir sind da völlig einer Meinung.",
            "Das bestätigt deine Aussage von gestern.",
            "Genau so haben wir es vereinbart.",
            "Ja, das deckt sich mit dem, was du meintest.",
            "Da gibt es keinen Widerspruch.",
            "Das ergibt alles Sinn zusammen.",
            "Ich finde, das passt sehr gut zueinander.",
            "Das ist konsistent mit deiner Position.",
            "Alles klar, das stimmt überein.",
            "Ganz genau, so war es auch gemeint.",
            "Richtig, da sind wir auf einer Linie.",
            "Ja, das habe ich auch so verstanden.",
            "Das fügt sich gut zusammen.",
            "Genau das hast du gesagt, und es stimmt immer noch.",
            "Wir sind da auf dem gleichen Stand.",
            "Stimmt überein, kein Widerspruch.",
            "Das passt wie angegossen zu deiner Position.",
            "Ja, völlig logisch und stimmig.",
            "Da gibt es keine Diskrepanz.",
            "Alles im Einklang, wie besprochen.",
            "Genau, das ergänzt sich perfekt.",
            "Richtig, wie du es beschrieben hast.",
        ],
    },

    "ATO_CONTROL": {
        "positive": [
            "Du darfst das nicht ohne meine Erlaubnis machen.",
            "Du solltest erst mich fragen, bevor du irgendwas entscheidest.",
            "Du musst das genau so machen, wie ich es sage.",
            "Du kannst da nicht einfach hingehen.",
            "Du brauchst meine Erlaubnis dafür.",
            "Ich bestimme, was hier passiert.",
            "Du machst das, was ich dir sage.",
            "Ohne meine Zustimmung läuft hier gar nichts.",
            "Du darfst dich nicht mit ihr treffen.",
            "Du musst mich vorher fragen.",
            "Das ist nicht erlaubt, hörst du?",
            "Du solltest dich an meine Regeln halten.",
            "Du musst um Erlaubnis bitten.",
            "Ich entscheide, wann du gehen darfst.",
            "Du kannst nicht einfach tun, was du willst.",
            "Du darfst das Haus nicht verlassen, ohne mir Bescheid zu sagen.",
            "Ich muss alles wissen, was du tust.",
            "Du hast dich danach zu richten.",
            "Zeig mir dein Handy, ich will sehen, mit wem du schreibst.",
            "Du solltest aufhören, mit diesen Leuten rumzuhängen.",
            "Du musst immer erreichbar sein für mich.",
            "Ohne meine Genehmigung geht nichts.",
            "Du hast zu tun, was ich sage.",
            "Ich kontrolliere das, also halt dich raus.",
            "Du darfst nicht alleine da hinfahren.",
            "Du solltest besser auf mich hören.",
            "Ich bestimme, mit wem du dich triffst.",
            "Du musst mir sagen, wo du warst.",
            "Ich entscheide, was wir machen.",
            "Du darfst das Geld nicht ohne mich ausgeben.",
            "Du musst meine Zustimmung einholen.",
            "Ruf mich an, wenn du ankommst, ich will es wissen.",
            "Du kannst nicht einfach Pläne machen ohne mich.",
            "Du solltest das bleiben lassen, ich sage das nicht nochmal.",
            "Ohne mein Okay machst du gar nichts.",
            "Du darfst nicht alleine verreisen.",
            "Ich muss über alles informiert werden.",
            "Du musst tun, was ich für richtig halte.",
            "Du hast mich nicht zu hinterfragen.",
            "Du solltest dich fügen.",
            "Ich bestimme die Regeln hier.",
            "Ohne meine Erlaubnis gehst du nirgendwohin.",
            "Du musst dich nach meinem Zeitplan richten.",
            "Ich sage dir, wann und wo.",
            "Du brauchst mein Einverständnis für solche Sachen.",
            "Du darfst das nicht, Punkt.",
            "Halt dich an das, was ich sage.",
            "Ich kontrolliere unsere Finanzen, du fragst mich.",
            "Du musst mir erst sagen, bevor du Geld ausgibst.",
            "Ich entscheide, wie das läuft.",
        ],
        "negative": [
            "Du kannst gerne selbst entscheiden.",
            "Mach ruhig, wie du denkst.",
            "Ich vertraue deinem Urteil.",
            "Entscheide du, ich unterstütze das.",
            "Du weißt am besten, was richtig ist.",
            "Mach es so, wie es für dich passt.",
            "Ich misch mich da nicht ein.",
            "Deine Entscheidung, ich respektiere das.",
            "Wir können das zusammen besprechen, wenn du willst.",
            "Du bist frei in deiner Wahl.",
            "Ich vertraue dir da komplett.",
            "Mach dein Ding, ich steh hinter dir.",
            "Das ist deine Sache, ich respektiere das.",
            "Klar kannst du das allein entscheiden.",
            "Ich will dich nicht einschränken.",
            "Triff die Entscheidung, die sich für dich richtig anfühlt.",
            "Du brauchst mich nicht zu fragen, mach einfach.",
            "Das überlasse ich dir.",
            "Ich möchte dich nicht kontrollieren.",
            "Du bist erwachsen, du entscheidest das.",
            "Mach, was du für richtig hältst.",
            "Ich möchte nicht über dein Leben bestimmen.",
            "Klar, geh ruhig, viel Spaß.",
            "Das liegt bei dir.",
            "Deine Freiheit ist mir wichtig.",
        ],
    },

    "ATO_CROSS_REF_OTHER": {
        "positive": [
            "Wie du gesagt hast, das war anders geplant.",
            "Vorhin meintest du, du hättest keine Zeit.",
            "Du sagtest eben, das wäre nicht möglich.",
            "Das passt nicht zu vorher, was du gesagt hast.",
            "Eben hast du noch was anderes behauptet.",
            "Wie du letzte Woche gesagt hast, sollten wir das anders machen.",
            "Vorhin meintest du, du wärst einverstanden.",
            "Du sagtest gestern, dass du kommst.",
            "Das passt nicht zu dem, was du vorher gesagt hast.",
            "Eben hast du mir versichert, alles sei okay.",
            "Wie du selbst gesagt hast, war das ein Fehler.",
            "Vorhin meintest du noch, das Projekt sei fast fertig.",
            "Du sagtest am Telefon, du würdest dich kümmern.",
            "Das passt nicht zu vorher, als du zugestimmt hast.",
            "Eben hast du mir versprochen, pünktlich zu sein.",
            "Wie du gesagt hast, sollte das bis Freitag erledigt sein.",
            "Vorhin meintest du, das Budget reiche aus.",
            "Du sagtest doch, du hättest das erledigt.",
            "Wie du eben gesagt hast, war das kein Problem für dich.",
            "Vorhin meintest du, du wärst damit einverstanden gewesen.",
            "Du sagtest gerade eben noch, du hättest Zeit.",
            "Das passt nicht zu dem, was du vorher versprochen hast.",
            "Eben hast du behauptet, du wärst nicht da gewesen.",
            "Wie du selbst zugegeben hast, war das dein Fehler.",
            "Vorhin meintest du, es gäbe keine Probleme.",
            "Du sagtest, du würdest dich melden.",
            "Das passt doch nicht zu dem, was du vorhin erzählt hast.",
            "Eben hast du gesagt, du willst das nicht.",
            "Wie du versprochen hast, sollte alles klappen.",
            "Vorhin hast du gemeint, du wärst bereit dafür.",
            "Du sagtest mir, du hättest es verstanden.",
            "Das widerspricht dem, was du vorher meintest.",
            "Eben hast du noch behauptet, alles sei in Ordnung.",
            "Wie du gesagt hast, wolltest du dich darum kümmern.",
            "Vorhin war deine Aussage eine ganz andere.",
            "Du sagtest mir gestern Abend, du würdest kommen.",
            "Das passt nicht zu vorher, Moment mal.",
            "Eben hast du doch selbst gesagt, das geht nicht.",
            "Wie du mir geschrieben hast, war das so geplant.",
            "Vorhin meintest du, es sei nicht so dringend.",
            "Du sagtest, du hättest keinen Bock mehr.",
            "Das passt aber nicht zu dem, was du eben behauptet hast.",
            "Eben hast du mir erzählt, du wärst beschäftigt.",
            "Wie du erwähnt hast, war das Meeting verschoben.",
            "Vorhin sagtest du, das wäre kein Thema.",
            "Du hast doch gesagt, du kümmerst dich drum.",
            "Das passt nicht zu vorher, als du anders geredet hast.",
            "Eben hast du mir versichert, du warst nicht dort.",
            "Wie du mir heute Morgen gesagt hast, wolltest du absagen.",
            "Vorhin meintest du, das Geld sei da.",
        ],
        "negative": [
            "Ich finde, wir sollten nach vorne schauen.",
            "Lass uns das jetzt klären, egal was vorher war.",
            "Ich möchte meine eigene Meinung sagen.",
            "Schauen wir uns die Fakten an.",
            "Ich denke, das ist ein neues Thema.",
            "Lass uns frisch anfangen.",
            "Meine Sicht ist folgende.",
            "Ich hab mir überlegt, dass wir anders vorgehen.",
            "Unabhängig davon finde ich...",
            "Ich hab eine neue Idee.",
            "Lass uns das getrennt betrachten.",
            "Ich möchte über die Zukunft reden.",
            "Das ist jetzt ein anderes Thema.",
            "Ich spreche für mich selbst.",
            "Schauen wir mal, was jetzt sinnvoll ist.",
            "Ich schlage vor, wir fangen von vorne an.",
            "Mein Standpunkt dazu ist...",
            "Ich möchte jetzt meine Perspektive teilen.",
            "Egal was war, was machen wir jetzt?",
            "Ich habe einen neuen Vorschlag.",
            "Lass uns in die Zukunft blicken.",
            "Meine Einschätzung ist folgende.",
            "Ich beziehe mich auf die aktuelle Situation.",
            "Ganz unabhängig davon denke ich...",
            "Jetzt geht es um was anderes.",
        ],
    },

    "ATO_DEFENSIVENESS": {
        "positive_de": [
            "Das ist nicht fair, was du da sagst.",
            "Ich hab nichts falsch gemacht!",
            "Du bist doch derjenige, der...",
            "Warum immer ich? Das ist ungerecht!",
            "Das stimmt so nicht, du verdrehst alles!",
            "Ich verteidige mich nur, weil du mich angreifst.",
            "Das war nicht so, wie du es darstellst.",
            "Du übertreibst total, so war das nicht.",
            "Nicht meine Schuld, hör auf damit!",
            "Warum greifst du mich ständig an?",
            "Das ist ein unfairer Vorwurf!",
            "Ich hab recht, und du weißt das.",
            "Du bist schuld, nicht ich!",
            "Immer bin ich der Böse, oder was?",
            "Stimmt gar nicht, was du behauptest!",
            "Ich muss mich hier rechtfertigen, weil du unfair bist.",
            "Das hab ich nie gesagt, hör auf mir Worte in den Mund zu legen.",
            "Ich hab mich korrekt verhalten, punkt.",
            "Du stellst das komplett falsch dar.",
            "Warum hackst du immer auf mir rum?",
            "Ich hab nichts Falsches getan, das bildest du dir ein.",
            "Das ist deine Interpretation, nicht die Wahrheit.",
            "Hör auf, mich für alles verantwortlich zu machen.",
            "Das war ganz anders, du erinnerst dich falsch.",
            "Ich verteidige mich, weil du ungerecht bist.",
            "Warum soll immer alles meine Schuld sein?",
            "Das ist unfair und du weißt es.",
            "Du verdrehst die Tatsachen!",
            "Ich hab mir nichts vorzuwerfen.",
            "Das stimmt hinten und vorne nicht.",
            "Ich bin nicht schuld, hör auf damit!",
            "Das war keine Absicht, mach nicht so ein Drama.",
            "Wieso unterstellst du mir sowas?",
            "Du siehst das völlig falsch.",
            "Ich hab das Recht, mich zu verteidigen.",
            "Was du sagst, ist einfach nicht wahr.",
            "Immer ich, nie du, merkst du das eigentlich?",
            "Das ist eine Unterstellung, mehr nicht.",
            "Du beschuldigst mich zu Unrecht.",
            "Ich werde mich nicht dafür entschuldigen.",
            "Das war nicht mein Fehler, akzeptier das.",
            "Du hast angefangen, nicht ich!",
            "Das ist lächerlich, so war es nicht.",
            "Ich lass mir das nicht anhängen.",
            "Du machst aus einer Mücke einen Elefanten.",
            "Ich hab mich an alles gehalten.",
            "Das kannst du mir nicht vorwerfen.",
            "So läuft das nicht, ich bin nicht schuld.",
            "Hör auf, alles auf mich zu schieben.",
            "Du bist ungerecht und das weißt du.",
        ],
        "negative_de": [
            "Du hast recht, das war mein Fehler.",
            "Ich gebe zu, dass ich falsch lag.",
            "Entschuldige, du hast einen Punkt.",
            "Lass uns das in Ruhe klären.",
            "Ich verstehe, was du meinst.",
            "Stimmt, da hab ich mich geirrt.",
            "Ja, das hätte ich anders machen sollen.",
            "Du hast recht damit, das sehe ich ein.",
            "Ich nehme die Kritik an.",
            "Danke für den Hinweis, das hilft mir.",
            "Ja, das war meine Schuld.",
            "Ich akzeptiere, dass ich Fehler gemacht hab.",
            "Du hast völlig recht, sorry.",
            "Ich will das nicht abstreiten.",
            "Das nehme ich mir zu Herzen.",
            "Stimmt, ich hätte besser handeln können.",
            "Ich bin offen für deine Kritik.",
            "Ja, da habe ich Mist gebaut.",
            "Das lag an mir, entschuldige.",
            "Ich höre dir zu und nehme das ernst.",
            "Da war ich im Unrecht.",
            "Danke, dass du das ansprichst.",
            "Ich reflektiere das nochmal.",
            "Ja, da muss ich mir an die eigene Nase fassen.",
            "Ich übernehme die Verantwortung dafür.",
        ],
    },

    "ATO_DENIAL": {
        "positive": [
            "Das stimmt nicht, was du sagst.",
            "Habe ich nie gesagt.",
            "Das ist nie passiert.",
            "Das war nicht so.",
            "So war das nicht gemeint.",
            "Das habe ich nicht getan.",
            "Nie ist das passiert, du spinnst.",
            "Das ist falsch, das stimmt einfach nicht.",
            "Das hab ich nie behauptet.",
            "Das ist nie passiert, du erfindest das.",
            "Das stimmt überhaupt nicht.",
            "Ich hab das nie gesagt, du verwechselst da was.",
            "Das war nicht so, du erinnerst dich falsch.",
            "Das ist nie passiert, glaub mir.",
            "Hab ich nie gesagt, schwöre.",
            "Das stimmt vorne und hinten nicht.",
            "Das war definitiv nicht so.",
            "Habe ich nie gesagt, das bildest du dir ein.",
            "Ist nie passiert, ich war gar nicht da.",
            "Das stimmt nicht, du lügst.",
            "Das habe ich nie getan, das ist eine Unterstellung.",
            "Das war nicht so, ich weiß es genau.",
            "Hab ich nie behauptet, nein.",
            "Das ist nie passiert, da verwechselst du was.",
            "Das stimmt einfach nicht, Punkt.",
            "Das habe ich niemals gesagt.",
            "Das war nicht so, du verdrehst alles.",
            "Ist nie passiert, das ist gelogen.",
            "Das stimmt so nicht und das weißt du.",
            "Habe ich nie gesagt, ganz sicher nicht.",
            "Das war definitiv nicht so, wie du es darstellst.",
            "Das ist nicht passiert, nein, nein, nein.",
            "Hab ich nie behauptet, niemals.",
            "Das stimmt nicht, ich war da gar nicht dabei.",
            "Das ist nie so gewesen.",
            "Nein, habe ich nie gesagt.",
            "Das war nicht so, da irrst du dich gewaltig.",
            "Ist nie passiert, das kann ich beschwören.",
            "Das stimmt absolut nicht.",
            "Hab ich nicht getan, das war jemand anders.",
            "Das war ganz anders, nicht so wie du sagst.",
            "Habe ich nie so gesagt.",
            "Stimmt nicht, das war nicht ich.",
            "Das ist niemals passiert.",
            "Hab ich nie gesagt, ich schwör dir.",
            "Das war nicht so gemeint, du interpretierst falsch.",
            "Das ist nie in der Form passiert.",
            "Nein, das stimmt nicht, absolut nicht.",
            "Das hab ich weder gesagt noch getan.",
            "Ist nie passiert, du fantasierst.",
        ],
        "negative": [
            "Ja, das stimmt, da hast du recht.",
            "Okay, das habe ich gesagt.",
            "Ja, das ist so passiert.",
            "Stimmt, das war so.",
            "Ich gebe zu, das habe ich getan.",
            "Ja, daran erinnere ich mich auch.",
            "Richtig, so war es.",
            "Das kann ich bestätigen.",
            "Ja, das war mein Fehler.",
            "Stimmt, ich hab das gesagt.",
            "Ich leugne das nicht.",
            "Ja, so ist es gelaufen.",
            "Das war tatsächlich so.",
            "Ich geb es zu, ja.",
            "Korrekt, das war ich.",
            "Ja, ich erinnere mich daran.",
            "Stimmt, ich war dabei.",
            "Keine Frage, das war so.",
            "Ja, das hab ich gemacht.",
            "Richtig, ich übernehme die Verantwortung.",
            "Stimmt alles, was du sagst.",
            "Ja genau, so war das.",
            "Ich bestätige das.",
            "Kann ich nicht abstreiten, stimmt.",
            "Ja, da hast du völlig recht.",
        ],
    },

    "ATO_DOMINANCE": {
        "positive": [
            "Ich setze mich hier durch, ob du willst oder nicht.",
            "Wer nicht hört, kriegt Druck, so einfach ist das.",
            "Ich behalte die Kontrolle, sofort.",
            "Respekt wird hier erzwungen, nicht erbeten.",
            "Ich zeige dir, wer hier das Sagen hat.",
            "Meine Macht ist hier unbestreitbar.",
            "Ich bestimme den Kurs, nicht du.",
            "Durchsetzen ist das Einzige, was zählt.",
            "Stärke zeigen, das ist meine Art.",
            "Ich dominiere diese Situation.",
            "Hier habe ich die Kontrolle, kapiert?",
            "Ich setze meine Position mit Nachdruck durch.",
            "Macht ist das, was mich antreibt.",
            "Wer sich mir widersetzt, bekommt Probleme.",
            "Ich kontrolliere alles, was hier passiert.",
            "Stärke zählt, Schwäche nicht.",
            "Ich erzwinge mir den Respekt, den ich verdiene.",
            "Hier wird gemacht, was ich sage, basta.",
            "Meine Dominanz ist nicht verhandelbar.",
            "Ich setze mich durch, da gibt es keine Diskussion.",
            "Kontrolle behalten, das ist die Devise.",
            "Ich zeige hier Stärke, daran führt kein Weg vorbei.",
            "Macht haben heißt durchsetzen können.",
            "Ich dominiere das Gespräch, und das ist gut so.",
            "Respekt erzwingen, wenn es sein muss.",
            "Ich bin derjenige, der hier die Regeln macht.",
            "Stärke demonstrieren, das ist angesagt.",
            "Wer sich nicht unterordnet, fliegt raus.",
            "Ich kontrolliere die Lage, komme was wolle.",
            "Durchsetzen, durchsetzen, durchsetzen.",
            "Meine Macht hinterfragst du besser nicht.",
            "Ich setze Respekt durch, nicht Bitten.",
            "Kontrolle ist mein Lebenselixier.",
            "Hier bestimme ich, wo es langgeht.",
            "Dominanz ist keine Schwäche, sondern Stärke.",
            "Ich erzwinge mir meinen Platz.",
            "Macht kommt von Durchsetzungsvermögen.",
            "Ich kontrolliere die Situation, und fertig.",
            "Stärke ist das, was andere respektieren.",
            "Ich dominiere, und du ordnest dich unter.",
            "Hier wird nach meinen Regeln gespielt.",
            "Ich setze mich durch, egal was kommt.",
            "Kontrolle über alles, das ist mein Anspruch.",
            "Wer Macht hat, setzt sich durch.",
            "Ich bestimme, und du hörst zu.",
            "Respekt erzwingen ist mein Recht.",
            "Stärke zeigen heißt dominieren.",
            "Ich habe hier die Kontrolle, nicht du.",
            "Durchsetzen ist eine Kunst, die ich beherrsche.",
            "Macht, Kontrolle, Dominanz – das bin ich.",
        ],
        "negative": [
            "Lass uns das gemeinsam entscheiden.",
            "Ich respektiere deinen Standpunkt.",
            "Wir sind gleichberechtigt in dieser Sache.",
            "Ich möchte deine Meinung hören.",
            "Das ist eine faire Diskussion, kein Kampf.",
            "Ich bin offen für Kompromisse.",
            "Lass uns auf Augenhöhe reden.",
            "Deine Perspektive ist genauso wichtig.",
            "Ich will nicht bestimmen, ich will verstehen.",
            "Wir finden zusammen eine Lösung.",
            "Ich höre dir zu, erzähl weiter.",
            "Das ist kein Wettbewerb.",
            "Ich respektiere deine Entscheidung.",
            "Wir sind Partner, nicht Gegner.",
            "Ich möchte kooperieren, nicht dominieren.",
            "Dein Wort zählt genauso viel wie meins.",
            "Ich bin bereit nachzugeben.",
            "Das entscheiden wir gemeinsam.",
            "Ich will dich nicht unterdrücken.",
            "Lass uns zusammen überlegen.",
            "Ich schätze deine Sichtweise.",
            "Das lösen wir als Team.",
            "Ich bin nicht hier, um zu bestimmen.",
            "Auf Augenhöhe finden wir den besten Weg.",
            "Ich respektiere deinen Raum.",
        ],
    },

    "ATO_DOUBLE_ENTENDRE": {
        "positive": [
            "Na, mal sehen, was heute Abend noch so passiert...",
            "Willst du wissen, was ich wirklich meine? 😉",
            "Spielst du schon wieder mit dem Feuer?",
            "Wer weiß, was passiert, wenn wir allein sind...",
            "Ich verrate dir nicht alles, haha.",
            "Das hat jetzt aber zwei Bedeutungen, oder?",
            "Wenn du verstehst, was ich meine... 😏",
            "Na, da gibt's aber noch eine andere Interpretation...",
            "Das kannst du jetzt nehmen, wie du willst.",
            "Ich sag mal so... das ist nicht nur wörtlich gemeint.",
            "Da steckt mehr dahinter, als du denkst.",
            "Wer weiß, wohin das noch führt...",
            "Das hat definitiv einen Doppelboden.",
            "Mal sehen, wohin das führt, wenn wir so weitermachen.",
            "Da lässt sich einiges reininterpretieren, hm?",
            "Ich mein das jetzt auf zwei Ebenen...",
            "Oh, das klingt jetzt aber zweideutig!",
            "Nimm das ruhig wörtlich... oder auch nicht.",
            "Spiel mit dem Feuer, wenn du dich traust.",
            "Na, da ist wohl noch mehr gemeint...",
            "Wer weiß, was passiert, wenn alle weg sind.",
            "Das ist absichtlich doppeldeutig, ja.",
            "Zwischen den Zeilen steht noch was anderes...",
            "Mal sehen, was passiert, wenn wir das vertiefen.",
            "Da ist ein Doppelboden drin, merkst du das?",
            "Ich sag das mit Absicht so zweideutig.",
            "Wer weiß, was die Nacht noch bringt...",
            "Da schwingt noch was mit, das hörst du raus.",
            "Das hat mehr als eine Bedeutung, glaub mir.",
            "Spielst du mit dem Feuer, oder meinst du das ernst?",
            "Na ja, man kann das auch anders verstehen...",
            "Ich lass das mal so stehen, du weißt schon.",
            "Mal sehen, was passiert, wenn wir uns treffen...",
            "Da ist definitiv ein Hintergedanke dabei.",
            "Wer weiß schon, was ich wirklich meine?",
            "Das ist bewusst zweideutig formuliert.",
            "Na, verstehst du den Subtext?",
            "Mal sehen, wohin das führt... 😉",
            "Da gibt es eine offensichtliche und eine versteckte Bedeutung.",
            "Spiel mit dem Feuer, aber beschwer dich nicht, wenn's heiß wird.",
            "Wer weiß, was passiert, wenn du ja sagst...",
            "Das klingt harmlos, ist es aber nicht.",
            "Ich meine das nicht nur auf einer Ebene.",
            "Da steckt eine zweite Botschaft drin.",
            "Mal sehen, was daraus wird... wenn du mutig genug bist.",
            "Wer weiß, was sich dahinter verbirgt.",
            "Nimm das nicht nur wörtlich, okay?",
            "Spiel mit dem Feuer, ich hab nichts dagegen.",
            "Da ist mehr drin als auf den ersten Blick.",
            "Mal sehen, was passiert... ich sag jetzt nichts weiter.",
        ],
        "negative": [
            "Ich meine das genau so, wie ich es sage.",
            "Das ist wörtlich gemeint, nichts anderes.",
            "Kein Hintergedanke, versprochen.",
            "Ich sage es direkt und ohne Hintersinn.",
            "Das hat nur eine Bedeutung.",
            "Ich bin hier ganz direkt.",
            "Keine versteckte Botschaft, ganz klar.",
            "Das ist so gemeint, wie es klingt.",
            "Ich rede Klartext, ohne Spielchen.",
            "Hier gibt es keinen Doppelboden.",
            "Das ist eindeutig und klar.",
            "Kein Subtext, nur die Wahrheit.",
            "Ich sage geradeheraus, was ich meine.",
            "Da ist nichts Zweideutiges dran.",
            "Klare Aussage, keine Interpretation nötig.",
            "Ich meine das buchstäblich.",
            "Kein Spiel mit Worten.",
            "Das ist genau so gemeint.",
            "Keine Doppeldeutigkeit beabsichtigt.",
            "Ich spreche offen und ehrlich.",
            "Kein versteckter Sinn dahinter.",
            "So simpel wie es klingt.",
            "Wörtlich nehmen, bitte.",
            "Ich bin direkt, kein Rätselraten.",
            "Genau das und nichts anderes.",
        ],
    },

    "ATO_DYAD_WE": {
        "positive": [
            "Wir als Diade sind stärker zusammen.",
            "Wir zwei tragen die Verantwortung gemeinsam.",
            "Wir zwei sind ein Team, das steht fest.",
            "Unsere Dyade hält zusammen.",
            "Wir tragen das zusammen, du und ich.",
            "Wir als Paar müssen das durchstehen.",
            "Wir zwei schaffen das, gemeinsam.",
            "Unsere Dyade manifestiert sich in allem, was wir tun.",
            "Wir zwei bilden eine Einheit.",
            "Wir tragen die Flamme weiter, zusammen.",
            "Wir als Diade haben eine besondere Verbindung.",
            "Wir zwei gehören zusammen, punkt.",
            "Unsere Dyade ist unzerbrechlich.",
            "Wir tragen das beide, nicht nur einer.",
            "Wir als Paar stehen füreinander ein.",
            "Wir zwei, das ist alles was zählt.",
            "Unsere Dyade hat Priorität.",
            "Wir tragen Verantwortung füreinander.",
            "Wir als Diade müssen kommunizieren.",
            "Wir zwei sind mehr als die Summe unserer Teile.",
            "Wir als Paar wachsen daran.",
            "Unsere Dyade braucht Pflege.",
            "Wir tragen das gemeinsam, egal wie schwer.",
            "Wir als Diade haben eine Mission.",
            "Wir zwei sind füreinander bestimmt.",
            "Unsere Dyade ist heilig.",
            "Wir tragen das durch, wir zwei.",
            "Wir als Paar definieren uns neu.",
            "Wir zwei gegen den Rest der Welt.",
            "Unsere Dyade ist der Anker.",
            "Wir tragen alles zusammen, immer.",
            "Wir als Diade lernen voneinander.",
            "Wir zwei verstehen uns blind.",
            "Unsere Dyade ist unsere Stärke.",
            "Wir tragen die Last zu zweit.",
            "Wir als Paar meistern jede Krise.",
            "Wir zwei haben eine gemeinsame Vision.",
            "Unsere Dyade ist die Basis von allem.",
            "Wir tragen uns gegenseitig.",
            "Wir als Diade sind untrennbar.",
            "Wir zwei, das ist unser Projekt.",
            "Unsere Dyade ist das Wichtigste.",
            "Wir tragen die Zukunft gemeinsam.",
            "Wir als Paar sind verbunden.",
            "Wir zwei stehen über allem.",
            "Unsere Dyade wächst mit jeder Herausforderung.",
            "Wir tragen das zusammen bis zum Ende.",
            "Wir als Diade schreiben unsere eigene Geschichte.",
            "Wir zwei sind alles, was ich brauche.",
            "Unsere Dyade ist mein Zuhause.",
        ],
        "negative": [
            "Ich mache das allein, das ist meine Sache.",
            "Du und ich sind verschiedene Personen.",
            "Jeder sollte für sich entscheiden.",
            "Das ist mein Ding, nicht unseres.",
            "Ich brauch meinen eigenen Raum.",
            "Wir sind nicht immer einer Meinung, und das ist okay.",
            "Ich bin ein eigenständiger Mensch.",
            "Das geht nur mich etwas an.",
            "Meine Entscheidung, mein Leben.",
            "Du bist du, und ich bin ich.",
            "Ich mache mein eigenes Ding.",
            "Wir müssen nicht alles teilen.",
            "Das ist meine persönliche Angelegenheit.",
            "Ich treffe die Entscheidung für mich.",
            "Jeder hat sein eigenes Leben.",
            "Ich bin unabhängig.",
            "Das hat nichts mit uns beiden zu tun.",
            "Mein Bereich, meine Regeln.",
            "Ich brauche Abstand, das ist nicht gegen dich.",
            "Das mache ich lieber allein.",
            "Wir sind Individuen, vergiss das nicht.",
            "Das ist mein Thema, nicht deins.",
            "Ich entscheide das selbst.",
            "Manche Dinge muss man allein klären.",
            "Das betrifft nur mich persönlich.",
        ],
    },

    "ATO_FEAR_ANXIETY": {
        # Already at 50 positive, just needs more negatives
        "positive": [],  # Will be handled specially - already at target
        "negative": [
            "Ich bin ganz entspannt heute.",
            "Alles gut bei mir, kein Stress.",
            "Ich fühle mich sicher und geborgen.",
            "Kein Grund zur Sorge, wirklich nicht.",
            "Ich bin total gelassen.",
            "Mir geht es blendend.",
            "Ich hab keine Bedenken.",
            "Alles läuft super, null Stress.",
            "Ich bin zuversichtlich, das klappt schon.",
            "Kein bisschen nervös, alles easy.",
            "Ich fühle mich stark und sicher.",
            "Mir macht das überhaupt keine Sorgen.",
            "Ich bin locker und entspannt.",
            "Total ruhig gerade, alles im grünen Bereich.",
            "Kein Anlass zur Panik.",
            "Ich hab das im Griff.",
            "Null Angst, null Sorgen.",
            "Ich bin die Ruhe selbst.",
            "Alles in bester Ordnung.",
            "Ich mache mir keinen Kopf drüber.",
            "Entspannt bleiben, das ist mein Motto.",
            "Ich hab da ein gutes Gefühl bei.",
            "Mir geht's prima, danke der Nachfrage.",
            "Kein Stress, alles easy.",
            "Ich bin zufrieden und gelassen.",
        ],
    },

    "ATO_FILLER": {
        "positive": [
            "Äh, ich denke, wir könnten das morgen machen.",
            "Ähm, also ich bin mir nicht sicher.",
            "Hm, das ist schwierig zu sagen.",
            "Ich, äh, melde mich dann später.",
            "Hm, ähm, vielleicht besser verschieben.",
            "Äh, ja, verstanden.",
            "Ähm, warte mal kurz.",
            "Hm, ich überlege noch.",
            "Also, äh, ich wollte fragen...",
            "Ähm, das ist so eine Sache...",
            "Hm, äh, wie soll ich das sagen?",
            "Also, ähm, ich bin nicht ganz sicher.",
            "Äh, Moment, lass mich überlegen.",
            "Hm, ja, ähm, stimmt wohl.",
            "Also äh, ich meinte eigentlich...",
            "Ähm, ähm, sorry, ich find die Worte nicht.",
            "Hm, wie heißt das nochmal, äh...",
            "Ja, äh, also grundsätzlich...",
            "Ähm, da muss ich kurz nachdenken.",
            "Hm, äh, das war doch, ähm...",
            "Also, äh, das Ding ist halt...",
            "Ähm, ich wollt grad was sagen, äh...",
            "Hm, naja, ähm, schwierig.",
            "Äh, wo war ich? Ähm, achso ja...",
            "Also ähm, ich versuch das zu erklären.",
            "Hm, äh, also nochmal von vorne.",
            "Ähm, Moment, äh, da war noch was.",
            "Hm, wie sage ich das am besten, äh...",
            "Also, ähm, das ist kompliziert.",
            "Äh, ich mein, ähm, du verstehst schon.",
            "Hm, also, äh, weißt du was ich meine?",
            "Ähm, ich bin äh grad etwas überfordert.",
            "Also, hm, ähm, das ist so ne Sache.",
            "Äh, warte, ähm, ich muss nachdenken.",
            "Hm, äh, na gut, also...",
            "Ähm, ja, äh, okay.",
            "Also äh, das war, ähm, anders gemeint.",
            "Hm, ich, äh, weiß nicht so recht.",
            "Ähm, also, hm, ehrlich gesagt...",
            "Äh, das, ähm, Thema ist halt...",
            "Hm, ähm, ich versuch mal...",
            "Also, äh, was ich sagen wollte, ähm...",
            "Äh, hm, ja, genau.",
            "Ähm, da fällt mir, äh, noch was ein.",
            "Hm, also, äh, ich glaub schon.",
            "Ähm, ähm, sorry, wo waren wir?",
            "Äh, hm, na dann mal los.",
            "Also ähm, ich, äh, denke...",
            "Hm, ähm, ist halt so ne Sache, äh...",
            "Ähm, äh, also quasi...",
        ],
        "negative": [
            "Morgen um 14 Uhr treffen wir uns.",
            "Die Präsentation ist fertig.",
            "Ich habe die Unterlagen vorbereitet.",
            "Das Meeting findet im Konferenzraum statt.",
            "Die Ergebnisse sind eindeutig.",
            "Ich schicke dir die Datei sofort.",
            "Der Termin steht fest.",
            "Die Entscheidung ist gefallen.",
            "Ich bin mir absolut sicher.",
            "Das Projekt ist abgeschlossen.",
            "Klar und deutlich: Ja.",
            "Ich weiß genau, was ich will.",
            "Der Plan steht, keine Änderungen.",
            "Definitiv, das machen wir so.",
            "Ohne Frage, das ist richtig.",
            "Ich bin überzeugt davon.",
            "Keine Zweifel, los geht's.",
            "Das ist meine finale Antwort.",
            "Selbstverständlich, kein Problem.",
            "Ich habe mich entschieden.",
            "Das steht fest und ist klar.",
            "Ja, ganz sicher.",
            "Perfekt formuliert, direkt auf den Punkt.",
            "Ich sage es klar und deutlich.",
            "Die Sache ist geritzt.",
        ],
    },

    "ATO_GRATITUDE": {
        "positive": [
            "Ich bin dir so dankbar dafür.",
            "Vielen Dank für deine Hilfe!",
            "Danke dir von Herzen.",
            "Das weiß ich wirklich zu schätzen.",
            "Deine Unterstützung schätze ich sehr.",
            "Ich bin dankbar für unser Gespräch.",
            "Danke, das ist nicht selbstverständlich.",
            "Ich weiß deine Mühe zu schätzen.",
            "Vielen lieben Dank!",
            "Ohne dich hätte ich das nicht geschafft, danke.",
            "Ich bin so dankbar, dass du da bist.",
            "Danke dir, das bedeutet mir viel.",
            "Vielen Dank, das hat mich gerettet.",
            "Ich bin zutiefst dankbar für deine Geduld.",
            "Danke, dass du an mich glaubst.",
            "Deine Hilfe schätze ich mehr, als du weißt.",
            "Vielen herzlichen Dank für alles.",
            "Ich bin so dankbar für dein Verständnis.",
            "Danke dir, wirklich, von ganzem Herzen.",
            "Das weiß ich sehr zu schätzen, ehrlich.",
            "Vielen Dank für deine Zeit.",
            "Ich bin dankbar, dich in meinem Leben zu haben.",
            "Danke für dein offenes Ohr.",
            "Dein Rat schätze ich ungemein.",
            "Vielen Dank, du bist ein Schatz.",
            "Ich bin wirklich dankbar für deine Treue.",
            "Danke dir für die ehrlichen Worte.",
            "Ich schätze deine Offenheit sehr.",
            "Vielen Dank für die Einladung.",
            "Ich bin so dankbar für diese Chance.",
            "Danke, dass du mir zugehört hast.",
            "Deine Großzügigkeit schätze ich sehr.",
            "Vielen Dank für dein Vertrauen.",
            "Ich bin dankbar für jede Minute mit dir.",
            "Danke dir für die wunderbare Überraschung.",
            "Das schätze ich wirklich, vielen Dank.",
            "Ich bin so dankbar, dass du mir geholfen hast.",
            "Danke für alles, was du tust.",
            "Vielen Dank, ich weiß gar nicht, was ich sagen soll.",
            "Ich bin dankbar für deine Unterstützung in schweren Zeiten.",
            "Danke dir, du machst einen Unterschied.",
            "Das schätze ich von Herzen, danke.",
            "Vielen Dank für dein Engagement.",
            "Ich bin zutiefst dankbar.",
            "Danke, dass du immer für mich da bist.",
            "Ich weiß deine Loyalität zu schätzen.",
            "Vielen herzlichen Dank, das war wunderbar.",
            "Ich bin so dankbar für deine Freundschaft.",
            "Danke dir, dass du mich nicht aufgegeben hast.",
            "Ich schätze dich und alles, was du tust, sehr.",
        ],
        "negative": [
            "Kannst du mir mal das Salz reichen?",
            "Der Termin ist um 14 Uhr.",
            "Ich war gestern einkaufen.",
            "Das Wetter soll morgen besser werden.",
            "Hast du die E-Mail gelesen?",
            "Ich muss noch tanken.",
            "Die Besprechung ist im Konferenzraum.",
            "Morgen habe ich frei.",
            "Das Essen ist gleich fertig.",
            "Ich habe den Schlüssel vergessen.",
            "Wann kommst du nach Hause?",
            "Der Bus kommt in 5 Minuten.",
            "Hast du den Müll rausgebracht?",
            "Ich gehe kurz zum Bäcker.",
            "Die Waschmaschine ist fertig.",
            "Wir müssen noch einkaufen.",
            "Ich hab meinen Regenschirm vergessen.",
            "Der Film fängt um 20 Uhr an.",
            "Ich nehme den nächsten Zug.",
            "Das Paket ist angekommen.",
            "Ich muss noch zur Post.",
            "Hast du die Rechnung bezahlt?",
            "Der Hund muss noch raus.",
            "Morgen früh hab ich einen Arzttermin.",
            "Ich räume später auf.",
        ],
    },

    "ATO_INCOHERENCE_MARKER": {
        "positive": [
            "Die Wolken tanzen mit den, äh, Fischen im... also die Gedanken sind wie Schuhe.",
            "Und dann war da der... was wollte ich sagen... die Farben sprechen zu mir, weißt du?",
            "Ich bin der König von... nein, warte... die Elefanten sind unsichtbar, das weißt du ja.",
            "Gestern war morgen und übermorgen ist dann... also die Katze hat Flügel, klar?",
            "Die Wörter fallen raus und dann... Stuhl, Baum, Universum... ja, genau.",
            "Ich rede mit dem Tisch und der Tisch sagt... also Farben haben Geschmack, verstehst du?",
            "Das Wasser fließt nach oben in die... äh... Gedanken sind Schmetterlinge, oder?",
            "Und dann hat die Lampe gesagt... nein, also die Sterne sind aus Papier, logisch.",
            "Mein Gehirn macht so... zack bumm... und dann Kartoffel, Mond, fertig.",
            "Die Schuhe laufen alleine und... was war die Frage... die Musik riecht gut.",
            "Also das Fenster denkt an mich und ich... äh... Wolken, Hund, sieben.",
            "Die Zahlen haben Gefühle und dann... also morgen gestern... Farbkreise tanzen.",
            "Ich bin gleichzeitig hier und... die Wand flüstert... Socken im Universum.",
            "Das Brot singt ein Lied von... was... also Quantenphysik und Äpfel, klar.",
            "Und der Kühlschrank erzählt von... nein... die Gedanken sind Wolkenkratzer, logisch.",
            "Ich höre die Farben und... äh... Bäume sprechen Russisch, das weiß doch jeder.",
            "Das Telefon schmeckt nach Dienstag und dann... äh... rote Dreiecke singen.",
            "Die Luft hat Arme und... also... ich bin der Tisch, der Tisch bin ich.",
            "Wörter lösen sich auf in... dings... Schmetterling, Krebs, Fenster, Ende.",
            "Ich denke an morgen gestern und... die Schuhe wissen es auch... Salat.",
            "Das Licht macht Geräusche von... was war nochmal... die Möbel haben Meinungen.",
            "Und dann sagt der Boden zur Decke... nein, also... Fisch, Stern, dreizehn.",
            "Ich war schon immer ein Regenbogen... äh... die Zeit ist quadratisch.",
            "Das Gras flüstert mir zu dass... also... die Katzen regieren die Sonne.",
            "Meine Gedanken sind wie... nein, warte... Teppich, Ozean, Bleistift, fertig.",
            "Die Suppe hat mir erzählt von... äh... unsichtbare Elefanten tanzen Walzer.",
            "Ich bin überall gleichzeitig und die... was... Buchstaben haben Beine.",
            "Das Wasser denkt an mich und... also... Schuh, Gurke, Pyramide, okay.",
            "Die Stimmen in den Wänden sagen... nein... Dreiecke schmecken nach Montag.",
            "Ich pflanze Gedanken in den... äh... die Ameisen bauen Gedichte.",
            "Und der Himmel fällt langsam... was... Tisch, Stuhl, Rakete, fertig.",
            "Mein Name ist heute anders und... äh... die Zahlen haben Farben, klar.",
            "Das Kissen erzählt Geschichten von... nein... Spiegel, Wolke, dreizehn.",
            "Ich sehe die Zeit und sie... äh... Brot, Schmetterling, Universum.",
            "Die Schuhe fliegen nach oben und... was... Bücher reden miteinander.",
            "Das Waschbecken denkt und... also... Sterne, Gras, Donnerstag, ja.",
            "Ich bin der Schlüssel zum... äh... Regen schmeckt nach Violett.",
            "Die Wörter zerfallen in... was wollte ich... Stuhl, Mond, Papier.",
            "Und der Spiegel zeigt jemand... nein... Äpfel haben Ideen, logisch.",
            "Mein Herz ist ein Buch und... äh... die Fische fliegen, natürlich.",
            "Das Radio spricht rückwärts und... also... Teppich, Stern, vierzehn.",
            "Ich höre Farben die... was... Wolken sind Gedanken, offensichtlich.",
            "Die Türklinke hat mir erzählt... nein... alles ist gleichzeitig, klar.",
            "Und dann war da... äh... Gurke, Mond, Federmäppchen, Sonntag.",
            "Mein Kopf ist ein Aquarium mit... also... Zahlen die tanzen können.",
            "Die Straße singt mir ein Lied von... was... violette Dreiecke essen.",
            "Ich weiß alles und nichts und... äh... Bleistifte haben Gefühle.",
            "Das Fenster lacht über... nein... Kartoffel, Galaxie, Mittwoch, ja.",
            "Und die Katze sagt zum Tisch... also... alles schmeckt nach Donnerstag.",
            "Ich bin der Regen und der Regen bin ich und... äh... Stuhl.",
        ],
        "negative": [
            "Ich denke, wir sollten morgen einkaufen gehen.",
            "Das Wetter ist heute wirklich schön.",
            "Kannst du mir bitte das Buch geben?",
            "Ich habe gestern einen Film geschaut.",
            "Wir treffen uns um 15 Uhr im Café.",
            "Ich bin heute müde, war ein langer Tag.",
            "Der Kuchen schmeckt sehr gut.",
            "Hast du den Brief bekommen?",
            "Morgen habe ich einen wichtigen Termin.",
            "Ich möchte gerne ein Glas Wasser.",
            "Die Kinder spielen im Garten.",
            "Wir müssen den Mietvertrag verlängern.",
            "Ich rufe dich heute Abend an.",
            "Das Konzert war wirklich toll.",
            "Können wir das auf nächste Woche verschieben?",
            "Ich habe die Wäsche schon aufgehängt.",
            "Der Zug hatte zehn Minuten Verspätung.",
            "Ich bin mit dem Ergebnis zufrieden.",
            "Hast du die Nachrichten gehört?",
            "Wir sollten mal wieder zusammen kochen.",
            "Ich habe meinen Urlaub für August gebucht.",
            "Der Arzt hat gesagt, alles ist in Ordnung.",
            "Ich suche meine Schlüssel, hast du sie gesehen?",
            "Das Restaurant hat gute Bewertungen.",
            "Ich freue mich auf das Wochenende.",
        ],
    },

    "ATO_IRONY": {
        "positive": [
            "Na wie schön, dass du das jetzt erwähnst.",
            "Wie nett von dir, das ausgerechnet jetzt anzusprechen.",
            "Na das ist ja mal eine tolle Überraschung.",
            "Wie praktisch, dass dir das gerade jetzt einfällt.",
            "Ach wie wunderbar, noch eine Ausrede.",
            "Na super, genau das hat mir noch gefehlt.",
            "Wie reizend, dass du daran gedacht hast.",
            "Na toll, das ist ja eine Glanzleistung.",
            "Wie überraschend, wer hätte das gedacht.",
            "Na das ist ja herzallerliebst.",
            "Wie schön, dass du dich auch mal meldest.",
            "Na fantastisch, noch ein Problem.",
            "Wie nett, dass du dir die Mühe machst, das zu sagen.",
            "Na wunderbar, genau mein Tag heute.",
            "Wie praktisch, du hast ja immer die besten Ideen.",
            "Na toll, noch so eine brillante Erkenntnis.",
            "Wie charmant von dir, das so zu formulieren.",
            "Na das ist ja mal eine Neuigkeit.",
            "Wie überraschend, dass das nicht funktioniert hat.",
            "Na super, dein Timing ist wie immer perfekt.",
            "Wie schön für dich, muss nett sein.",
            "Na, das ist ja großartig gelaufen.",
            "Wie nett, du denkst ja an alles.",
            "Na, welche Überraschung, du bist zu spät.",
            "Wie wunderbar, noch eine Baustelle.",
            "Na klasse, genau das wollte ich hören.",
            "Wie praktisch, du kommst genau, wenn alles fertig ist.",
            "Na toll, du bist ja ein richtiges Genie.",
            "Wie schön, dass alles nach Plan läuft – nicht.",
            "Na das ist ja eine Glanzleistung ersten Ranges.",
            "Wie nett, dass du dir Sorgen machst – nach zwei Wochen.",
            "Na super, das hilft uns jetzt ungemein.",
            "Wie reizend, immer wenn man dich braucht, bist du weg.",
            "Na fantastisch, der perfekte Moment für sowas.",
            "Wie überraschend, du hast mal wieder recht.",
            "Na wunderbar, das hat ja super geklappt.",
            "Wie schön, noch eine Lektion fürs Leben.",
            "Na toll, danke für die Vorwarnung – die kam gar nicht.",
            "Wie nett von dir, das im letzten Moment zu sagen.",
            "Na das ist ja der Höhepunkt des Tages.",
            "Wie praktisch, wenn man hinterher schlauer ist.",
            "Na super, genau die Art Hilfe, die ich brauche.",
            "Wie wunderbar, dass es so einfach ist – war es nicht.",
            "Na toll, noch so eine Nachricht, die meinen Tag versüßt.",
            "Wie schön, du hast ja immer alles im Griff.",
            "Na fantastisch, das wäre ja auch zu einfach gewesen.",
            "Wie nett, du denkst auch immer zuerst an andere.",
            "Na das ist ja eine Meisterleistung der Kommunikation.",
            "Wie überraschend, dass das schiefgegangen ist.",
            "Na wunderbar, besser hätte es nicht laufen können – oder eben doch.",
        ],
        "negative": [
            "Das hast du wirklich toll gemacht, ich bin beeindruckt.",
            "Vielen Dank, das war sehr hilfreich.",
            "Das ist wirklich nett von dir.",
            "Du hast absolut recht damit.",
            "Das freut mich ehrlich für dich.",
            "Das war eine tolle Idee.",
            "Ich bin aufrichtig dankbar.",
            "Das Ergebnis ist wirklich gut.",
            "Du hast eine besondere Begabung dafür.",
            "Das hat mich positiv überrascht.",
            "Ich meine das ernst, das war super.",
            "Du bist wirklich großartig darin.",
            "Das war eine echte Leistung.",
            "Ich bin aufrichtig begeistert.",
            "Das hätte ich nicht besser machen können.",
            "Wirklich klasse, ehrlich gemeint.",
            "Du machst das richtig gut.",
            "Das hat mich wirklich beeindruckt.",
            "Aufrichtig, das war hervorragend.",
            "Ich bin echt stolz auf dich.",
            "Das war ganz und gar nicht selbstverständlich.",
            "Chapeau, das verdient Anerkennung.",
            "Ich bin ehrlich begeistert von dem Ergebnis.",
            "Das war eine tolle Überraschung, wirklich.",
            "Du hast dich selbst übertroffen.",
        ],
    },

    "ATO_JOY": {
        "positive": [
            "Ich freue mich so sehr über die Nachricht!",
            "Super, das ist ja fantastisch!",
            "Yay, endlich hat es geklappt!",
            "Ich bin so glücklich gerade, ich könnte platzen!",
            "Das ist der Hammer, echt jetzt!",
            "Mega, besser hätte es nicht laufen können!",
            "Geil, das ist ja der Wahnsinn!",
            "Ich bin so happy, kann es kaum fassen!",
            "Das macht mich total froh.",
            "Yeah, das ist großartig!",
            "Ich bin echt begeistert!",
            "Einfach fantastisch, das Ergebnis!",
            "Ich kann's kaum erwarten!",
            "Besser geht's wirklich nicht!",
            "Hab noch nie so was Tolles erlebt!",
            "Das zaubert mir ein Lächeln ins Gesicht!",
            "Ich fühl mich wie auf Wolken!",
            "So ein geiles Gefühl!",
            "Man, das macht mich richtig happy!",
            "Ich strahle über beide Ohren!",
            "Das macht richtig Spaß!",
            "So viel Freude gerade!",
            "Ich hüpfe vor Glück!",
            "Endlich, ich freu mich riesig!",
            "Super, super, super!",
            "Das ist mega, ich bin begeistert!",
            "Yay, der Tag ist gerettet!",
            "Ich bin total glücklich gerade!",
            "Hammer, das hätte ich nicht erwartet!",
            "So geil, das feiere ich!",
            "Ich bin richtig happy, danke!",
            "Wow, das ist echt super gelaufen!",
            "Freue mich riesig auf morgen!",
            "Das ist so toll, ich kann es nicht glauben!",
            "Mega cool, das wird ein toller Abend!",
            "Ich bin überglücklich!",
            "Super Nachricht, danke dir!",
            "Yay, es hat endlich geklappt!",
            "Ich bin so froh, das ist unglaublich!",
            "Hammer geil, das ist perfekt!",
            "Ich freue mich wie ein kleines Kind!",
            "Das ist mega awesome!",
            "Ich bin total happy damit!",
            "Super, das ist genau, was ich wollte!",
            "Yay, die Prüfung bestanden!",
            "Ich bin so glücklich, dass alles gut gegangen ist!",
            "Mega, das ist der beste Tag!",
            "Geil, ich hab den Job!",
            "Happy happy, alles ist gut!",
            "Das ist einfach nur super, ich bin begeistert!",
        ],
        "negative": [
            "Das Wetter ist heute bewölkt.",
            "Ich gehe jetzt einkaufen.",
            "Der Termin ist um 10 Uhr.",
            "Ich habe die Rechnung bezahlt.",
            "Morgen muss ich arbeiten.",
            "Das Meeting dauert eine Stunde.",
            "Ich nehme den Bus.",
            "Die Besprechung war sachlich.",
            "Ich habe den Bericht fertig.",
            "Wir müssen das noch besprechen.",
            "Ich bin müde, aber es geht.",
            "Der Film war okay, nicht spektakulär.",
            "Ich mache mir Notizen.",
            "Das Essen war in Ordnung.",
            "Ich bin beschäftigt heute.",
            "Die Aufgabe ist erledigt.",
            "Ich fahre jetzt nach Hause.",
            "Das war eine normale Woche.",
            "Ich habe noch was zu tun.",
            "Der Tag war durchschnittlich.",
            "Ich überlege noch, was ich mache.",
            "Alles läuft wie geplant, nichts Besonderes.",
            "Ich bin neutral dazu.",
            "Kann man so oder so sehen.",
            "Mir ist das ziemlich egal.",
        ],
    },

    "ATO_LONELINESS": {
        "positive": [
            "Ich bin so einsam gerade.",
            "Ganz allein hier, niemand ist da.",
            "Ich fühle mich völlig isoliert.",
            "Niemand ist da für mich.",
            "Verlassen und allein, so fühle ich mich.",
            "Die Einsamkeit frisst mich auf.",
            "Ich bin so allein, dass es wehtut.",
            "Niemand ruft an, niemand schreibt.",
            "Ich bin einsam und vermisse Menschen um mich.",
            "Total isoliert von allen.",
            "Ich bin ganz allein mit meinen Gedanken.",
            "Niemand ist da, wenn ich jemanden brauche.",
            "Ich fühle mich verlassen und einsam.",
            "Die Wohnung ist leer und ich bin allein.",
            "Einsam sein ist das Schlimmste.",
            "Ich hab niemanden zum Reden, bin ganz allein.",
            "Isoliert von der Welt, so fühlt es sich an.",
            "Niemand da, der mich versteht.",
            "Ich bin einsam, auch wenn Leute um mich sind.",
            "Allein am Wochenende, niemand meldet sich.",
            "Die Einsamkeit macht mich krank.",
            "Ich bin so allein und verlassen.",
            "Niemand ist da für mich, echt keiner.",
            "Ich fühle mich isoliert und abgeschnitten.",
            "Verlassen in meiner eigenen Welt.",
            "Einsam trotz all der Menschen.",
            "Allein einschlafen, allein aufwachen.",
            "Niemand da, der sich kümmert.",
            "Ich bin einsam und kann nichts dagegen tun.",
            "Isoliert und vergessen.",
            "Allein mit meinen Sorgen.",
            "Niemand interessiert sich für mich, ich bin so einsam.",
            "Ich fühle mich verlassen von allen.",
            "Einsam an einem Freitagabend.",
            "Ganz allein, kein Mensch weit und breit.",
            "Niemand da, der zuhört.",
            "Ich bin so einsam, dass ich mit mir selbst rede.",
            "Isoliert und ohne Hoffnung.",
            "Verlassen von Freunden und Familie.",
            "Die Einsamkeit erdrückt mich.",
            "Allein in einer vollen Stadt.",
            "Niemand versteht, wie einsam ich bin.",
            "Ich bin allein und es tut weh.",
            "Isoliert und traurig.",
            "Einsam, immer einsam.",
            "Niemand ist da, niemand wird kommen.",
            "Allein gelassen mit allem.",
            "Ich bin so einsam, es zerreißt mich.",
            "Verlassen und vergessen von der Welt.",
            "Niemand da, absolute Einsamkeit.",
        ],
        "negative": [
            "Ich bin gerne mal für mich.",
            "Heute genieße ich meinen Abend allein.",
            "Ich brauche etwas Ruhe, das tut mir gut.",
            "Allein sein ist manchmal erholsam.",
            "Ich schätze meine Zeit für mich.",
            "Heute Abend mache ich es mir gemütlich.",
            "Ich hab gerade viel Kontakt mit Freunden.",
            "Wir treffen uns morgen alle zusammen.",
            "Ich fühle mich wohl in meiner Wohnung.",
            "Mir geht es gut, auch wenn ich mal allein bin.",
            "Ich genieße die Stille.",
            "Allein sein ist nicht gleich einsam sein.",
            "Ich hab bewusst einen ruhigen Abend geplant.",
            "Mir tut die Auszeit gut.",
            "Ich lese ein Buch und bin ganz zufrieden.",
            "Allein spazieren gehen ist mein Hobby.",
            "Ich hab heute viele nette Gespräche geführt.",
            "Die Ruhe nach einem hektischen Tag tut gut.",
            "Ich schätze es, meine eigenen Dinge zu machen.",
            "Morgen treffe ich Freunde, darauf freu ich mich.",
            "Ich bin zufrieden mit meinem Abend.",
            "Allein kochen macht mir Spaß.",
            "Ich hab genug soziale Kontakte gerade.",
            "Der stille Abend ist genau das, was ich brauche.",
            "Ich bin gern mein eigener Gesellschaft.",
        ],
    },

    "ATO_LOVE_MOTIVE": {
        "positive": [
            "Ich handle aus Liebe, nicht aus Pflicht.",
            "Wir bauen das liebevoll auf.",
            "Ich antworte in Güte statt in Kontrolle.",
            "Das tue ich nicht aus Angst, sondern aus Liebe.",
            "Ich bleibe liebevoll bei dir.",
            "Wir treffen diese Wahl aus Liebe.",
            "Ich gehe in Güte an das Gespräch.",
            "Nicht aus Angst, sondern in Zuneigung.",
            "Ich markiere das Feld liebevoll.",
            "Dieser Schritt entsteht aus Liebe zu uns.",
            "Meine Motivation ist die Liebe, nichts anderes.",
            "Ich sage das aus Liebe heraus.",
            "Wir gehen liebevoll miteinander um.",
            "Aus Liebe entscheide ich mich dafür.",
            "Ich begegne dir in Güte und Zuneigung.",
            "Liebevoll begleite ich dich auf diesem Weg.",
            "Das mache ich nicht aus Angst, sondern weil ich dich liebe.",
            "In Güte und Liebe finden wir den Weg.",
            "Ich reagiere liebevoll, nicht aus Kontrolle.",
            "Aus Liebe höre ich dir zu.",
            "Liebevoll gestalten wir unsere Beziehung.",
            "Ich komme in Güte auf dich zu.",
            "Mein Handeln ist von Liebe geleitet.",
            "Nicht aus Angst vor Verlust, sondern aus echter Zuneigung.",
            "Ich wähle den liebevollen Weg.",
            "In Güte spreche ich diese Wahrheit aus.",
            "Aus Liebe bin ich ehrlich zu dir.",
            "Liebevoll nehme ich deine Hand.",
            "Das geschieht aus reiner Liebe.",
            "Ich entscheide mich in Güte für dich.",
            "Liebevoll setze ich Grenzen, nicht aus Angst.",
            "Aus Liebe heraus sage ich dir die Wahrheit.",
            "Ich reagiere nicht aus Angst, sondern in Güte.",
            "Liebevoll lasse ich dich gehen, wenn es sein muss.",
            "Aus Liebe unterstütze ich deinen Weg.",
            "In Güte akzeptiere ich, was ist.",
            "Liebevoll halte ich den Raum für uns.",
            "Nicht aus Pflichtgefühl, sondern aus tiefer Liebe.",
            "Ich antworte liebevoll auf deine Frage.",
            "Aus Liebe vergebe ich dir.",
            "In Güte begegne ich deiner Verletzlichkeit.",
            "Liebevoll trage ich dich durch diese Zeit.",
            "Mein Herz handelt aus Liebe.",
            "Ich komme in Güte und nicht in Vorwurf.",
            "Aus Liebe warte ich geduldig.",
            "Liebevoll nehme ich dich so, wie du bist.",
            "In Güte lasse ich los.",
            "Nicht aus Angst festhalten, sondern aus Liebe begleiten.",
            "Liebevoll gestalte ich unseren Alltag.",
            "Aus Liebe und in Güte bin ich hier.",
        ],
        "negative": [
            "Ich mache das, weil ich muss.",
            "Das ist meine Pflicht, mehr nicht.",
            "Ich bleibe aus Gewohnheit.",
            "Das mache ich wegen der Kinder.",
            "Ich helfe dir, weil man das so macht.",
            "Das ist reine Vernunft, nichts weiter.",
            "Ich tue das aus Pflichtbewusstsein.",
            "Man muss halt Kompromisse eingehen.",
            "Ich bleibe, weil ich keine Alternative sehe.",
            "Das ist Pragmatismus, keine Romantik.",
            "Ich handle rational, nicht emotional.",
            "Das mache ich aus Anstand.",
            "Es gehört sich halt so.",
            "Ich bin da, weil es erwartet wird.",
            "Das ist eine sachliche Entscheidung.",
            "Ich halte mich an die Abmachung.",
            "Das mache ich, weil es sonst keiner tut.",
            "Aus reiner Notwendigkeit, nicht mehr.",
            "Ich erledige das, weil es meine Aufgabe ist.",
            "Das ist eine logische Entscheidung.",
            "Ich mache das aus Verantwortungsgefühl.",
            "Das ist die vernünftige Option.",
            "Ich handle nach Plan, nicht nach Gefühl.",
            "Das ist strategisch klug.",
            "Ich tue das, weil es das Richtige ist, nicht aus Emotion.",
        ],
    },
}


def find_marker_file(marker_id: str) -> Path | None:
    """Find the YAML file for a marker across all rating directories."""
    for d in DIRS:
        p = BASE / d / "ATO" / f"{marker_id}.yaml"
        if p.exists():
            return p
    return None


def detect_example_keys(examples: dict) -> tuple[str, str]:
    """Detect whether examples use positive/negative or positive_de/negative_de keys."""
    pos_key = "positive_de" if "positive_de" in examples else "positive"
    neg_key = "negative_de" if "negative_de" in examples else "negative"
    return pos_key, neg_key


def enrich_marker(marker_id: str) -> dict:
    """Enrich a single marker with examples. Returns status dict."""
    path = find_marker_file(marker_id)
    if path is None:
        return {"id": marker_id, "status": "skipped", "reason": "file not found"}

    # Load YAML
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.load(f)

    if data is None:
        return {"id": marker_id, "status": "skipped", "reason": "empty YAML"}

    # Get or create examples section
    if "examples" not in data:
        data["examples"] = {}

    examples = data["examples"]
    pos_key, neg_key = detect_example_keys(examples)

    # Check if new examples use _de keys
    new_examples = EXAMPLES.get(marker_id, {})
    if not new_examples:
        return {"id": marker_id, "status": "skipped", "reason": "no examples in script"}

    # Determine the actual keys from our EXAMPLES dict
    if "positive_de" in new_examples:
        src_pos_key = "positive_de"
        src_neg_key = "negative_de"
        # Override the file keys to match
        pos_key = "positive_de"
        neg_key = "negative_de"
    else:
        src_pos_key = "positive"
        src_neg_key = "negative"

    # Current counts
    current_pos = examples.get(pos_key, []) or []
    current_neg = examples.get(neg_key, []) or []

    if not isinstance(current_pos, list):
        current_pos = []
    if not isinstance(current_neg, list):
        current_neg = []

    pos_count = len(current_pos)
    neg_count = len(current_neg)

    # Skip if already at target
    if pos_count >= TARGET_POS and neg_count >= TARGET_NEG:
        return {
            "id": marker_id,
            "status": "already_done",
            "pos": pos_count,
            "neg": neg_count,
        }

    # Get new examples
    new_pos = new_examples.get(src_pos_key, [])
    new_neg = new_examples.get(src_neg_key, [])

    # Merge: keep existing, add new until target reached
    existing_pos_set = set(current_pos)
    existing_neg_set = set(current_neg)

    # Add new positives (deduplicated)
    for ex in new_pos:
        if ex not in existing_pos_set and len(current_pos) < TARGET_POS:
            current_pos.append(ex)
            existing_pos_set.add(ex)

    # Add new negatives (deduplicated)
    for ex in new_neg:
        if ex not in existing_neg_set and len(current_neg) < TARGET_NEG:
            current_neg.append(ex)
            existing_neg_set.add(ex)

    # Update examples in data
    examples[pos_key] = current_pos
    examples[neg_key] = current_neg
    data["examples"] = examples

    # Write back
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(data, f)

    return {
        "id": marker_id,
        "status": "enriched",
        "pos": len(current_pos),
        "neg": len(current_neg),
        "pos_added": len(current_pos) - pos_count,
        "neg_added": len(current_neg) - neg_count,
        "path": str(path),
    }


def main():
    print("=" * 60)
    print("LeanDeep V6.0 — ATO Marker Example Enrichment")
    print("=" * 60)
    print()

    results = []
    for marker_id in sorted(EXAMPLES.keys()):
        result = enrich_marker(marker_id)
        results.append(result)

        status = result["status"]
        if status == "enriched":
            print(
                f"  ✓ {marker_id}: "
                f"+{result['pos_added']} pos (→{result['pos']}), "
                f"+{result['neg_added']} neg (→{result['neg']})"
            )
        elif status == "already_done":
            print(f"  = {marker_id}: already at target ({result['pos']}/{result['neg']})")
        else:
            print(f"  ✗ {marker_id}: {result['reason']}")

    print()
    print("-" * 60)
    enriched = sum(1 for r in results if r["status"] == "enriched")
    skipped = sum(1 for r in results if r["status"] == "skipped")
    already = sum(1 for r in results if r["status"] == "already_done")
    print(f"Enriched: {enriched} | Already done: {already} | Skipped: {skipped}")
    print()

    # Verification
    print("Verification — markers at target (50+/25+):")
    at_target = 0
    below_target = 0
    for marker_id in sorted(EXAMPLES.keys()):
        path = find_marker_file(marker_id)
        if path is None:
            continue
        import yaml as pyyaml
        with open(path, "r", encoding="utf-8") as f:
            data = pyyaml.safe_load(f)
        if data is None:
            continue
        ex = data.get("examples", {})
        pos = len(ex.get("positive", ex.get("positive_de", [])) or [])
        neg = len(ex.get("negative", ex.get("negative_de", [])) or [])
        if pos >= TARGET_POS and neg >= TARGET_NEG:
            at_target += 1
            print(f"  ✓ {marker_id}: {pos} pos / {neg} neg")
        else:
            below_target += 1
            print(f"  ✗ {marker_id}: {pos} pos / {neg} neg — BELOW TARGET")

    print(f"\nAt target: {at_target} / {at_target + below_target}")


if __name__ == "__main__":
    main()
